### ISSUE TITLE
February monthly meeting agenda

### ISSUE THREAD

**Issue by spartantri** [SpiderLabs/owasp-modsecurity-crs#1003]
Here are some items to discuss during our monthly chat:

- PR #989 : 942490 regressiontest
- PR #990 : Java attacks
- PR #994 : File attacks
- PR #1004 : 921169
- PR #1000 : 921160 unnecessary space
- PR #1008 : Regression test overhaul by @csanders-git based on dozens of PRs @azhao155
- PR #1009 : FP: superlike
- PR #1010 : NextCloud
- PR #1011 : Docuwiki
- Bunch of PR : Fix for ######
- Rule cleanup phase:2 -> phase:1
- Review January decision: "csanders will write some of the documentation from #986 and provide a space on coreruleset.org for the information to live."
- Issue #731 : CPanel, delayed PR
- 136 open issues
- Updated release poster coming up (we'll do poster sale, possibly more merchandise)

**Comment by csanders-git** [comment]
thanks :) i'll be adding my updates soon

**Comment by allanbomsft** [comment]
Any chance I could join the meeting?

**Comment by dune73** [comment]
Sure thing, it's a community meeting.

First monday every month, 2030 CET, freenode IRC, channel #modsecurity. Would be nice to see you. And put things up on the agenda if you want to have it covered.
