### ISSUE TITLE
Decide on placement of ctl:forceRequestBodyVariable in rules files or in init (=901)

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1012]
The new 914 and 944 rules brought up this question.

Let's decide this in time for 3.1.

**Comment by spartantri** [comment]
I vote moving 944000 to 901110 or something like that and remove it from both 914 and 944 :+1:

**Comment by spartantri** [comment]
Opened PR #1046 to move the rule out of java attacks into initialization ruleset 944000 to 901170

**Comment by spartantri** [comment]
PR merged
