### ISSUE TITLE
Rule Cleanup: Determine most efficient phases

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#1015]
Our current rules take liberties with the phase that rules are placed in. This is because placing rules in higher phases still gives these rules access to elements from the lower phases. See https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#Processing_Phases for more information. In order to account for performance, elements that are only touching phase:1 variables should be labeled as phase 1 and so on.

**Comment by dune73** [comment]
This sounds good, but your plan is not very clear.

Are you stating that we want to move rules that work only on stuff available in phase-1 to this phase-1?

**Comment by spartantri** [comment]
What will be the strategy for this? 
It could result in duplicated rules splitting ARGS into ARGS_GET in phase:1 and ARGS_POST in phase:2 or split everything related to headers and cookies to phase:1 and leave ARGS and bodies to phase:2.

**Comment by dune73** [comment]
Good thinking. I guess we need some more good thinking. In order to make a reasonable decision we will need to balance the benefits against performance loss due to the possible splitting and the complexity of the rule base.

Personally, I do not have a plan, but I like the idea of intercepting offenders at the end of phase 1 immediately.

**Comment by spartantri** [comment]
what if we do this for PL1 only?
maybe start with:
- 910-ip reputation
- 911-method enforcement
- 913-scanner detection
- 920-protocol enforcement
- 921-protocol attacks

**Comment by fgsch** [comment]
Hi there. We'll certainly welcome a PR to sort this out.
As this issue has not been updated in over a year I'd suggest to move this convo to a PR.
I will close this issue for now.
