### ISSUE TITLE
the rule(932150) of modsecurity3.0 uses a lot of strange regrex like [\\\\'\"]

### ISSUE THREAD

**Issue by illman2** [SpiderLabs/owasp-modsecurity-crs#1018]
hello: 
      I found the rule(932150) of modsecurity3.0 used a lot of strange regrex like [\\\\'\"],what is the [\\\\'\"] meaning ? it want matching what ? I'm puzzled ！

      thanks!

**Comment by dune73** [comment]
The unix bash shell is very liberal with what it executes.
```
$> n\e'ts'tat -n
```
Is perfectly find and will execute the command. This rule tries to catch the netstat command and all these obfuscations.

**Comment by illman2** [comment]
> I guess,because “[\\\\'\"]” in the “”，it triggering the first eascapping，becoming to [\\'\"], and then runing the regex in modsecurity, triggering the second eascapping, becoming to [\'\"],means: \ | ' | "  ，is it right

**Comment by illman2** [comment]
`I guess,because “[\\\\'\"]” in the “”，it triggering the first eascapping，becoming to [\\'\"], and then runing the regex in modsecurity, triggering the second eascapping, becoming to [\'\"],means: \ | ' | "  ，is it right`

**Comment by dune73** [comment]
I'm not really familiar with the regex, but I think this is about correct.

**Comment by lifeforms** [comment]
Yes, this was a bit of trial and error for me. ;) That regexp accepts a `\` or `'` or `"` character.
