### ISSUE TITLE
Rule id 920140 causes "Expecting a variable, got:" error in ModSecurity v3.0.0

### ISSUE THREAD

**Issue by psybustermk2** [SpiderLabs/owasp-modsecurity-crs#1021]
I kept getting this error when I tried starting nginx with ModSecurity 3.0.0 and owasp-modsecurity-crs 3.0.2.

`[emerg] 5373#5373: "modsecurity_rules_file" directive Rules error. File: /usr/local/owasp-modsecurity-crs-3.0.2/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf. Line: 169. Column: 390. Expecting a variable, got:  :  MULTIPART_SEMICOLON_MISSING},\ in /etc/nginx/conf.d/default.conf:6`

I found that ModSecurity's file `modsecurity.conf-recommended` has an entry "MULTIPART_MISSING_SEMICOLON" so I tried replacing the line  in `rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf` that has "MULTIPART_SEMICOLON_MISSING" with the former and I successfully started nginx.

Should the correction be on the owasp-modsecurity-crs or ModSecurity?

**Comment by psybustermk2** [comment]
I checked with the other branches and this seems to be fixed in 3.1/dev. I'm closing this.

**Comment by dune73** [comment]
Thank you for submitting. And yes, we covered that. Sorry for not getting back to you earlier.
