### ISSUE TITLE
Failed to open file: scanners-user-agents.data

### ISSUE THREAD

**Issue by GainfulShrimp** [SpiderLabs/owasp-modsecurity-crs#1025]
Apologies if this is a ModSecurity (or ModSecurity-nginx) problem rather than a CRS problem; I'm new to all three.

I've compiled and installed ModSecurity v3 (from v3/master branch) and compiled nginx 1.13.9 with the ModSecurity-nginx connector.

When I use a simple example/test rule, like this one, it works (i.e. requests including "?testparam=test" get 403ed), so I think my modsec installation is OK:

`SecRule ARGS:testparam "@contains test" "id:1234,deny,status:403"`

However, with the latest (from Github) CRS v3 rules, I can't successfully test my nginx config, as I get the following error:

```
pi@pi2:~ $ sudo nginx -t
nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /etc/nginx/modsec/crs/rules/REQUEST-913-SCANNER-DETECTION.conf. Line: 33. Column: 34. Failed to open file: scanners-user-agents.data. Looking at: 'scanners-user-agents.data',   in /etc/nginx/conf.d/ghost-proxy.conf:17
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Comment by dune73** [comment]
Hi there, sorry for the inconvenience @GainfulShrimp.

We are depending on NGINX here for loading these files. The rule in question tries to load the said file from the local path. So there might be an issue with you include statement and / or NGINX loading files.

Alternatively a permission problem.

Please try to fix these by playing around with the path right in the inclusion statement or directly in the rule file and check the permissions too. 

I am closing this now. If you are sure it's our fault, then please re-open.

Good luck!

**Comment by csanders-git** [comment]
Also if you're on redhat derived is it may be selinux

**Comment by victorhora** [comment]
Looks like it was related with this missing [patch](https://github.com/SpiderLabs/ModSecurity/commit/e3b6b4ccff5b4388bde4485049af382a21d4cbb8).

[Latest comment ](https://github.com/SpiderLabs/ModSecurity/issues/1687#issuecomment-368964961)suggest it was solved :)

**Comment by GainfulShrimp** [comment]
Thanks all. Yes, my problem is now solved after recompiling libModSecurity from the latest v3/master. :)
