### ISSUE TITLE
March monthly meeting agenda

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#1026]
- [x] Adding modsecurity v3 support to testing env
- [x] #990 java attacks
- [x] CRS Summit in AppSec EU?
- [x] #1013 FP resolution
- [x] #1010 Nextcloud
- [x] #994 File detection
- [x] #989 regression test fixes
- [x] remaining @azhao155 issues
- [x] #896 command injection update.
- [x] CRS 3.1 release date.
- [ ] Upgrades to how we handle tickets
- [ ] GeoIP legacy format reaching EOL

**Comment by spartantri** [comment]
#990 java attacks

**Comment by ffichter** [comment]
Support for the new MaxMind format? Since the GeoLite Legacy databases updates are discontinued as of April 1, 2018 (https://dev.maxmind.com/geoip/geoip2/geolite2/)

**Comment by dune73** [comment]
I agree with @ffichter this is a hard problem. It's one that ModSecurity needs to solve though. But given the size of the problem we should at least discuss a position for the project that we write down for our users.

**Comment by fzipi** [comment]
CRS Summit in AppSec EU?
