### ISSUE TITLE
Azure Firewall blocking the signalr request - it's false positive 

### ISSUE THREAD

**Issue by elango79** [SpiderLabs/owasp-modsecurity-crs#1030]
That firewall rule is matching on connectionData=%5B%7B%22name%22%3A%22srhub%22%7D%5D
That field contains name of the SignalR hub on the server.

Example – before it gets encoded this would contain:
connectionData      [{"name":"chathub"}]

And it blocking following rule and uri in Azure Application Gateway 

"requestUri": "/SignalR/Hubs/signalr/negotiate?clientProtocol=1.5&connectionData=%5B%7B%22name%22%3A%22srhub%22%7D%5D&_=1517861089117",
"ruleSetType": "OWASP",
"ruleSetVersion": "3.0",
"ruleId": "942340",
"message": "Detects basic SQL authentication bypass attempts 3/3",
"action": "Blocked",
"site": "Global",
"details": {
"message": "Warning. Pattern match \"(?i?:in\\\\s*?\\\\(\\\\s*?select)|(??:n?and|x?x?or|div|like|between|and|not|\\\\|\\\\||\\\\&\\\\&)\\\\s\\\\s\\\\w+(?:regexp\\\\s*?\\\\(|sounds\\\\s+like\\\\s*?\\\"'`|[=\\\\d]+x))|(\\\"'`\\\\s*?\\\\d\\\\s*?(?:--|#))|(?:\\\"'`\\\\%&<>^=\\\\d\\\\s*?(=|x?or|div|like|between|and))|(?:[
...\" at ARGS:connectionData.",

Please help on this

**Comment by dune73** [comment]
Sorry for your inconvenience.

This is a Paranoia Level 2 false positive. 

You have two options:
- Reduce the Paranoia Level to 1
- Handle the false positive yourself. https://www.netnea.com/cms/apache-tutorials/ has instructions for you.

I'm closing this now. Please re-open if you need more help.

**Comment by elango79** [comment]
Thanks for your support can you please guide me how to try your two option in my environment
I am using web app, app service and application gateway in Azure 
Help me on this

**Comment by dune73** [comment]
Sorry, but Azure is a paid offering. You should ask them to support you.

I write tutorials and share them for free. Supporting commercial platforms for free is outside of my scope.

**Comment by elango79** [comment]
Thanks but your recommendation to change the Paranoia Level  2 to 1 in REQUEST-942-APPLICATION-ATTACK-SQLI.conf am I correct

**Comment by dune73** [comment]
No, you change the PL in crs-setup.conf. That's supposed to be the first include.

And please read the documentation / tutorials so you know what you are doing. Changing the PL changes your security level.

**Comment by csanders-git** [comment]
The exception process might look something like the following
```SecRuleUpdateTargetById 942340 !ARGS:connectionType```

We unfortunately don't have any insight into how to fix this within Azure, if you find out please list here

The underlying issue is  ```connectionData=[{"name":"srhub"}]```

The triggered text is ```"name":"```

It triggers this part of the rule ```(?i:(?:[\"'`]\|?[\w-]{3,}[^\w\s.,]+[\"'`]))```

This rule is in PL2 which means that we can expect some false positives.
