### ISSUE TITLE
OWASP blocking yoast plugin

### ISSUE THREAD

**Issue by adrian-alephit** [SpiderLabs/owasp-modsecurity-crs#1041]
[Fri Mar 16 15:39:13.048602 2018] [:error] [pid 267578:tid 140349869573888] [client 203.59.228.9:45605] [client 203.59.228.9] ModSecurity: Access denied with code 403 (phase 2). Operator GE matched 5 at TX:anomaly_score. [file "/etc/apache2/conf.d/modsec_vendor_configs/OWASP3/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "30"] [id "949110"] [msg "Inbound Anomaly Score Exceeded (Total Score: 15)"] [severity "CRITICAL"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "xxxxxxx.com"] [uri "/wp-json/yoast/v1/prominent_words"] [unique_id "WqtKcQHXq@Gf6NfRiWq9LAAAARc"], referer: 
https://xxxxxxx.com/wp-admin/post.php?post=392&action=edit

Hi Wonderful OWASP team, Above is the error we receiving and it caused the client to get blocked from his wp-admin by CSF for breaching mod security 5 times. 

Can we advise why it is happening and if there is a resolution or whitelist I can implement?Or is the above being over protection? Or something else? I am a little new and confused. 
Thanks team.

**Comment by dune73** [comment]
Thanks for reporting and sorry for the inconvenience, @devteam9200.

Unfortunately you reported only the final blocking alert, not the security alert that prompted the final blocking. Please provide us with the full error log entries for the request and ideally with the modsec audit log record with the complete request payload.

We have a rule exclusion package for Wordpress, but it does not cover individual plugins. If you are in a situation to help us extend the rule exclusion package to a number of core modules, that would be very interesting. You bring the WP expertise, we add the CRS knowledge.

**Comment by theMiddleBlue** [comment]
no updates received. Please, feel free to reopen if needed.
