### ISSUE TITLE
Rule 942450 reports a false positive when a matching pattern exists in asp.net view state

### ISSUE THREAD

**Issue by StingyJack** [SpiderLabs/owasp-modsecurity-crs#1044]
If I have an asp.net viewstate being returned to the server with a value of "0xA" in it, this rule is triggered.  This should not be reported as a SQLi, as its not user data being submitted currently and is not a latent SQLi from a prior session. Its base64 encoded and that character set will sometimes include these values in this sequence.  

Is there a way to configure the rule to ignore view state, or is there another recommended course of action for the short term? 

For the unfamiliar, asp.net viewstate is a state representation of the form data that is encrypted by the server, then encoded, then sent to the user. The browser returns this data when posting back, and the server is able to reconstruct the prior state before it applies the newly submitted data. At no point does the user modify the data.

**Comment by spartantri** [comment]
Hi @StingyJack, you can do in your local configuration a whitelist to that argument globally if present everywhere or per uri.
Globally:
SecRuleUpdateTargetById 942450 !ARGS:viewstate
Per Uri:
SecRule REQUEST_URI ...... ctl:ruleRemoveTargetById=942450;ARGS:viewstate

For further questions is better to use the distribution list instead opening issues.

**Comment by StingyJack** [comment]
Thanks!  I'll pass this along.
