### ISSUE TITLE
Hybrid Paranoia Mode

### ISSUE THREAD

**Issue by spartantri** [SpiderLabs/owasp-modsecurity-crs#1050]
I just made some changes to PR #1045 to add an hybrid paranoia mode where you may choose to run some PL in detection only and others in blocking mode, I put it in the same file to have something in it instead of an empty template.

Basically the PL behavior still the same but added a paranoia_test_level where you pick from what levels and above the engine should be turned in in detectiononly, it turn it to detection only before entering the PL then set it back on when leaving phase:1 and phase:2 so it should not affect the rules in other files.

The idea is ease the implementation of higher PL without service disruptions or digging holes in the security.

**Comment by dune73** [comment]
That is a welcome initiative and you put the finger where it hurts. Raising the PL in production is very hard with 3.0 and I thought long about how to pull this off. I think I have a solution but I have not put it into practice.

What you have done in #1045 is you mixed your approach to a PL problem with the malicious file upload detection rule. And I do not like that mixing. Hybrid Paranoia Mode and Malicious File Upload are two distinct things and they should be kept separate. And if we come to a solution with the Hybrid Paranoia Mode, it will affect all rule files.

Then I have technical issues with your approach:
- In 900001, you assume that the engine is 'on'. Maybe it is 'DetectionOnly' but you do not know and you overwrite the state.
- Your switching of the Engine state is really complicated - and does this really work in scoring mode?
- You are accepting illegal values for the paranoia test level and silently bend it to work. I think you should break immediately with illegal values. The way you do it, the user may get unexpected behaviour.

Let me propose a different approach to the Hybrid Paranoia Mode:
- Every PL counts the score separately. (-> `anomaly_score_pl1`, `anomaly_score_pl2` etc.)
- In 949, create some rules that sum up the _blocking_ and the _testing_ anomaly score separately based on these values. We then block based on the blocking anomaly score and we report the testing anomaly score for the defined testing paranoia level.

**Comment by spartantri** [comment]
Hi @dune73 I removed all the hybrid stuff from 914, just put it there to see it working and as you may have guessed from the comments all that logic do not belongs on that file it is either setup or 901 the issue that remains is that it is not compatible with scoring as variable score are still modified, but the idea was making it work without touching any existing rule not touching every rule to have different score splits.

Now on the PL counts per level that's doable before May and adjusting the logic for 949 is also also easy as well.

Additionally, we can also verify that all PL tags are on every rule including those that make the skipafter and send you to the end of the level that way the user may simply remove an entire PL with a simple SecRuleRemoveByTag which is faster and lighter than loading additional rules that will never be triggered and for deployments where there are multiple reverse proxy chains it allows to do things like having PL2 in a frontal modsec server and PL3 o 4 in another behind it but entirely remove the lower PL1 and PL2 that have been already processed somewhere else and set in that server the detection only, that's just an example.
Another tag we miss is one per file something like CRS/914 so that all the file content can be removed by tag and let untouched the include rules/*.conf instead of doing SecRuleRemoveById 914000-914999.

Let's add a discussion topic on this for the monthly meeting.

**Comment by emphazer** [comment]
I really like the idea

**Comment by dune73** [comment]
That you for your cooperation @spartantri.

I see your points with regards to tagging. That makes sense. We had this idea to revise the tagging completely for 3.1, but never pulled it off.

As far as the blocking / testing PLs are concerned, I thought about this a long, long time. But I never put it to work because it touches everything and I never that the time to actually do it. It's now very late in the dev cycle for 3.1, but on the other hand, it's a major feature improvement that would ease things for many people. So if you want to do that work, I'd be more than happy to review.

**Comment by spartantri** [comment]
Some tags are easy to fix like the ones on PL, something like
```
sed -i "s|^(SecRule TX:PARANOIA_LEVEL \"@lt )([0-4])(.*)(skipAfter:END-REQUEST-.*)$|\1\2\3,tag:'paranoia-level/\2'\4|" rules/REQ*.conf
```
But all others will not be as easy as then we may also want to do tag ordering (totally cosmetic).
I may have a couple of looong plane trips coming that may let me handle this.

**Comment by spartantri** [comment]
Added PR #1052 to address this, this is only the split logic the rule files should be modified, it runs but needs testing and review.

**Comment by dune73** [comment]
Could you explain the logic that you are implementing in #1052? It is not quite what I described, I think and it's maybe better to agree on a technical mechanism before putting it in practice. Looking over #1052 makes it look fairly complicated and I wonder if a more simple approach would not be more effective and less error prone for our users.

**Comment by spartantri** [comment]
Hi @dune73 I find very useful have a working prototype (meant 20 min rule writing) to understand what it does than having just an abstract idea, this is not what you described it is just a global + per phase counters to tailor the crazy rules but let's discuss it to try to get something to improve the higher PL adoption. :)

**Comment by dune73** [comment]
We decided that we would squeeze this into 3.1 if we get a PR in working state until the next community chat.
I only found time to work on this today, but I think I have a working prototype. It follows my proposal above and has very simple logic / rules with minimal overhead. Trying to get this done by Monday.
(And sorry, I can't take part at the meeting on Monday. I'll be speaking at a conference.)

@spartantri : Sorry, I did not get back to you on this anymore. I was feeling I wanted to try out the mechanism I had in mind and I think it really does what you had in mind initially with quite simple and easy to understand changes.

**Comment by dune73** [comment]
This is done. In #1076. Please review.

**Comment by spartantri** [comment]
Hi @dune73 , yep it works for what I wanted, originally I didn't want to introduce hundreds of changes myself to introduce independent scores per level, good that someone had the time to do all the copy pasting on all files :+1: .

**Comment by dune73** [comment]
Thanks, @spartantri. I did the changes on most files with a script to ease the work a bit...

**Comment by dune73** [comment]
Closing in favour of #1076.
