### ISSUE TITLE
IIS application pool crashes when modsecurity set to PL 2

### ISSUE THREAD

**Issue by lordnsa** [SpiderLabs/owasp-modsecurity-crs#1058]
I installed mod security v2.9.2 with v3 rule set on server 2012 R2 IIS 8.5. It was working really well with out any issues. i previously tested level 2 with any issues. But after solving issues at level 1 now i can,t change the paranoia level to 2. IIS app pool crashes instantly when i change it to 2 but reverting it back to 1 solves the problem. 
This is what i get in the  event log. 

Faulting application name: w3wp.exe, version: 8.5.9600.16384, time stamp: 0x5215df96
Faulting module name: ModSecurityIIS.dll, version: 0.0.0.0, time stamp: 0x596e429a
Exception code: 0xc0000005
Fault offset: 0x000000000000d3f7
Faulting process id: 0xc6c
Faulting application start time: 0x01d3c800a617509d
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: C:\Windows\System32\inetsrv\ModSecurityIIS.dll
Report Id: e4c1249e-33f3-11e8-811b-00155d0c160a
Faulting package full name: 
Faulting package-relative application ID: 

My First thought was this caused by audit log. but after looking in to it i can confirm it's not the problem. 
Any help is appreciated.

**Comment by dune73** [comment]
That's a tough one. I reckon it is a ModSecurity issue, but I'm sorry it happens with CRS.

What is hard is that few people use ModSec on IIS, certainly nobody in the CRS team. Maybe ask on the ModSec user mailinglist. But you are quite much on your own, I'm afraid.

**Comment by csanders-git** [comment]
I'll give it a test to try and confirm, no sweat, but it'll be on Monday

**Comment by lordnsa** [comment]
Thank you dune and csanders for the reply. appreciate it very much.

**Comment by fgsch** [comment]
This definitely sounds like a ModSecurity issue. 

@lordnsa are you still experiencing this?

**Comment by dune73** [comment]
This is unlikely to be a CRS problem and we have not heard from the original reporter. Closing this.
