### ISSUE TITLE
Add PL1 tags to all PL1 rules

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1060]
PL2-4 are tagged. PL1 is not. We decided to do this during the April community chat.

**Comment by fgsch** [comment]
I will take this.

**Comment by annawinkler** [comment]
I'd like to help out with this work!

**Comment by dune73** [comment]
Very cool. Thank you for volunteering.

Do you see what needs to be done? If not, I'll be glad to help.

**Comment by annawinkler** [comment]
I don't yet know what to do - but I like diving in to learn 😺 I'll ask questions when I have them - thanks!

**Comment by annawinkler** [comment]
As I read https://www.modsecurity.org/CRS/Documentation/metadata.html#tags-about-paranoia-level it sounds like `any rule in a paranoia level greater than 1 will have a ‘paranoia-level’ tag` - does this issue mean that we wish to change that so that even PL1 rules will have `paranoia-level` tags?

**Comment by fzipi** [comment]
@annawinkler Yes, the idea is to have consistent naming everywhere. So we need to add the tag `paranoia-level` to all rules in PL1.

**Comment by dune73** [comment]
Exactly. It's really simple. Just add the new tag across all PL1 rules.

You can do it by hand, or if you want to be smart and learn hot new stuff, then use the msc_pyparser script by @airween at https://github.com/digitalwave/msc_pyparser to do this in a badge. It even comes with an example to manipulate tags in rules.
