### ISSUE TITLE
Maxmind GeoIP database has been discontinued

### ISSUE THREAD

**Issue by darrellenns** [SpiderLabs/owasp-modsecurity-crs#1063]
As it currently stands, CRS does not receive any GeoIP updates (it's stuck on the March 2018 version). CRS would need to be migrated to use the "GeoLite2" database in order to receive free updates.

> Updated versions of the GeoLite Legacy databases are now only available to redistribution license customers, although anyone can continue to download the March 2018 GeoLite Legacy builds. Starting January 2, 2019, the last build will be removed from our website. GeoLite Legacy database users will need to switch to the GeoLite2 or commercial GeoIP databases and update their integrations by January 2, 2019.

https://dev.maxmind.com/geoip/legacy/geolite/
https://support.maxmind.com/geolite-legacy-discontinuation-notice/

**Comment by csanders-git** [comment]
This has been discussed and is a major contributing factor to why geolite2 support was added to modsecv3 in the last push. Unfortunately, it does not appear there is much desire to add the same support for v2 modsec. For more information you can see this ticket https://github.com/SpiderLabs/ModSecurity/issues/1727

**Comment by darrellenns** [comment]
Perhaps some notes in the documentation/config sample/update script are in order? At the moment, there is nothing that would let users know that they aren't getting any updates.
