### ISSUE TITLE
Apache, latest mod_security, and reverse proxy

### ISSUE THREAD

**Issue by CoderJason123** [SpiderLabs/owasp-modsecurity-crs#1066]
Hello.  I went to test my installation and configuration per the instructions, and exactly nothing happened.  I want to explain, and I hope that in my use case, that I am not out of luck.

I use apache purely as a reverse proxy to an aspnet core application.  In addition, all port 80 requests are rewritten to port 443 (ssl/tls).  

I tried a few combinations of urls and what not, but they all positively returned my home page without incident.

Does the use of mod proxy prevent my use of mod security??  I feel like there's a gap I'm missing and searching did not yield any results.

Please advise.

**Comment by dune73** [comment]
You generally need to do simulate an attack to provoke a ModSec alert. A default installation is meant to block https://localhost/index.html?exec=/bin/bash

If this request passes, something is amiss. If you raise the ModSecDebugLogLevel to 9, this file should be filling up very quickly. If it does not, then ModSec / CRS is probably not active.

Generally, I advise you to follow the tutorials at https://netnea.com to make your first steps with ModSec. They are guaranteed to work and combine the setup with mod_proxy (which is no problem whatsoever).

Good luck!

**Comment by CoderJason123** [comment]
I appreciate what you are saying, it is encouraging.  What i did was follow the instruction in the guthub repo [https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/INSTALL](url).  

i went back and re-read them, as well as the NEA site.  I do not have plans to compile apache or mod security in my future.  Do i need to?

I did notice the modsecurity.conf file, on my machine, which owasp does not configure, was still named .example, renamed that, restarted apache, and no lock.  Mod security is loaded i can tell.

I literally followed those instructions to a tee, including the "includes" in the apache2.conf.  

The url example you provided, would be fully routes to the reverse proxy.  Seems like this bypasses mod security.  Please help, i feel i am within 1 missed step to making this work.

**Comment by CoderJason123** [comment]
Additionally, when i turned off the proxy, i received a 403, as expected!!  So at least some good news, it worked when i have proxy disabled.  Bad news, i need it fully enabled.

**Comment by CoderJason123** [comment]
so @dune73 -- it looks like the issue is that the default modsecurity.conf file has "detection only" enabled for secruleengine .... so this whole time, stuff has just been logging.  I realize the spider team doesn't have control over that file but it would be helpful to realize that that is a file to be concerned with and to change the setting.  My requests are being correctly blocked at this time.  thanks for your input.

**Comment by dune73** [comment]
Glad you sorted it out.

The first steps with ModSec are tough.

No, you do not need to compile this yourself. But if you follow my tutorials, I can guarantee that it will work - and that you will learn to understand the full stack. Afterwards you are ready to adopt to your local needs with precompiled binaries and specific needs.
