### ISSUE TITLE
XSS check in JSON body

### ISSUE THREAD

**Issue by 1Jesper1** [SpiderLabs/owasp-modsecurity-crs#1068]
Hello, I was interested if there is as rule for XSS checking in the POST request payload: Content-Disposition: form-data; name="json" or for checking XSS in a GET request with content-type: application/json;?

I'm trying to prevent stored XSS.

**Comment by dune73** [comment]
It depends on the rules. Many rule are selective and many are applied to the raw body as well.

I suggest you look into the XSS rule rule yourself. Or setup a test site and play with a few attacks.

If you see gaps in our coverage, please report and open issues here on GH.

**Comment by 1Jesper1** [comment]
Thanks for the fast reply, does the rules in the xss.config needs the JSON variable added? 
e.g. : SecRule ARGS_NAMES|ARGS|XML|JSON:

**Comment by dune73** [comment]
Now, that's not how it works with JSON.

Among the recommended rules that come with ModSecurity (outside of the CSR), there is a rule to trigger the JSON body processor. This will parse JSON and populate ARGS and ARGS_NAMES with the JSON payload in REQUEST_BODY.

I'm not totally sure with regards to exact handling of Content-Disposition and MIME formats. You need to try this out, I reckon the documentation does not cover it either.

**Comment by 1Jesper1** [comment]
Thanks! I saved the modsecurity.config again after adding `SecResponseBodyMimeType text/plain text/html text/xml` **application/json** and now it triggers.

**Comment by dune73** [comment]
Glad it works for you. If you see anything amiss, please report back here. We're very eager to close gaps.

**Comment by 1Jesper1** [comment]
Great to hear. Maybe add **application/json** to **SecResponseBodyMimeType** as default?

**Comment by dune73** [comment]
Setting this directive is done outside CRS. It's part of the modsec configuration you need to perform.

(I know it's annoying, but engine and rules are separate...)

**Comment by 1Jesper1** [comment]
Ah, I see. So I should request that improvement in the ModSecurity repo?

**Comment by dune73** [comment]
Yes, that would be a smart move.

**Comment by 1Jesper1** [comment]
Thanks for the help and the fast responses, I appreciate it.

**Comment by dune73** [comment]
You are most welcome. 

... and call this your lucky day, often issues go unanswered much longer. ;(
