### ISSUE TITLE
High CPU with CRS and ModSecurity 2.9.2 Apache 2.4

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/owasp-modsecurity-crs#1069]
Hello,
I've been doing analysis on a set of web servers configured the same behind a load balancer. I use a log aggregator solution to aggregate apache logs so that I can obtain metrics for speed.  We're seeing high CPU utilization on our web servers when send load to them. 
Without Modsecurity enabled, response times are 200ms max.  With ModSecurity and CRS, its 830ms.  With ModSecurity and CRS and response body disabled, its 780ms. 

During the load testing, we see the load spike and its all high cpu. Memory and Disk performance metrics look fine. I reviewed Trustwave's blog about performance: https://www.trustwave.com/Resources/SpiderLabs-Blog/ModSecurity-Performance-Recommendations/
I added ModSec perf log and ran tests and see that most time is spent in Phase 2. I used PERF_RULES to log anything > 1000 microseconds and then I analyzed the log data and found most of the rule catagories consistently over 1000 microseconds are:
category | count
941 | 18220
942 | 13439
932 | 5178
921 | 2921
943 | 1563
930 | 1323
920 | 960
931 | 754
951 | 580
959 | 473
901 | 247
209 | 231

Is this expected behavior?  Is there anything that can be done to improve performance? 
These servers have 8 vCPU Xeon 3Ghz and 5GB memory assigned. 

ModSecurity is compiled like this:
./configure --with-apxs=/opt/apache/bin/apxs --with-apr=/opt/apache/bin/apr-1-config --enable-pcre-match-limit=500000 --enable-pcre-match-limit-recursion=500000 --enable-pcre-jit --enable-lua-cache
(we increased pcre recursion because we kept seeing errors related to hitting the pcre limit) 

Thank you for your help.

**Comment by dune73** [comment]
This is unusually high. ModSec has a perf impact, also a significant one, but this seems too high at first sight.

I recommend you using the extended Access Log format described in my tutorials at netnea.com together with the integration of the ModSecurity performance data. This lets you identify those requests with the highest performance impact. 

In fact, I read your message as "max response time". And max time can me extremely high when the payload is big, complex whatever. So median response times are maybe more relevant. Again, my tutorials provide you with the necessary information / scripts on how to calculate that easily.

With this being said, you might be in a situation where you need to do performance optimization on some of the requests. Identifying them is essential, then you disable certain rules based on certain information about the client / request. Actually it is quite rare, you would need to do that with the exception of very big response files where problems such as your's are known. However, this does not seem to be your problem.

My guess is, you have a special set of payloads that distort your numbers and they will need to be handled specially. I am closing this issue. If you are sure, it's a more general CRS problem, then please re-open.

Good luck!

**Comment by ghost** [comment]
I do suspect some type of larger issue with CRS rules because it would appear to be related to 941 and 942 which are XSS and SQLI rules.  Those are obviously some of the most beneficial rules.  I've already set a RESPONSE rule to ignore Cookie headers because our application doesnt use cookies. I also disabled RESPONSE inspection.  These 2 alone helped reduce response times to 200ms avg.  Disabling 1 of the 2 rules files results in 40ms quicker response time.  Post Data for us isnt generally very large, so I'm puzzled why it adds so much overhead. 
Is there a way to exclude arg names from inspection?  This might help me narrow down the problem?

**Comment by dune73** [comment]
You can do the the following:

```
SecRuleUpdateTargetById 942110 !ARGS:foo
```

Make sure this is done _after_ you include the rule files.
