### ISSUE TITLE
block wordpress scanner

### ISSUE THREAD

**Issue by rayenmessaoudi** [SpiderLabs/owasp-modsecurity-crs#1071]
Hi ,
is there any rule to detect changing user agent in order to block wpscan tool.

**Comment by spartantri** [comment]
@rayenmessaoudi, Yes there is, well ... more like there was, look in old 2.2 CRS in the optional rule the one of session hijacking, you will need to start tracking user sessions to detect changes over time in the user-agent header BUT beware that some browsers may send request without UA header (e.g. when triggered by javascript).

If you want a simple block based on bad user agent the 3.1 rule 913100 will block WPScan default UA.

**Comment by rayenmessaoudi** [comment]
@spartantri Thanks :+1:
