### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by rayenmessaoudi** [SpiderLabs/owasp-modsecurity-crs#1072]
Hi all,
i have 2 questions :
1 )
how i can resolve this error
AH00526: Syntax error on line 40 of /usr/share/modsecurity-crs/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf:
Error creating rule: Failed to resolve operator: detectXSS
Action 'configtest' failed.
2)
i want to ask if there is known false positive rules for wordpress in order to exclure them

**Comment by dune73** [comment]
It looks like you are using an old version of ModSec that does not support the detectXSS operator.

There is a rule exclusion package for a default WordPress installation. See the documentation.

**Comment by rayenmessaoudi** [comment]
i installed modsecurity using the default package libapache2-modsecurity ?
i need to install the v2.9.2 version how to check which version i had ?

**Comment by dune73** [comment]
ModSec writes its version into the error-log during startup.

**Comment by rayenmessaoudi** [comment]
yes i found it i have the v2.9.1 how to upgrade to the v2.9.2 ?

**Comment by dune73** [comment]
Ooops. v2.9.1 should have the detectXSS alright. Could you please submit your full error-log from the moment the server starts?

If you want 2.9.2, you need to look for backports for your distribution or compile yourself.

**Comment by rayenmessaoudi** [comment]
sorry i reinstalled my vps i lost the error log :( cauz i want now to install the v2.9.2 i don't know why when i installed this package apt-get install libapache2-mod-security2 i got the version 2.9.1 not 2.9.2 ?

**Comment by rayenmessaoudi** [comment]
problem solved i installed v2.9.2 successfully for the default wordpress package do you mean this file -WORDPRESS-EXCLUSION-RULES.conf ??

**Comment by dune73** [comment]
Yes, please see the documentation in crs-setup.conf.
