### ISSUE TITLE
Add some default sanitise rules?

### ISSUE THREAD

**Issue by tunetheweb** [SpiderLabs/owasp-modsecurity-crs#1073]
Given the recent [GitHub ](https://www.bleepingcomputer.com/news/security/github-accidentally-recorded-some-plaintext-passwords-in-its-internal-logs/)and [Twitter](https://blog.twitter.com/official/en_us/topics/company/2018/keeping-your-account-secure.html) accidental password logging leaks should we add some rules for this to the CRS to try to make this sort of thing less likely?

It has always worried me that add ModSecurity - presumably for security purposes - opens up a risk of information leakage as it now allows full logging of the request easily which web servers traditionally do not make easy.

For example if you have the following request and the cookie header flags a rule then the whole request, including the password, would be added to the audit log whereas only the cookie would be added to the error log:

    POST /login HTTP/1.1
    Host: www.example.com
    Cookie: BADPAYLOAD

    username=myuser&password=myPassword

I think this is easily solved with a rule like this:

    SecRule ARGS_NAMES "p.*word" "phase:5,id:12345,nolog,pass,sanitiseMatched,t:lowercase"

There are very little downsides to this. The false positive rate should be low, and worst case scenario is that we just miss a little logging.

Now it's true that Sanitise commands only work in the Audit log and [not the Error log](https://github.com/SpiderLabs/ModSecurity/issues/1132) (and it would be great if ModSecurity would fix this btw), and also not the debug log. However this small step is at least reducing the likelihood, and I would argue it's less likely a password would be in the error log anyway as 1) password fields shouldn't flag if rules are set up correctly (e.g. assuming they are hashed before going near the database then they shouldn't be subject to SQL injection rules so no need to run them against this field as just restricts passwords for no reasons and leads to more false positives)  and 2) as per above, they can be leaked with other rules on other arguments which may be more likely to flag (e.g. cookies). So to me the audit log is more dangerous and also easily fixed with a rule like above.

I would even take this further and add similar rules for other common sensitive information (e.g. payment information or social security numbers):

    #Only show first and last 4 chars of Credit Card numbers (First 4 chars give type - VISA or Mastercard)
    SecRule ARGS "@verifyCC \d{13,16}" "phase:5,id:12346,nolog,pass,sanitizeMatchedBytes:4/4,capture"
    #Mask ccv/cvn fields
    SecRule ARGS_NAMES "@contains cvv" "phase:5,id:12347,nolog,pass,sanitiseMatched,t:lowercase"
    SecRule ARGS_NAMES "@contains cvn" "phase:5,id:12348,nolog,pass,sanitiseMatched,t:lowercase"
    #Mask iban fields
    SecRule ARGS_NAMES "@contains iban" "phase:5,id:12349,nolog,pass,sanitiseMatched,t:lowercase"
    #Mask social security fields
    SecRule ARGS_NAMES "@verifySSN \d{3}-?\d{2}-?\d{4}" "phase:5,id:12350,nolog,pass,sanitiseMatched,t:lowercase"

Oh and I know [sanitizeMatchedBytes doesn't work properly](https://github.com/SpiderLabs/ModSecurity/issues/841) btw but keep using it in the hope it'll be fixed one day :-)

Some of these may be more likely to have false positives so could be further refined (e.g. ccv and cvn only have 3 characters AFAIK).

Should this be done in ModSecurity itself rather than CRS? Potentially, as you can also leak passwords just by turning on the audit log with no rules, or by using a different rules set to CRS. They could add it to modsecurity.conf for example. But not sure everyone uses that. Personally I prefer them in CRS to be honest but open to others opinion on this.

Thoughts?

**Comment by dune73** [comment]
I am torn.

I do not like CRS to influence things outside its ruleset. There is the ModSec configuration of your server and there is the CRS configuration. CRS tries to do very few things that change the ModSec behaviour like SecDefaultAction and it does not change the Audit Log format on purpose. This issue would change the ModSec behaviour. That's not good.

On the other hand, the issue is real and ModSec development seems to be postponing things here. The core issue that this proposal solves is that the AuditLog logs the password whenever there is a FP with the request regardless of the password. That's quite bad.

But I also do not like the fact that we have a hard time defining which variable names we should cover with this. `p[a-z]*word`? How about arg name `pass`? You mention CC, with GDPR a ton springs to mind and myriads of rules jump to my mind. It's definitely an integration thing that's better solved in close interaction with developers.

Ideally ModSec would:
* [fix the error-log](https://github.com/SpiderLabs/ModSecurity/issues/1132)
* add 1-2 rules to the recommended-rules with the most common args

**Comment by lifeforms** [comment]
Oh, this is a frequent complaint of mine too.

CRS appears to be the common denominator among free WAF installs, so we do have an opportunity to address this problem. 

I agree with the principle that CRS should prefer not to modify ModSec engine settings. But, the spirit of that principle is not to cause "spooky action at a distance" that's hard to trace and debug or could override a user's reasonable wishes. We shouldn't force engine changes upon administrators, but we have `crs-setup.conf`, and we could expose this functionality as a tweakable option. Power users who want to take care of sanitization themselves, who want to add more fields, or who want to disable it, could set the option.

I would support it if we'd do that.

**Comment by lifeforms** [comment]
I'll put this on hold, because ModSec 3.0.3 does not have `sanitiseMatched` operator yet, so currently we cannot reasonably activate some of these sanitizations without breaking part of the userbase: https://github.com/SpiderLabs/ModSecurity/issues/1898
