### ISSUE TITLE
rule syntax error

### ISSUE THREAD

**Issue by rayenmessaoudi** [SpiderLabs/owasp-modsecurity-crs#1074]
Hi guys i m not able to restart apache due to this error
my modsecurity version is 2.9.2
AH00526: Syntax error on line 40 of /usr/share/modsecurity-crs/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf:
Error parsing actions: Unknown action: \\
Action 'configtest' failed.

error log
https://gist.github.com/rayenmessaoudi/4752385111f54cd265449dcdcbf1f27a

**Comment by lifeforms** [comment]
This is a known Apache bug in old Apache versions. The best course of action is to upgrade to Apache 2.4.11 or later, but we also have a workaround script if that's impossible.

See https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0.0-rc2/KNOWN_BUGS
