### ISSUE TITLE
Unable to disable rule on string match for .axd

### ISSUE THREAD

**Issue by mparsonspcis** [SpiderLabs/owasp-modsecurity-crs#1075]
Hello, my application uses .axd files which are by default blocked in a few rules.  Specifically, I'm triggering 920440 and have been unable to address the issue by creating my own rules to allow it.  My attempts are below, and then below that is the log.  Can anybody provide any suggestions on how to disable only the .axd string, without disabling the entire rule?

**My failed attempts:**
SecRuleUpdateTargetById 920440 "!ARGS:.axd"

SecRule REQUEST_FILENAME "@beginswith /ScriptResource.axd" \
"phase:2,nolog,pass,id:10000,ctl:ruleRemoveTargetByID=920440;TX:extension"

SecRule REQUEST_URI "@beginswith /ScriptResource.axd" \
"phase:2,nolog,pass,id:10000,ctl:ruleRemoveTargetByID=920440;TX:extension"

**Log:**
ModSecurity: Warning. String match within ".asa/ .asax/ .ascx/ .axd/ .backup/ .bak/ .bat/ .cdx/ .cer/ .cfg/ .cmd/ .com/ .config/ .conf/ .cs/ .csproj/ .csr/ .dat/ .db/ .dbf/ .dll/ .dos/ .htr/ .htw/ .ida/ .idc/ .idq/ .inc/ .ini/ .key/ .licx/ .lnk/ .log/ .mdb/ .old/ .pass/ .pdb/ .pol/ .printer/ .pwd/ .resources/ .resx/ .sql/ .sys/ .vb/ .vbs/ .vbproj/ .vsdisco/ .webinfo/ .xsd/ .xsx/" at TX:extension. [file "C:\/Program Files\ModSecurity IIS\rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "1075"] [id "920440"] [rev "2"] [msg "URL file extension is restricted by policy"] [data ".axd"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS/POLICY/EXT_RESTRICTED"] [tag "WASCTC/WASC-15"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "WEBQA01"] [uri "/WebResource.axd?d=K3rgOUcO-xtnBUWvrxCVcGKTsXZUdp1tjjueL57Jr1lnMA54ZwzIt8vKjV132tXTYwl_xnSqN5V9RvyaNmQfXB5f1U01&t=636511160826842555"] [unique_id "17654110541440022223"]

**Comment by dune73** [comment]
Hi @mparsonspcis, you should be able to edit the variable `tx.restricted_extensions` in `crs-setup.conf` to no longer restrict `.axd`.

**Comment by mparsonspcis** [comment]
Thanks for the info, but can you please clarify how?  I do not see any reference to ID 920440 in the crs-setup.conf file.

**Comment by dune73** [comment]
It's not the rule 920440 you need to edit in said file, but the variable I mentioned.

**Comment by mparsonspcis** [comment]
Got it.  Apologies for my arrogance, but do I need to uncomment the entire rule, or just remove the .axd filetype?  I'm new to modsecurity, and this is my first foray into tuning the rules.


#SecAction \
# "id:900240,\
#  phase:1,\
#  nolog,\
#  pass,\
#  t:none,\
#  setvar:'tx.restricted_extensions=.asa/ .asax/ .ascx/ .axd/

**Comment by mparsonspcis** [comment]
Sorry about that, those lines with capatilization included an "#" in front of them so made them bold/large.
