### ISSUE TITLE
CRS Community Chat Agenda for May 7

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1077]
I'm currently in Berlin at a conference and I won't attend the chat on Monday. But here are some agenda entries:

* Travis fails due to docker issues
* Please review PR #1076 (In April we stated this could make it to 3.1 if a mergable PR was ready by May 7)
* Release of 3.1 (Let's do a RC first.)
* More open PRs
* Community Summit on July 4 is coming along nicely a dozen confirmed participants from various companies. CPanel promised to sponsor the dinner. Official registration will be open soon via AppSecEU website.

**Comment by csanders-git** [comment]
docker was fixed, apparently github changed their cert (or we changed our docker image) so that certs weren't included... anyway minor change fixed it -- should be working now!

**Comment by csanders-git** [comment]
All old PR's are closed, 4 left.

**Comment by spartantri** [comment]
Just arrived from the airport, I missed the meeting, will check the meeting notes later :)
