### ISSUE TITLE
Clean up `tx.anomaly_score`

### ISSUE THREAD

**Issue by studersi** [SpiderLabs/owasp-modsecurity-crs#1083]
After discussing PR https://github.com/SpiderLabs/owasp-modsecurity-crs/pull/1076 with @dune73, it became clear that `tx.anomaly_score` could use refactoring.

While going through all the rules, the variable is reused multiple times for different purposes. It might be better to use separate variables for each purpose and only collect the total in`tx.anomaly_score` at the very end.

**Comment by fgsch** [comment]
Hi there. We'll certainly welcome a PR to clean up tx.anomaly_score.
As this issue has not been updated in over a year and the next steps are clear I'm going to close it for now.
