### ISSUE TITLE
False positive when copying iubenda js into Wordpress backend

### ISSUE THREAD

**Issue by axettone** [SpiderLabs/owasp-modsecurity-crs#1097]
I was inserting this code from Iubenda Privacy Solutions, using Wordpress.
==
<br />
<a href="https://www.iubenda.com/privacy-policy/MY_POLICY_ID" class="iubenda-black iubenda-embed " title="Privacy Policy">Privacy Policy</a> <script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src="https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script>
==
Rules affecting the FP are: 932130, 941100, 941110, 941160, 941180

**Comment by lifeforms** [comment]
Hi @axettone, thanks for the report!

Could you paste the ModSec audit log entry for your false positive?
It contains useful information like the URL and parameters used.

**Comment by axettone** [comment]
I changed the domain and the policyid to 999999. I also removed cookie infos and ips.
[20180521-123947-WwK@E9TVCPJ2Lz9vn7D3rwAAAAs.txt](https://github.com/SpiderLabs/owasp-modsecurity-crs/files/2022664/20180521-123947-WwK.E9TVCPJ2Lz9vn7D3rwAAAAs.txt)

**Comment by lifeforms** [comment]
I've tried to reproduce, but it seems that this request is already fixed by our WordPress exclusions!

If you activate rule 900130 in `crs-setup.conf` by removing the comment chars `#`, you will enable our WordPress exclusions, and you should be good!

```
SecAction \
 "id:900130,\
  phase:1,\
  nolog,\
  pass,\
  t:none,\
  setvar:tx.crs_exclusions_drupal=0,\
  setvar:tx.crs_exclusions_wordpress=1"
```

If this doesn't help, please reply with the new part of the ModSec audit log and we'll check it out.
