### ISSUE TITLE
Using the danish letters æ ø å and so forth - will tricker SQL injection signatures in contact forms.

### ISSUE THREAD

**Issue by Ovdach** [SpiderLabs/owasp-modsecurity-crs#1099]
Using the danish letters æ ø å and so forth - will tricker SQL injection signatures in contact forms.

Please create support for more launguages than english.

**Comment by lifeforms** [comment]
Hi @Ovdach, I hope we can fix this, but it might be due to features in ModSecurity itself.

Nevertheless, to learn more about your case, could you paste the full ModSec audit log entry? (Removing any personal data)

**Comment by fgsch** [comment]
There has not been an update in over a year. 

@lifeforms Can we close it as Timed out?

**Comment by lifeforms** [comment]
Agreed, without log information it is hard to say what exactly has happened here. We will close, but please reopen the issue if more information is available!
