### ISSUE TITLE
Wordpress admin-ajax.php issues

### ISSUE THREAD

**Issue by Mag8891** [SpiderLabs/owasp-modsecurity-crs#1100]
Hi there,

I have installed OWASP rules set including REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf

However, I get 500 error on admin-ajax.php when trying to use backup plugin through admin page

Is there any information how to overcome this issue?

I can provide access to my AWS instance if required.

Thanks for your help.

Best regards,
Taya

**Comment by csanders-git** [comment]
Hey Taya, can you let us know what the mod security error log or audit log says?

**Comment by Mag8891** [comment]
Hi, the module us called duplicator-pro https://snapcreek.com/duplicator/

here are the error and modsec_audit logs you can download at the link below
they are from /var/log/nginx folder, I am not sure how to read error log but see issues in audit log

https://cloud.mail.ru/public/Ln5T/M8HqZnh9K

there is also another error log here
error_log /var/www/mysite/logs/error2.log;

As for memory size errors below, I was able to start scan of my website by increasing the memory limit to 850M, however, I don't understand what is the issue as I have tried this on plain server without any additional nginx modules installed and the plugin works fine even with 512M memory limit in php.ini
But even after increasing memory limit it still freezes when I am trying to import older backup for installation

2018/05/25 10:49:08 [error] 3453#3453: *21 FastCGI sent in stderr: "PHP message: WordPress database error MySQL server has gone away for query UPDATE `wp_options` SET `option_value` = '{\"Created\":\"2018-05-25 10:48:57\",\"Version\":\"3.7.1.2\",\"VersionWP\":\"4.9.6\",\"VersionDB\":\"10.1.29\",\"VersionPHP\":\"7.2.5-1+ubuntu18.04.1+deb.sury.org+1\",\"VersionOS\":\"Linux\",\"ID\":null,\"Name\":\"20180525_mysite\",\"Hash\":\"0b0ffc91c1ade32f2440_20180525104857\",\"NameHash\":\"20180525_mysite_0b0ffc91c1ade32f2440_20180525104857\",\"Type\":0,\"Notes\":\"\",\"StorePath\":\"\\/var\\/www\\/cclub\\/wp-content\\/backups-dup-pro\\/tmp\",\"StoreURL\":\"https:\\/\\/mysite\\/wp-content\\/backups-dup-pro\\/\",\"ScanFile\":\"20180525_mysite_0b0ffc91c1ade32f2440_20180525104857_scan.json\",\"timer_start\":-1,\"Runtime\":null,\"ExeSize\":null,\"ZipSize\":0,\"Brand\":\"Default\",\"Brand_ID\":-2,\"ziparchive_mode\":null,\"Archive\":{\"ExportOnlyDB\":0,\"FilterDirs\":\"\",\"FilterExts\":\"\",\"FilterFiles\":\"\",\"FilterDirsAll\":[\"\\/var\\/www\\/cclub\\/wp-content...
PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 128240952 bytes) in /var/www/mysite/wp-content/plugins/query-monitor/classes/Collector.php on line 40
PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 78266368 bytes) in Unknown on line 0" while reading response header from upstream, client: 92.237.96.21, server: mysite, request: "POST /wp-admin/admin-ajax.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "mysite", referrer: "https://mysiteb/wp-admin/admin.php?page=duplicator-pro&tab=packages&inner_page=new2"
2

so I am wandering can I exclude anything this module does from admin side duplicator-pro  from being checked with modsecurity if it will be safe, as I trust this module it meant to do the backups and it is important that nothing blocks it, so I can be sure I can have my backups and will be able to restore them, it also does the site scanning prior the backup and it also causes 500 error admin-ajax. at the moment upon uploading the older backup it freezes on 100% instead of launching the installer.
You can enable import option by going to duplicator settings/ features/ and need to tick 
Design Concepts at the very buttom.

site scanning issues are
/wp-admin/admin.php?page=duplicator-pro&tab=packages&inner_page=new1
/wp-admin/admin.php?page=duplicator-pro&tab=packages&inner_page=new2
and older backup import issues
/wp-admin/admin.php?page=duplicator-pro-tools&tab=import

thank you.


also a bit off topic but this page doesn't work
http://www.modsecurity.org/CRS/Documentation/configuration.html
I am trying to understand if maybe I have missed something on the install, reading here
http://www.modsecurity.org/CRS/Documentation/install.html
In addition to csr-setup.conf.example there are two other .example files within our repository. These files are: rules/REQUEST-00-LOCAL-WHITELIST.conf.example and rules/RESPONSE-99-EXCEPTIONS.conf.example. 
however when I go to owasp-modsecurity-crs/rules/  I can't see REQUEST-00-LOCAL-WHITELIST.conf.example  or is it the same as REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf just different name?

my modsecurity includes include 
include modsecurity.conf
include owasp-modsecurity-crs/crs-setup.conf
and requests from 900-999

**Comment by dune73** [comment]
I see a fatal PHP error above. And you work on NGINX, which is a new piece of code. I do not know about the interference, but given it is a memory problem, maybe ModSecurity plays a role in this.

Take a look at https://www.netnea.com/apache-tutorials/ to learn how to exclude certain rules. The modsecurity.org documentation you quote are seriously outdated (and broken apparently). Better stick to my site netnea.com for beginner's guidance.
