### ISSUE TITLE
Issue loading CRS 3.1/Dev on Nginx 1.13.12

### ISSUE THREAD

**Issue by cattlemantech** [SpiderLabs/owasp-modsecurity-crs#1104]
I am using owasp-modsecurity-crs-3.1-dev since i had an issue with 3.0/master (#1032 ). But i am getting different errors as below: please help:

nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/owasp-modsecurity-crs-3.1/rules/REQUEST-910-IP-REPUTATION.conf. Line: 70. Column: 22. This version of ModSecurity was not compiled with GeoIP support.  in /etc/nginx/conf.d/nginx-ext.conf:19

nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/owasp-modsecurity-crs-3.1/rules/REQUEST-912-DOS-PROTECTION.conf. Line: 187. Column: 29. Expecting an action, got:  ,\ in /etc/nginx/conf.d/nginx-ext.conf:19

nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/owasp-modsecurity-crs-3.1/rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf. Line: 333. Column: 38. Expecting an action, got:  ctl:requestBodyProcess▒ in /etc/nginx/conf.d/nginx-ext.conf:19

nginx: [emerg] "modsecurity_rules_file" directive Rules error. File: /usr/local/owasp-modsecurity-crs-3.1/rules/RESPONSE-954-DATA-LEAKAGES-IIS.conf. Line: 40. Column: 109. Expecting an action, got:  ,\ in /etc/nginx/conf.d/nginx-ext.conf:19
c

if i remove these 4 rules, i can able to use the CRS 3.1/dev.

for 1st issue, i checked and below are the GeoIP package installed in my Cent OS 7 server. 
GeoIP-1.5.0-11.el7.x86_64
GeoIP-devel-1.5.0-11.el7.x86_64

I have compiled using above packages, but still throwing error 1 with IP-REPUTATION rule.
please help resolving these issues - especially issue 1 & 2 as we are not using JAVA, IIS. thank you.

**Comment by csanders-git** [comment]
I reopened individual issues on the ModSecurity project as the 'dev' branch changes haven't been merged into master yet. But this is very much a ModSecurity problem and not a CRS project. As a result I am closing, but if you need more support on the modsec side please be sure to include me.
