### ISSUE TITLE
ModSec 3.0 fails on new rule 901350 (enforce body processor URLENCODED)

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1120]
Houston, we have a problem.

ModSec 3.0 implements `ctl:requestBodyProcessor=JSON`, but fails to run with `ctl:requestBodyProcessor=URLENCODED`.

I have opened an issue over at ModSec: https://github.com/SpiderLabs/ModSecurity/issues/1797

This issue could mean, that we do not support ModSec 3.0 with our 3.1 release. I hope it gets fixed in ModSec 3.0, or ModSec and our project both are in a tricky situation.

**Comment by csanders-git** [comment]
I suppose i should just switch the NGINX Docker to be libmodsec ;)

**Comment by dune73** [comment]
I guess so. Actually I've seen other regressions too, but that's more semantic and not missing features, I think. I need to investigate this sooner or later.

**Comment by spartantri** [comment]
Crap! I use it in the but only in Apache with no issues, I have no nginix to test, we are in a bad spot here, there are plenty of missing fetures in modsec3 and modsec2 is missing bugfixes and apparently there will be no efforts to support new stuff :'(

We may have to do an include for Apache (faster and better so far) and another for nginix with 100% compatible stuff

**Comment by victorhora** [comment]
Hey folks,

I'm on this. Adding support for ctl:requestBodyProcessor=URLENCODED should be fine. 

Apologies I've failed to provide a feedback on this thing before as we agreed on the meeting in May. I'll provide updates here.

Thanks for your patience.

**Comment by dune73** [comment]
Thank you @victorhora .

Yes, I agree with you @spartantri. We're between a hammer and a hard place here. ModSec 2.9 is degrading slowly and 3.0 is nowhere near production quality in my eyes.

**Comment by spartantri** [comment]
:'( I can see modsec 2.9 forking in the near future if this trend continues

**Comment by dune73** [comment]
There is a lack of ModSec devs to fork IMHO. Forking 2.9 would mean to abandon years of work on 3.0. 

I really like the basic direction of 3.0, I just do not like the way it was done - and the way it is being done.

So do you seriously see that happen?

**Comment by csanders-git** [comment]
I too would be surprised, once modsec 3 gets a little closer in terms of functionality I think you'll see less issue. A big missing part for many is also sanitize

**Comment by christiantreutler-avi** [comment]
There is an issue we are currently looking at which is concerning the CRS 3.1 release I think. The ruleRemoveTargetByID does not take ranges, which are needed for the NextCloud rules.
@dune73 The subset of features needed for CRS are mostly ok in modsec 3. Everything else is unchartered territory from my point of view.
Hopefully if we can get the abstracted language of the ground, we can think of much easier implementation models of the same CRS protection without all the baggage.

**Comment by dune73** [comment]
This rings a bell, @christiantreutler-avi. Thanks for the reminder.

**Comment by emphazer** [comment]
@dune73 
well, i could do a PR for the modsec   v3 nextcloud id range issue

**Comment by dune73** [comment]
That would be helpful, #emphazer.

**Comment by christiantreutler-avi** [comment]
@emphazer PR for CRS or PR for modsec 3?

**Comment by emphazer** [comment]
@christiantreutler-avi PR for CRS

**Comment by victorhora** [comment]
Initial support for ctl:requestBodyProcessor=URLENCODED at PR https://github.com/SpiderLabs/ModSecurity/pull/1807

**Comment by dune73** [comment]
Thank you @victorhora. 

That's quite a change set. Wish I had the time to test this, but I am too busy.

What is the time frame for ModSec 3.0.3?

**Comment by victorhora** [comment]
You're welcome @dune73. The buildbots suggests that the patch is fine and I also ran some tests here that tells me that should solve the issue. I'll see about also adding a test case for this one to make it easier for others to test. Should be merged to master soon I think.

About 3.0.3, we have a [public milestone](https://github.com/SpiderLabs/ModSecurity/milestone/12) set with a due date of June 25th. I'm not sure if we will make it as there's some tricky issues there for  fixing in such a short notice and we are also overly busy :(

**Comment by dune73** [comment]
I see. Thank you for the info. I'm relieved we have a solution here. Would have been a roadblock otherwise.

Closing this in favor of the fix in ModSec!

(Btw: How do you see adding our new 901350 to the list of recommended ModSec rules?)

**Comment by victorhora** [comment]
I'm not sure about enforcing URLENCODED by default @dune73. I see positive and negative aspects about it. But I'd say if it's something that most would like to see, an issue about it should be opened for discussion and adding it to the file but leaving disabled by default can also be an option.

**Comment by dune73** [comment]
Thank you for sharing your view. I agree that there are PROs and CONs. Having it in the recommended rules and if even as an option, would ease things for us, as it is a setting that changes the behavior of the engine and we would like CRS to have no side effects if possible.

If it is part of the recommended rules, then we can simply point to said rules in our documentation and tell people to enable it for a really secure setup.

I'll open an issue.
