### ISSUE TITLE
Review usage of tx.0

### ISSUE THREAD

**Issue by fgsch** [SpiderLabs/owasp-modsecurity-crs#1121]
We have many rules (grep says 140) using something along this line:

`setvar:'tx.%{rule.id}-OWASP_CRS/LEAKAGE/ERRORS-%{matched_var_name}=%{tx.0}'`

As found by @dune73 in #1107, `%{matched_var}` would be a better fit.
There is also the question about how useful this is.

**Comment by dune73** [comment]
I'm not a fan of this construct and I have played around with removing this altogether. It was needed in a special construct in 949xxx in former versions, but that construct is gone and I think we could kick it together with the `setvar:'tx.msg=%{rule.msg}'` construct (the latter is used in 980xxx).

Thoughts?

CC @csanders-git, @lifeforms

**Comment by fgsch** [comment]
Yes! I can open a PR 😁

**Comment by fgsch** [comment]
PR opened

**Comment by DenysFrasinich** [comment]
Hello!
I have some lua scripts which are called by rules at logging phase to push events from modsecurity to external system.   
What should i use as alternative of TX.INBOUND_TX_MSG and TX.MSG to get pretty textual blocking reason in lua scripts?

**Comment by dune73** [comment]
Hi @DenysFrasinich, you are the first one to report to actually using these variables. Our call for opinions went unheard for many weeks, so we decided to axe them.

I do not see a way to get this information. However, ModSec is only writing the audit log in the logging phase AFAIK, maybe lua can lay its hand on this info that way. But I do not really know.

**Comment by fgsch** [comment]
This has been completed.
