### ISSUE TITLE
False Positive 941120. 

### ISSUE THREAD

**Issue by jonlupo** [SpiderLabs/owasp-modsecurity-crs#1122]
We are using ModSec 2.9.2 with CRS 3.0.2. Running SAP Portal behind an Apache reverse proxy. Which uses base64 encoded data in requests.

The rule is matching the "ON" keyword in the base64 string and its returning a 403 page. 
I see in previous issue #675 this was solved by changing `on\w+` to `on[a-zA-Z]+` however it is still throwing a false positive in my case.

[log.txt](https://github.com/SpiderLabs/owasp-modsecurity-crs/files/2081621/log.txt)

**Comment by dune73** [comment]
Why don't you write a rule exclusion for said rule?

Base64 encoded payloads are hard since they can match random regexes.

**Comment by jonlupo** [comment]
I created a rule exclusion for it but I was hoping to see if there was a way to fix the regex for anyone else who might come across this issue.. It also would be handy in catching XSS attacks.

Does that mean there are no good ways to tweak the rule?

**Comment by jonlupo** [comment]
Going ahead and closing this issue. Since I was able to resolve it using an exclusion rule. Can't think of any better solutions...
