### ISSUE TITLE
 Modsecurity + Nginx Only warnings in log file, not blocking attacks

### ISSUE THREAD

**Issue by AnnuA** [SpiderLabs/owasp-modsecurity-crs#1128]
I have Nginx 1.14.0, Modsecurity 3 with nginx connector. Owasp 3.0.0. Ubuntu -14.04.

Modsecurity is not blocking attacks although warning logs can be seen in /var/log/modsec_audit.log.
Also, I do have SecRuleEngine On in my modsecurity.conf.
Also, replaced "Include /usr/local/owasp-modsecurity-crs/rules/*.conf" with list of individual conf file as answered in SpiderLabs/owasp-modsecurity-crs#777 .
Why it is not blocking the attack?

Below is my /etc/nginx/conf.d/default.conf file contents:

```
server {
    listen       80;
    server_name  localhost;

    modsecurity on;
    modsecurity_rules_file /etc/nginx/modsec/main.conf;

    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        proxy_pass http://192.168.100.145:8080/;
    }
```
Is it something related with anomaly score? because attack is blocked when Self-contained mode is enabled instead of Anomaly mode(Default) in /usr/local/owasp-modsecurity-crs-3.0.0/crs-setup.conf.

This is the same issue as https://github.com/SpiderLabs/ModSecurity-nginx/issues/113.
I didn't know where to post so posting here as well as I am badly stuck.
I have attached modsec_audit.log.
[modsec_audit.log](https://github.com/SpiderLabs/owasp-modsecurity-crs/files/2105888/modsec_audit.log)

**Comment by dune73** [comment]
Thank you for reporting and sorry for the inconvenience.

Can you show us your main.conf, please?

**Comment by fernandogalves** [comment]
Annua, 

Did you check the SecDefaultAction value in the crs-setup.conf file? because the default value don't block attacks, i.e.:

SecDefaultAction "phase:1,log,auditlog,pass"
SecDefaultAction "phase:2,log,auditlog,pass"

I was with a problem like you, and I changed the values to:

SecDefaultAction "phase:1,log,auditlog,deny,status:403"
SecDefaultAction "phase:2,log,auditlog,deny,status:403"

After, I restarted the apache and everything worked!

I hope to help you!

**Comment by AnnuA** [comment]
@dune73  I have attached my main.conf file.
[main.conf.txt](https://github.com/SpiderLabs/owasp-modsecurity-crs/files/2107925/main.conf.txt)

@fernandogalves  I have tried doing what you mentioned and it works but it changes the CRS  to "Self-Contained mode", but I want to keep it in "Anomaly scoring mode" only which is the default one.

**Comment by dune73** [comment]
Does your rule 1234 block? If it does, then 949110 should block too with the only difference that the blocking is based on the anomaly score and not on a parameter.

Your request 152897962388.766237 should definitely be denied, but 949110 is not being triggered.

**Comment by AnnuA** [comment]
Yes, 1234 is blocking. I could not see rule 949110 in the modsec_audit.log file.
I had used attack "http://192.168.100.145/?param=%22%3E%3Cscript%3Ealert(1);%3C/script%3E".
I have also tried some other sql injection attack, but even those are not getting blocked.
Where should I look into?

**Comment by dune73** [comment]
Please add the following rule to your main.conf, after all the includes:

```
SecRule TX:ANOMALY_SCPRE "@unconditionalMatch" "id:1235,phase:2,pass,log,auditlog,msg:'Anomaly score at the end of phase 2: %{MATCHED_VAR}'"
```

Then repeat your attack request, and report on the output of the rule 1235. It should trigger on every request and report the anomaly score.

**Comment by AnnuA** [comment]
Adding this rule has no effect. modsec_audit.log is not showing anomaly score. Just for your reference attaching files.
[main.conf.txt](https://github.com/SpiderLabs/owasp-modsecurity-crs/files/2122207/main.conf.txt)
[modsec_audit.log](https://github.com/SpiderLabs/owasp-modsecurity-crs/files/2122209/modsec_audit.log)

**Comment by dune73** [comment]
Seems I have a typo (ANOMALY_SCPRE.) And you might be affected by this bug: https://github.com/SpiderLabs/ModSecurity/pull/1810

**Comment by theraw** [comment]
I'm having the same problem.
did a fresh install right now and i'm getting just warns no deny :confused:

My configuration was the same as my old server which/where modsec was installed long time ago and it's working..

**Comment by csanders-git** [comment]
I have tested this using the latest CRS NGINX Docker image (see PRs for more detail). Beyond DOS protections being broken, and URLENCODE not being valid as a request processor, it seems the rules are in working order on NGINX.

**Comment by csanders-git** [comment]
Please reopen if the problem persists
