### ISSUE TITLE
When uncommented the rule to change paranoia level, httpd fails to start

### ISSUE THREAD

**Issue by AnnuA** [SpiderLabs/owasp-modsecurity-crs#1129]
I have installed apache-2.4.6. Owasp CRS - 3.0.2.

I want to change the default paranoia level, so I uncommented following ruke in crs-setup.conf.
```
SecAction \
  "id:900000,\
   phase:1,\
   nolog,\
   pass,
   t:none,\
   setvar:tx.paranoia_level=1"
```
Now, when I restart httpd, it fails and log shows following error:
"httpd[14633]: Invalid command 't:none,', perhaps misspelled or defined by a module not included in the server configuration"

**Comment by csanders-git** [comment]
There should be a slash (line continuation after pass)

**Comment by AnnuA** [comment]
Ohhh Thankyou so much. I don't know how I missed it.
