### ISSUE TITLE
FP due to CloudFlare WAF token parameter

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#1141]
Sometimes CloudFlare WAF adds the `__cf_waf_tk__` query parameter to an URL.

This can have a form of:

```
ARGS:__cf_waf_tk__: 084114209tC--03bGArl4CMk9rzqhPW23-F0
```

This example triggered rule 942440 (SQL Comment Sequence Detected) but I also see it likely to trigger 942450 (SQL Hex Encoding Identified).

Not sure how commonly CF sets this parameter, but it'd be nice if we'd exclude it from the rule.

**Comment by dune73** [comment]
If it is random content, then there are far more rules affected. I have a list of 30 rules that could be hit, but it's true that many of them also take whitespace to be triggered and that does not seem to be the case.

But soon we will have a contact with CF thanks to @csanders-git and then we'll know about frequency and format - and possibly also meaning.

**Comment by csanders-git** [comment]
actually see the auth0 ticket -- looks mighty similar 

https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1135
