### ISSUE TITLE
Integrate SecRule Parser Into testing suite

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#1142]
Hey @fzipi do you mind if we pull https://github.com/fzipi/secrules-parser into the CRS-support org and then submodule it for testing -- I have done a pretty large rewrite to support what we need and modularize it but it uses the same underlying CFG you specified, great work. Thoughts?

**Comment by fzipi** [comment]
Sure! Let's move it. And please push your rewriting/refactoring.

I am in the process of generating Python classes for all objects along the way, so once we have python objects we can do practically anything. Your refactoring will come handy for this.

My principal use case was to rewrite my own million chaotic non-conformant rules, to the new beauty of the CRS 3.1 :), but I see the potential. It can be used also for interacting with new ruleset language that is being proposed.

I think @fgsch had additional stuff for merging to it!

**Comment by dune73** [comment]
Very useful contribution in the making here!

**Comment by fgsch** [comment]
I have a patch to fix some remaining parsing issues but I was not happy with the generated AST.
I can push it and we can rework the syntax if the desire here is to ensure the rules are correct.
Thoughts?

**Comment by csanders-git** [comment]
I love it... I'm more focused on the front end, making it accessible from both CLI and API. I've pushed up the first version, I'll be adding some of the features I stripped out probably tonight.

**Comment by fgsch** [comment]
This should be the last bit of it https://github.com/fzipi/secrules-parser/pull/6

**Comment by csanders-git** [comment]
Thanks @fgsch, i'll merge that in here as well. The new stuff is all Python3 compat (or it should be)

https://github.com/CRS-support/secrules_parsing

**Comment by fzipi** [comment]
We could add that repository and others that we use in the CRS support to some document. What do you think?

**Comment by dune73** [comment]
That sounds like a good plan. I'd welcome that.

**Comment by fgsch** [comment]
I believe this is done now and we have a PR for the remaining work (https://github.com/SpiderLabs/owasp-modsecurity-crs/pull/1301).
