### ISSUE TITLE
getting 403 Forbidden for file upload size >5mb

### ISSUE THREAD

**Issue by tonyzeng91** [SpiderLabs/owasp-modsecurity-crs#1146]
Hi Team, 

I am attempting to upload files to our website, it works fine with small files but when trying to upload files with size > 5mb, I am getting the 403 Forbidden error. Looking at the log, the two rules that is causing the issue looks like rules/REQUEST-949-BLOCKING-EVALUATION.conf and rules/RESPONSE-900-CORRELATION. I am using ModSecurity version 3.0. Any idea where the issue is?

**Comment by dune73** [comment]
You have probably limited the request size. The alert messages should tell you more exactly, what is going on. The correlation rule file is certainly innocent.

If you lack the knowledge to dig to the bottom of this, I suggest you read through the tutorials at netnea.com. Please do not use github to ask questions. This is meant to report bugs or feature requests.
