### ISSUE TITLE
Magento 2 admin URL blocking console issue

### ISSUE THREAD

**Issue by cattlemantech** [SpiderLabs/owasp-modsecurity-crs#1147]
we are using magento 2.2.0 on Nginx 1.15.1 + ModSec CRS 2.0.2. The magento admin URL is being blocked by modsec with below error:
------------------------------------------------------------------------------------------------------------
ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Eq' with parameter `0' against variable `MULTIPART_UNMATCHED_BOUNDARY' (Value: `2' ) [file "/etc/nginx/modsec/modsecurity.conf"] [line "59"] [id "200004"] [rev ""] [msg "Multipart parser detected a possible unmatched boundary."] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "217.33.238.119"] [uri "/index.php/admin_iotg5s/admin/system_config/save/store/4/key/1c2858e574d25767cff6913941f33ede8e6c1411f9541d925884b43d1050b85e/section/general/"] [unique_id "153148571655.812994"] [ref "v994,1"]
------------------------------------------------------------------------------------------------------------
Sample Magento admin console URL: https://<domain>/index.php/admin_iotg5s/admin/system_config/save/store/4/key/1c2858e574d25767cff6913941f33ede8e6c1411f9541d925884b43d1050b85e/section/general/
--------------------------------------------------------------------------------------------------------------

please advise how to resolve this problem? or how to whitelist this pattern of URL?

**Comment by dune73** [comment]
The rule ID 200004 points to the brief list of recommended rules that come with ModSecurity itself and not a CRS rule.

Still it is likely a false positive that you may have to work around with a rule exclusion. You may want to check the series of tutorials at www.netnea.com for advice on how to do this.

**Comment by spartantri** [comment]
Hi @cattlemantech  that false positive may be caused because the content of the request contains double dash at the beginning of the line if that is your case and it happens often, then as @dune73 suggests deal with the false positive, you may have to disable that rule or adjust your anomaly thresholds and default behavior so that it don't block your requests.
