### ISSUE TITLE
Question - PATCH and DELETE not in default HTTP methods?

### ISSUE THREAD

**Issue by vikas027** [SpiderLabs/owasp-modsecurity-crs#1150]
I am just curious to know why are verbs like `PATCH` and `DELETE` are not there in the [default](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/rules/REQUEST-901-INITIALIZATION.conf#L149-L155) list of allowed `http` methods?

**Comment by csanders-git** [comment]
TBH it's because the majority of sites don't use them. The most common use case is share point or a rest based site but probably upwards of 95% of sites don't need them and if they were enabled it would be representative of a misconfiguration ( again not REST)

**Comment by vikas027** [comment]
Thanks @csanders-git  and @dune73 !
