### ISSUE TITLE
issue with geoip database

### ISSUE THREAD

**Issue by toutougabi** [SpiderLabs/owasp-modsecurity-crs#1151]
when i reload nginx i get this message

Invalid database type GeoIP Country Edition, expected GeoIP City Edition, Rev 1

also there's a deadline in january 2019 to upgrade to the new version of the database. Any work being done ?

**Comment by dune73** [comment]
This is an issue with ModSecurity. ModSec 2.9.x depends on the legacy DB format that is no longer available. With NGINX and ModSec 3.0.x you are on the safe side as there is support for the new format. Did not try it out together with CRS though. But any feedback is appreciated. Closing this now, but feel free to reopen if it does not work out of the box.

**Comment by toutougabi** [comment]
From everything i can see, i'm using ModSecurity-nginx which is based on libmodsecurity which is ModSec 3.

but looking at the python upgrade script, if the new version is using the new geoip format i'm pretty sure you are fetching the legacy format. 

in upgrade.py you have this line
url = 'https://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz'

my understanding is that this is the legacy format and not the new one.

**Comment by dune73** [comment]
Reopening the issue. :) Thank you for reporting. We'll handle it.

**Comment by strangegitter** [comment]
This does not appear to have been fixed yet; is there any ETA?

**Comment by dune73** [comment]
It has been fixed by axing the update script. ModSec 2.9.x is not getting support for the "new" GeoIP format.

However, there is a script that converts the new format to the legacy format that works with ModSec 2.9.

Link: https://github.com/emphazer/GeoIP_convert-v2-v1

I'm closing this.

**Comment by toutougabi** [comment]
I am pretty sure i was using version 3 of modsecurity, are you sure this should have been close, see my comment on Jul 16, 2018

**Comment by dune73** [comment]
Our script pulled the legacy format DB. ModSec3 supports the new format, but ModSec2 does not.

GeoIP support is no core feature of CRS, so we decided to remove the script instead of supporting something for only ModSec3.

**Comment by JeffCleverley** [comment]
that is great and everything.... but if you are going to remove the update script, perhaps you should update the example conf...

This is still in the latest tar version for download.

```
#
# -- [[ GeoIP Database ]] ------------------------------------------------------
#
# There are some rulesets that inspect geolocation data of the client IP address
# (geoLookup). The CRS uses geoLookup to implement optional country blocking.
#
# To use geolocation, we make use of the MaxMind GeoIP database.
# This database is not included with the CRS and must be downloaded.
# You should also update the database regularly, for instance every month.
# The CRS contains a tool to download it to util/geo-location/GeoIP.dat:
#   util/upgrade.py --geoip
#
# This product includes GeoLite data created by MaxMind, available from:
# http://www.maxmind.com.
#
# Ref: http://blog.spiderlabs.com/2010/10/detecting-malice-with-modsecurity-geolocation-data.html
# Ref: http://blog.spiderlabs.com/2010/11/detecting-malice-with-modsecurity-ip-forensics.html
#
# Uncomment this rule to use this feature:
#
#SecGeoLookupDB util/geo-location/GeoIP.dat
```
