### ISSUE TITLE
Error - Can not start Apache and shows error "Disruptive actions can only be specified by chain starter rules"

### ISSUE THREAD

**Issue by UzuNARUKi** [SpiderLabs/owasp-modsecurity-crs#1169]
## Type of Issue

Bug fix / incompatibility issue

## Description

We have ModSecurity working for some time, (from december 2017) and we had it working fine since that day without problems with the free rules.

On Thursday 15th we restarted the server and we checked the service on Monday 13th and it worked fine, but on Tuesday 14th the apache service was off and we can not start it and it shows the following error:

[Wed Aug 15 11:22:27.246286 2018] [so:debug] [pid 36484:tid 140705883277184] mod_so.c(266): AH01575: loaded module ssl_module from /opt/apache/modules/mod_ssl.so
[Wed Aug 15 11:22:27.246950 2018] [so:debug] [pid 36484:tid 140705883277184] mod_so.c(337): AH01576: loaded file /usr/lib64/liblua-5.1.so
[Wed Aug 15 11:22:27.255696 2018] [so:debug] [pid 36484:tid 140705883277184] mod_so.c(266): AH01575: loaded module security2_module from /opt/apache/modules/mod_security2.so
AH00526: Syntax error on line 136 of /opt/modsecurity/etc/modsecurity.conf:
ModSecurity: Disruptive actions can only be specified by chain starter rules.

We did not do any change in the configuration, the apache service was down and now it does not start and shows as if the Modsecurity configuration is wrong, we tried commenting that line from the configuration file and then it shows another mistake in the file, we have commented all the lines with error in the configuration file (modsecurity.conf) but then it shows errors in the crs-setup.conf confgiration file.

We commented again all lines with errores from that file and then it shows errors in the files of the rules folder of the free rules.

We decided to download again the free rules but the problem is still the same.

The first error is showed in our configuration file in this part:

#########################################################
#########################################################

SecRule REQBODY_ERROR "!@eq 0" \
"id:'200001', phase:2,t:none,log,deny,status:400,msg:'Failed to parse request body.',logdata:'%{reqbody_error_msg}',severity:2"

However like I said before even if we comment htis line the problem is shown in other lines after that.

Is there any incompatibility issue that is generating the errors? We have not made any changes in the configuration files and we even have backups of the configuration files but the problem is still the same.

## Your Environment

* CRS version (e.g. v3.0.2):  v3.0.2
* ModSecurity version (e.g. 2.9.2): v2.9.2
* Web Server and version (e.g. apache 2.4.27): Apache v2.4.29
* Operating System and version: Red Hat Enterprise Linux 7 64 bits

## Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by csanders-git** [comment]
There is no known incompatability between v2.9.2 and v3.0.2 (in fact this is the most common deployment). Additionally, modsecurity.conf is provided with ModSecurity itself so something odd is going on. Can you share your modsecurity.conf with us?

**Comment by UzuNARUKi** [comment]
Hi;

We have licensed the Mod Security Commercial Rules and they are in the first lines of our modsecurity.conf  configuration file, we commented this line and the apache server started fine.

The incompatability issue seems to be between the CRS rules and these commercial rules, 

The rules updated on monday 13th at 22:00 UTC -5 and the problem started at that time.

I writed to them abouts thiis issue if I have any update I will update here.

**Comment by csanders-git** [comment]
Perfect, we do not maintain or test integrations with the trustwave rules. They will have to provide support for their integration as needed. If you find out what the problem is please let us know. Thanks

**Comment by mirkodziadzka-avi** [comment]
@UzuNARUKi Just curious ... what is the line in your modsec.conf before line 136?  Because the problem is not the SecRule in line 136, but the last SecRule before this line. Which probably includes in "chain".

**Comment by csanders-git** [comment]
He probably can't tell us easily since secremoterules is bringing in rules and making a new .conf in memory.

**Comment by mirkodziadzka-avi** [comment]
@csanders-git Well, if the last line before 136 is secremoterules, it would confirm that the problem is in the remote rules.

**Comment by UzuNARUKi** [comment]
This was the answer from Spider Labs:

"......There’s a chance that the problem is related with the way that some ModSecurity v2 builds process line endings leading to the parser being confused waiting for another rule when there’s a chained rule.
We’ve performed some changes (basically changing line endings) ....."

After that I eneabled again the commercial rules and restarted Apache and it worked again.
