### ISSUE TITLE
REQUEST-941-APPLICATION-ATTACK-XSS rules would not protect against attacks that aren't in the query string

### ISSUE THREAD

**Issue by greeniguana10** [SpiderLabs/owasp-modsecurity-crs#1170]
I've looked through the documentation here:
`https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#ARGS`

And also searched through the `REQUEST-941-APPLICATION-ATTACK-XSS.conf` file.

My understanding is since the `REQUEST_URI` argument isn't present before any of the rules, the full get request would never be passed to any of the regular expressions and any XSS attack that isn't in a query string wouldn't be detected?

I'm thinking specifically of an example such as the attack used in exercise 6 here:
`http://www.behindthefirewalls.com/2014/06/xss-game-by-google-exercises-4-5-and-6.html`

Am fairly new to ModSec so apologies if this is a misunderstanding on my part. My understanding is that since the `ARGS` argument is present in all the rules only key value pairs of the query string would be passed to the regex?

**Comment by dune73** [comment]
No, I think you are wrong. In ModSec, this is all about the phases. Most of the rules in 941 are in phase 2, and this is where the ARGS collection is fully populated with query strings and parameter out of the request body.

**Comment by theMiddleBlue** [comment]
Agree with @dune73. The user-agent shouldn't send the `fragment` part to the web server. On the exercises mentioned by @greeniguana10, the payload leads to a reflected XSS just because the `fragment` it's included client-side... creating a script element using DOM (`includeGadget(getGadgetName());` that get it by `window.location.hash.substr(1)`).

**Comment by greeniguana10** [comment]
Oh ok, thanks for letting me know. So the regular expressions in 941 are intended to be applied to the entire GET request if the line `phase:request` is present?

I'm asking as I'm writing a script to analyse apache log files using the ModSec regular expressions and am getting a lot of false positives when I apply some filters such as `XSS Filter - Category 5: Disallowed HTML Attributes`. Where the regular expression is:
`(?i)\b(?:s(?:tyle|rc)|href)\b[\s\S]*?=`

Many of the false positives are of the form:
`/xxx/xxx/xxx/xxx/xxx/src/xxx/?xx=xx`
The `src` in the URL is getting picked up by the regex and flagged:
`https://regex101.com/r/WqV6Sp/1`

If the ModSec regular expressions are being used in a standalone script, should they only be applied to the query string? Or is it just a case of dealing with false positives? Or have I fundamentally misunderstood something?

**Comment by dune73** [comment]
What version of CRS are you using? And could you post some of the alert messages out of the error- or audit-log?

**Comment by greeniguana10** [comment]
Using `OWASP_CRS/3.0.0` and applying the regular expressions in `REQUEST-941-APPLICATION-ATTACK-XSS.conf` and `REQUEST-942-APPLICATION-ATTACK-SQLI.conf` to the request lines of apache log files using a python script which I've written to identify malicious GET requests (as part of a University project)

I'm just concerned about whether I'm applying these filters correctly - since I mentioned I am getting a lot of false positives for specific filters (if I pass the entire GET request to the regular expressions).

I'm not sure exactly what you mean by `alert messages` from the log.
