### ISSUE TITLE
FP 942360: create charge triggers this rule

### ISSUE THREAD

**Issue by anush-cr** [SpiderLabs/owasp-modsecurity-crs#1175]
## Type of Issue
incorrect blocking (false positive)

## Description
Matched Data: create char found within ARGS:q: create charge
`curl localhost:80?q=create%20charge`

## Your Environment

* CRS ver.3.0.2
* ModSecurity 3.0 with nginx

## Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by theMiddleBlue** [comment]
confirmed, it matches **942360** in PL1:

```
[942360] Detects concatenated basic SQL injection and SQLLFI attempts
Matched Data: create char found within ARGS:q: create charge
```

**Comment by franbuehler** [comment]
The regexp `create\s+char\s?[(]?` on line 4 (https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.2/dev/util/regexp-assemble/regexp-942360.data#L4) matches the string `create charge`.

How about adding a word boundary just after the word `char`?
`create\s+char\b\s?[(]?`

The strings `create char(`, `create char (` and `create char` still match.

I would add a word boundary to the other regexes of this file too.
