### ISSUE TITLE
Fix anomaly scoring in 933190, 932180, 920341; complete response rules are doing this wrong too

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1178]
## Type of Issue
Clearly a bug fix

## Description
@fgsch noticed on slack that the rule ids above are not setting the anomaly scores for the PLs correctly. Not sure how this happened. Maybe merge failures.

It seems that this whole executing PL stuff does not cover the responses at all. Should be checked seperately.

## Your Environment
irrelevant

## Confirmation

Check rules of IDs name in title

**Comment by fgsch** [comment]
Also 920470 and 932190.

**Comment by fgsch** [comment]
This should also be applied to 3.2

**Comment by fgsch** [comment]
@dune73 this can be closed now, or is there anything remaining to do here?

**Comment by dune73** [comment]
I think we are covered.
