### ISSUE TITLE
Doubled entry "/.env" in file "rules/restricted-files.data"

### ISSUE THREAD

**Issue by jschleus** [SpiderLabs/owasp-modsecurity-crs#1183]
Probably only a minor flaw: The entry `/.env`in the file `rules/restricted-files.data` exists twice (but not in owasp-modsecurity-crs-3.0.2.tar.gz).

**Comment by csanders-git** [comment]
Good eye, I'll make a PR to fix this now.

**Comment by lifeforms** [comment]
Thanks for reporting!
