### ISSUE TITLE
Request body disrupted due to issues with 944220

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1185]
As mentioned during the community chat, I have isolated an issue with the new JAVA rules in connection with chunked JSON payloads that lead to ModSec cutting a response short. 

There is a certain chance that special local configuration of when the JSON body processor is called is playing into this.

I am not yet able to reproduce it, but it's definitely there and should be fixed before 3.1. I'm working on this.

## Type of Issue

* Disruption of payload

## Description

See above. More information will be added here.

## Your Environment
* CRS version 3.1-RC1
* ModSecurity version 2.9.2
* Apache 2.4.34, self compiled
* RHAT
* The payload is sent chunked. Thus no content-length is known for the POST request.

**Comment by dune73** [comment]
I am still working on this bug. I was able to confirm it, but I was not able to reproduce it without the help of a  commercial user-agent that bumped into the problem first.

**Comment by csanders-git** [comment]
let me know when you track it down a bit more.

**Comment by dune73** [comment]
Will do. Keeping my fingers crossed I'll manage. I'm a wee bit desperate here. Can't sniff the traffic so far and audit-log does not show the payload. :(

**Comment by dune73** [comment]
Outcome of community chat on slack last night:

@lifeforms feels the first regex in the chained rule could be the reason for the bug. Given the payload, @dune73 supports this idea.

For 3.1, we will drop the rule in favor of 944240 that has a very similar purpose.
@dune73 will handle the PR and @lifeforms  will review and merge.

If @dune73 manages to consistently reproduce this, we will contact @victorhora / TW.

**Comment by spartantri** [comment]
Hi @dune73,
Have you tried to use burp interception proxy in transparent mode? that way you set burp in a local port and it will forward everything to the modsec server and you get a full capture of the traffic. 
What is this issue about?
I have been very busy so got out of the loop.

**Comment by dune73** [comment]
The commercial user-agent running into this problem is a Windows fat client. So far we did not manage to get access to the local port in order to dump the traffic. This might be me or the guys running the client, but it's still a roadblock.

We **believe** this bug is a rare ModSec bug due triggered by a labour-intense rule, 944220, under very rare conditions that we can not reproduce with standard tools.

**Comment by dune73** [comment]
This is solved in #1198 as planned above (Removal of rule 944220).

The difference between 944240 and 944220 is the two keywords `runtime` and `processbuilder` that are missing in 944240.
