### ISSUE TITLE
False positives on 942130 when query string variable separator is ";" instead of "&"

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1188]
## Type of Issue

False Positive at PL1

## Description

When an application uses "`;`" as variable separator in the query string instead of the more widespread "`&`" then this leads to FPs on 942130 (SQL Injection Attack: SQL Tautology Detected) quickly.

Example payloads: 
```
curl "http://localhost/index.html?a=b;h=H"
```

## Your Environment
* CRS version 3.0.2 and onwards
* ModSecurity version: 2.9.2
* Web Server and version: latest apache
* Operating System and version: Ubuntu

## Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
Maybe, setting `SecArgumentSeparator` in ModSec is the solution, but can we advise people to do that?

**Comment by lifeforms** [comment]
`SecArgumentSeparator` is not always great in my experience.

If I recall correctly, `SecArgumentSeparator` also changes the parsing of POST request bodies.

There is some software which uses `;` as a separator in GET query strings, but POST forms are generated normally with `&` as separator. Now when I used `SecArgumentSeparator`, GET query strings were parsed, but forms checking was broken... So I could pick between two problems...

I wish the few remaining applications using `;` would just go away...

**Comment by dune73** [comment]
My initial assessment about this being PL1 was wrong. It's PL2. And given it's a fairly rare FP, I do not see the need to act anymore. Closing this.
