### ISSUE TITLE
Is dos protection only for the same tcp link

### ISSUE THREAD

**Issue by hbt19860104** [SpiderLabs/owasp-modsecurity-crs#1189]
Hi!
I saw the rules coresponsed  to dos protection all accumulating based on individual http request. So, it will not work if dos attack doesn't use keep-alive connection. Does my opinion correct？
Thanks a lot!
>  SecRule REQUEST_BASENAME ".*?(\.[a-z0-9]{1,10})?$" \
>      "phase:5,\
>      id:912150,\
>      t:none,\
>      t:lowercase,\
>      nolog,\
>      pass,\
>      tag:'application-multi',\
>      tag:'language-multi',\
>      tag:'platform-multi',\
>      tag:'attack-dos',\
>      capture,\
>      setvar:tx.extension=/%{TX.1}/,\
>      chain"
>      SecRule TX:EXTENSION "!@within %{tx.static_extensions}" \
>          "setvar:ip.dos_counter=+1"

**Comment by dune73** [comment]
No, that is not correct. CRS initializes a session bound to the client IP address. ModSecurity allows to do that. You can see this session on the last line of the rule that you quote.
