### ISSUE TITLE
False Negative: UA "Wappalyzer" is not detected

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1190]
## Type of Issue

False Negative 

## Description

The following User-Agent 
```
Mozilla/5.0 (compatible; Wappalyzer)
```
is not being detected. The software is used to finger print webservers and application servers.

See https://www.wappalyzer.com/.

The UA should be added to the scanner date file `scanners-user-agents.data`.

## Your Environment

irrelevant

## Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by csanders-git** [comment]
Adding it now.

**Comment by csanders-git** [comment]
Ready for review.
