### ISSUE TITLE
Lots of unnecessary comments in 944

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1199]
The 944 rule file has a lot of comments that deal with how the rules have been shuffled around during the PR creation. This should be removed before the release.

## Type of Issue

Superflous comments

## Description

See above.

## Your Environment

irrelevant

## Confirmation

[X ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by lifeforms** [comment]
I removed the extra comments in commit 424f664.
