### ISSUE TITLE
Deal with X-HTTP-Method-Override header and friends

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1200]
CRS is not handling / preventing the use of the optional X-HTTP-Method-Override header.

## Type of Issue

Feature request

## Description

* https://www.infoworld.com/article/3249687/web-development/how-to-implement-a-delegatinghandler-for-x-http-method-override-in-web-api.html
* https://vulncat.fortify.com/en/detail?id=desc.dynamic.xtended_preview.often_misused_http_method_override

We're talking about these headers:
* X-HTTP-Method
* X-HTTP-Method-Override
* X-Method-Override

I suggest to simply forbid them on PL3.

## Your Environment

Irrelevant

## Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by spartantri** [comment]
I can smell a full header whitelist in PL4 or is it the birth of PL5 with a full set of whitelists for better 0day protection?

**Comment by dune73** [comment]
I think a full header whitelist in PL4 would be a good feature.

**Comment by spartantri** [comment]
Me too, maybe we can ask some CDN also fellow ISPs to share the stats of header names they see traversing their networks so we can start building `http-headers.data` and the `9205**` rule set
