### ISSUE TITLE
Rule Question

### ISSUE THREAD

**Issue by Dhariaj** [SpiderLabs/owasp-modsecurity-crs#1202]
## Type of Issue
Issue with the rule 
![image](https://user-images.githubusercontent.com/38356060/46669391-4a339a80-cb9d-11e8-9560-ae4503339cd8.png)

## Description
We are using modsecurity rules as part of the NGINX plus configuration and yesterday and one of our vendors was having some issues getting their requests through.  After sniffing through the logs we found out that the following rule was getting triggered every time they would send a request
 
SecRule REQBODY_ERROR "!@eq 0" \
"id:'200002', phase:2,t:none,log,deny,status:400,msg:'Failed to parse request body.',logdata:'%{reqbody_error_msg}',severity:2"
 
And if you look at the audit logs it gives us the following information
 
---kMQLOcON---H--
ModSecurity: Access denied with code 400 (phase 2). Matched "Operator `Eq' with parameter `0' against variable `REQBODY_ERROR' (Value: `1' ) [file "/etc/nginx/modsec/modsecurity.conf"] [line "44"] [id "200002"] [rev ""] [msg "Failed to parse request body."] [data "JSON parsing error: parse error: premature EOF\x0a"] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "x.x.x.x"] [uri "/v1/members/xxxxxx/xxxx-details"] [unique_id "153901811455.132212"] [ref "v1591,1"]
 
Something similar has been explained out here https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/271 and I am still researching on a solution but I dont see a solution. Was wondering if anyone has faced something like this and were able to resolve the issue?

## Your Environment

* modsecurity-crs-3.0.2

*nginx version: nginx/1.15.2 (nginx-plus-r16)

## Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
Rule 200002 is a rule that comes together with a very small group of recommended rules distributed with ModSecurity.

-> https://github.com/SpiderLabs/ModSecurity/blob/v2/master/modsecurity.conf-recommended

Sorry for the inconvenience.

I'm closing this now.

**Comment by Dhariaj** [comment]
@dune73 
Let me add some details, this is a GET request with application/json and valid JSON being returned but it is still causing the rule to trigger

**Comment by dune73** [comment]
Yes, this is unfortunate, but you are talking to the wrong project. 

This is the issue tracker of the of the OWASP ModSecurity Core Rule Set project. You have a problem with a rule by the ModSecurity project itself. ModSec only recommends like 5 rules. This is one of them.

**Comment by Dhariaj** [comment]
ok I will post it to the other project

**Comment by swatantrajain-sapiens** [comment]
Can you share the link to the other project, where this has been raised
