### ISSUE TITLE
I want to Know how can i make rule to manage the param -length in request-header or response-header?

### ISSUE THREAD

**Issue by meigea** [SpiderLabs/owasp-modsecurity-crs#1211]
# Want a Help

i want to know how to set the param length in phaser:(request/response) the request-header params like proxy,  cookie, refer, user-agent and so on.

## what i  known
i know the params REQUEST_HEADERS:User-Agent, but i cant get the length; i want to know what's the length-fun that like \@ length_func

**Comment by dune73** [comment]
I do not think this is an issue with our project and I do not think this is the ModSecurity support forum. But if you look up the documentation and read it, you will stumble over the t:length transformation.
