### ISSUE TITLE
The modsecurity.log  sometimes  will not produce new log util i restart nginx

### ISSUE THREAD

**Issue by meigea** [SpiderLabs/owasp-modsecurity-crs#1212]
what're the problem that my modsecurity.log will not produce sometimes. then it will run well util i restart nginx ... i run the command `nginx -s reload` also not use. is there log-pid that i don't now but existed?

my env:
- openresty 1.13
- modsec3
- crs-302

**Comment by lifeforms** [comment]
This seems not a problem with the CRS ruleset but with the WAF engine (Modsec3) therefore I will close this issue.

For support on Modsec3 the best thing you can do probably is e-mail the ModSecurity mailinglist: https://sourceforge.net/projects/mod-security/lists/mod-security-users

**Comment by zimmerle** [comment]
Hi @meigea,

Please disregard @lifeforms comment. I am afraid the malign list is _not so popular_, therefore unlike to get an answer there. Specially for version 3 (...). On other hand the **GitHub project** is very active. Thus, I wold like to invite you to visit [ModSecurity for nginx on GitHub](https://github.com/SpiderLabs/ModSecurity-nginx).

**Comment by lifeforms** [comment]
Thanks @zimmerle will send people over there from now on :P

**Comment by zimmerle** [comment]
Thank you @lifeforms, I really appreciate.
