### ISSUE TITLE
check_upload_uri required warnings relates to REQUEST-914-FILE-DETECTION

### ISSUE THREAD

**Issue by muzammel111** [SpiderLabs/owasp-modsecurity-crs#1213]
Dear All,
My environment info is below.

Apache = 2.2
Modsecurity version = 2.9.2
CRS version = OWASP_CRS/3.1.0

Issue = My web server error logs has been full for every requests as per below warning messages.

[Thu Oct 25 17:02:16 2018] [error] [client 193.222.106.30] ModSecurity: Warning. Match of "within %{tx.protected_uploads}" against "TX:check_upload_uri" required. [file "/etc/httpd/modsecurity-crs/rules/REQUEST-914-FILE-DETECTION.conf"] [line "248"] [id "9142050"] [msg "Performing image and document file signature check for protected upload URI"] [ver "OWASP_CRS/3.1.0"] [tag "application-multi"] [tag "platform-multi"] [tag "file-upload"] [tag "paranoia-level/2"] [hostname "ab.com"] [uri "/sale_centres"] [unique_id "W9GwyAoyfCYAAF0FngwAAAAD"

I want to know is there any thing need i want to fix ?  also warning comes with simple page calls which not contains images, i tried to found check_upload_uri" in conf file but not found any directive, . Please advise me regarding this.

Regards,

**Comment by spartantri** [comment]
Hi @muzammel111 this is a setting that was left there unnecessarily for now adjust 9142050 and remove the log action, it should use your defaults not its own.
Will fix it later today if I can.

**Comment by muzammel111** [comment]
Hi @spartantri Thankyou so much for your guidance and support. Please let me know, is file signature working to check every file ? or it works to scan the content of a file ?. As i just by copying test.pdf (orginal pdf) file to test.png and modsecurity not give me any alert or block request, and test.png file open in url with error content type message.

**Comment by spartantri** [comment]
Hi @muzammel111 the current version only checks for binaries, the other checks were dropped to be included in a future version

**Comment by muzammel111** [comment]
Right @spartantri, thankyou for the information.

**Comment by fgsch** [comment]
This rule has been removed so this ticket is OBE. Closing.
