### ISSUE TITLE
Documentation error:  Incorrect URL in crs-setup.conf.example

### ISSUE THREAD

**Issue by fruviad** [SpiderLabs/owasp-modsecurity-crs#1216]
Lines 37-39 of https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.2/dev/crs-setup.conf.example state:

 The CRS assumes that modsecurity.conf has been loaded. If you don't have this
 file, you can get it from:
 https://github.com/SpiderLabs/ModSecurity/blob/master/modsecurity.conf-recommended

That URL is incorrect.  Loading it results in a 404 error from the server.  

I'm guessing that perhaps it should it actually be:

https://github.com/SpiderLabs/ModSecurity/blob/v2/master/modsecurity.conf-recommended

...which is accessible.

**Comment by lifeforms** [comment]
Thanks so much! Will fix.
