### ISSUE TITLE
Issue with rule id:960038 while accessing to a web service with some browser (safari 5.1.7 for windows and some other smartphone browsers)

### ISSUE THREAD

**Issue by hrirm** [SpiderLabs/owasp-modsecurity-crs#1224]
## Type of Issue

error 403 in apache

## Description

[error] [client XXX(ip address)] ModSecurity: Access denied with code 403 (phase 2). String match within "/Proxy-Connection/ /Lock-Token/ /Content-Range/ /Translate/ /via/ /if/" at TX:header_name. [

file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_crs_30_http_policy.conf"] [line "100"] [id "960038"] [rev "2"] [msg "HTTP header is restricted by policy"] [data "/Proxy-Connection/"] [severity "WARNING"] [ver "OWASP_CRS/2.2.6"] [maturity "9"] [accuracy "9"] [tag "OWASP_CRS/POLICY/HEADER_RESTRICTED"] [tag "OWASP_CRS/POLICY/FILES_NOT_ALLOWED"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/12.1"] [tag "WASCTC/WASC-15"] [tag "OWASP_TOP_10/A7"] [tag "PCI/12.1"] [hostname "www.host.com"] [uri "/context/text.html"] [unique_id "WvVo8ApSAjhjhuhDFe4AAAAAj"]

## Your Environment

* CRS version **2.2.6**
* ModSecurity version **2.2.6**
* Web Server and version apache **2.2.15**
* Operating System and version: **CentOS release 6.9**

## Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
You are using an outdate version of CRS and bumped into a false positive.

If you upgrade, it should be gone. Otherwise, please see https://www.netnea.com/cms/apache-tutorial-8_handling-false-positives-modsecurity-core-rule-set/ to learn how to deal with false positives.
