### ISSUE TITLE
Ensure that all rules with ARGS also consider XML:*

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#1227]
## Type of Issue
Feature Request

## Description
In general we'll like to have XML considered for all rules, where it is evaluated. This can be done by adding the TARGET of XML:* to the rules. But we need to be careful to ensure only the rules that need it, get it. Starting with rules that have ARGS, is a good start

## Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by spartantri** [comment]
I think that `XML:/*` would be the equivalent for `XML` to `ARGS` in `URLENCODED`, so it makes sense to have them together by default

**Comment by ghost** [comment]
Taking this issue. I think I understand it, and if that's the case, I'll have it done in two weeks...testing for a cert this weekend or would have it all sooner :)

**Comment by dune73** [comment]
Looking forward to that! Thanks.

**Comment by ghost** [comment]
Does someone have an example of what this rule would look like? The only way I can see to specifically target XML coming in is to check the Headers. E.g.:

`SecRule REQUEST_HEADERS:Content-Type ^text/xml` ?

or maybe

`SecRule ARGS|XML:/* blahblahblah id:2000` ?

I actually don't see a mention of `XML:/*` anywhere in the documentation I'm looking at, although it is for 2.9.

**Comment by ghost** [comment]
@dune73 Just look at this comment:

Actually, I think this is the answer.

Anything that has the word `ARGS` after SecRule should, if it doesn't right now, have `|XML:/*` appended to it?

E.g. like the following rule:

`SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|REQUEST_HEADERS:User-Agent|REQUEST_HEADERS:Referer|ARGS_NAMES|ARGS|XML:/* "@detectSQLi" \`

**Comment by dune73** [comment]
Could you guys please support @danehrlich1? I'm overly busy at the moment.

**Comment by ghost** [comment]
@spartantri Can you look at my comment really quickly? Think I am correct but just want someone to double check.

**Comment by spartantri** [comment]
Hi @danehrlich1 it may be better to discuss this in slack, but basically, this one is to add `XML:/*` to all `SecRule`'s that have ARGS as targets of the rule.
You may find all targets with running the command below on the rule set directory:
`egrep -o "SecRule ([^\s])ARGS([^\s]) " *|grep -v "XML:"`
You may find rules that do check both ARGS and XML removing the `-v` from the previous command:
`egrep -o "SecRule ([^\s])ARGS([^\s]) " *|grep "XML:"`

**Comment by fzipi** [comment]
@danehrlich1 Did you made any progress with this? Do you need more help/advise?

**Comment by dune73** [comment]
@lifeforms volunteered to fix this issue during the monthly CRS chat.

Meeting minutes: https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1671#issuecomment-584320407

**Comment by dune73** [comment]
@lifeforms: Any update here?
