### ISSUE TITLE
please add detectivy to scanners-user-agents.data

### ISSUE THREAD

**Issue by EeroV** [SpiderLabs/owasp-modsecurity-crs#1234]
## Type of Issue

add detectify to scanners-user-agents.data

useragent data:

"Mozilla/5.0 (compatible; Detectify) +https://detectify.com/bot/ed2230ece7206bf5da08e6ca677b08ee7dbae2d8"

So, I think Mozilla/5.0 (compatible; Detectify)  is enought to filter this scanner.

## Your Environment

* CRS version (e.g. v3.0.2):
* ModSecurity version (e.g. 2.9.2):
* Web Server and version (e.g. apache 2.4.27):
* Operating System and version:

## Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
Thank you for reporting @EeroV. We'll definitely cover this. Maybe we can fit it into the upcoming release.

Personally, I think "Detectify" as string would be most successful.

**Comment by dune73** [comment]
This is implemented in PR #1235 thanks to a PR by @theMiddleBlue. It has also been backported to the upcoming 3.1 release by @csanders-git. Closing this now.
