### ISSUE TITLE
False Positive in Rule 941100

### ISSUE THREAD

**Issue by blappm** [SpiderLabs/owasp-modsecurity-crs#1237]
From the Logs we found that the following example is matching as a false positive (URLs have been obfuscated):

`[Wed Nov 14 15:32:13 2018] [error] [client XXX.XXX.XXX.XXX] ModSecurity: Access denied with redirection to https://www.sample.ch/ using status 302 (phase 2). detected XSS using libinjection. [file "/etc/apache2/mod_security2.d/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "64"] [id "941100"] [rev "2"] [msg "XSS Attack Detected via libinjection"] [data "Matched Data:  found within ARGS:url: https://www.sample.ch/detail/ISBN-2244020032148/Silver-Josie/One-Day-in-December?b=1"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "1"] [accuracy "9"] [tag "Host: www.sample.ch"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-xss"] [tag "OWASP_CRS/WEB_ATTACK/XSS"] [tag "WASCTC/WASC-8"] [tag "WASCTC/WASC-22"] [tag "OWASP_TOP_10/A3"] [tag "OWASP_AppSensor/IE1"] [tag "CAPEC-242"] [hostname "www.sample.ch"] [uri "/piwik/piwik.php"] [unique_id "W@wx7X8AAAIAAA5KFNQAAAAX"]`

We were able to strip it down to this regex:

`On\?[a-z0-9]{3,}=[a-z0-9]+`

so for example: `One?b=1`  is matching as well.

Config:

* CRS version (3.0.2):
* ModSecurity version 2.9.2:

## Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
Thank you for reporting @blappm. I confirm you conclusion, yet there is little we can do.

This false positive is based in the sql injection operator of ModSecurity, which is based on the libinjection library. So if you want this fixed, you should file a bug report with https://github.com/client9/libinjection.

Are you able to write a rule exclusion to work around this false positive yourself? If not, then I recommend the tutorials found at netnea.com.

Closing this now.

**Comment by blappm** [comment]
The bug is serious. We've got multiple false positives each day, for example 'online' is matching as well.

Pull request is filed:

https://github.com/client9/libinjection/pull/143/files
