### ISSUE TITLE
projectmsi

### ISSUE THREAD

**Issue by saoulim** [SpiderLabs/owasp-modsecurity-crs#1241]
## Your Environment

* CRS version (e.g. v3.0.2):
* ModSecurity version (e.g. 2.9.2):
* Web Server and version (e.g. apache 2.4.27):
* Operating System and version:

## Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by lifeforms** [comment]
This issue seems to be missing some content.

Please re-submit with the necessary information if you have found a problem! Thanks!
