### ISSUE TITLE
False positives on 920300 and should it be PL3?

### ISSUE THREAD

**Issue by tunetheweb** [SpiderLabs/owasp-modsecurity-crs#1244]
## Type of Issue
Incorrect blocking (false positive)

## Description
Many agents don't send an Accept-Header. Admittedly they probably should but it's not a mandatory header in HTTP. For example Twitter bot:

```
--37b54761-A--
[24/Nov/2018:19:20:31 +0000] W-mkf6pZ8ArsqcQv7l9m3wAAAIc 199.16.157.181 50370 123.45.67.890 443
--37b54761-B--
GET /robots.txt HTTP/1.1
X-B3-SpanId: ab60cd4e49f1a35b
User-Agent: Twitterbot/1.0
Finagle-Ctx-com.twitter.finagle.Retries: 0
X-B3-Sampled: false
X-B3-Flags: 2
Host: www.example.com
X-B3-ParentSpanId: ab12c34d56efabcd
X-B3-TraceId: 00a6b12345678c12
```

I like that you have added exceptions for those user agents that are known to sometimes not send this (e.g. AppleWebKit and Android), so should we add TwitterBot to this? And probably a few others too.

To be honest I question the value of this rule. At the very least I think it should be PL 3 or even PL 4.

Thoughts? Happy to submit a pull request if in agreement.

## Your Environment
* CRS v3.1.0
* ModSecurity 2.9.2
* Apache 2.4.37

## Confirmation

[ X ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
You have a point here and we definitely did not the rule in PL1 anymore. But it's also a sure way to identify a malicious bot. Shifting it to PL3 for the future is an option.

**Comment by tunetheweb** [comment]
Alternatively it may be useful for anomaly scoring (since it gets a low "notice" weight which isn't sufficient to block on it's own), but it is less useful for Self-Contained (aka Blocking) mode that some of us prefer to run in (mostly to reduce noise).

Should this rule (only potentially others) only apply to Anomaly scoring mode? Or is that a bad precedent to set?

**Comment by tunetheweb** [comment]
Actually looking at it some more it seems like rule 920300 (plus some others - e./g. 920320) will never block in Self-Contained (aka Blocking) mode as the action is set to `pass` rather than `block`. Is this intentional?

**Comment by dune73** [comment]
Yes, it's one of very few rules that stand at pass. AFAIK this rule was always set to pass. With anomaly scoring, you can make it block by lowering the threshold to 2. (See how much more flexible anomaly scoring is :)

**Comment by tunetheweb** [comment]
Nah, it used to block: https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v2.2/master/base_rules/modsecurity_crs_21_protocol_anomalies.conf

And I don’t want to make it block. As I say I think this rule is kind of pointless. While I agree most HTTP clients (e.g. browsers) send this, so the absence of it suggests a non-standard client, I still don’t think that’s enough to warrant this rule: It’s not against spec and is not an attack.

Anyway will turn it off in my instance (as I did in v2.2 before) but thought I’d start the discussion. Feel free to close if you disagree.

Barry

P.S. The reason I dislike Anomay scoring mode is it is noisy IMHO and difficult to see badly configured rules. A WAF can be noisy enough without having the added complexition of rules that might block and might not.

**Comment by dune73** [comment]
I've been asked to comment some more. :)

I think we are open to add more user-agents to the exception list. Other than that, there are few people complaining about this rule in PL2. So I think there is no pressing need to remove the rule or shift it to a higher PL.

Let's let this stand for a few more days and then close the issue unless we get additional information / complaints.

**Comment by fgsch** [comment]
It's been 10 days since the last comment and we haven't heard anything back.
I will close this now but feel free to reopen it.
