### ISSUE TITLE
False positives on 920274 for From Header (including GoogleBot)

### ISSUE THREAD

**Issue by tunetheweb** [SpiderLabs/owasp-modsecurity-crs#1245]
## Type of Issue
Incorrect blocking (false positive)

## Description
GoogleBot uses brackets in it's from header which flags rule:

```
--69338640-A--
[24/Nov/2018:17:20:19 +0000] W-mIU7YF@9bJNYby0IXMNwAAAAA 66.249.79.152 40727 123.456.789.123 443
--69338640-B--
GET / HTTP/1.1
Host: www.example.com
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
From: googlebot(at)googlebot.com
User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
Accept-Encoding: gzip,deflate,br
If-Modified-Since: Thu, 15 Nov 2018 04:32:45 GMT
```

I know this is a PL 4 rule, so false positives are expected, but GoogleBot is pretty common so should do something to prevent it flagging.

Additionally this is expected to be an email address (https://tools.ietf.org/html/rfc7231#section-5.5.1) the fact the rule does not allow an @ symbol will lead to more falsde positives unless everyone follows Google's example and spells it out as `at`.

So we could either add brackets and @ to the allowed characters or exclude the `From` header from this rule.

Personally I think we should exclude From: header from this rule, since there is already precedent with the User-Agent, Referrer and Cookie headers. Let me know if you agree and want a pull request.

## Your Environment
* CRS v3.1.0
* ModSecurity 2.9.2
* Apache 2.4.37

## Confirmation

[ X ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by fgsch** [comment]
Makes sense.

Do you mind opening a PR for this?

**Comment by dune73** [comment]
Sorry for chiming in so late. 

Still, I disagree with the need for a rule exclusion in this case.

- It complicates the rule 920274 or costs everybody cycles if adding exclusion to 905.
- People working in PL4 are perfectly capable of excluding it themselves if they want googlebot.
- People working in PL4 are maybe happy to see googlebot blocked
  (In fact we have a crawler list in crawlers-user-agents.data and I am not sure about the criteria that has UAs being added to that list.)

Anybody want to challenge me?

**Comment by fgsch** [comment]
It just requires '!REQUEST_HEADERS:From' and we are already excluding User-Agent, Referer and Cookies. Why is this any different?

**Comment by lifeforms** [comment]
Running in PL4 will come with many false positives, of which this is only one. These FPs will vary from app to app. Due to our resource constraints, we have to prioritize false positives that come in the default install. But a PR for these kinds of things would be welcome imho.

**Comment by dune73** [comment]
If you do '!REQUEST_HEADERS:From', you remove protection for the header via this rule completely and all only because google does not provide @ in the email address.

The need is much bigger with the other headers where most requests will score an FP. On the FROM header, the FP is very rare.

**Comment by fgsch** [comment]
I understand but there is nothing wrong with () in headers' values. This rule will also trigger for Via requests where the parenthesis are not uncommon. I'd also expect Googlebot to be quite common.

That said, it is indeed in PL4 and easy to exclude so nothing further from me.

**Comment by spartantri** [comment]
PL4 is for experts only, I don't mind dealing with all those anomalies, plus for all my sites running PL4, having google or anybody else crawling and indexing is definitively not a welcome request.
White listing this is easy but I think it should be a local exclusion.

**Comment by dune73** [comment]
Glad we agree (more or less :). Sorry @bazzadp, but I'm closing this now.
