### ISSUE TITLE
Add support of Paranoia Levels to non-anomaly mode

### ISSUE THREAD

**Issue by tunetheweb** [SpiderLabs/owasp-modsecurity-crs#1247]
## Type of Issue
feature suggestion

## Description
It seems to me that the Paranoia Levels (PL) only work in anomaly scoring mode. Let me know if this is not the case as only just upgraded to CRSv3 recently and may have missed this.

I think these are good features but some, like myself, prefer Blocking mode to reduce noise and have a black or white view of rules (they either fire or they do not - they either block a potential vulnerability or they do not).

Would there be any interest, or has there been any discussion of making PLs work in blocking mode? I’m thinking of setting a variable if this mode is in operation and then creating a rule using `SecRuleRemoveByTag` to remove PL/4 rules if running PL/3 for example.

I can’t think of an easy way to allow higher PL rules to execute but not block like you can in anomaly mode (there is no `SecRuleUpdateActionByTag` unfortunately which might have allowed this). Open to ideas if anyone else can think of a way of doing this, but just allowing PL at all on Blocking mode is a good start.

Thoughts? Happy to make a start on this if there is interest. Maybe one to discuss on the December Slack chat (will try to make it along).

## Your Environment
* CRS version v3.0.2.
* ModSecurity 2.9.2.
* Apache 2.4.37.

## Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
With the introduction of executing paranoia level in 3.1, this is now very hairy. I think it would complicate the whole rule construct very much for something, that is more and more a niche case. You are like the only person I know that has not adopted the anomaly scoring mode.

If you really want this, then I suggest you remove the branching rules by means `SecRuleRemoveById`. For rule file 910 and PL2, this would be 910013 and 910014. The numbering is consistent in almost all the cases. PL2 branching is done on xxxx13 and xxxx14, etc.
