### ISSUE TITLE
ModSecurity: JSON parsing error: lexical error: invalid char in json text.

### ISSUE THREAD

**Issue by MZSN** [SpiderLabs/owasp-modsecurity-crs#1248]
I am getting the error written in the title whenever my application hits my server. It is blocking all requests even the login requests as well. The difference only here is I have used end to end encryption. Is it why I am getting this error?

**Comment by csanders-git** [comment]
This sounds like a modsec question in which case you'd be better suited asking on the modsecurity GitHub. The answer is likely going to be changing what pages are treated as JSON. But there are numerous other factors such as what version of mod sec you're using and what other information is being displayed

**Comment by fgsch** [comment]
Looks like this ticket has been answered. Feel free to reopen it if not.
