### ISSUE TITLE
Catch XSS quoting variable injections if the webserver target code is vulnerable to those attacks

### ISSUE THREAD

**Issue by blappm** [SpiderLabs/owasp-modsecurity-crs#1249]
This is a suggestion to attacks like the following one:

`https://testurl.testdomain.test/myphpcode.php?userid=%22hacker&msg=blabla%27);alert(1);},1)}`

If the bad code just accepts the variable as it is and doesn't remove the quotes, it will be possible for attackers to inject javascript code into the destination page if this variable is rendered as an element or printed as a message.

CRS: 3.02

`SecRule ARGS "@rx (?:[\x27]\s*[\;\)\}\]\+\-\<\>\=\!](?:(?![\x27])|.*[\x22]|[^\x22\x27]+)$|[\x22]\s*[\;\)\}\]\+\-\<\>\=\!](?:(?![\x22])|.*[\x27]|[^\x22\x27]+)$)" \
    "msg:'XSS Injection: Quote(s) found within argument string, followed by js-logic', \
    id:300,phase:3,pass,log,auditlog,t:none,t:utf8toUnicode, \
    t:urlDecodeUni,t:htmlEntityDecode,t:jsDecode,t:cssDecode,t:removeNulls"`

I've double checked that balanced quotes in arguments like `'<xml>'` will be catched, while unbalanced ones wont.

**Comment by dune73** [comment]
Thank you for your suggestion @blappm.

Your payload is currently caught by the following rules, none of them in the default installation:

```
942110 PL2 SQL Injection Attack: Common Injection Testing Detected
942430 PL2 Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (12)
942431 PL3 Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (6)
942460 PL3 Meta-Character Anomaly Detection Alert - Repetitive Non-Word Characters
920273 PL4 Invalid character in request (outside of very strict set)
942432 PL4 Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (2)
```
I assume you want this caught in the default installation / PL1 too. 

Other opinions?

**Comment by csanders-git** [comment]
thanks for the report @blappm. I wanted to put a little more context onto this request. Is this injection you're describing specific to injections in a JS context (i.e a dev has allowed an attacker to inject content between <script> tags)? I'm thinking it is, but let me know if i'm misunderstanding. Just trying to think of possible solutions :)

**Comment by blappm** [comment]
@csanders-git

It's worse. The source page calls itself with an error-message variable named 'msg'. This message is untested printed with javascript alert(). PHP quoting wasn't helpful here because those quotes were not html special chars ...

I'm sure there are other bad usage examples where developers programmed bad code.

**Comment by blappm** [comment]
@dune73

> Your payload is currently caught by the following rules, none of them in the default installation:
> 942110 PL2 SQL Injection Attack: Common Injection Testing Detected
> Other opinions?

I just had a look at this, thank you.

Looking at the regex in rule 942110 it's much more simpler and doesn't catch all edge cases. And of course it leads to false positives since it catches balanced quotes within variables.

Why aren't you taking my example and move it to L1 ?

**Comment by blappm** [comment]
My regex didn't catch backticks. I've added this too to make it match 942110 more closely:

`SecRule ARGS "@rx (?:[\x27]\s*[\;\)\}\]\+\-\<\>\=\!](?:(?![\x27])|.*[\x22\x60]|[^\x22\x27\x60]+)$|[\x22]\s*[\;\)\}\]\+\-\<\>\=\!](?:(?![\x22])|.*[\x27\x60]|[^\x22\x27\x60]+)$|[\x60]\s*[\;\)\}\]\+\-\<\>\=\!](?:(?![\x60])|.*[\x27\x22]|[^\x60\x27\x22]+)$)" \
    "msg:'XSS Injection: Unbalances quote(s) found within argument string followed by operator', \
    id:300,phase:3,pass,log,auditlog,t:none,t:utf8toUnicode, \
    t:urlDecodeUni,t:htmlEntityDecode,t:jsDecode,t:cssDecode,t:removeNulls"`
