### ISSUE TITLE
Add Nginx+libmodsec to our Travis testing

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#1250]
We have automated testing running on Apache + ModSec 2.9, but not yet for Nginx + ModSec 3.

This would be useful as this combination is becoming more common and the active development on ModSec 3 requires also us keeping more close tabs on our compatibility.

**Comment by lifeforms** [comment]
Duplicate of #1113. Please look better before opening issues, thanks.

**Comment by zimmerle** [comment]
@lifeforms That is indeed a great idea. Notice that you may not need nginx to test v3. Unless you want to test the nginx connector. Using the regression test schema is a way faster and gives you more precise results. Let me know if you need any help.
