### ISSUE TITLE
Auto-create documentation about rules

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#1251]
Users who want to upgrade don't have a clear view of new ruleIds and their functionality.

We've talked a bit about creating a "rule zoo" with metadata taken from the CRS repo (paranoia level, rule type, attack class, platforms). Can we also import the relevant comment block above the rule?

We have to automatically import changes from the repo, otherwise it will get stale.

TBD: use cases - publish on website as a post-per-rule, a generated rule matrix, a matrix by version? Allow users to comment, upvote, downvote? Make data available as JSON for integrators?

**Comment by lifeforms** [comment]
@lifeforms and @christiantreutler-avi will have a chat about this and make a proposal.

**Comment by lifeforms** [comment]
Not a showstopper for CRS 3.2 but labeled it to not forget it.

**Comment by airween** [comment]
@theMiddleBlue and me also discussed about this (before I found this issue :)). I'ld like to join to this task.

My primary goal is that when I parsed the rules (and build AST), the comments remains and will parts of the structure. It would be good to bind the right comment to the specific rule, thus if somebody wants to operate with the structure, then the documentations is available.

Furthermore above I found more good ideas, which could work in reverse direction, eg generates some metadata (PL, rule type - the attack class and platforms is not sure).

After a quick review, I found so many "metadata-like" information in comments, eg:
```
# -=[ Rule Logic ]=-
# -=[ Targets, characters and html entities ]=-
# -=[ References ]=-
```
The information what not available explicitly is where the comment starts - the end is guessable. Assume that the last commented line to backward from the rule...?

What do you think about?

**Comment by dune73** [comment]
I think your parser is the way to so many nice things and defining a way for meta-information about rules sounds like a good start, then we can adopt the rules, extract the data and publish it in an accessible way on the website. Possibly also via a JSON API, so integrators could simply fetch rule information from crs.org and we would thus get an overview over CRS usage in return.
