### ISSUE TITLE
Create whitelist rules at PL3 for most important HTTP request headers

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1258]
See #1137 for reasoning.

We need to make sure that HTTP header pollution and header bypasses are ruled out. At least in PL3.

Candidates for whitelisting:
* Content-Type
* Content-Length

Possible additional headers:
* Authorization
* Connection
* Cookie
* Host
* Range
* Referer
* User-Agent
* Via

**Comment by franbuehler** [comment]
WIP suggestion in https://github.com/franbuehler/owasp-modsecurity-crs/tree/header-whitelisting-pl4:

- Content-Type
- Accept
- Authorization
- Pragma
- Range, Request-Range

Content-Length Whitelist `!@rx ^\d+$` is already covered: rule id 920160.

**Comment by dune73** [comment]
We're actively working on this. Just not as active as necessary to implement this within 120 days.
