### ISSUE TITLE
Fix broken FTW tests and enable them in Travis

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1260]
I thought we were covered as far as FTW tests were concerned, but unfortunately, we have 78 failing tests and it seems travis is no fully enabled.

* 4 of the failing tests are in 920
* 74 of the failing tests are in 944

Here is the list:

* 920120-2
* 920130-1
* 920130-2
* 920400-1
* 944100-11
* 944100-12
* 944100-15
* 944100-16
* 944110-11
* 944110-12
* 944110-15
* 944110-16
* 944120-5
* 944120-6
* 944120-13
* 944120-14
* 944120-15
* 944120-16
* 944120-22
* 944120-23
* 944120-30
* 944120-31
* 944120-32
* 944120-33
* 944120-39
* 944120-40
* 944120-47
* 944120-48
* 944120-49
* 944120-50
* 944120-56
* 944120-57
* 944120-64
* 944120-65
* 944120-66
* 944120-67
* 944120-73
* 944120-74
* 944120-81
* 944120-82
* 944120-83
* 944120-84
* 944120-90
* 944120-91
* 944120-98
* 944120-99
* 944120-100
* 944120-101
* 944120-107
* 944120-108
* 944120-115
* 944120-116
* 944120-117
* 944120-118
* 944120-124
* 944120-125
* 944120-132
* 944120-133
* 944120-134
* 944120-135
* 944210-5
* 944210-6
* 944210-13
* 944210-14
* 944210-15
* 944210-16
* 944210-22
* 944210-23
* 944210-30
* 944210-31
* 944210-32
* 944210-33
* 944210-39
* 944210-40
* 944210-47
* 944210-48
* 944210-49
* 944210-50

The idea is to make them work again and then to enable all of them for Travis. I think this should be a high priority, so I am tagging it as such.

Running the tests is explained in his blog post: https://coreruleset.org/20171214/practical-ftw-testing-the-core-rule-set-or-any-other-waf/

Running a single tests is done as follows:

```
(env) $> py.test -sv CRS_Tests.py --ruledir_recurse=tests -k  920120-2
```

**Comment by csanders-git** [comment]
I'll take a look not sure why this is the case

**Comment by fgsch** [comment]
Anything left to do in this ticket? Seems like all tests are passing now.

**Comment by dune73** [comment]
True. Closing this.
