### ISSUE TITLE
List of hidden directories and files (published research)

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1263]
There is a new article with hidden files and artefacts that we ought to detect. Yet there are some that we ignore:

https://medium.com/@_bl4de/hidden-directories-and-files-as-a-source-of-sensitive-information-about-web-application-84e5c534e5ad

**Comment by ghost** [comment]
@dune73 Do you mean updating this file? https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.2/dev/rules/restricted-files.data

If so, I'm going to be greedy and take the other "good first issue" if I can 💯

**Comment by dune73** [comment]
Hi @danehrlich1, sorry for the late response. Yes, exactly this.

**Comment by ghost** [comment]
@dune73 
1. Quick question. Can we restrict access to every file or folder that begins with a "." ? I can't think of why something would need to access a hidden dot file or dot directory. 

2. So we could restrict:

- .a*
- .b*
- .c*
- .d*
- etc.
- .z*

3. If a user really needed someone to access a hidden dot file / directory, they could turn off this rule or perhaps there should be space for an exception?

4. This would free me up to focus only on files that aren't hidden like `wp-config.php` for example.

**Comment by dune73** [comment]
That sounds like a classic case for a stricter sibling. That is a more severe version of the rule at a higher paranoia level. So you have the base rule at PL1 and then at PL2 or PL3 an additional rule where you forbid all hidden files.

Good thinking actually!
