### ISSUE TITLE
Whitelisting IP addresses for  "host header is a numeric ip address"  error 

### ISSUE THREAD

**Issue by rcbarnett-zz** [SpiderLabs/owasp-modsecurity-crs#127]
CORERULES-73: Hi,

Facing the problem in IP based access through mod security. Checked the mod sec logs, its due to "host header is a numeric ip address " rule in  modsecurity_crs_21_protocol_anomalies.conf file. 

Instead of commenting particular line the file modsecurity_crs_21_protocol_anomalies.conf, need to do whitelist for certain IP to do IP based access . Rest can be accessed through hostname or domain.

Pls advice.

Regards
Siva

**Comment by pleothaud** [comment]
REMOTE_ADDR is for the client address, not for the target Web Server.

The rule also needs an id.

@ipMatch will fail if the content is not an IP address, leading to problems if some users do use a hostname or a FQDN.

So finally I used :

SecRule REQUEST_HEADERS:Host "192.168.1.100" "id:'1011', phase:1,t:none,nolog,pass,ctl:ruleRemoveById=960017"

which seems to be working as expected.

Thanks

**Comment by csanders-git** [comment]
@pleothaud make sure to bound your regex ^192.168.1.100$ otherwise it is possible you might be open to various malicious activities. enjoy

**Comment by pleothaud** [comment]
Yes sure you're right, and I did not escape the '.' chars

Note also that you may have a port after the IP :-) 

So the trailing $ should  come after something like (:[0-9]+)?

Thanks

**Comment by csanders-git** [comment]
Yup, as long as you're aware :)
