### ISSUE TITLE
Submit CRS to stackshare.io

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1279]
https://stackshare.io is a place where online sites describe their stack so people get to see what other sites are using in terms of software. Apache is there, NGINX is, ModSecurity and CRS are not.

Submissions can be made via mail or twitter. It's probably smart to plan this a bit, add the logo and start a campaign to tell people to pick CRS on the sight.

**Comment by csanders-git** [comment]
Interesting never heard of this but I think it makes sense what is the level of effort
