### ISSUE TITLE
Create unit-test to check for rule range

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1285]
In the standard rule files, we should only allow 9xxxxx rule IDs.
In the rule exclusions, we should only allow 9xxxxxx rule IDs.

3.1 was released with 9xxxxxx rule IDs within the REQUEST-914 file. And that's really annoying.

**Comment by lifeforms** [comment]
REQUEST-914 was not present in 3.1.

(But I don't disagree with some kind of linting on this!)

**Comment by dune73** [comment]
Ah, yes. We postponed this from 3.1. Thanks for pointing this out. I'm so much on 3.2 now, I got nervous, when I saw the PR #1284.
