### ISSUE TITLE
Enable SSL on the Docker CRS Proxy

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/owasp-modsecurity-crs#1289]
## Type of Issue

Feature suggestion for Dockerfile of ModSecurity.
## Description

ModSecurity should allow SSL as well on this proxy. Simple SSL termination for now on this proxy would be fine. 

I know how to do this for the most part as I spent forever configuring it for another project. Could I create a pull request with the code required (will just extend current Dockerfile and Entry Point script)?

## Your Environment

* CRS version (e.g. v3.0.2):
* ModSecurity version (e.g. 2.9.2):
* Web Server and version (e.g. apache 2.4.27):
* Operating System and version:

## Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by csanders-git** [comment]
Great idea I'll get right on this

**Comment by dune73** [comment]
Totally welcome contribution.

You guys may want to coordinate with @franbuehler and her plans for the docker container. Not sure if she had any time to work on it as of late.

**Comment by dune73** [comment]
I suggest to contribute this issue to the discussion in #1290 and then close this one here.

**Comment by franbuehler** [comment]
Finally, I started to work on integrating my changes into the official image.
See issue #1290.

**Comment by fgsch** [comment]
Can this be closed in favour of #1290?

**Comment by dune73** [comment]
Yes.

I'm closing this in favour of #1290 as I understand that covers SSL too. Please reopen, if I am wrong.
