### ISSUE TITLE
 Agenda for Monthly Chat: February 2019 (2019-01-04)

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1291]
This is the Agenda for the Monthly CRS Chat.

The chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, February 4, at 20:30 CET.

### PRs

    #... ...

### Other items

* Release 3.1.1 release because of #1276 (JWall compatibility)
* Cloudfest workshop
* AppSecGlobal Tel Aviv
* CRS swag, proposal by @fzipi
* #1277 GeoIP deprecated their old database, so our upgrade script and our documentation are currently not valid.
* Core Rule Set Container discussion: https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1290

Feel free to add items as you see fit either above, or below as comments.

If you are not yet on the OWASP Slack, here is your invite: https://join.slack.com/t/owasp/shared_invite/enQtNDI5MzgxMDQ2MTAwLTEyNzIzYWQ2NDZiMGIwNmJhYzYxZDJiNTM0ZmZiZmJlY2EwZmMwYjAyNmJjNzQxNzMyMWY4OTk3ZTQ0MzFhMDY

**Comment by danehrlich1** [comment]
What is the issue with GeoIP not working? 

Could the below work?

1. Update the GeoIP database daily
```
wget https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz \
&& tar -xvf GeoLite2-Country* && mkdir /usr/local/share/GeoIP \
&& mv GeoLite2-Country*/GeoLite2-Country.mmdb /usr/local/share/GeoIP 
```
2. In ModSec offload to script that uses one of the many MaxMind GeoIP2 apis (they have ones for Perl, Java, PHP, Python, Javascript, C, etc) to read from above database and find location of REMOTE_IP.

**Comment by spartantri** [comment]
Hi @dune73, do you know when was the last time JWall was updated and how big is its user base?
I would like to have the PR#1294 on 3.1.1 to make it worth the updating effort for lots of users.

**Comment by dune73** [comment]
I can not really tell, but the user base seems to be steady. I have a commerical customer integrating ModSec and they are referring their users to use JWall. Have not talked to Developer Christian Bockermann in years.

As far as #1294 is concerned, I doubt we'll backport this as it's a new rule and release policy states that we do not include new rules in point releases.

**Comment by fgsch** [comment]
Completed.
