### ISSUE TITLE
Still including the update utility in the example conf - utility is now defunct

### ISSUE THREAD

**Issue by JeffCleverley** [SpiderLabs/owasp-modsecurity-crs#1303]
## Type of Issue

Error upgrading geoip database using modsec 3 and nginx

## Description

In this ticket #1277

Seems to suggest that the only problem is with older versions of ModSec, 2.9x etc and not 3.0

## Your Environment

CRS version v3.1
ModSecurity v3.0.3
(libmodsecurity.so.3.0.3)
(https://github.com/SpiderLabs/ModSecurity)
Nginx 1.15.8
ModSec v3 Nginx Connector
(https://github.com/SpiderLabs/ModSecurity-nginx)
Ubuntu 18.04 

## Confirmation

[x ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

## Console output

`geoip: HTTP Error 404: Not Found`

**Comment by JeffCleverley** [comment]
`/owasp-modsecurity-crs-3.1.0/util.py`

includes:

`url = 'https://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz'`

new databse is at

`https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz`

**Comment by JeffCleverley** [comment]
I see from #1151 

That you pulled the database update script, and we need to do it ourselves...

Fair enough... but the packaged example conf still includes the update utility

```
#
# -- [[ GeoIP Database ]] ------------------------------------------------------
#
# There are some rulesets that inspect geolocation data of the client IP address
# (geoLookup). The CRS uses geoLookup to implement optional country blocking.
#
# To use geolocation, we make use of the MaxMind GeoIP database.
# This database is not included with the CRS and must be downloaded.
# You should also update the database regularly, for instance every month.
# The CRS contains a tool to download it to util/geo-location/GeoIP.dat:
#   util/upgrade.py --geoip
```

**Comment by JeffCleverley** [comment]
Also

just to confirm

crs3 works with the new format?

`GeoLite2-Country.mmdb`

**Comment by dune73** [comment]
Thanks for the hint about the example conf.

CRS is just fine with the format. It's with ModSec where the problem lies. ModSec 2 does not support the new format. However, there is now a conversion script by @emphazer, that allows you to continue to use the GeoIP DB with ModSec2.

**Comment by JeffCleverley** [comment]
That great, thanks for the reply.

What I should also ask is...

Does ModSec 3 work with the new GeoIP DB format

`GeoLite2-Country.mmdb`

**Comment by dune73** [comment]
Yes it does. Many other things are unstable with ModSec3, but this seems to be OK.

**Comment by fzipi** [comment]
After merging #1584 , text has been extended to provide better insights.
