### ISSUE TITLE
XSS false positive on "-->"

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#1313]
## Type of Issue

False positive

## Description

The sequence `-->` sometimes turns up in natural text as users make an arrow.

Example request:

```
curl --data 'foo=x --> y' http://localhost/
```

This triggers rule 941180 (Node-Validator Blacklist Keywords)

Perhaps it's possible to move the comment close tag `-->` to paranoia level 2, while keeping the comment open tag `<!--` in paranoia level 1.

## Your Environment

CRS 3.1.0

## Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by csanders-git** [comment]
The problem with this is that it is really a control char from escaping comment syntax in HTML. Therefore it would be dangerous to add an exception, even if a <!-- wasn't seen.

**Comment by lifeforms** [comment]
Good point.
