### ISSUE TITLE
false positives with matrix synapse homeserver

### ISSUE THREAD

**Issue by damnms** [SpiderLabs/owasp-modsecurity-crs#1321]
The default ruleset blocks matrix synapse (reference server implementation)

## Type of Issue

https://github.com/SpiderLabs/ModSecurity/issues/2036
and also uploads in general seems to be blocked, at least images
```
Message: Access denied with code 403 (phase 2). Match of "rx ^%{tx.allowed_request_content_type}$" against "TX:0" required. [file "/usr/share/modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "995"] [id "920420"] [rev "2"] [msg "Request content type is not allowed by policy"] [data "image/jpeg"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS/POLICY/ENCODING_NOT_ALLOWED"] [tag "WASCTC/WASC-20"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/EE2"] [tag "PCI/12.1"]
Apache-Error: [file "apache2_util.c"] [line 273] [level 3] [client %s] ModSecurity: %s%s [uri "%s"]%s
Action: Intercepted (phase 2)
Apache-Handler: proxy-server
Stopwatch: 1551902256288022 54267 (- - -)
Stopwatch2: 1551902256288022 54267; combined=866, p1=420, p2=392, p3=0, p4=0, p5=54, sr=57, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.1 (http://www.modsecurity.org/); OWASP_CRS/3.0.0.
Server: Apache
Engine-Mode: "ENABLED"
```

## Your Environment

* CRS version (e.g. v3.0.2): ii  modsecurity-crs                    3.0.0-3                        all          OWASP ModSecurity Core Rule Set
* ModSecurity version (e.g. 2.9.2): ii  libapache2-mod-security2           2.9.1-2                        amd64        Tighten web applications security for Apache

* Web Server and version (e.g. apache 2.4.27): ii  apache2-bin                        2.4.25-3+deb9u6                amd64        Apache HTTP Server (modules and other binary files)

* Operating System and version: debian 9

## Confirmation

[x ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by theMiddleBlue** [comment]
Hi @damnms 

thanks for reporting this! It seems related to the content-type `image/jpeg` that is not allowed by default. Could you try to uncomment the rule `900220` on your crs-setup.conf and add `image/jpeg` to the list?

thank you

**Comment by damnms** [comment]
Thanks that worked. in my crs-setup.conf i now have that block:

```
# Content-Types that a client is allowed to send in a request.
# Default: application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/x-amf|application/json|text/plain
# Uncomment this rule to change the default.
SecAction \
 "id:900220,\
  phase:1,\
  nolog,\
  pass,\
  t:none,\
  setvar:'tx.allowed_request_content_type=application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/x-amf|application/json|text/plain|image/jpeg'"

```

I am just wondering if there is some kind of "global whitelist for audio/image" ? 
Sorry, i am total unfamiliar with all that. Maybe you have an idea?

**Comment by theMiddleBlue** [comment]
to be honest, I don't know how matrix synapse works. With a little search on the github repo I've found this: https://github.com/matrix-org/synapse/search?q=content-type&unscoped_q=content-type 

Maybe you should include `image/png` too

**Comment by damnms** [comment]
its like whatsapp, people can register and then communicate with others, but on your own server. there is also `Content-Type: <media-type>` in a code part, so i guess there is some more to whitelist.

edit: even worse... https://github.com/matrix-org/synapse/blob/829213523eadad30aabedf8242c6c02f3dfcbe24/synapse/rest/media/v0/content_repository.py#L70

**Comment by fgsch** [comment]
This looks like a support question so maybe more suitable for https://security.stackexchange.com/questions/tagged/mod-security?

**Comment by fgsch** [comment]
@damnms is there anything outstanding on this issue or can be closed? Thanks!

**Comment by dune73** [comment]
I do not see anything for us to do. So I'm closing this.

@damnms: Feel free to reopen, if the project should act.
