### ISSUE TITLE
No libinjection check on last path segment

### ISSUE THREAD

**Issue by theseion** [SpiderLabs/owasp-modsecurity-crs#1328]
The libinjection rule doesn't perform checks against the last path segment. That allows attackers to spam a webserver with URL's like the following:

```
https://domain.com/a/b/some-page_name999999.1%20union%20select%20unhex(hex(version()))%20--%20and%201%3D1
```

**Comment by fgsch** [comment]
Isn't this a dup of #1022?

**Comment by ssiar-fastly** [comment]
Appreciate a response to this! @fgsch

**Comment by fgsch** [comment]
@ssiar-fastly Please see PR above.

**Comment by dune73** [comment]
PR #1329 superseeded by PR #1492.

PR #1492 has been merged. It fixes this issue. Closing this.

**Comment by theseion** [comment]
Awesome! Thanks @dune73!

**Comment by dune73** [comment]
You're most welcome. Glad we could merge this. Thank you for the initiative.
