### ISSUE TITLE
crs-setup.conf config error！

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/owasp-modsecurity-crs#1331]
## Description
When I have all the configurations installed,I use nginx -t  It show "nginx: [emerg] unexpected end of file, expecting ";" or "}" in /etc/nginx/conf.d/crs-setup.conf:857" ? why??? This CRS configuration file is directly copied from your official file without any modification

## Your Environment

* CRS version  master
* ModSecurity version 3.0.2
* Web Server and version  nginx1.15.9
* Operating System and version: centos7.5

![error1](https://user-images.githubusercontent.com/17851645/54897750-a9475a80-4f04-11e9-9838-8f551e990e68.png)
![error2](https://user-images.githubusercontent.com/17851645/54897752-ae0c0e80-4f04-11e9-961a-1bfa98646cb3.png)

**Comment by Nymeria1** [comment]
Hello,
how did you solve the issue? I have got the same problem

**Comment by csanders-git** [comment]
Not sure what is causing this but i'd like to try and help in case someone else sees this ticket. Perhaps try adding a space before the line continuation (if there is one at that location). -- There was an old apache bug like this.
