### ISSUE TITLE
Monthly Chat Agenda April 2019 (2019-04-01)

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1333]
This is the Agenda for the Monthly CRS Chat.

The chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, April 1, at 20:30 CET.

### PRs
* #1113 Add NGINX Docker and Travis Testing support.
* #1320 XML attack rules file 945000
* #1327 Remove old and unwanted constructs
* #1329 Added libinjection SQLi rule for last path segment
* #1330 WordPress: exclude Gutenberg via rest_route
* #1332 XML Soap Encoding 920240

### Other items

* CRS Community Summit: Nobody seems to be eager to go to Tel Aviv and they say we might be charged 2K for a room for half a day. 
Proposal: Community Summit in Amsterdam at AppSecEU in September
* Should we open a paypal account to receive our share of the swag if we sell anything? https://github.com/fzipi/owasp-swag/tree/add-coreruleset-logos/projects/coreruleset
* Status of the update of the CRS docker container(s) (@csanders-git / @franbuehler / @danehrlich1)

I, Christian speaking here, will try to attend the chat, but I am on a business trip in Ireland, so I might be late - or not show up at all. [Update: 7pm: Customer invited the whole class to dinner ... Don't wait for me with the chat. Sorry.]

Feel free to add items as you see fit either above, or below as comments.

If you are not yet on the OWASP Slack, here is your invite: https://join.slack.com/t/owasp/shared_invite/enQtNDI5MzgxMDQ2MTAwLTEyNzIzYWQ2NDZiMGIwNmJhYzYxZDJiNTM0ZmZiZmJlY2EwZmMwYjAyNmJjNzQxNzMyMWY4OTk3ZTQ0MzFhMDY

**Comment by theMiddleBlue** [comment]
to remind myself: talk about RomHack 2019 :)
