### ISSUE TITLE
Demo page isn't working

### ISSUE THREAD

**Issue by robsch** [SpiderLabs/owasp-modsecurity-crs#1334]
https://www.modsecurity.org/crs-demo.html

Whatever I try, the response page is:

> Created
> 
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> 
> Please contact the server administrator, support@modsecurity.org and inform them of the time the error occurred, and anything you might have done that may have caused the error.
> 
> More information about this error may be available in the server error log.

**Comment by fgsch** [comment]
Unfortunately that page is outside our control.

Please do check with support@modsecurity.org.
