### ISSUE TITLE
ModSecurity failed rules

### ISSUE THREAD

**Issue by Ezizeay** [SpiderLabs/owasp-modsecurity-crs#1349]
Hello

It has been long time, no matter what attacks to the Apache/2.9.0, only following rule is triggered
[file "/etc/httpd/modsecurity.d/ruleset-01-crs/REQUEST-20-PROTOCOL-ENFORCEMENT.conf"] [line "722"] [id "960015"] [rev "3"] 
# Environment
Producer: ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/); OWASP_CRS/3.0.0.
CentOS release 6.10 (Final)

Any idea how to fix it please.

**Comment by lifeforms** [comment]
Hi @Ezizeay , it seems you are running a very old version of the CRS ruleset.

Would it be possible for you to upgrade them to the latest version?

**Comment by Ezizeay** [comment]
Hi  @lifeforms, thanks for your attention.  OWASP_CRS/3.0.0. is old version???
Yes, it is possible to upgrade it.  Will you please provide some link/descriptions to do it??
By the way, what is your suggestions of testing crs without browsers?

**Comment by theMiddleBlue** [comment]
Hi @Ezizeay 

You can find information on how to install CRS3.1 here: https://coreruleset.org/installation/ 
Please, feel free to reopen this if you have further details about your issue.

**Comment by Ezizeay** [comment]
Hi @theMiddle

Thanks for your attentions. I was told to trigger crs rules with current configurations.
I have trying followings on centos6.10 (modsecurity enable on apache without browser), but not working. 
curl 'http://ip/?q="><script>alert(1)</script>'
curl "http://ip/?q='1 OR 1=1"
curl localhost/index.html?exec=/bin/bash
curl ip/index.html?exec=/bin/bash
Please shed some lights to trigger crs rules?

![Untitled](https://user-images.githubusercontent.com/49372377/56125505-5d268d80-5f79-11e9-89ef-47ce15dade11.png)
