### ISSUE TITLE
test modsecurity from CLI

### ISSUE THREAD

**Issue by Ezizeay** [SpiderLabs/owasp-modsecurity-crs#1351]
Hi, as the title says I need to test if crs can be fired or not.
Since there is no GUI installation of centOS6.10 in my environment,
I have to test it by command line .
Any suggestion will highly be appreciated.

**Comment by theMiddleBlue** [comment]
Hi @Ezizeay 

I'm closing this issue because it's not related to a CRS problem. BTW, If you need to send HTTP requests via CLI, you can use something like `curl`, `wget`, `httpie`, etc...

thanks!
