### ISSUE TITLE
Apache configuration should include Modsecurity confiuration?

### ISSUE THREAD

**Issue by Ezizeay** [SpiderLabs/owasp-modsecurity-crs#1353]
What if Apache configuration does not include the Core Rules, ModSecurity? 
Is it essential for ModSecurity functioning well?
Should it be included automatically or manually?

I have checked httpd.conf file and found that Modsecurity confiurations are not there (e.g. the attached configurations.

![Untitled](https://user-images.githubusercontent.com/49372377/56139809-e3eb6280-5f99-11e9-8b99-b31346f48c7e.png)
)?

**Comment by spartantri** [comment]
Hi @Ezizeay if the modsec main setup, crs setup and rules are not in your webserver include list, modsecurity provide no protection against attacks if you want that you need to add the includes yourself.

**Comment by Ezizeay** [comment]
Hi @spartantri
  Thanks a lot for your comments.
Can I COPY/PASTE the include directives in modsecurity.conf into httpd.conf file ???
Or I simply delete the includes directives (attached above) in modsecurity.conf and rewrite the include directives (or just copy) in httpd.conf file??
Thanks in advance of your attention.

**Comment by spartantri** [comment]
That depends if yours match the same path then copy/past the includes will work, I do not advise you to copy the entire `httpd.conf` as there may be other settings that are not compatible.
Once you do that also verify the CRS setup conf file and restart your Apache and it should load the rules.

**Comment by Ezizeay** [comment]
Can't thank enough @ spartantri.
Really helpful. I don't know how to close it.
Have a nice day
