### ISSUE TITLE
Why modsecurity register Apache2 403 .htaccess rule event instead only own modsecurity event?

### ISSUE THREAD

**Issue by itmagpro** [SpiderLabs/owasp-modsecurity-crs#1360]
@itmagpro uhm, sorry the K section was not so helpful in this case. If I understand well, Apache itself return 403 because of your .htaccess configuration. Anyway, it seems that your issue is not related to a CRS problem (and your request doesn't match any CRS rule). Closing this for now but if you disagree feel free to reopen.

_Originally posted by @theMiddleBlue in https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1352#issuecomment-483171472_

You not read and not giving me answer on my previous general question!

I putin the question otherwise...

Why modsecurity register Apache2 403 .htaccess rule event instead only own modsecurity event? How to avoid this modsecurity behavior?

Also I repeat previous related general question: how to avoid dublicate Apache2 403 behavior from .htaccess rules to /var/log/httpd/modsec_audit.log?

**Comment by theMiddleBlue** [comment]
I'm not sure to understand well your question. If I'm not wrong, you get a 403 from your Apache when you request some paths that are disallowed by your .htaccess configuration, is it right? What you see on your modsecurity audit logs, depends on how you have configured `SecAuditEngine` and `SecAuditLogRelevantStatus`. For example, if you have configured `SecAuditEngine` to `RelevantOnly` and `SecAuditLogRelevantStatus` to de default value (`^(?:5|4(?!04))`) you'll see a log for each response error, but that doesn't mean that your request has triggered a SecRule.

Please refer to https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29#secauditengine for any further question about ModSecurity, you can refer to the [ModSecurity GitHub Project](https://github.com/SpiderLabs/ModSecurity).

thanks!
