### ISSUE TITLE
Why Packages are incompatible

### ISSUE THREAD

**Issue by Ezizeay** [SpiderLabs/owasp-modsecurity-crs#1363]
Dear all
Why packages of CRS 2.x are incompatible with CRS 3.x. ??
(what packages for example?)
How to check if CRS 3.x is upgraded from CRS 2.x or simply installed freshly?

Thanks in advance for your attentions.

![Capture](https://user-images.githubusercontent.com/49372377/56295729-7f610c80-612d-11e9-9c79-2e7924c47780.PNG)

**Comment by spartantri** [comment]
Hi @Ezizeay we did a lot of changes including rule id changes from old 2.x to 3.0, I would advice to go directly to the latest 3.1, the number of false positive in v2 is much higher and there are tons of new features included since then.
