### ISSUE TITLE
rejected (Error 500) at our modsecurit crs with error

### ISSUE THREAD

**Issue by Ezizeay** [SpiderLabs/owasp-modsecurity-crs#1365]
Hello 

Requests are rejected (Error 500) at our modsecurit crs with error “"Outbound Anomaly Score Exceeded (score 4): The application is not available" ." .

AAA-20191219:22.14.12.125 - - [18/Dec/2019:9:43:23 +00] 
"POST /XXX-server-app/v1/licenses/ HTTP/1.1" 500 78 "-" "okhttp/3.11.0" 48718µs 744 UNIQUE_ID="XLiN@38AAAEAAPnddHgAAAAR" 
SSL_CLIENT_S_DN_CN="-" SOAPAction=- SOAP_RESPONSE=-

AAA-20190419:[Thu Apr 1& 9:43:23 2019] [error] [client 22.14.12.125] 
ModSecurity: Warning. Pattern match "^5\\\\d{2}$" at RESPONSE_STATUS. [file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_crs_50_outbound.conf"] 
[line "53"] [id "970901"] [rev "2"] [msg "The application is not available"] [data "Matched Data: 500 found within RESPONSE_STATUS: 500"] [severity "ERROR"] 
[ver "OWASP_CRS/2.2.6"] [maturity "9"] [accuracy "9"] [tag "WASCTC/WASC-13"] [tag "OWASP_TOP_10/A6"] [tag "PCI/6.5.6"] 
[hostname "aaa"] [uri "/xxx-server-app/v1/licenses/"] [unique_id "XLiN@38AAAEAAPnddHgAAAAR"]

Appreciated of your propositions:
Regards

**Comment by spartantri** [comment]
Hi @Ezizeay this error means that the application replied with a 500 reply and ModSecurity is blocking it.

If you need to let those 500 response (/!\ caution can be risky) to go out, you can do it with this run-time rule removal added into your custom rules.
```SecRule RESPONSE_STATUS "@eq 500" "phase:3,id:58,t:none,ctl:ruleRemoveById=970901"```

Be careful as this will let all 500 response to leak.

PS: Notice that this rule in the new CRS was renumbered to `950100`

**Comment by spartantri** [comment]
Closing this since it is not a bug, feel free to contact us over slack or mail list for support related questions
