### ISSUE TITLE
Freshly installing CRS 3.1 into Apache 2.2

### ISSUE THREAD

**Issue by Ezizeay** [SpiderLabs/owasp-modsecurity-crs#1366]
what is worse case of installing CRS 3.1 into Apache 2.2 (End-of-Life) in CentOS?
what is best environment requirements to install CRS 3.1?

**Comment by spartantri** [comment]
Hi @Ezizeay for support questions you can use the mail list https://sourceforge.net/projects/mod-security/lists/mod-security-users or even better use  https://owasp.slack.com in the channel #coreruleset

As for your question, I would definetively stay away from EOL software, you may compile your own Apache 2.4, here is a good tutorial to help you start with ModSecurity and CRS https://www.netnea.com/apache-tutorials/

If you are not yet on the OWASP Slack, here is your invite: https://join.slack.com/t/owasp/shared_invite/enQtNDI5MzgxMDQ2MTAwLTEyNzIzYWQ2NDZiMGIwNmJhYzYxZDJiNTM0ZmZiZmJlY2EwZmMwYjAyNmJjNzQxNzMyMWY4OTk3ZTQ0MzFhMDY
