### ISSUE TITLE
why modsec_audit.log is NOT ABEFHIJZ format

### ISSUE THREAD

**Issue by Ezizeay** [SpiderLabs/owasp-modsecurity-crs#1367]
Hello ;
1. 
Since configured as `SecAuditLogParts              ABEFHIJZ`.
but why modsec_audit.log looks like below? I can't understand anything from the log.

secure-xxx 60.180.1.15 - - [1/Mar/2019:15:26:11 +0100] "POST xx/v1u1 HTTP/1.1" 200 309 "-" "-" XBEag6rT8su8jTS1nrYlCwAAAAU "-" /2019512/2019512-1526/2019512-152611-XBEag6rTsdz"nrYlCwAAAAU 0 26599 md5:ae4bsdfze67a4a9277zee67a4ac988af1

2. 
Is there any way to check if owasp-modsecurity-crs is freshly installed or upgraded?
Thanks in advance.

**Comment by spartantri** [comment]
Hi @Ezizeay this is not an auditlog sample, it looks more like a custom format access log, there are two format for auditlog native and json, native is human readable pretty easy to read clear text, json is better for scripting and searching but looks ugly unless you parse it with `jq` or `python -m json.tool`.

Please read the tutorials I shared in other ticket, to help you better understand ModSecurity, and contact us over slack or the mail list if you need help with your setup.

**Comment by Ezizeay** [comment]
Thanks spartantri
I will do what you said
