### ISSUE TITLE
ReDoS meeting agenda - Apr 29

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#1369]
We will hold a chat on the Slack channel to triage, review and merge the ReDoS fixes (the proposed changes are welcome, yet they could lead to changes in the behavior and we need to be very careful).

The date = 29 Apr 2019, 19:30 UTC = 20:30 CEST.

The agenda:
- https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1359 report 5 (Priority 1)
- https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1354 report 1 (Priority 2)
- https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1356 report 2 (Priority 2)
- https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1357 report 3 (Priority 2)
- https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1358 report 4 (Priority 2)
- (If we have time) brainstorm about our future work for this class of problems, add documentation and guidelines to our wiki, etc.
- Plans for backporting and a 3.1.1 release?

Feel free to add items as you see fit either above, or below as comments.

If you are not yet on the OWASP Slack, here is your invite: https://join.slack.com/t/owasp/shared_invite/enQtNjExMTc3MTg0MzU4LTViMDg1MmJiMzMwZGUxZjgxZWQ1MTE0NTBlOTBhNjhhZDIzZTZiNmEwOTJlYjdkMzAxMGVhNDkwNDNiNjZiOWQ

**Comment by lifeforms** [comment]
@s0md3v We would love it if you could join our chat on Monday! Do you think you can make this time? It might be a bit late, depending on your time zone, but I don't know your sleeping schedule ;) Let us know.

**Comment by s0md3v** [comment]
Hi @lifeforms ,
I would love to join the chat but it would be 1:30 AM in here, so for some reason I fail to make it to the chat, I apologize in advance.
You can mail me conference details through s0md3v@gmail.com or just DM me on my twitter @s0md3v.

**Comment by lifeforms** [comment]
Hi @s0md3v , wow that's very late. We can't ask that of you of course. But we could also discuss it earlier.

We always hold the chat on the OWASP Slack. You can find an invite in the top post, please join us in channel #coreruleset if you like :)

**Comment by s0md3v** [comment]
@lifeforms I appreciate you for changing the schedule for my comfort. thanks. That invite link expired tho.

**Comment by dune73** [comment]
Could you try out the following invite https://join.slack.com/t/owasp/shared_invite/enQtNjExMTc3MTg0MzU4LTViMDg1MmJiMzMwZGUxZjgxZWQ1MTE0NTBlOTBhNjhhZDIzZTZiNmEwOTJlYjdkMzAxMGVhNDkwNDNiNjZiOWQ

It takes you to the channel #OWASP, then join channel #coreruleset.

**Comment by s0md3v** [comment]
[Joined]
