### ISSUE TITLE
High Memory with Nginx 1.14 + ModSecurity v3

### ISSUE THREAD

**Issue by NizarBlond** [SpiderLabs/owasp-modsecurity-crs#1370]
## Type of Issue
performance issue

## Description
I'm running on a 4GB RAM on Amazon Linux 2 server which hosts multiple WP sites, almost 90, all have static content (cached pages) and the images/assets are all on CDN. Up until now, it was running perfectly fine.

I recently installed ModSecurity + OWASP ModSecurity

https://github.com/SpiderLabs/ModSecurity
https://github.com/SpiderLabs/ModSecurity-nginx.git
https://github.com/SpiderLabs/owasp-modsecurity-crs.git

I configured "Include rules/*" and then each Nginx process consumes 45% of the memory, 2 processes are enough to break the system's performance.

```
> ps -aux | grep nginx
root 2649 0.0 45.8 1949448 1825280 ? Ss 11:07 0:00 nginx: master process /usr/sbin/nginx
nginx 2650 0.0 45.9 1950956 1827908 ? S 11:07 0:00 nginx: worker process
nginx 2653 0.0 45.9 1950956 1827908 ? S 11:07 0:00 nginx: worker process

```

Now, I wonder why that happens in such a drastic increment in the Memory. My server is going down after a while and I am pretty sure this is what is causing it. Any explanation? The default OWASP setup includes all rules.

I tried to include only certain rules e.g.

```
Include rules/REQUEST-910-IP-REPUTATION.conf
Include rules/REQUEST-912-DOS-PROTECTION.conf
Include rules/REQUEST-921-PROTOCOL-ATTACK.conf
Include rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
Include rules/REQUEST-949-BLOCKING-EVALUATION.conf
Include rules/RESPONSE-980-CORRELATION.conf
```

> ps -aux | grep nginx
root      8964  0.4 10.9 522440 437408 ?       Ss   15:52   0:02 nginx: master process /usr/sbin/nginx
nginx     9105  0.0 10.8 522444 431900 ?       S    16:00   0:00 nginx: worker process
nginx     9106  0.0 10.8 522444 431900 ?       S    16:00   0:00 nginx: worker process

Apparently now it is consuming less.

I am not sure how the ModSecurity works and handles the rules, I would be grateful for explanation and how I can improve the performance. 

## Your Environment
* CRS version (latest-  3.1.0)
* ModSecurity v3
* Nginx 1.14.2
* Amazon Linux 2 (4GB RAM)

**Comment by fgsch** [comment]
This is really not a CRS question and probably more suited for https://github.com/SpiderLabs/ModSecurity or https://security.stackexchange.com/questions/tagged/owasp-crs.
