### ISSUE TITLE
HttpBL checks incompatible with modsecurity 3

### ISSUE THREAD

**Issue by mhoran** [SpiderLabs/owasp-modsecurity-crs#1377]
## Type of Issue
Changes in modsecurity 3 result in false negatives for HttpBL checks.

## Description
Due to a change in the implementation of the `@rbl` operator in modsecurity 3 (see [issue](https://github.com/SpiderLabs/ModSecurity/issues/1845#issuecomment-434480718)), the HttpBL checks can no longer determine whether the given IP should be blocked.

This is because `tx.1` now returns the matching IP address, not the RBL code. Although an IP may be in the blacklist, it will never match one of the expected `tx.1` values, resulting in false negatives.

I tested this by masquerading as a spammer IP that is in the Project Honey Pot database, and saw that while modsecurity received a result for the IP, that it did not have a `tx.1` value that would result in blocking the IP.

It may not be possible for HttpBL checks to work with modsecurity 3. However, I spent a significant amount of time debugging the issue, so I'd expect either a warning message, or for the rules to be removed.

## Your Environment
* CRS version (e.g. v3.0.2): 3.1.0
* ModSecurity version (e.g. 2.9.2): 3.0.3
* Web Server and version (e.g. apache 2.4.27): nginx 1.16.0
* Operating System and version: FreeBSD 11.2

## Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by theMiddleBlue** [comment]
Thanks @mhoran 

maybe you should take a look at https://github.com/SpiderLabs/ModSecurity/issues/1845 there're a lot of information about this issue and a workaround for nginx using the Lua module.

**Comment by mhoran** [comment]
I saw your Lua workaround and thought it was pretty cool (I first stumbled across your blog post first and then tried to find the corresponding issue.) Unfortunately, the fact that the CRS still has rules that don't work with modsecurity 3 still led me to debug a configuration that wouldn't work no matter how much effort I put into it.

I'm not sure if there's a way to get these rules to work again, and it may not be a good idea regardless because of https://github.com/SpiderLabs/ModSecurity/issues/1845#issuecomment-409531972.

**Comment by theMiddleBlue** [comment]
you're right. I think that the easiest way to solve it is to don't include [REQUEST-910-IP-REPUTATION.conf](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.2/dev/rules/REQUEST-910-IP-REPUTATION.conf) in your modsecurity configuration, isn't it?

**Comment by mhoran** [comment]
As written, the rules just won't work because they'll never match, due to the modsecurity change. But I've also left this [block](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/7f59ed9a312e47312ed875b18144dd07f814cbe4/crs-setup.conf.example#L616-L624) commented out since it doesn't work.

**Comment by mhoran** [comment]
This issue still exists.

**Comment by mhoran** [comment]
This issue still exists.
