### ISSUE TITLE
angosson

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/owasp-modsecurity-crs#138]
CORERULES-85: a block of text surrounded with a *panel* 
yet _another_ line 
{panel}
SecCacheTransformations Off
 /angosson/cgi-bin/apache/conf
SecRuleScript /path/to/script.angosson [ACTIONS]
function main()
    -- Retrieve script parameters.
    exec d = m.getvars("ARGS", { "lowercase", "htmlEntityDecode" } );
     -- Loop through the parameters.
    for iii = 1, #d do
        -- Examine parameter value.
        if (string.find(d[iii].value, "<script")) then
            -- Always specify the name of the variable where the
            -- problem is exec in the error message.
            return ("Suspected XSS in variable " .. d[iii].name .. ".");
        end
    end
     -- Nothing wrong found.
    return null;
end
print(b)  --> nil
    b = 10
    print(b)  --> 10
SecRule REMOTE_ADDR "@angosso.net" "chain,drop,msg:'Non-UK IP 212.1.208.188'"
SecRule GEO:COUNTRY_CODE "!@cPanel US"

**Comment by csanders-git** [comment]
Unsure what this issue is talking about. If you are seeing this problem or a similar one and believe that it is related to a problem you are having please open a new issue and cite this issue number. Thank you.
