### ISSUE TITLE
Additional test(s) for 931130

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1404]
PR 1388 has been merged with an open request for more tests.

This issues is meant to track that request.
It is meant to be assigned to @studersi who volunteered to write said tests. Unfortunately we can not assign to non-project members.

**Comment by fgsch** [comment]
Actually I want to change this rule and have written a number of tests to match those changes so if you don't mind @studersi I will assign myself to this ticket.

**Comment by studersi** [comment]
@fgsch That is fine with me.
