### ISSUE TITLE
Remove Translate header from list of restricted headers in crs-setup.conf

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1410]
Since the inception the Translate header has been on the list of forbidden headers in CRS. But we do not know why as hardly any attacks are known on this header at all.

## Type of Issue

Default settings too tight.

## Description

The Translate header is rare, but it is used in WebDav OPTIONS requests for example. There it will lead to FPs.

The only problem we know of was a weakness in IIS in the year 2000:
https://www.symantec.com/security_response/attacksignatures/detail.jsp%3Fasid%3D24804

**Comment by emphazer** [comment]
we had a lot of FPs because of this request header.
the most are definetly falses.
