### ISSUE TITLE
Incorrect escape with dot '.' symbol in rule 943120

### ISSUE THREAD

**Issue by XeroChen** [SpiderLabs/owasp-modsecurity-crs#1413]
## Type of Issue

bug fix
## Description

```
SecRule ARGS_NAMES "@rx ^(?:jsessionid|aspsessionid|asp.net_sessionid|phpsession|phpsessid|weblogicsession|session_id|session-id|cfid|cftoken|cfsid|jservsession|jwsession)$" \
    "id:943120,\
    phase:2,\
    block,...
```
asp.net_sessionid  
here should be  
asp\.net_sessionid  

according to Rule id **943110**, which is

```
SecRule ARGS_NAMES "@rx ^(?:jsessionid|aspsessionid|asp\.net_sessionid|phpsession|phpsessid|weblogicsession|session_id|session-id|cfid|cftoken|cfsid|jservsession|jwsession)$" \
    "id:943110,\
    phase:2,\
    block,\
    capture,...

```
## Your Environment

* CRS version : 3.1.0
* ModSecurity version : N/A
* Web Server and version (e.g. apache 2.4.27):  N/A
* Operating System and version:  N/A

## Confirmation

[v ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by lifeforms** [comment]
Well spotted, thank you! 

The cookie is named `ASP.NET_SessionId`. So the `.` character should be escaped in the regexp.

I've merged your PR and it will be part of the 3.2 release.
