### ISSUE TITLE
unable to log x-forwarded-for value when a given rule is fired

### ISSUE THREAD

**Issue by smartITNinja** [SpiderLabs/owasp-modsecurity-crs#1415]
## Type of Issue

I'm not able to log X-Forwarded-For value when a SecRule is fired.

I've verified that Owasp manages REQUEST_HEADERS_NAMES "^x-forwarded-for" as expected, and Apache web server manages it OK too.

I want to log x-forwarded-for value in the msg section of the rule, like using  %{REMOTE_ADDR} for non-proxied IPs. But without luck so far. Is it possible to achieve this goal?

## Description

I'd like to insert the real X-Forwarded-For value in place of %{X-Forwarded-For} below.
Is it possible? Which would be the expected syntax? 

My current rule:

SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|!REQUEST_COOKIES:/_pk_ref/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "(?i:(?:select \* from|select\*from|load_file|sleep\())" "phase:2,capture,t:none,t:urlDecodeUni,block,deny,status:510,msg:'IP: %{REMOTE_ADDR} %{X-Forwarded-For} SQL injection and other data/structure manipulation attempts',id:'9900002',tag:'WEB_ATTACK/SQL_INJECTION',logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',severity:'2',setvar:'tx.msg=%{rule.id}-%{rule.msg}',setvar:tx.sql_injection_score=+1,setvar:tx.anomaly_score=+%{tx.critical_anomaly_score},setvar:'tx.%{tx.msg}-WEB_ATTACK/SQLI-%{matched_var_name}=%{tx.0}'"

## Your Environment
modsecurity-2.9.1
httpd 2.2
Linux RedHat 6.5

## Confirmation

[ *] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by csanders-git** [comment]
you'll need to use REQUEST_HEADERS:X-Forwarded-For

The REQUEST_HEADERS collection contains all the headers, some of the elements you are seeing are other collections, for more information please see https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#REQUEST_HEADERS

**Comment by smartITNinja** [comment]
Yes, I saw the reference guide, but it's not detailed in any place how to obtain the "REQUEST_HEADERS:X-Forwarded-For" value.

Is it possible to obtain it? which is the proper syntax for that?

**Comment by csanders-git** [comment]
ahh -- good question, when used in the macro expansion format it would be a dot so


%{REQUEST_HEADERS.X-Forwarded-For} should be what you need. let me know if that helps - weird design decision earlier on I think due to Apache's config file parser.

**Comment by smartITNinja** [comment]
Excellent, it worked OK

Thanks a bunch!

**Comment by scaarup** [comment]
So how can we accomplish this without modifying every secrule in crs?
