### ISSUE TITLE
Exclusion rules doesn't work with libmodsecurity (v3) due to ctl:ruleRemoveTargetByTag

### ISSUE THREAD

**Issue by theMiddleBlue** [SpiderLabs/owasp-modsecurity-crs#1419]
The following exclusion files contain many rules that don't work on libmodsecurity (v3) due to `ctl:ruleRemoveTargetByTag`

https://github.com/SpiderLabs/owasp-modsecurity-crs/search?q=ruleRemoveTargetByTag&unscoped_q=ruleRemoveTargetByTag

**Rules files**:
- rules/REQUEST-903.9001-DRUPAL-EXCLUSION-RULES.conf
- rules/REQUEST-903.9002-WORDPRESS-EXCLUSION-RULES.conf
- rules/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf
- rules/REQUEST-903.9004-DOKUWIKI-EXCLUSION-RULES.conf

**Comment by theMiddleBlue** [comment]
@airween has just done his magic things about this problem. A PR will be available soon. Please refer to https://github.com/SpiderLabs/ModSecurity/issues/2099

**Comment by airween** [comment]
PR sent:
https://github.com/SpiderLabs/ModSecurity/pull/2102
