### ISSUE TITLE
Audit log not recording

### ISSUE THREAD

**Issue by Ezizeay** [SpiderLabs/owasp-modsecurity-crs#1423]
Dear all

 Following is from tail modsec_debug.log.

![image](https://user-images.githubusercontent.com/49372377/58179065-b20ba100-7ca7-11e9-8abf-58498a9286e7.png)

1) What should I do to make Audit log to be configured?
2) What to do according to the log above? what does the log say anyway?

SecAuditLog looks OK.
![image](https://user-images.githubusercontent.com/49372377/58179178-f9922d00-7ca7-11e9-8b32-306b31b45754.png)

Environment
CentOS 7.5.1804 (Core)
ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/); OWASP_CRS/3.0.2.
Apache/2.4.29 (CentOS)

**Comment by dune73** [comment]
The rule you quote is not from the CRS. So I can not tell if it should be logging to the audit log. Generally, CRS rules should log to the audit log. Common pitfall is bad write permissions on the logfile and subsequently on the audit log. The audit log itself is explained in the online reference for ModSec, the ModSecurity Handbook and the tutorials at https://netnea.com. Closing this.

**Comment by csanders-git** [comment]
Also if you're on CentOS make sure that you try turning SELinux off. @Ezizeay

**Comment by Ezizeay** [comment]
The question is that 
How to configure Audit Log to run for a particular request?

**Comment by dune73** [comment]
Make a rule that triggers on the request, set it to pass and to "auditlog" in the action list.

**Comment by dune73** [comment]
Make a rule that triggers on the request, set it to pass and to "auditlog" in the action list.
