### ISSUE TITLE
Rule 941120: bad usage of "t:urlDecodeUni" ?

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/owasp-modsecurity-crs#1426]
Hi,

## Type of Issue

I suspect bad usage of "t:urlDecodeUni".

## Description

I think there are a bug with the rule 941120:

```
SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|REQUEST_HEADERS:User-Agent|REQUEST_HEADERS:Referer|ARGS_NAMES|ARGS|XML:/* "@rx (?i)[\s\"'`;\/0-9=\x0B\x09\x0C\x3B\x2C\x28\x3B]+on[a-zA-Z]+[\s\x0B\x09\x0C\x3B\x2C\x28\x3B]*?=" \
    "id:941120,\
    phase:2,\
    block,\
    capture,\
    t:none,t:utf8toUnicode,t:urlDecodeUni,t:htmlEntityDecode,t:jsDecode,t:cssDecode,t:removeNulls,\
    msg:'XSS Filter - Category 2: Event Handler Vector',\
    logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\
    tag:'application-multi',\
    tag:'language-multi',\
    tag:'platform-multi',\
    tag:'attack-xss',\
    tag:'OWASP_CRS/WEB_ATTACK/XSS',\
    tag:'WASCTC/WASC-8',\
    tag:'WASCTC/WASC-22',\
    tag:'OWASP_TOP_10/A3',\
    tag:'OWASP_AppSensor/IE1',\
    tag:'CAPEC-242',\
    ctl:auditLogParts=+E,\
    ver:'OWASP_CRS/3.1.0',\
    severity:'CRITICAL',\
    setvar:'tx.msg=%{rule.msg}',\
    setvar:'tx.xss_score=+%{tx.critical_anomaly_score}',\
    setvar:'tx.anomaly_score_pl1=+%{tx.critical_anomaly_score}',\
    setvar:'tx.%{rule.id}-OWASP_CRS/WEB_ATTACK/XSS-%{MATCHED_VAR_NAME}=%{tx.0}'"
```

The initial value is:

```
   "%C3%A9%2B"
```

Is url decoded and becomes:

```
   "\xc3\xa9+"
```

or in UTF-8

```
   "é+"
```

The rule 941120 chain these two rules: "t:utf8toUnicode,t:urlDecodeUni",
"t:utf8toUnicode" does this transform:

```
   "%u00e9+"
```

Reading the code of the "t:utf8toUnicode" transformation function
I understand that the produced output is "homemade" encoding and
not "Microsoft-specific %u encoding", so we have NOT url-encoded
form as input of the next transform function "t:urlDecodeUni". So
the output of "t:urlDecodeUni" doesn't have sense because the input
doesn't have expected encoding. "t:urlDecodeUni":

```
   "\xe9 "
```

or in ISO8859-1 (é is the same code number in iso and unicode)

```
   "é "
```

Unfortunately the "+" becomes " " (space). So, the rule "941120" match many false positive.

## Your Environment

* CRS version v3.1.0:
* ModSecurity version 3.0.3:

## Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
Thank you for the report and this exemplary writeup @tech-ozon-io.

The problem behind this is probably bigger than we would with for. In fact there are certain decodings done on the Apache / NGINX level and they are not the same for both platforms and all ModSec versions. And CRS is not making a very good job by lacking a stringend policy when to use which transformation. We have been planning to write such a policy and then put it into practice rule by rule, but nobody has tackled it yet.

With that being said, do you have the knowledge to make assessments like this quickly, or is the encoding question equally challenging to you as it is to most project members?

**Comment by ghost** [comment]
Hi,

Thank for the answer.

I do not use Nginx nor Apache. I use my own implementation. I'm confortable with encodings. We will try some transformations to remove this false positive.

After analysing ModSecurity source code, I saw that regex doesn't process utf8, so it will be a good idea to convert utf8 to many one-byte encoding. The file "unicode.mapping" does this job, but I will protect multi language web site, and I can't map all entry to only one code.

IMHO, UTF8 characters higher than 255 doesn't represent a threat. The only one who are dangerous are the protocol special characters like '"%()<>@, and ascii control characters (between 0x00 and 0x1f, also 0x7f and maybe some char between 0x80 and 0xff). So, we will try to create a transformation function which converts any valid UTF8 character (including overlong encoding) to a single neutral character like 'a'. (maybe the file unicode.mapping allow this transformation)

So, the following string:

```
   %C3%A9%2B
```

becomes after decoding url-encoded and decoding utf8:

```
   a+
```

And can be analyzed by rules because, rule are looking for some escape sequence or dangerous words. Dangerous word and valid escape sequences are composed by characters between 0x20 and 0x7e. 

IMHO, we don't care about the semantic. Is the french sentence the following french sentence contains basic SQLi:

```
l'éléphant doit être protégé." OR 1=1; SELECT
```

become before SQLi analysis:

```
l'alaphant doit atre protaga." OR 1=1; SELECT
```

The non-utf8 PCRE regex Tcan be appliyed, and the SQLi will be detected.

The conditions for the transformation are:

 - All the character of the analysed parameter are utf8 encoded
 - No invalid sequence (utf8 sequence attack)
 - Overlong is allowed
 - bad ranges character are allowed (maybe other rule can detect this)

Your opinion ?

Thierry
