### ISSUE TITLE
CRS 2 rule 973344 in mapping table points to inexisting 941000, should be 941100

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1427]
See Title.

**Comment by csanders-git** [comment]
I can make a quick or at some point today or tomorrow, good eye

**Comment by dune73** [comment]
Thank you man. Saw it in a transposed config of a customer. Hence the quick note as we were browsing his config.

**Comment by csanders-git** [comment]
the issue was resolved.
