### ISSUE TITLE
Paranoia test is not working 

### ISSUE THREAD

**Issue by Ezizeay** [SpiderLabs/owasp-modsecurity-crs#1428]
Hello

I tried to adjust Paranoia Level on a per-website basis, by copying rule 900000 from the crs-setup.conf file into the  <VirtualHost> section.
`<VirtualHost IP:80>
include sites/xxx.conf
SecAction \
  "id:10123,\
   phase:1,\
   nolog,\
   pass,\
   t:none,\
   setvar:tx.paranoia_level=4"
</VirtualHost>`
I tested by
curl -vv "http://IP/?q='1 OR 1=1"
curl "http://IP/?q='1 OR 1=1"
curl 'http://IP/?union+select'

 I expected PL indication in audit log, but nothing. There is simply even no log anyway.
1)How to get audit log by the 3 curl tests above?

I can have audit log When I tried this, but no information about PL.
curl IP/index.html?exec=/bin/bash

It seems PL is not functioning at all (even I tried PL in `crs-setup.conf` file yet not affect).

How to get PL working please?
Thanks in advance

**Comment by csanders-git** [comment]
Hey, so there are a couple things that can be going wrong here. We traditionally assume users include the crs-setup, however your approach should work just as well.
Some considerations, ordering is important, this rule (setting the variable) should happen before you include the rules folder. Additionally, you should also make sure that your engine is on and configured, this is part of the modsecurity configuration, a sample is available as part of the package.

For audit logging ensure it is enabled. If none of this is working, we can trouble shoot more with additional details. Good luck

**Comment by csanders-git** [comment]
feel free to reopene this is the issue persists.
