### ISSUE TITLE
Try to retrieve a traditional Chinese document from a web site, 1st get a "forbidden", then take off 8 CORERULEs becomes "invalid URL". From wireshark, the HTTP URL is truncated.

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/owasp-modsecurity-crs#143]
CORERULES-90: Try to retrieve a traditional Chinese document from a web site, initially get a "forbidden", after take off eight CORERULEs(981242,1981243,1981245,960010,970901,981205,960008,981319), it becomes "invalid URL". After review wireshark packet tracing, the HTTP Request Header URL is truncated.

**Comment by dune73** [comment]
I have a hard time understanding the problem. Namely: _Wireshark will show "GET /doc/%E5 HTTP/1.1_
How can CRS be the problem if wireshark shows it does not get the full request?

But whatever, I called the said URL via Chrome against CRS3 and the request passes through in the default installation without any rule being triggered.

![chinese](https://cloud.githubusercontent.com/assets/618722/20453044/a41b29d0-ae19-11e6-845c-30860233f24a.jpeg)

At PL3, we hit the invalid byterange rule (920272), but that was kind of expected. 

Closing this now. Please reopen if the problem persists or if I did not understand it correctly.
