### ISSUE TITLE
941170 - json with base64 string image 

### ISSUE THREAD

**Issue by casper5822** [SpiderLabs/owasp-modsecurity-crs#1431]
I have a rest json post with a base64 string field. It's a simple user avatar.
The field is in a json with this format:  
{
new_image: "stringbase64"
}
For me it's a false negative. 
I tried to add this to my config file to fix my error, but it not works:
SecUpdateTargetById 941170 !ARGS:json.new_image.

How can i fix this problem?

## Type of Issue
Incorrect bypass (false negative)

## Description
This is my audit log:

ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?i)(?:\W|^)(?:javascript:(?:[\s\S]+[=\\\(\[\.<]|[\s\S]*?(?:\bname\b|\\[ux]\d))|data:(?:(?:[a-z]\w+\/\w[\w+-]+\w)?[;,]|[\s\S]*?;[\s\S]*?\b(?:base64|charset=)|[\s\S]*?,[\s\S]*?<[\s\S]*?\w[\s\S]*?>))|@\ (188 characters omitted)' against variable `ARGS:json.new_image' (Value: `data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8lJCIfI (11423 characters omitted)' ) [file "/usr/local/owasp-modsecurity-crs-3.1.0/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "223"] [id "941170"] [rev ""] [msg "NoScript XSS InjectionChecker: Attribute Injection"] [data "Matched Data: data:image/jpeg; found within ARGS:json.new_image: data:image/jpeg;base64

## Your Environment
Operating system: Ubuntu 16.04 lts
Nginx: nginx/1.14.2
modsecurity-crs: 3.1.0

## Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by csanders-git** [comment]
While i don't see that rule ID in the current build of CRS 3.1.0, we can see in the regex that it is likely the word base64 triggering this. 

In general though you should add add an exclusion. There are more examples in the following file (https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.2/dev/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example), however something like (untested):

```
 SecRule ARGS:json.new_image "@streq stringbase64" \
     "id:1001,\
     phase:1,\
     pass,\
     nolog,\
     ctl:ruleRemoveTargetById= 941170;ARGS:json.new_image"
```


I'd read the document, the likely issue is where the rule was placed. As a reminder, SecUpdateTargetById and the like go AFTER the rules as they are processed at runtime and need the rule to be in memory. ctl:xyz and the like go BEFORE the rule as they are processed at request/response time.
