### ISSUE TITLE
utf8=✓ is always included in Ruby RAILS forms, triggers 41_sql_injection_attacks

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/owasp-modsecurity-crs#144]
CORERULES-91: Apparently (I'm no expert in Ruby on RAILS and I've just started with mod_security) it's normal for RAILS to include a hidden element in all it's webforms. The argument then gets passed on as utf8=✓, along with the other ones. 

This is done on purpose, apparently to force some brain-dead browser to submit data in UTF-8.

It however triggers 41_sql_injection_attacks:

[error] ModSecurity: Access denied with code 403 (phase 2). Pattern match "(^[\"'`\\xc2\\xb4\\xe2\\x80\\x99\\xe2\\x80\\x98;]+|[\\"'`\xc2\xb4\xe2\x80\x99\xe2\x80\x98;]+$)" at ARGS:utf8. [file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_crs_41_sql_injection_attacks.conf"] [line "64"] [id "981318"] [rev "2.2.5"] [msg "SQL Injection Attack: Common Injection Testing Detected"] [data "\xe2"] [severity "CRITICAL"] [tag "WEB_ATTACK/SQL_INJECTION"] [tag "WASCTC/WASC-19"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/CIE1"] [tag "PCI/6.5.2"] 

I have no idea (yet) how to add this as an exception, but it seems to me, as this match will basically break any and all Rails apps, it's eligible for a permanent fix (which shouldn't be hard since it's always that single character in that single argument) in the CRS.

**Comment by nicedawg** [comment]
I just ran into this as well, but I was able to correct it by adding this rule to my config after all rules have been loaded:
````SecRuleUpdateTargetById 981318 !ARGS:utf8````

Of course, double-check that rule id... but that tells the SQL Injection rule to not consider the utf8 arg when looking for sql injection attacks. (That should be safe, since a rails app wouldn't be using the value of the utf8 arg in a database query anyways, right?)  And this method doesn't throw the baby out with the bathwater -- you still benefit from sql injection prevention.

**Comment by pgwillia** [comment]
We encountered this issue as well. `SecRuleUpdateTargetById 981318 !ARGS:utf8` worked for us.

**Comment by dune73** [comment]
After a rule renumbering, rule 981318 is now 942110 in Core Rule Set 3.0.

With CRS3, this rule is no longer part of the default installation. It has been shifted to Paranoia Level 2, where we expect people to be able to write casual rule exclusions themselves.

As reported here by various users, the best way to write a rule exclusion for this (in CRS3; if you run PL2 or higher) is:

```
SecRuleUpdateTargetById 942110 !ARGS:utf8
```

Closing this now.
