### ISSUE TITLE
https://coreruleset.org/ dead links

### ISSUE THREAD

**Issue by tlhackque** [SpiderLabs/owasp-modsecurity-crs#1442]
on the https://coreruleset.org/ website, near the bottom, one finds

> For a full list of changes in this release, see the CHANGES document.

Following the [CHANGES](https://raw.githubusercontent.com/SpiderLabs/owasp-modsecurity-crs/v3.1/master/CHANGES) link results in a 404

> 404: Not Found

I also noticed that on https://coreruleset.org/20181114/crs-project-news-november-2018/, there is a reference to https://www.approach.be/en/modsecurity.htm, which displays as plain text (not a hyperlink) - and also returns a 404 error.

**Comment by fgsch** [comment]
Thanks for the report.

The first link should be https://raw.githubusercontent.com/SpiderLabs/owasp-modsecurity-crs/v3.1/dev/CHANGES. For the second the trailing l is missing. 
Correct link is https://www.approach.be/en/modsecurity.html.

They will be corrected.

**Comment by dune73** [comment]
Thank you for reporting @tlhackque - and for the suggestions @fgsch. Fixed.
