### ISSUE TITLE
FalsePositive with SQL HAVING clause, for rule 942230

### ISSUE THREAD

**Issue by j0k2r** [SpiderLabs/owasp-modsecurity-crs#1448]
Hi,

Im doing some tests with the OWASP CRS ver.3.1.0, specifically with the rule 942230.

The SQLi HAVING regex `(?:having\s*?[^\s]+\s*?[^\w\s])` can cause a lots of false positives:
- https://regex101.com/r/BiFuQv/2

Related discussion: #409

As discussed in #409, the HAVING pattern was moved to PL3, since it's very complicated, if not impossible to match all cases with no false positive.

Let me know if you find a better HAVING pattern or if you have a better detection idea.

**Comment by csanders-git** [comment]
on P2 perhaps we can add a rule that requires GROUP BY to be part of the query -- as far as i remember HAVING must be preceded by GROUP BY
