### ISSUE TITLE
List of complete set of unique rule id

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/owasp-modsecurity-crs#145]
CORERULES-92:  Do we have a complete list of unique id. 
i search for any such list but could not find the URL for that.
this list can not only help in identify attack in more better way, but also will help in pinpointing the attack.
e.g. consider a log line :

[DATE] [error] [client <IP_address>] ModSecurity: Warning. Pattern match "\\\\balert\\\\b\\\\W*?\\\\(" at ARGS:first_name. [file "/etc/httpd/modsecurity-crs/base_rules/modsecurity_crs_41_xss_attacks.conf"] [line "148"] [id "958052"] [rev "2.2.5"] [msg "Cross-site Scripting (XSS) Attack"] [data "alert("] [severity "CRITICAL"] [tag "WEB_ATTACK/XSS"] [tag "WASCTC/WASC-8"] [tag "WASCTC/WASC-22"] [tag "OWASP_TOP_10/A2"] [tag "OWASP_AppSensor/IE1"] [tag "PCI/6.5.1"] [hostname "<ip_address>"] [uri "/html/tags/html_form_tag_action.cfm"] [unique_id "ULTWV38AAAEAABdIFBMAAAAD"]

the log line suggest XSS attack and i have to go to the .conf file to get more info.
generally, if such attack happen, an administrator has to go through all the .conf file to understand it better.

if we have a list of unique id , (in this case 958052 ) we can get more insight, with this number only.

**Comment by csanders-git** [comment]
IDs have been updated for CRSv3 to reflect more readily the file and paranoia level that they have. While there isn't a unique list, one could be very quickly made using grep. The issue has been stagnant for long enough that if there is beyond what has been done a new issue should be opened. We are still open to the idea of undertaking this action if there is interest.
