### ISSUE TITLE
"Bad robots" rule (id 990012) blocks all Java applets running on Windows XP

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/owasp-modsecurity-crs#146]
CORERULES-93: The "bad robots" rule blocks a user agent string that includes "Windows XP 5". However, each and every Java applet running on Windows XP has a user agent string like this: "User-Agent: Mozilla/4.0 (Windows XP 5.1) Java/1.7.0_13".

So every Java applet running on Windows XP is blocked by this rule. The rule should be fixed to either not block sessions with a user agent string containing "Window XP" or to only block if the user agent string contains exactly "Windows XP 5", i.e. with no period following it.

**Comment by csanders-git** [comment]
This issue is confirmed to not be present in CRS 3.0-RC1 Closed
