### ISSUE TITLE
False positive with "postgres SQL Information Leakage" rule 951240

### ISSUE THREAD

**Issue by duckasylum** [SpiderLabs/owasp-modsecurity-crs#1468]
Rule 951240 seems to trigger for example when I have used a string sequence *PG_* anywhere in text. For example I am trying to edit an email draft in Roundcube email webclient which contains a string "GPG_AGENT" and this will trigger the rule (I changed the PG_ with "pgeeunderscore" and the rule was not triggered).

Log snippet from audit.log

ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?i:PostgreSQL query failed:|pg_query\(\) \[:|pg_exec\(\) \[:|PostgreSQL.*ERROR|Warning.*pg_.*|valid PostgreSQL result|Npgsql\.|PG::[a-zA-Z]*Error|Supplied argument is not a valid PostgreSQL .*? resou (43 characters omitted)' against variable `RESPONSE_BODY' (Value: `<!DOCTYPE html>\x0a<html lang="en">\x0a<head>\x0a<title>Roundcube Webmail :: Compose</title>\x0a<met (39446 characters omitted)' ) [file "/etc/nginx/crs/rules/RESPONSE-951-DATA-LEAKAGES-SQL.conf"] [line "356"] [id "951240"] [rev ""] [msg "postgres SQL Information Leakage"] [data "Matched Data: connection found within TX:sql_error_match: 1"] [severity "2"] [ver "OWASP_CRS/3.1.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-pgsql"] [tag "attack-disclosure"] [tag "OWASP_CRS/LEAKAGE/ERRORS_SQL"] [tag "CWE-209"] [hostname "127.0.0.1"] [uri "/"] [unique_id "156154978641.594817"] [ref "o4703,32476v786,37179"]

* CRS version 3.1.0 (cloned from v3.2/dev on 22.06.2019)
* ModSecurity version 3.0.3 (cloned from v3/master on 22.06.2019)
* NGINX 1.16.0 (built from source)
*  Ubuntu 16.04.6 (Xenial) LTS

**Comment by jbtule** [comment]
Same

> ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?i:PostgreSQL query failed:|pg_query\(\) \[:|pg_exec\(\) \[:|PostgreSQL.*ERROR|Warning.*pg_.*|valid PostgreSQL result|Npgsql\.|PG::[a-zA-Z]*Error|Supplied argument is not a valid PostgreSQL .*? resou (43 characters omitted)' against variable `RESPONSE_BODY

My rando false positive was some url safe base64 data (excerpt `oTIScWqgwDjKvA0UKbB1WV6pg_URyHwagG9u3`) in an hidden input used for cross site request forgery detection.

So I think you should open this issue back up.
