### ISSUE TITLE
Log apache errors to console

### ISSUE THREAD

**Issue by tlaukkan** [SpiderLabs/owasp-modsecurity-crs#1469]
## Description
Please, let ErrorLog go to /proc/self/fd/2 so docker logging solutions will collect the mod security rule alerts without extra log configuration.

httpd-logging-before-modsec.conf 
ErrorLog                /proc/self/fd/2

**Comment by fzipi** [comment]
@franbuehler Aren't we properly logging in docker now? I guess we can close this one just letting people know which one is the crs docker... and maybe have it documented somewhere :thinking:

**Comment by spartantri** [comment]
Hi @tlaukkan 

Just set a envvar ERRORLOG, that should make what you need.

`ENV ERRORLOG=/proc/self/fd/2`

Maybe the README file needs some improvement, I tested using the `Dockerfile-2.9-apache` file and it works as expected.

**Comment by franbuehler** [comment]
Logging for http and https should work now, yes. Logfiles can be set as spartantri described above.
There is an open issue for documentation: #1464.
