### ISSUE TITLE
942190: False Positive

### ISSUE THREAD

**Issue by osamamaruf** [SpiderLabs/owasp-modsecurity-crs#1470]
## Type of Issue

False Positive
## Description

The regex used in this rule detects user ( as an sql injection attack.

> ModSecurity: Warning. Matched "Operator `Rx' with parameter `(?i:(?:\s*?(?:exec|execute).*?(?:\W)xp_cmdshell)|(?:[\"'`]\s*?!\s*?[\"'`\w])|(?:from\W+information_schema\W)|(?:(?:(?:current_)?user|database|schema|connection_id)\s*?\([^\)]*?)|(?:[\"'`];?\s*?(?:sele (185 characters omitted)' against variable `ARGS:json.something.event' (Value: `Hello user (external), Modify user, Status changes from Any to Rejec (101 characters omitted)' ) [file "/etc/nginx/owasp-modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "156"] [id "942190"] [rev "2"] [msg "Detects MSSQL code execution and information gathering attempts"] [data "Matched Data: user ( found within ARGS:json.something.event: Hello user (external), Modify user, Status changes from Any to Rejec and other statuses"] [severity "2"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "8"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-sqli"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"] [tag "WASCTC/WASC-19"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/CIE1"] [tag "PCI/6.5.2"] [hostname "XXX.XXX.XX.XX"]

## Your Environment

* CRS version (v3.0.0)
* ModSecurity version (3.0.2)
* Web Server and version (Nginx 1.15.9)

## Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by theMiddleBlue** [comment]
Thanks @osamamaruf 

it seems that your application arg `json.something.event` doesn't encode round brackets characters and it's really similar to the SQL syntax `SELECT USER();`:

![image](https://user-images.githubusercontent.com/4454961/61442553-23826b80-a948-11e9-9ac4-9fbba7325006.png)

You should fix this by removing `ARGS:json.something.event` from 942190 with something like:
```perl
SecRule ... "id:123,phase:2,nolog,pass,\
    ctl:ruleRemoveTargetById=942190;ARGS:json.something.event"
```

Closing this now, but feel free to send an update with more information/follow up.
