### ISSUE TITLE
 Monthly Chat Agenda July (2019-07-01)

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1471]
This is the Agenda for the Monthly CRS Chat.

The chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, July 1, at 20:30 CET.

### PRs
* RE2 PRs by @allanrbo
* Other PRs, that are not yet on-hold

### Other items

* Project funds at OWASP HQ
* Swag 
* CRS community summit in Amsterdam
* Reaching out to Mitre because of the CVEs

Feel free to add items as you see fit either above, or below as comments.

If you are not yet on the OWASP Slack, here is your invite: https://join.slack.com/t/owasp/shared_invite/enQtNjExMTc3MTg0MzU4LTViMDg1MmJiMzMwZGUxZjgxZWQ1MTE0NTBlOTBhNjhhZDIzZTZiNmEwOTJlYjdkMzAxMGVhNDkwNDNiNjZiOWQ .
Everybody is welcome to join our community chat.

**Comment by fgsch** [comment]
Completed!
