### ISSUE TITLE
database syntax error not detected 

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/owasp-modsecurity-crs#148]
CORERULES-95: http://www.modsecurity.org/testphp.vulnweb.com/listproducts.php?cat=interesting(idea)

no wanring, no error  but on screen:

Error: FUNCTION acuart.interesting does not exist Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /hj/var/www/listproducts.php on line 74

**Comment by csanders-git** [comment]
In CRS v3rc1 this results in a warning about database leakage.
