### ISSUE TITLE
Installation guide on https://modsecurity.org/crs is not up to date. 

### ISSUE THREAD

**Issue by mum-viadee** [SpiderLabs/owasp-modsecurity-crs#1482]
In the head of the  owasp-modsecurity-crs github page the link to the project page is https://modsecurity.org/crs which contains an installation guide, that is not up to date.

Please update installation instruction on https://modsecurity.org/crs or change link to official OWASP CRS page https://coreruleset.org

**Comment by fzipi** [comment]
@mum-viadee Please refer to #996 .

**Comment by dune73** [comment]
Thank you for reporting @mum-viadee. Unfortunately, both pieces of infos are beyond our reach as we are residing under a Trustwave github account and Trustwave ignores all our requests to fix this / update the links. And there have been many, many requests.

Sorry for the inconvenience.
