### ISSUE TITLE
Application blocked by Azure Application firewall "941-APPLICATION-ATTACK-XSS-941120"

### ISSUE THREAD

**Issue by SS-Raman** [SpiderLabs/owasp-modsecurity-crs#1489]
Hi Team,
We have faced the Issue in your application to blocking the Auth-key in login page "941-APPLICATION-ATTACK-XSS-941120". Kindly share the Rule-ID: 941120 details.

**Comment by spartantri** [comment]
This is the regular expression on that rule in v3.2
```(?i)[\s\"'`;\/0-9=\x0B\x09\x0C\x3B\x2C\x28\x3B]+on[a-zA-Z]+[\s\x0B\x09\x0C\x3B\x2C\x28\x3B]*?=```
You can find the full rule at [XSS rules](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.2/dev/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf)

**Comment by dune73** [comment]
You will need to write a rule exclusion. You can learn how to do that with the tutorials at https://netnea.com/apache-tutorials - or seek support from Azure.

**Comment by SS-Raman** [comment]
Hi Spartantri,

Thanks for your reply, I want to know about the particular Rule-ID: 941120 essential and which category the Rule is blocking your application Auth-key.
