### ISSUE TITLE
Nginx directive rules error in REQUEST-920-PROTOCOL-ENFORCEMENT.conf

### ISSUE THREAD

**Issue by mark4409** [SpiderLabs/owasp-modsecurity-crs#1499]
I have performed a git pull this morning on the 3.2/Dev branch.

Since then, I am receiving an error in Nginx:

`"modsecurity_rules_file" directive Rules error. File: /etc/nginx/modsec/owasp-modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf. Line: 321. Column: 10. Expecting an action, got  ,\ in ...... `

This seems to relate to id:920220

I am using the latest Nginx 17.2 together with the latest releases of modsecurity and the nginx connector.

**Comment by fgsch** [comment]
Can you paste what's in that line for the rules you have?

**Comment by fgsch** [comment]
Also please specify which modsecurity version you are using and the revision of the 3.2/dev branch you are on.

**Comment by mark4409** [comment]
I am on modsecurity v3.0.3-95-gd5b93c10

I followed the procedure:
git checkout v3/master
git submodule init
git submodule update

With the Nginx connector, I'm on version 1.0.0-58-gd7101e1

With the CRS, I'm on v3.1.0-rc1-292-gc5f1656

git branch shows v3.2/dev

Line 321 is the second line here:

```
SecRule REQUEST_URI "@contains %" \
    "id:920220,\
    phase:2,\
    block,\
    .........
```
I can see that there have been changes in this file 4 days ago - looks like a change of the regular expression to RE2

Am I lacking something?

**Comment by fgsch** [comment]
To confirm, you were using CRS v3.1.0-rc1-292-gc5f1656 without problems and when you switched to CRS v3.2/dev, using the same setup you are getting that error?

I can't see anything wrong in that file. I will investigate.

**Comment by mark4409** [comment]
no, this is whats weird. Before I updated with git pull, i did a git branch to make sure I was on the correct one. It showed I was on v3.2/dev. However when I type git descripe --tags, it says CRS v3.1.0-rc1-292-gc5f1656

**Comment by mark4409** [comment]
When I first logged this issue, I noticed after that I was still on modsecurity 3.0.2. I have since recompiled and installed the latest but it hasn't resolved this particular issue.

**Comment by fgsch** [comment]
You are using `git describe` incorrectly.  Please check the manpage.
That aside (and what we need to understand) is:

- Which version/revision of ModSecurity you are running
- Which version/revision of CRS you are running
- Which version/revision of nginx
- What error you are seeing

Can you provide that information after ensuring that your setup matches your expectations?
It's hard to pinpoint what the issue could be if you are unsure of your setup or is not what you expect.

**Comment by mark4409** [comment]
I am by no means an expert in the usage of git, but lets try this from `git log -1`. If it's not correct then I'd very much appreciate a bit of help in finding the exact revision:

**ModSecurity**
`commit d5b93c1013ca9c9a96c75369576b54832e9a2b48 (HEAD -> v3/master, origin/v3/master, origin/HEAD)`

**CRS:** 
`commit c5f165634623a51b1d082a830ca6f70b526470d6 (HEAD -> v3.2/dev, origin/v3.2/dev, origin/HEAD)`

Worth noting that I also updated with git pull around a week ago, and that particular version worked fine so I assume the breaking change has happened between then and now.

**Nginx-connector** 
`commit d7101e13685efd7e7c9f808871b202656a969f4b (HEAD -> master, origin/master, origin/HEAD)`

**Nginx**
nginx version: nginx/1.17.2
built by gcc 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 
built with OpenSSL 1.1.1c  28 May 2019
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-cc-opt='-g -O2 -fdebug-prefix-map=/usr/local/src/nginx/nginx-1.17.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie'

Also with modsecurity-nginx and geoip2 loaded as dynamic modules

The error is as described in the original post after running nginx -t (or restarting the service)

My most recent git pull was this morning for both CRS and Modsecurity so both should be current.

**Comment by fgsch** [comment]
Thanks for all the details. I will try to reproduce the issue and see what I find.

**Comment by mark4409** [comment]
I've just tried a little test and commented that particular rule out. Upon doing so, I get the same error message again but this time at line 354 - which happens to be the next occurence of `"@contains %" \`

**Comment by fgsch** [comment]
Ok, I think I know what's going on.

Could you put a backslash (\) in front of the percentage (%) in those rules?

**Comment by mark4409** [comment]
so like `"@contains \(%)"` ?

**Comment by fgsch** [comment]
Without the ()s, it should be `"@contains \%"`

**Comment by mark4409** [comment]
Nope, same message just with the backslash 

I did try it with the brackets whilst waiting for your reply... and that didn't fail!

**Comment by mark4409** [comment]
does `"@contains %"` really do the same thing as the previous `"@rx \%(?:(?!$|\W)|[0-9a-fA-F]{2}|u[0-9a-fA-F]{4})"` ?

**Comment by fgsch** [comment]
Nop, and is not supposed to. The original rule was wrong.

**Comment by mark4409** [comment]
Well the backslash didn't work I'm afraid. I have disabled modsecurity temporarily until it is fixed.

**Comment by fgsch** [comment]
Unfortunately you are hitting a bug in modsec 3. 
I've opened https://github.com/SpiderLabs/ModSecurity/issues/2145 to track this.

In the meantime we'll see if we can workaround it.
