### ISSUE TITLE
Review recent changes to rule 942370 

### ISSUE THREAD

**Issue by fgsch** [SpiderLabs/owasp-modsecurity-crs#1504]
We recently updated rule 942370 (commit 62e7a8d2d68fe38f2acfe1335839b7caf09aed70 via #1466).

I believe there are a number of issues with this change:

- The resulting pattern doesn't make much sense to me
- We removed part of the pattern from the .data file
- We added (12) unnecessary capture groups

The last 2 points are self explanatory. For the first one, we now have:

```
^[\w\s\"'`-]*(and\s)(?:(between)|(and\s)|(like)|(div)|(xor)|(or))(xor\s)(nand\s)(not\s)(\|\|)(\&\&)\w+\(
```

Which seems incorrect.
This is not to say that the previous pattern was better:

```
^[\w\s\"'`-]+(?<=and\s)(?:(?<=between)|(?<=and\s)|(?<=like)|(?<=div)|(?<=xor)|(?<=or))(?<=xor\s)(?<=nand\s)(?<=not\s)(?<=\|\|)(?<=\&\&)\w+\(
```

I'd rather try to understand the intent here and find a suitable replacement or remove it altogether.

**Comment by dune73** [comment]
Can we close #1477 in favor of this issue?

**Comment by franbuehler** [comment]
I reviewed this Pull Request #1466.

1. Yes, the resulting pattern is wrong!
The result of 
`$ util/regexp-assemble/regexp-assemble.pl util/regexp-assemble/regexp-942370.data`
is:
 ```
(?:[\"'`](?:\s*?(?:(?:\*.+(?:(?:an|i)d|between|like|x?or|div)\W*?[\"'`]|(?:between|like|x?or|and|div)\s[^\d]+[\w-]+.*?)\d|[^\w\s?]+\s*?[^\w\s]+\s*?[\"'`]|[^\w\s]+\s*?[\W\d].*?(?:--|#))|.*?\*\s*?\d)|[()\*<>%+-][\w-]+[^\w\s]+[\"'`][^,]|\^[\"'`])
```
without these capturing groups!
I am sorry, I do not know how I could overlook that! I have no clue. Maybe I concentrated on the regexes in the data file and not on the result of the assembly tool.

2. yes, that is true. The remove parts do not make sense. Therefore I (or @dune73) opened #1477. I would like to bring back the originally intended regular expressions.

3. they are gone now.

Does that make sense to you @fgsch ??

**Comment by fgsch** [comment]
@franbuehler So we basically removed that part but forgot to regenerate it?
IIUC that makes sense. So we need to update the pattern in the rule?

**Comment by franbuehler** [comment]
Yes, only the pattern in the rulefile is wrong. And I did not check that.

Shall I open a PR to fix that? It's my fault!

**Comment by fgsch** [comment]
Nobody's fault, things happen.
Sure, if you have the time please go ahead 👍

**Comment by franbuehler** [comment]
Thank you, that you took a closer look!
Ok, I'll provide a PR soon.

**Comment by dune73** [comment]
PR #1505 fixed this.

**Comment by allanrbo** [comment]
Must have must have had a copy-paste error! The text in the PR description was correct, but the file was not... Sorry about that, @franbuehler !
