### ISSUE TITLE
Rewrite links to blog.modsecurity.org

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#1506]
In several places we refer to http://blog.modsecurity.org/2007/06/optimizing-regu.html but that site has disappeared off the web.

The content has been spidered at https://web.archive.org/web/20180822205124/http://blog.modsecurity.org/2007/06/optimizing-regu.html

We should rewrite it and replace the links.

**Comment by fgsch** [comment]
What do you think about moving the article to https://coreruleset.org/ instead of using internet archive ?

**Comment by lifeforms** [comment]
Yes @fgsch I think we should do that, but since we don't know the license of the original content we should rewrite it instead of copying.

**Comment by dune73** [comment]
I'm writing to Ofer, the original author.

**Comment by dune73** [comment]
Ofer agrees to us re-publishing the blog post on https://coreruleset.org.

**Comment by lifeforms** [comment]
Fixed in #1523.
