### ISSUE TITLE
Rule 941100 false positive with Drupal

### ISSUE THREAD

**Issue by azurit** [SpiderLabs/owasp-modsecurity-crs#1510]
Rule number 941100 is triggering 2 times for Drupal version 6.26 with crs_exclusions_drupal enabled. Example of URI (POST request):
/?q=node/205/edit

What other info do you need?

## Your Environment
* CRS version (e.g. v3.0.2): 3.1.1
* ModSecurity version (e.g. 2.9.2): 2.9.3
* Web Server and version (e.g. apache 2.4.27): Apache 2.4.25
* Operating System and version: Debian Stretch

## Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
Sorry for the inconvenience and thank you for letting us know.

Would you please send us the rule alerts (from the error.log or the audit-log)? That would help.

Also: Can you write a rule exclusion yourself or do you need help?

**Comment by azurit** [comment]
Can i send it privately? There's probably lot's of sensitive data. It's in JSON format.

I never done it before, maybe i can try. Any initial hints?

**Comment by dune73** [comment]
Sending via private mail is welcome: folini@netnea.com

Rule Exclusions: Maybe take a look at my tutorials at https://netnea.com/apache-tutorials.

**Comment by azurit** [comment]
E-mail sent.

Well, i think that whole regexp is wrong. The one doing problems is in file REQUEST-903.9001-DRUPAL-EXCLUSION-RULES.conf, line 330:
`SecRule REQUEST_FILENAME "@rx /node/[0-9]+/edit$" \`

I think that '/' characters should be escaped - this should fix it and also workaround my problem (not sure if the '^' at the beggining is needed?):

`SecRule REQUEST_FILENAME "@rx ^\/(?:s|\?q=){0,1}node\/[0-9]+\/edit$" \`

**Comment by dune73** [comment]
Thank you for your message.

I see 4 false positives against 941100 on uri "/" in the parameters `body` and `field_teaser[0][value]`.

The rule exclusion you point to does not apply, because your requests go against /.

As for the regex, we do not need to escape the slash. But we need to understand why your requests are sent to / and if this is the new normal with Drupal.

**Comment by azurit** [comment]
Well, as it's Drupal version 6.26, released in 2012, it's probably the old way. Would be fine, if you can support it.

**Comment by dune73** [comment]
Our rules exclusions are based on Drupal 8. Drupal 6 has long lost support. I doubt we are going to add support for it in CRS.

Please understand that excluding a strong and important rule like 941100 on / is very dangerous.

**Comment by azurit** [comment]
Ok, thank you for your time.

**Comment by dune73** [comment]
You are welcome.
