### ISSUE TITLE
Rules matched at REQUEST_BODY instead of ARGS

### ISSUE THREAD

**Issue by azurit** [SpiderLabs/owasp-modsecurity-crs#1518]
## Type of Issue

Bug

## Description

Rules 930100 and 930110 are getting matched at whole REQUEST_BODY instead of ARGS:redirect . I sent the full log to folini@netnea.com.

## Your Environment

* CRS version (e.g. v3.0.2): 3.1.1
* ModSecurity version (e.g. 2.9.2): 2.9.3
* Web Server and version (e.g. apache 2.4.27): 2.4.25
* Operating System and version: Debian Stretch

## Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by azurit** [comment]
We are still having problems with this (maybe also with other rules).

**Comment by theMiddleBlue** [comment]
Hi @azurit 

could you please provide the full blocked request log here too? Anyway, If your request is blocked by both rules because of something inside ARGS:redirect, a possible solution could be to remove ARGS:redirect evaluation from  930100 and 930110.

**Comment by azurit** [comment]
I don't have that log anymore (but it's quite common issue, maybe i will get another one soon).

The problem which i see here is when i write a rule to exclude, for example, ARGS:redirect, the modsecurity is, sometimes (NOT always of course), matching the SAME problem second time for, this time for whole REQUEST_BODY. TO bypass this, i need to exclude whole REQUEST_BODY, which means that i'm excluding also other arguments (which i don't want, i may need to keep other arguments secured).

I don't know how to explain this problem better. It's like, in regexp, using .* instead of .*? ('smallest' match).

**Comment by theMiddleBlue** [comment]
Oh okay, I got it now. It should be solved replacing REQUEST_BODY with ARGS so you can write your exclusion rule. Is it?

**Comment by azurit** [comment]
No, as i said, i alredy have exclusion rule for ARGS but modsecurity is triggering the same thing again but this time on REQUEST_BODY (so i'm forced to rewrite the rule to exclude whole REQUEST_BODY).

**Comment by theMiddleBlue** [comment]
Yes, I mean we should replace REQUEST_BODY in both rules (930100 and 930110) with ARGS.

**Comment by fgsch** [comment]
@dune73 do you have the logs @azurit sent? Is there any information that can be shared from them?

**Comment by dune73** [comment]
I'm sure I do. I remember receiving it. But I can't seem to find it anymore.

Who was the sender @azurit? The email address, I mean, so I have a keyword to search my archive.

**Comment by azurit** [comment]
@dune73 I sent you another e-mail with list of address (don't remember which one i used). Thank you.

**Comment by dune73** [comment]
Dug out the message / attachment in question successfully. Forwarded to @fgsch and @azurit.

**Comment by fgsch** [comment]
@dune73 thanks. I had a quick look and I think what @theMiddleBlue wrote makes sense. We should replace REQUEST_BODY with ARGS so a rule to exclude specific arguments can be written.

**Comment by fgsch** [comment]
@theMiddleBlue Do you want to open a PR or should I take a look?

**Comment by theMiddleBlue** [comment]
Sure! Thanks. I'll open a PR

**Comment by theMiddleBlue** [comment]
should be fixed by #1659

**Comment by Taiki-San** [comment]
Hey! Sorry for arriving late to the party but this change introduced many false positives to the rule.
I'm seeing many of our users with patterns similar to `http://url?query=../img/social_icons.png`.
Although that could be construed as a LFI vulnerability, this case is a false positive.

We had already forked the rule to run on ARGS at a lower confidence level but with this change, the main rule become dangerous.

**Comment by azurit** [comment]
@Taiki-San Hi, how this change could introduced new FPs? Before, it was matching the whole REQUEST_BODY (including ARGS) and now it is matching only ARGS.

**Comment by Taiki-San** [comment]
@azurit `REQUEST_BODY` is a subset of `ARGS`, at least according to the [reference](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-%28v2.x%29).
`REQUEST_BODY` only contains the POST payload, while `ARGS` also include the query string. Our false positives are on parameters coming from query strings.

**Comment by azurit** [comment]
Ok, i see. In this case, it should be set to ARGS_POST instead of ARGS to keep backward compatibility.
