### ISSUE TITLE
Rule triggering : Execution error - PCRE limits exceeded (-8)

### ISSUE THREAD

**Issue by Nyloth** [SpiderLabs/owasp-modsecurity-crs#1535]
## Type of Issue
Execution error - PCRE limits exceeded (-8)

## Description
We have the rule 981243 in the ruleset which triggers a PCRE error everytime on the same page. Here is an example of a trigger.

[Fri Aug 30 09:29:31.360865 2019] [:error] [pid 7841:tid 140301347780352] [client X.X.X.X] ModSecurity: Rule 7f9a94002918 [id "981243"][file "/etc/modsecurity/activated_rules/modsecurity_crs_41_sql_injection_attacks.conf"][line "245"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "XXXXXXXXXXX"] [uri "XXXXXXXXXXXX"] [unique_id "XWjQWwrATAEAAB6h5BMAAACT"]

We have made some researches over the internet, and found an issue on this github talking about this : https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/656

We have changed the PCRE limits as suggested to 500K and then to 10'000K. Unfortunatly we do still get the error.

What can we do ?

## Your Environment
* CRS version : 2.2.9-1+deb8u1
* ModSecurity version : 2.8.0-3
* Web Server and version : Apache 2.4.10
* Operating System and version: Debian 8 Jessie

## Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
Sorry for the inconvenience @Nyloth. However, we are no longer supporting 2.2.9. I suggest you upgrade to 3.1 which has vastly better detection rates and far less false positives. 3.1 is supported by your ModSec version.

Upgrading is relatively simple and I think there is even a backported CRS package.
