### ISSUE TITLE
modsecurity_crs_35_bad_robots.conf  - Execution error - PCRE limits exceeded

### ISSUE THREAD

**Issue by remotehelp** [SpiderLabs/owasp-modsecurity-crs#155]
[Mon Nov 04 15:49:43 2013] [error] [client 37.115.184.70] ModSecurity: Rule 7f18
532e53f8 [id "-"][file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_crs
_35_bad_robots.conf"][line "28"] - Execution error - PCRE limits exceeded (-8):
(null). [hostname "example.com"] [uri "/index.php"] [unique_id "UneJ112qgHI
AAAguT-EAAAAA"]

== OWASP ModSecurity Core Rule Set (CRS) CHANGES ==

== Report Bugs/Issues to GitHub Issues Tracker ==
- https://github.com/SpiderLabs/owasp-modsecurity-crs/issues

== Version 2.2.8 - 06/30/2013 ==

**Comment by 735tesla** [comment]
Exact same issue using nginx, a bunch of reports that like this:
```
--2d51bd24-H--
Message: Rule 7feff7710a68 [id "950901"][file "/etc/nginx/conf/modsecurity.conf"][line "1683"] - Execution error - PCRE limits exceeded (-8): (null).
Message: Rule 7feff7710a68 [id "950901"][file "/etc/nginx/conf/modsecurity.conf"][line "1683"] - Execution error - PCRE limits exceeded (-8): (null).
Message: Rule 7feff7710a68 [id "950901"][file "/etc/nginx/conf/modsecurity.conf"][line "1683"] - Execution error - PCRE limits exceeded (-8): (null).
Message: Rule 7feff7710a68 [id "950901"][file "/etc/nginx/conf/modsecurity.conf"][line "1683"] - Execution error - PCRE limits exceeded (-8): (null).
Message: Rule 7feff7710a68 [id "950901"][file "/etc/nginx/conf/modsecurity.conf"][line "1683"] - Execution error - PCRE limits exceeded (-8): (null).
Apache-Handler: IIS
Stopwatch: 1421699005000687 913586 (- - -)
Stopwatch2: 1421699005000687 913586; combined=12865, p1=241, p2=12375, p3=3, p4=160, p5=85, sr=23, sw=1, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for nginx (STABLE)/2.9.0-RC2 (http://www.modsecurity.org/); OWASP_CRS/2.2.5.
Server: ModSecurity Standalone
Engine-Mode: "DETECTION_ONLY"

--2d51bd24-Z--
```

**Comment by 735tesla** [comment]
The error appears to be in the last line of:
```
# -=[ SQL Tautologies ]=-
#
SecRule REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_FILENAME|ARGS_NAMES|ARGS|XML:/* "(?i:([\s'\"`´’‘\(\)]*)?([\d\w]+)([\s'\"`´’‘\(\)]*)?(?:=|<=>|r?like|sounds\s+like|regexp)([\s'\"`´’‘\(\)]*)?\2|([\s'\"`´’‘\(\)]*)?([\d\w]+)([\s'\"`´’‘\(\)]*)?(?:!=|<=|>=|<>|<|>|\^|is\s+not|not\s+like|not\s+regexp)([\s'\"`´’‘\(\)]*)?(?!\6)([\d\w]+))" \
        "phase:2,rev:'2.2.5',capture,multiMatch,t:none,t:urlDecodeUni,t:replaceComments,ctl:auditLogParts=+E,block,msg:'SQL Injection Attack',id:'950901',logdata:'%{TX.0}',severity:'2',tag:'WEB_ATTACK/SQL_INJECTION',tag:'WASCTC/WASC-19',tag:'OWASP_TOP_10/A1',tag:'OWASP_AppSensor/CIE1',tag:'PCI/6.5.2',setvar:'tx.msg=%{rule.msg}',setvar:tx.sql_injection_score=+%{tx.critical_anomaly_score},setvar:tx.anomaly_score=+%{tx.critical_anomaly_score},setvar:tx.%{rule.id}-WEB_ATTACK/SQL_INJECTION-%{matched_var_name}=%{tx.0}"
```

**Comment by 735tesla** [comment]
#### What completely fixed the issue for me was just cloning the latest version of modsecurity crs from this repository instead of just using the one from my package manager

(which I honestly never should have used in the first place no matter how lazy I was feeling)

**Comment by Spiritux** [comment]
@735tesla, when I update the base rules to the last version (downloaded from owasp-git), the **apache2 failed to start**. The error points to new line formats, for example the new line of -=[ SQL Tautologies ]=-, which change from: 
```
SecRule REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_FILENAME|ARGS_NAMES|ARGS|XML:/* "(?i:([\s'\"`´’‘\(\)]*)?([\d\w]+)([\s'\"`´’‘\(\)]*)?(?:=|<=>|r?like|sounds\s+like|regexp)([\s'\"`´’‘\(\)]*)?\2|([\s'\"`´’‘\(\)]*)?([\d\w]+)([\s'\"`´’‘\(\)]*)?(?:!=|<=|>=|<>|<|>|\^|is\s+not|not\s+like|not\s+regexp)([\s'\"`´’‘\(\)]*)?(?!\6)([\d\w]+))" \
        "phase:2,rev:'2.2.5',capture,multiMatch,t:none,t:urlDecodeUni,t:replaceComments,ctl:auditLogParts=+E,block,msg:'SQL Injection Attack',id:'950901',logdata:'%{TX.0}',severity:'2',tag:'WEB_ATTACK/SQL_INJECTION',tag:'WASCTC/WASC-19',tag:'OWASP_TOP_10/A1',tag:'OWASP_AppSensor/CIE1',tag:'PCI/6.5.2',setvar:'tx.msg=%{rule.msg}',setvar:tx.sql_injection_score=+%{tx.critical_anomaly_score},setvar:tx.anomaly_score=+%{tx.critical_anomaly_score},setvar:tx.%{rule.id}-WEB_ATTACK/SQL_INJECTION-%{matched_var_name}=%{tx.0}"
```
to:
```
SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|!REQUEST_COOKIES:/_pk_ref/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "(?i:([\s'\"`´’‘\(\)]*?)\b([\d\w]++)([\s'\"`´’‘\(\)]*?)(?:(?:=|<=>|r?like|sounds\s+like|regexp)([\s'\"`´’‘\(\)]*?)\2\b|(?:!=|<=|>=|<>|<|>|\^|is\s+not|not\s+like|not\s+regexp)([\s'\"`´’‘\(\)]*?)(?!\2)([\d\w]+)\b))" \
          "phase:2,rev:'2',ver:'OWASP_CRS/2.2.9',maturity:'9',accuracy:'8',capture,multiMatch,t:none,t:urlDecodeUni,t:replaceComments,ctl:auditLogParts=+E,block,msg:'SQL Injection Attack: SQL Tautology Detected.',id:'950901',logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',severity:'2',tag:'OWASP_CRS/WEB_ATTACK/SQL_INJECTION',tag:'WASCTC/WASC-19',tag:'OWASP_TOP_10/A1',tag:'OWASP_AppSensor/CIE1',tag:'PCI/6.5.2',setvar:'tx.msg=%{rule.msg}',setvar:tx.sql_injection_score=+%{tx.critical_anomaly_score},setvar:tx.anomaly_score=+%{tx.critical_anomaly_score},setvar:tx.%{rule.id}-OWASP_CRS/WEB_ATTACK/SQL_INJECTION-%{matched_var_name}=%{tx.0}"
```
Of course, a lot of other rules has been updated in same way.. I mean, including !REQUEST_COOKIES:/__utm/ and so on..

Could you please tell me if you had this problem when you updated your rules? Maybe is mandatory to update modsecurity to the last version? 
I am running the last stable version of modsecurity and for apache as well, via apt-get in Debian.

Thanks

**Comment by dune73** [comment]
The PCRE match limits are here to prevent Regular Expression Denial of Service attacks. That is the CPU getting eaten up completely calculating evil regexes...

Now the defaults are very low, which leads to false positives in the sense that rule execution on regular requests run into the PCRE match limit failure as reported above several times.

I have successfully configured productive servers with PCRE match limits of 500000 or even 1000000. This makes most, if not all PCRE match limit failures go away and is still not a value, that would allow an easy DDoS. However, let' make this clear: You need to monitor your server and then - in case of an attack - you may need to lower the match limit to save CPU power.

An alternative is to improve the regular expressions to make them less prone to this sort of problem. This is an ongoing process and @csanders-git has made some progress with this.

For now, I am closing this issue as a more sane PCRE match limit makes the problem go away. Please reopen, if you still encounter this problem with benign requests and a PCRE match limit in the range of several hundred thousand.
