### ISSUE TITLE
Add REQBODY_PROCESSOR_ERROR checks

### ISSUE THREAD

**Issue by spartantri** [SpiderLabs/owasp-modsecurity-crs#1550]
## Type of Issue
Add verification of body processor errors

## Description
This may lead to both false positives and false negatives, requires testing

## Your Environment

* CRS version (e.g. v3.0.2): 3.3
* ModSecurity version (e.g. 2.9.2): *
* Web Server and version (e.g. apache 2.4.27): *
* Operating System and version: *

## Confirmation

[ X ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by na1ex** [comment]
Rule 920130 has been removed in crs-3.2.0.
My opinion : a replacement is required.
Depending on parser involved, parsing error leads to different situations : 
   * xml parser goes 500 
   * json parser will let things go ( with REQBODY_ERROR set to 1 ) 
   * urlencoded parser is very permissive (e.g. xml or json bodies are accepted.)
   * multipart parser : not checked (multipart is 'special'!)
As said, more testing is required.
