### ISSUE TITLE
CRS 3.1.0: How to customize apache error log entries

### ISSUE THREAD

**Issue by interN3rd** [SpiderLabs/owasp-modsecurity-crs#1553]
Hey guys,

so far I'm getting along well with **ModSecurity (version 2.9.3)** and kind of learning it. But there is one special issue that I can't handle myself (despite having read the ModSecurity Handbook by Christian Folini and a couple of tutorials):

I want to build a website and secure it with ModSecurity and the OWASP CRS. I have installad an **Apache Webserver** (version 2.4.41 (Debian) for local testing and when I enter for example "`<script>`" into an input field, the CRS blocks the request. The Apache error log however is then full of information that I don't actually need. Is there any way to globally configure the apache error log entries? For a better overview I don't want to log several tags like "[tag "application-multi"]" or "[tag "platform-multi"]" and so on.

I have found out that I can adjust every single CRS rule on it's own. So I can customize the logging for CRS id 941100 but I really don't want to adjust every. single. rule. on it's own :D So how can I adjust the apache error log messages (I know about the ErrorLogFormat), especially the CRS log messages?

Thank you for any advice :)

**Comment by dune73** [comment]
Thank you for writing in and glad you find our stuff useful. Also thank you for reading my boring book.

Unfortunately, the so called alert message is hard-coded into ModSecurity. There is no way to to configure it. If you look in my tutorial on netnea.com, where I configure the ErrorLogFormat, you see, that the ModSec part is just a message block, that you can not re-configure with Apache and there are no ModSec directives that work on it.

My personal approach is to ignore the problem. You could post-process the logs (-> sed is your friend) or pipe into an ELK or similar solution that extracts the information you are interested in.

Closing this for now. Feel free to re-open if you need more info.
