### ISSUE TITLE
Unable to remove rule 960012 with SecRuleRemoveById

### ISSUE THREAD

**Issue by level420** [SpiderLabs/owasp-modsecurity-crs#156]
I'm trying create a setup for a subversion dav over http server. I've successfully managed to enable the needed content-type 'application/vnd.svn*' and the request methods like PROPFIND etc.

While trying to commit to the repositories which are served via the above setup, I'm getting a rule violation against rule id "960012" in modsecurity_crs_20_protocol_violations.conf, line 312, which is caused by the javahl svn client of eclipse.

I've tried to disable the rule via 

```
<LocationMatch /* >
   <IfModule mod_security2.c>
       SecRuleRemoveById 960012
  </IfModule>
</LocationMatch>
```

with no success.

I've seen in line 312 of modsecurity_crs_20_protocol_violations.conf that rule id 960012 has a chained rule which has no rule id.

Would I need to also disable the chained rule, which of course, I can't do because of the missing rule id?

Is this a bug or a newbies common mistake?

Regards
Dietrich

**Comment by Hotboy178** [comment]
i have my own php script which upload files to server at first it was working now its not even working its giving me this error->add_music_handler.php:1 Failed to load resource: the server responded with a status of 412 (Precondition Failed)
![error22](https://user-images.githubusercontent.com/37395586/41112741-aa5d04de-6a34-11e8-84ce-d2d0b2f31f7e.PNG)

**Comment by lifeforms** [comment]
@Hotboy178 It's probably better if you open a new issue for this. Please include the relevant part of your ModSecurity audit log (usually in `/var/log/modsec_audit.log` or a similar location) Otherwise we cannot tell what's exactly happening...
