### ISSUE TITLE
Minimum version of mod_security question

### ISSUE THREAD

**Issue by a-zb** [SpiderLabs/owasp-modsecurity-crs#1562]
This is not an issue per se,- more of a question to the maintainers.
I tried the mailing list link, but it returns with a 404 status and nobody on IRC channel #modsecurity answers , so I came here as a last resort.

Question: Current ruleset has a minimum mod_security version requirement of 2.8.
Do you see the crs project moving up the minimum version requirement above 2.9 in the near future or even jumping to making 3.x the minimum ? If there is a strategy or timeline could we get an idea of when it could happen and what would push it to make 3.x the minimum version ?

Thanks

**Comment by lifeforms** [comment]
Hi @arekzb,

We always recommend running the latest ModSecurity version within a release train - IIRC we will run on ModSecurity 2.8, but ModSecurity 2.9.3 solves a lot of issues.

In our experiences, ModSecurity 3 still has some missing features and has performance disadvantages compared with ModSecurity 2. Also not all of our tests are yet running successfully on ModSecurity 3. The ModSecurity 3 Apache module is also still not finished, however, the ModSecurity 3 Nginx connector is good.

Therefore we recommend ModSecurity 3 if your webserver is Nginx, but recommend ModSecurity 2.9 on Apache.

As long as this situation is the reality, we will support both ModSecurity versions.

If ModSecurity 3 development continues and adds new features, we may in the future drop support for ModSecurity 2.

Thanks for your question!

**Comment by spartantri** [comment]
Hi @arekzb , 

I agree on all that Walter previously mentioned,  the CRS minimum version means which mod_security versions would be able to run the CRS. 

Version 3 still do not support some of the features that 2.9 does and that fact forced us to take specific alternatives on the rule writing style so the CRS could be compatible with version 3.

I recommend you to avoid using any version under 2.9.3 or 3.0.3 as some of the bugs can have severe impacts on stability or lead to filtering bypasses.

Personally, I prefer v2.9.3 running on Apache 2.4 as it is faster.
