### ISSUE TITLE
Rule 942360: Small bug in the regex cause FP 

### ISSUE THREAD

**Issue by Taiki-San** [SpiderLabs/owasp-modsecurity-crs#1580]
## Type of Issue

False positive.

## Description

The rule trigger a false positive for the following pattern: `\W asbla from`.  
More specifically, patterns similar to `, aside from` will trigger.

This is likely due to the following construct ```[\W]\s+as\s*?[\\"'`\w]+\s*?from``` being used instead ```[\W]\s+as\s+?[\\"'`\w]+\s*?from```.   
Specifically `\s*?` instead of `\s+?`.

## Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
Sorry for the inconvenience and thank you for reporting.

@franbuehler : You reassembled this rule in your regex archaeology project, I think. Anything comment?

**Comment by Taiki-San** [comment]
No problem, thanks for the quick response.
Do you want me to open a PR implementing this change?

**Comment by dune73** [comment]
The 184 open issues does not mean we don't care. It just means we're not enough people in the project. :)

In the light of this, a PR would be most welcome. Can't guarantee immediate merge though, we'll need to take a closer look first.

**Comment by Taiki-San** [comment]
Didn't meant to imply so :)
Created the PR!

**Comment by fgsch** [comment]
Changing the `\s*` to `\s+` will break e.g. `1 as' from`.

I think a better fix would be to add a word boundary:

```
[\W]\s+as\b\s*?[\\"'`\w]+\s*?from
```

This still matches the case above and doesn't match `, aside from`. 

Using pcretest:
```
"[\d\W]\s+as\s+?[\"'`\w]+\s*?from"
, aside from
No match
1 as' from
No match

"[\d\W]\s+as\b\s*?[\"'`\w]+\s*?from"
, aside from
No match
1 as' from
 0: 1 as' from
```

What do you think?

**Comment by Taiki-San** [comment]
Yeah, your solution is better, updated the PR.

**Comment by emphazer** [comment]
@fgsch good solution with \b instead of +.
okay, i could change the regression test to ````6 As" from```` for example

**Comment by fgsch** [comment]
@emphazer thanks. should we have a separate PR or include it in #1580?

**Comment by emphazer** [comment]
@fgsch no problemo, i will make a seperate PR today

**Comment by fgsch** [comment]
Sorry for the delay. The fix is merged now.
