### ISSUE TITLE
implementation of 912-DOS Protection makes no sense.

### ISSUE THREAD

**Issue by mphilipps** [SpiderLabs/owasp-modsecurity-crs#1597]
## Type of Issue
Incorrect blocking (false positive)

## Description
In the csr-setup.conf.example there is the following comment:

> When a client is making more than 100 requests (excluding static files) within 60 seconds, this is considered a 'burst'. After two bursts, the client is blocked for 600 seconds.

For me this implies that for each ip/useragent the last 100 requests are tracked to discover these burst. However after debugging why this rule would constantly trigger, I found the actual implementation is far from that. Using **modsec-sdbm-util** I monitored the ip.pag and found the "dos" protection works as follows:

* The first time a request from a new ip&useragent combination is seen an db entry is created. This Entry includes among others a dos_counter field and __expire_KEY. 
dos_counter is initialized with a 1 and __expire_KEY is set to a timestamp 10 Minutes into the future. 
* With the next request if the __expire_KEY has passed the entries is recreated, otherwise the dos_counter gets incremented and __expire_KEY gets updated. If the dos_counter reaches the threshold a bursts counter gets and at least on paranoia level 2 the client already gets blocked. There is additional logic for expiring the block and the burst counter, but at least on paranoia level 2 the harm is already done.

The end result of this is, is that a simple shell script like
`
while true; do sleep 1;curl domain.tld; done`

Already triggers the DOS protection even though it never sends more  than 60 requests per minute. Even worse, if a regular visitor visits 100 pages without taking a 10 minute break mod security again considers this is a dos.

Maybe we have a different idea of what qualifies as a denial of service, but reading a page every 9 minutes certainly isn't going to put an unusual strain on a server.
```

SecAction \
 "id:900700,\
  phase:1,\
  nolog,\
  pass,\
  t:none,\
  setvar:'tx.dos_burst_time_slice=60',\
  setvar:'tx.dos_counter_threshold=100',\
  setvar:'tx.dos_block_timeout=600'"
```

## Your Environment
* CRS version (e.g. v3.0.2): v3.1.1
* ModSecurity version (e.g. 2.9.2): 2.9.3
* Web Server and version (e.g. apache 2.4.27): apache 2.4.25
* Operating System and version: Debian stretch

## Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by dune73** [comment]
Hello @mphilipps, this is not our favorite part of CRS and there are reasons it is off by default.
Sorry, you are running into problems with this.

I reviewed and documented these rules a few years back and I think your summary more or less meets what I seem to remember as well.

And it seems the rules are not doing what they are meant to do.

So could you please confirm that the following leads to a blockade (it should not):

```
$> for I in {1..60}; do curl domain.tld; sleep 1; done
```

**Comment by mphilipps** [comment]
hi @dune73 
I was using 
`while true; do sleep 1;curl domain.tld; done`
to test this. I would assume that limiting it to just 60 requests won't hit the limit of 100. If you really want me to test that I can do that..

**Comment by mphilipps** [comment]
`for I in {1..60}; do curl domain.tld; sleep 1; done`

> Opening file: www-data-ip.pag
> Database ready to be used.
> Key: "10.8.5.2_e70998b778616b4073e9e0abea2c234b2b1d862b", Value len: 281
>  - ModSecurity variables:
>                   __expire_KEY: 1571916106
>                            KEY: 10.8.5.2_e70998b778616b4073e9e0abea2c234b2b1d862b
>                        TIMEOUT: 600
>                          __key: 10.8.5.2_e70998b778616b4073e9e0abea2c234b2b1d862b
>                         __name: ip
>                    CREATE_TIME: 1571915446
>                 UPDATE_COUNTER: 60
>                    dos_counter: 60
>               LAST_UPDATE_TIME: 1571915506
Every request was a 200.

`for I in {1..110}; do curl domain.tld; sleep 1; done`

First 100\*200 and then 10\*503 (Backend fetch failed)
> Opening file: www-data-ip.pag
> Database ready to be used.
> Key: "10.8.5.2_e70998b778616b4073e9e0abea2c234b2b1d862b", Value len: 464
>  - ModSecurity variables:
>                   __expire_KEY: 1571916349
>                            KEY: 10.8.5.2_e70998b778616b4073e9e0abea2c234b2b1d862b
>                        TIMEOUT: 600
>                          __key: 10.8.5.2_e70998b778616b4073e9e0abea2c234b2b1d862b
>                         __name: ip
>                    CREATE_TIME: 1571915637
>                 UPDATE_COUNTER: 111
>               LAST_UPDATE_TIME: 1571915749
>              dos_burst_counter: 1
>     __expire_dos_burst_counter: 1571915799
>                      dos_block: 1
>             __expire_dos_block: 1571916339
>              dos_block_counter: 10
>                 dos_block_flag: 1
>        __expire_dos_block_flag: 1571915800

**Comment by dune73** [comment]
Thank you for the clarification. I'm seeing clearer now.

So what you are saying is, that if a client does 100 requests stretched over longer than 60 seconds (burst_time_slice) it is still being blocked and it should not.

**Comment by mphilipps** [comment]
Yes, the client needs to take a 10 minute break  before it hits 100 to not trigger the dos detection.

**Comment by dune73** [comment]
Thank you for the confirmation. So the burst_time_slice functionality is broken. Need to check.

Generally: We kept this rule for historical reasons. It's not core CRS functionality and I do not think ModSec is very good at fighting DoS. Maybe a small one, but certainly nothing serious or nothing distributed.
