### ISSUE TITLE
Migration of the CRS site on the OWASP wiki

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#1601]
## Message from OWASP HQ

```
Hello, Leaders,

The website migration is Hello, Leaders,

The website migration is underway, with nearly all repositories having been
created already.  Not everyone has been added to your respective
repositories; that is an on-going process.  We now have a general document
detailing the content in your repository at https://www2.owasp.org/migration

A nice-to-accomplish goal would be to get the chapters and projects
migrated in the next 30 days.

Regards,

Harold L. Blankenship

OWASP Foundation

Director of Technology and Projects

```

**During the migration period, our new OWASP website will be at https://www2.owasp.org/www-project-modsecurity-core-rule-set/.**

**Comment by fzipi** [comment]
Yeah, it's jekyll based now. I've migrated a couple other projects already.

**Comment by fzipi** [comment]
How valid/updated are the https://www.owasp.org/index.php/ModSecurity_CRS_Rule_Description_Template ?

**Comment by dune73** [comment]
That was an attempt to do this. If it gets new traction, we would probably extract it from our comments with the msc_parser. But it's probably too detailed and many data points are wishful thinking.

**Comment by fzipi** [comment]
This is my initial attempt.
![Screenshot from 2019-10-20 18-00-47](https://user-images.githubusercontent.com/3012076/67166210-9d6d2b00-f363-11e9-80ba-af5d33813482.png)

There are some things to define, because we don't have the same information now. For example, wiki users don't exist anymore! So the tree leaders should migrate their info (or update their github profile).

The list of collaborators needs to be completed also.

**Comment by fzipi** [comment]
Need to move assets also (images and so).

**Comment by fzipi** [comment]
Added reference to logos in https://github.com/OWASP/www-project-modsecurity-core-rule-set/pull/3, and contributors list in https://github.com/OWASP/www-project-modsecurity-core-rule-set/pull/2.

**Comment by fzipi** [comment]
@dune73 Do you think we need anything more migrated?

**Comment by dune73** [comment]
This looks really good. Thank you very much. Some of the links on the right are broken. Is it possible to fix this?

**Comment by fzipi** [comment]
@dune73 Tried to find in the new website links similar to the previous one. Also linked to security policy for consistency.

See https://github.com/OWASP/www-project-modsecurity-core-rule-set/pull/4

**Comment by fzipi** [comment]
@dune73 I guess this one can be closed, now that the site is in production?

**Comment by dune73** [comment]
Yes, thanks to you.
