### ISSUE TITLE
JSON request body contains =calc|a!z value mod security doesn't capture

### ISSUE THREAD

**Issue by jofisiva** [SpiderLabs/owasp-modsecurity-crs#1606]
The JSON request body contains calculator function
{
"name": "=calc|a!z"
}

The request has not been blocked.

Include modsecurity-crs/crs-config.conf Include modsecurity-crs/rules/REQUEST-901-INITIALIZATION.conf
Include modsecurity-crs/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf
Include modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf
SecRule REQUEST_HEADERS:Content-Type "application/json"
"id:'200001',phase:1,t:none,t:lowercase,log,nolog,ctl:requestBodyProcessor=JSON"

SecRule REQBODY_ERROR "!@eq 0"
"id:'200002', phase:2,t:none,log,deny,status:400,msg:'Failed to parse request body.',logdata:'%{reqbody_error_msg}',severity:2"

SecRule MULTIPART_STRICT_ERROR "!@eq 0"
"id:'200003',phase:2,t:none,log,deny,status:400,
msg:'Multipart request body failed strict validation:
PE %{REQBODY_PROCESSOR_ERROR},
BQ %{MULTIPART_BOUNDARY_QUOTED},
BW %{MULTIPART_BOUNDARY_WHITESPACE},
DB %{MULTIPART_DATA_BEFORE},
DA %{MULTIPART_DATA_AFTER},
HF %{MULTIPART_HEADER_FOLDING},
LF %{MULTIPART_LF_LINE},
SM %{MULTIPART_MISSING_SEMICOLON},
IQ %{MULTIPART_INVALID_QUOTING},
IP %{MULTIPART_INVALID_PART},
IH %{MULTIPART_INVALID_HEADER_FOLDING},
FL %{MULTIPART_FILE_LIMIT_EXCEEDED}'"

ModSecurity doesn't throw any error

httpd -v
Server version: Apache/2.2.15 (Unix)
Server built: Jul 12 2017 13:32:34

**Comment by jofisiva** [comment]
ModSecurity for Apache/2.9.1 (http://www.modsecurity.org/) configured.
 ModSecurity: APR compiled version="1.3.9"; loaded version="1.3.9"
 ModSecurity: PCRE compiled version="7.8 "; loaded version="7.8 2008-09-05"
 YAJL compiled version="2.1.1"
 LIBXML compiled version="2.7.6"

**Comment by fgsch** [comment]
@jofisiva Thanks for the report.

Could you explain in more detail why you think this should be blocked and which rule should do it?

**Comment by fgsch** [comment]
Hi @jofisiva . Unfortunately without more information there is nothing we can do here.
I'm going to close this for now, but feel free to add more details or open a new ticket with all the needed information.
