### ISSUE TITLE
Inconsistent style in rule names

### ISSUE THREAD

**Issue by Taiki-San** [SpiderLabs/owasp-modsecurity-crs#1622]
## Type of Issue
Cosmetic

## Description
Some rules name finish with a dot, while others don't.
Should be unified one way or another.

**Comment by dune73** [comment]
Could you give a few examples?

**Comment by Taiki-San** [comment]
Sure! For instance, rules like 920160 have as `msg` property `"Content-Length HTTP header is not numeric."`.  
The final dots is there right and left (specifically 920160, 920190, 920210, 941190, 941200, 941210, 941220, 941230, 941240, 941250, 941260, 941270, 941280, 941290, 941300, 941310, 941350, 942160, 942270, 942500 in our set) but still in minority.

**Comment by airween** [comment]
You can see the values of `msg` actions [here](https://docs.google.com/spreadsheets/d/1jwBkFWIhuOThsBFXOCi8QReZpIjVxXLZ8QQNtwffDGo/edit?usp=sharing), marked with a boolean flag whether it contains a dot or not.

:)

Note, that turn on/off or modify the filters in the header row.

**Comment by dune73** [comment]
Ah, it's the msg you are talking about.

Yes, this is untidy. Feel free to open a PR to clean this up.

**Comment by nerrehmit** [comment]
Do we have a preference if we would rather have all the messages end with a dot or without? If there is a preferred way I'd gladly work on this.

**Comment by Taiki-San** [comment]
I think without dot make more sense to later format it in log messages and whatnot.

**Comment by dune73** [comment]
I agreee with @Taiki-San.

Thanks @nerrehmit!

**Comment by fgsch** [comment]
@nerrehmit Will you be working on this?
