### ISSUE TITLE
Error in file install

### ISSUE THREAD

**Issue by Mr-later** [SpiderLabs/owasp-modsecurity-crs#1623]
Line 30 of the file install
https://www.projecthoneypot.org/httpbl_configure.php.
cannt access

**Comment by fgsch** [comment]
Thanks for your report. Can you provide more details?

**Comment by fgsch** [comment]
Have you tried creating an account as described in the INSTALL doc?

```
The use of Project Honeypot requires a free API key. 
These require an account but can be obtained at https://www.projecthoneypot.org/httpbl_configure.php.
```

**Comment by fgsch** [comment]
Please try following that and let us know if you have any issues.
I will close this for now.
