### ISSUE TITLE
False positive 953120

### ISSUE THREAD

**Issue by GoldraK** [SpiderLabs/owasp-modsecurity-crs#1635]
## Type of Issue
False positive

## Description
We have Gzip active but only pass with two images.

Apache-Error: [file "apache2_util.c"] [line 271] [level 3] [client XXX.XXX.XXX.XXX] ModSecurity: Warning. Match of "rx (?:\\\\\\\\x1f\\\\\\\\x8b\\\\\\\\x08|\\\\\\\\b(?:(?:i(?:nterplay|hdr|d3)|m(?:ovi|thd)|r(?:ar!|iff)|(?:ex|jf)if|f(?:lv|ws)|varg|cws)\\\\\\\\b|gif)|B(?:%pdf|\\\\\\\\.ra)\\\\\\\\b|^wOF(?:F|2))" against "RESPONSE_BODY" required. [file "/etc/httpd/modsecurity.d/activated_rules_03/RESPONSE-953-DATA-LEAKAGES-PHP.conf"] [line "105"] [id "953120"] [msg "PHP source code leakage"] [data "Matched Data: <? found within RESPONSE_BODY: \\\\xff\\\\xd8\\\\xff\\\\xe0\\\\x00\\\\x10JFIF\\\\x00\\\\x01\\\\x01\\\\x00\\\\x00\\\\x01\\\\x00\\\\x01\\\\x00\\\\x00\\\\xff\\\\xfe\\\\x00>CREATOR: gd-jpeg v1.0 (using IJG JPEG v62), default quality\\\\x0a\\\\xff\\\\xdb\\\\x00C\\\\x00\\\\x08\\\\x06\\\\x06\\\\x07\\\\x06\\\\x05\\\\x08\\\\x07\\\\x07\\\\x07\\\\x09\\\\x09\\\\x08\\\\x0a\\\\x0c\\\\x14\\\\x0d\\\\x0c\\\\x0b\\\\x0b\\\\x0c\\\\x19\\\\x12\\\\x13\\\\x0f\\\\x14\\\\x1d\\\\x1a\\\\x1f\\\\x1e\\\\x1d\\\\x1a\\\\x1c\\\\x1c $.' \\\\x22,#\\\\x1c\\\\x1c(7),01444\\\\x1f'9=82<.342\\\\xff\\\\xdb\\\\x00C\\\\x01\\\\x09\\\\x09\\\\x09\\\\x0c\\\\x0b\\\\x0c\\\\x18\\\\x0d\\\\x0d\\\\x182!\\\\x1c!22222222222222222222222222222222222222222222222222\\\\xff\\\\xc0\\\\x0..."] [severity "ERROR"] [ver "OWASP_CRS/3.2.0"] [tag "application-multi"] [tag "language-php"] [tag "platform-multi"] [tag "attack-disclosure"] [tag "OWA [hostname "www.domain.com"] [uri "/imagen-producto/97/camiseta-quebranta-frontal.png"] [unique_id "XdL@Krad1fgIirQk35XoxQAAAAw"]

## Your Environment

* CRS version v3.2.0:
* ModSecurity version 2.9.2-1.el7
* Web Server and version apache 2.4.6
* Operating System and version: Centos 7

## Confirmation

[X] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by emphazer** [comment]
@GoldraK 
could you please post your response header?
what did you configure in SecResponseBodyMimeType?
gzip and jpeg makes no sense.

normally the response body handler shouldn't trigger a jpeg file.

**Comment by GoldraK** [comment]
@emphazer First thanks for your time

Don't have config SecResponseBodyMimeType

--99164202-A--
[18/Nov/2019:21:25:14 +0100] XdL@Krad1fgIirQk35XoxQAAAAw 159.138.150.192 46462 192.168.1.4 82
--99164202-B--
GET /imagen-producto/97/camiseta-quebranta-frontal.png HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.9
User-Agent: Mozilla/5.0 (Linux; Android 7.0; FRD-AL00 Build/HUAWEIFRD-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.49 Mobile MQQBrowser/6.2 TBS/043602 Safari/537.36 MicroMessenger/6.5.16.1120 NetType/WIFI Language/zh_CN
Connection: Close
Host: www.xxxxxxx.com
Accept-Encoding: gzip,deflate
X-Protocol: https

--99164202-F--
HTTP/1.1 403 Forbidden
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html; charset=iso-8859-1

--99164202-E--
ÿØÿà^@^PJFIF^@^A^A^@^@^A^@^A^@^@ÿþ^@>CREATOR: gd-jpeg v1.0 (using IJG JPEG v62), default quality
ÿÛ^@C^@^H^F^F^G^F^E^H^G^G^G             ^H
^L^T^M^L^K^K^L^Y^R^S^O^T^]^Z^_^^^]^Z^\^\ $.' ",#^\^\(7),01444^_'9=82<.342ÿÛ^@C^A                        ^L^K^L^X^M^M^X2!^\!22222222222222222222222222222222222222222222222222ÿÀ^@^Q^H^B^]^BX^C^A"^@^B^Q^A^C^Q^AÿÄ^@^_^@^@^A^E^A^A^A^A^A^A^@^@^@^@^@^@^@^@^A^B^C^D^E^F^G^H
^KÿÄ^@µ^P^@^B^A^C^C^B^D^C^E^E^D^D^@^@^A}^A^B^C^@^D^Q^E^R!1A^F^SQa^G"q^T2<81><91>¡^H#B±Á^URÑð$3br<82>
^V^W^X^Y^Z%&'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz<83><84><85><86><87><88><89><8a><92><93><94><95><96><97><98><99><9a>¢£¤¥¦§¨©ª²³´µ¶·¸¹ºÂÃÄÅÆÇÈÉÊÒÓÔÕÖ×ØÙÚáâãäåæçèéêñòóôõö÷øùúÿÄ^@^_^A^@^C^A^A^A^A^A^A^A^A^A^@^@^@^@^@^@^A^B^C^D^E^F^G^H
^KÿÄ^@µ^Q^@^B^A^B^D^D^C^D^G^E^D^D^@^A^Bw^@^A^B^C^Q^D^E!1^F^RAQ^Gaq^S"2<81>^H^TB<91>¡±Á  #3Rð^UbrÑ
^V$4á%ñ^W^X^Y^Z&'()*56789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz<82><83><84><85><86><87><88><89><8a><92><93><94><95><96><97><98><99><9a>¢£¤¥¦§¨©ª²³´µ¶·¸¹ºÂÃÄÅÆÇÈÉÊÒÓÔÕÖ×ØÙÚâãäåæçèéêòóôõö÷øùúÿÚ^@^L^C^A^@^B^Q^C^Q^@?^@ÎÚ^FyéïíJË<8c>n?ç^Tá<90>NFzÒ<9c>ã§ùÍy<87>¨5H^_<9d>8^QúÐ^OZU^X^\^OÖ<80>$<88><8d>Ç,^Fyæ­.Ür@ªÑ"°É^\ûÕ¸£^MÆ8=i^L<91>v<94>|t^U<9f>w*<96>-Æ^G^\Õ×<8d>^R&Áå«2â/3^H^Hàå¾<94>$^EeL^Vf^£<8a>¼<80>%²<81>Øw¤EQ<9e>01R0RÛHã^@P^H<90>^U-^[qÇ^_¥W¼l4^@ô2<80>qO.#qòòN?
<8e>`­%¿Ê@óW'µ^@YE^EUHç½JÑ^O+Ó-<80>=i^H]Ù^U&^OîÁ'^YÜj@a^YBsüX^_J<84>^MÅ<8f>ûU66<80>¼õ&¢A<80>N^N^KÐ^Dð^OÞ^U#<8c>Õ<87>
P<91>È^U^LC÷¸^YÍHaÏ^D<9c>qýh^Q^P
<9d>£®?<91> §^Y^@zcð©^X^Dã><9f>Ê<9a>«<8e>^T<9e>h^Xø<9f><83><90>F^N9©^C<80>^F^AÎj^P:<9c>wæ<97>^\
Lh<95><9f><8a><86>I^Q@Ï^Yj~^N:U{<87>]Ñô$^^<94>!<92>Gp¤<91>ÐqÍ]^D^Q&^[«^Nõ<9f>^Djw1^C¨â´"<89>Y»rÔ1^K.Ò_'¨ÅB<8b>µÈ_»<9a><96>d^D¶^G9ÅF<8a>^K^^{óHdêy8ëU<9d><98>Hr229«^A@RKUY<88>\<92>Ä^MËüè^Pc^N[Ñh`2»zÔ<9b>9Æìæ<98>bb¡<87>AééL^P¬^[g^Dr;Ò(a<80>Ç À¥Úä(ÝÆ?*VFS<81>Ï^T<82>ÃÔqÈ^Yô§Å<80>À<95>êi±å<94>6G#¥>^Eýâ<82>F^Kv¦!©þ» #5svsÅBc*äª<81><83>V#RW'^@b<86>0Ý<8c>^LT<8d>(ú^ZB1<80>E^E77^CÖ<92>^B<91><94>^WQ<9c>õ"£à¸ õ^D^QS2<85>uùy^B¡AÎJñ<93>@!<8e>^A\<92>xeÆ>µ^\À^Eàs¸^?:µ2î<84><8c>g$^Qù<8a>«*^W
....

--99164202-H--
Message: Warning. Match of "rx (?:\\x1f\\x8b\\x08|\\b(?:(?:i(?:nterplay|hdr|d3)|m(?:ovi|thd)|r(?:ar!|iff)|(?:ex|jf)if|f(?:lv|ws)|varg|cws)\\b|gif)|B(?:%pdf|\\.ra)\\b|^wOF(?:F|2))" against "RESPONSE_BODY" required. [file "/etc/httpd/modsecurity.d/activated_rules_03/RESPONSE-953-DATA-LEAKAGES-PHP.conf"] [line "105"] [id "953120"] [msg "PHP source code leakage"] [data "Matched Data: <? found within RESPONSE_BODY: \xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xfe\x00>CREATOR: gd-jpeg v1.0 (using IJG JPEG v62), default quality\x0a\xff\xdb\x00C\x00\x08\x06\x06\x07\x06\x05\x08\x07\x07\x07\x09\x09\x08\x0a\x0c\x14\x0d\x0c\x0b\x0b\x0c\x19\x12\x13\x0f\x14\x1d\x1a\x1f\x1e\x1d\x1a\x1c\x1c $.' \x22,#\x1c\x1c(7),01444\x1f'9=82<.342\xff\xdb\x00C\x01\x09\x09\x09\x0c\x0b\x0c\x18\x0d\x0d\x182!\x1c!22222222222222222222222222222222222222222222222222\xff\xc0\x0..."] [severity "ERROR"] [ver "OWASP_CRS/3.2.0"] [tag "application-multi"] [tag "language-php"] [tag "platform-multi"] [tag "attack-disclosure"] [tag "OWA
Message: Access denied with code 403 (phase 4). Operator GE matched 4 at TX:outbound_anomaly_score. [file "/etc/httpd/modsecurity.d/activated_rules_03/RESPONSE-959-BLOCKING-EVALUATION.conf"] [line "75"] [id "959100"] [msg "Outbound Anomaly Score Exceeded (Total Score: 4)"] [tag "anomaly-evaluation"]
Message: Warning. Operator GE matched 4 at TX:outbound_anomaly_score. [file "/etc/httpd/modsecurity.d/activated_rules_03/RESPONSE-980-CORRELATION.conf"] [line "96"] [id "980140"] [msg "Outbound Anomaly Score Exceeded (score 4): individual paranoia level scores: 4, 0, 0, 0"] [tag "event-correlation"]
Apache-Error: [file "apache2_util.c"] [line 271] [level 3] [client 159.138.150.192] ModSecurity: Warning. Match of "rx (?:\\\\\\\\x1f\\\\\\\\x8b\\\\\\\\x08|\\\\\\\\b(?:(?:i(?:nterplay|hdr|d3)|m(?:ovi|thd)|r(?:ar!|iff)|(?:ex|jf)if|f(?:lv|ws)|varg|cws)\\\\\\\\b|gif)|B(?:%pdf|\\\\\\\\.ra)\\\\\\\\b|^wOF(?:F|2))" against "RESPONSE_BODY" required. [file "/etc/httpd/modsecurity.d/activated_rules_03/RESPONSE-953-DATA-LEAKAGES-PHP.conf"] [line "105"] [id "953120"] [msg "PHP source code leakage"] [data "Matched Data: <? found within RESPONSE_BODY: \\\\xff\\\\xd8\\\\xff\\\\xe0\\\\x00\\\\x10JFIF\\\\x00\\\\x01\\\\x01\\\\x00\\\\x00\\\\x01\\\\x00\\\\x01\\\\x00\\\\x00\\\\xff\\\\xfe\\\\x00>CREATOR: gd-jpeg v1.0 (using IJG JPEG v62), default quality\\\\x0a\\\\xff\\\\xdb\\\\x00C\\\\x00\\\\x08\\\\x06\\\\x06\\\\x07\\\\x06\\\\x05\\\\x08\\\\x07\\\\x07\\\\x07\\\\x09\\\\x09\\\\x08\\\\x0a\\\\x0c\\\\x14\\\\x0d\\\\x0c\\\\x0b\\\\x0b\\\\x0c\\\\x19\\\\x12\\\\x13\\\\x0f\\\\x14\\\\x1d\\\\x1a\\\\x1f\\\\x1e\\\\x1d\\\\x1a\\\\x1c\\\\x1c $.' \\\\x22,#\\\\x1c\\\\x1c(7),01444\\\\x1f'9=82<.342\\\\xff\\\\xdb\\\\x00C\\\\x01\\\\x09\\\\x09\\\\x09\\\\x0c\\\\x0b\\\\x0c\\\\x18\\\\x0d\\\\x0d\\\\x182!\\\\x1c!22222222222222222222222222222222222222222222222222\\\\xff\\\\xc0\\\\x0..."] [severity "ERROR"] [ver "OWASP_CRS/3.2.0"] [tag "application-multi"] [tag "language-php"] [tag "platform-multi"] [tag "attack-disclosure"] [tag "OWA [hostname "www.xxxxx.com"] [uri "/imagen-producto/97/camiseta-quebranta-frontal.png"] [unique_id "XdL@Krad1fgIirQk35XoxQAAAAw"]
Apache-Error: [file "apache2_util.c"] [line 271] [level 3] [client 159.138.150.192] ModSecurity: Access denied with code 403 (phase 4). Operator GE matched 4 at TX:outbound_anomaly_score. [file "/etc/httpd/modsecurity.d/activated_rules_03/RESPONSE-959-BLOCKING-EVALUATION.conf"] [line "75"] [id "959100"] [msg "Outbound Anomaly Score Exceeded (Total Score: 4)"] [tag "anomaly-evaluation"] [hostname "www.xxxxx.com"] [uri "/imagen-producto/97/camiseta-quebranta-frontal.png"] [unique_id "XdL@Krad1fgIirQk35XoxQAAAAw"]
Apache-Error: [file "apache2_util.c"] [line 271] [level 3] [client 159.138.150.192] ModSecurity: Warning. Operator GE matched 4 at TX:outbound_anomaly_score. [file "/etc/httpd/modsecurity.d/activated_rules_03/RESPONSE-980-CORRELATION.conf"] [line "96"] [id "980140"] [msg "Outbound Anomaly Score Exceeded (score 4): individual paranoia level scores: 4, 0, 0, 0"] [tag "event-correlation"] [hostname "www.xxxxx.com"] [uri "/imagen-producto/97/camiseta-quebranta-frontal.png"] [unique_id "XdL@Krad1fgIirQk35XoxQAAAAw"]
Action: Intercepted (phase 4)
Apache-Handler: proxy-server
Stopwatch: 1574108714103989 124737 (- - -)
Stopwatch2: 1574108714103989 124737; combined=7965, p1=319, p2=644, p3=71, p4=6827, p5=103, sr=22, sw=1, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/); OWASP_CRS/3.2.0.
Server: Apache
Engine-Mode: "ENABLED"

**Comment by emphazer** [comment]
@GoldraK 
this is a very strange behavior.
i think the mime-type of the jpeg is misconfigured or missing.
normally the OUTBOUND shouldn't trigger the content-type image/jpeg
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#SecResponseBodyMimeType

the default is  text/plain text/html

you could set modsecurity to DetectionOnly to see what content-type the apache delivers.

**Comment by GoldraK** [comment]
He activated the rule again and put it on DetectionOnly and now I don't get on the record. If I activate again to stop it if it comes out in the log: S

**Comment by GoldraK** [comment]
Thanks for the info. Now Work perfect.
