### ISSUE TITLE
single quote in file

### ISSUE THREAD

**Issue by henryzhang87** [SpiderLabs/owasp-modsecurity-crs#1637]
When files uploaded into our application, the files contain single quote, especially French content.
These are blocked by MULTIPART_INVALID_QUOTE rule.

Some one suggested using separate rules to WARN not DENY, but this strategy won't stop malicious content 

Would you please advise how could we fix this problem?

## Your Environment

* CRS version (e.g. v3.0.2):
* ModSecurity version (e.g. 2.9.2):
* Web Server and version (e.g. apache 2.4.27):
* Operating System and version:

## Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by airween** [comment]
Hi @henryzhang87,

> These are blocked by MULTIPART_INVALID_QUOTE rule.

you think about [`MULTIPART_INVALID_QUOTING`](https://github.com/SpiderLabs/ModSecurity/blob/v2/master/modsecurity.conf-recommended#L78)? If yes, that's not part of CRS, that's part of default `modsecurity.conf`.

A possible solution could be to turn off this rule, and create a new (or more new) rule(s) for each `MULTIPART_*` checking.
