### ISSUE TITLE
ModSecurity CRS - possible to override certain rule sets?

### ISSUE THREAD

**Issue by dmarlow** [SpiderLabs/owasp-modsecurity-crs#1638]
(I tried to post to the security stack exchange site, but I don't have enough reputation points to be able to post something there).

I currently have `SecRuleEngine DetectionOnly`, but would like to enable something like `REQUEST-913-SCANNER-DETECTION` to actively block (i.e. prevention mode). What's the correct/best way to do that without going into that rule set file and changing each rule? I'd hate to not be able to easily update my rules down the road.

**Comment by csanders-git** [comment]
The quickest way to do this would probably be with `SecRuleRemoveById`. 

1) Set `SecRuleEngine On`
2) Modify 999-EXCLUSION (https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.3/dev/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example) to add two SecRuleRemoveById's (and also remove the .example, this prevents CRS from ever overwriting this on update)

```
SecRuleRemoveById 905000-913000
SecRuleRemoveById 914000-949000
```

This technically leaves on response body rules (you can add a third SecRuleRemoveById batch for that or just set `SecResponseBodyAccess` to off.)

All of these SecRuleRemoveById's must be placed AFTER the rules (hence the listed file) and will be removed on engine initialization 

Feel free to reopen if there are any other issues.

**Comment by dmarlow** [comment]
`SecRuleRemoveById` basically becomes detection only when `SecRuleEngine On`?

Seems like the reverse of this is a better approach, but can see why it's being done this way. I appreciate the response and suggestion! Thank you.

**Comment by dune73** [comment]
What @csanders-git suggests is removing all your rule other than the 913 block that you want to put into blocking.

If you want to retain everything else in detection mode and only 913xxx in blocking, this is going to be tough. It's probably best to rewrite the complete ruleset via a script. Either you trust `sed` to do this, or you use this handy tool https://github.com/digitalwave/msc_pyparser. Either way, I do not see a way to implement this in an easy manner (other than what @csanders-git proposed, but it's possibly not 100% what you had in mind).

**Comment by dmarlow** [comment]
Thank you, much appreciated!
