### ISSUE TITLE
Was the Bayesian Attack Analysis method abandoned？

### ISSUE THREAD

**Issue by illman2** [SpiderLabs/owasp-modsecurity-crs#1639]
I can‘t find the Bayesian Attack Analysis method in the latest modsecurity-crs. It maybe abandoned？what‘s wrong with this method？

**Comment by chaimsanders-okta** [comment]
Hi @illman2 all the experimental rules were removed from the 3.x branch. In most cases these were done as part of testing and were not production ready. Additionally, in many cases these were not the most efficient implementations of the solution.

We still have these available in the 2.x branch they are just not maintained by the Core Rule Set Team any longer. If you are interested in an area specifically, we'd encourage you to continue the work and we'd be happy to accept PR's for such capabilities.

https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v2.2/master/experimental_rules/modsecurity_crs_48_bayes_analysis.conf

**Comment by csanders-git** [comment]
Hi @illman2 all the experimental rules were removed from the 3.x branch. In most cases these were done as part of testing and were not production ready. Additionally, in many cases these were not the most efficient implementations of the solution.

We still have these available in the 2.x branch they are just not maintained by the Core Rule Set Team any longer. If you are interested in an area specifically, we'd encourage you to continue the work and we'd be happy to accept PR's for such capabilities.

https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v2.2/master/experimental_rules/modsecurity_crs_48_bayes_analysis.conf
