### ISSUE TITLE
 Monthly Chat Agenda December (2019-12-02) 

### ISSUE THREAD

**Issue by fzipi** [SpiderLabs/owasp-modsecurity-crs#1641]
This is the Agenda for the Monthly CRS Chat.

The chat is going to happen on https://owasp.slack.com in the channel #coreruleset on Monday, December 2, at 20:30 CET.

### PRs

* #1495 - Fix potential ReDoS in 933180 
* #1601 - Migration of the CRS site on the OWASP wiki
* #1610 - HTTP splitting
* #1627, #1628, #1629, #1630 Repo refactoring, step 1 (See #1600)

### Open Issues

* 

### Other items

We have pulls for Refactoring ModSecurity CRS Branch v3.x/dev to further discuss or merge.

Feel free to add items as you see fit either above, or below as comments.

If you are not yet on the OWASP Slack, here is your invite: https://join.slack.com/t/owasp/shared_invite/enQtNjExMTc3MTg0MzU4LWQ2Nzg3NGJiZGQ2MjRmNzkzN2Q4YzU1MWYyZTdjYjA2ZTA5M2RkNzE2ZjdkNzI5ZThhOWY5MjljYWZmYmY4ZjM .
Everybody is welcome to join our community chat.

**Comment by theMiddleBlue** [comment]
should this be removed/changed? Isn't it no longer true? If yes, I can open a PR during the meeting:
https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/7f228032ee9a4911043ed75a5c06eb8a869683c5/crs-setup.conf.example#L166-L168

**Comment by theMiddleBlue** [comment]
~If we all agree, I would like to remove `REQUEST_FILENAME` from 933210 because it could lead to FPs as @emphazer reported in https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1626~ need more time to test, removed from agenda

**Comment by dune73** [comment]
## Decisions

* #1495 is being assigned to Walter (issue)
* #1601 is good to go from our perspective.
* #1610 has been used in prod without any FPs and is ready to be merged (Many millions of requests served)
* #1627 is merged as is. Older stable branches are not changed, crs-setup.conf won't be moved to example folder
* #1600 We agree on the refactoring of the docker repo with a folder (vs branch) structure. A PR implementing this is welcome.
* dune73 will come with a proposal to get more sponsoring for our project until the next meeting
