### ISSUE TITLE
Rule 942100: False Positive

### ISSUE THREAD

**Issue by wilton-wu** [SpiderLabs/owasp-modsecurity-crs#1648]
### Type of Issue

Incorrect blocking (false positive)

### Description

Simplified Chinese characters are parsed into incorrect English characters.  
(异常) => 1)on;

### Audit Logs

```
ModSecurity: Warning. detected SQLi using libinjection. 
[file "/modpath/crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"]
 [line "45"] [id "942100"] [rev ""] 
[msg "SQL Injection Attack Detected via libinjection"]
 [data "Matched Data: 1)on; found within 
ARGS:json.array_0.Details.array_13.Remark: (\x028)>\xdd{\x8b\x19\xef;"] 
[severity "2"] [ver "OWASP_CRS/3.2.0"] [maturity "0"] [accuracy "0"] 
[hostname "192.168.1.33"] [uri "/the/api"] [unique_id "157551036835.773412"] 
[ref "v37,27t:urlDecodeUni"]
```

### Environment

+ CRS version: 3.2.0
+ ModSec version: v3
+ Nginx/1.15.12

**Comment by dune73** [comment]
Hi @HudsonWu, sorry to hear of this issue. Unfortunately, you are probably hitting on a ModSecurity shortcoming where CRS can not help you very much.

The point is, that ModSec is very weak in terms of Unicode.

What you can make sure is that your Unicode Mapping tables are correctly set up.
See the ModSecurity Handbook or this older blog post: https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/modsecurity-advanced-topic-of-the-week-unicode-mapping-support/

I also tried to reproduce your alert with curl, but I could not. I do not think we are really able to help you (other than with a rule exclusion workaround) if it's a ModSecurity limitation. However, if you could provide me with a one-liner to trigger this alert with this payload, it would be really helpful going forward.

**Comment by HudsonWu** [comment]
Thank you for your reply, I can trigger the rule with this curl request: 
```
curl -X POST "http://mysite.com/api" -H "Content-Type: application/json-patch+json" \
 -d "{\"Details\":\"(异常)社保;\"}"
```
## Audit Logs

```
ModSecurity: Warning. detected SQLi using libinjection. 
[file "/etc/nginx/owasp-modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] 
[line "45"] [id "942100"] [rev ""] [msg "SQL Injection Attack Detected via libinjection"]
 [data "Matched Data: 1)on; found within ARGS:json.Details: (\x028)>\xdd;"]
 [severity "2"] [ver "OWASP_CRS/3.2.0"] [maturity "0"] 
[accuracy "0"] [hostname "192.168.1.6"] [uri "/api"]
 [unique_id "157662.538784"] [ref "v13,15t:urlDecodeUni"]
```

**Comment by wilton-wu** [comment]
Thank you for your reply, I can trigger the rule with this curl request: 
```
curl -X POST "http://mysite.com/api" -H "Content-Type: application/json-patch+json" \
 -d "{\"Details\":\"(异常)社保;\"}"
```
## Audit Logs

```
ModSecurity: Warning. detected SQLi using libinjection. 
[file "/etc/nginx/owasp-modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] 
[line "45"] [id "942100"] [rev ""] [msg "SQL Injection Attack Detected via libinjection"]
 [data "Matched Data: 1)on; found within ARGS:json.Details: (\x028)>\xdd;"]
 [severity "2"] [ver "OWASP_CRS/3.2.0"] [maturity "0"] 
[accuracy "0"] [hostname "192.168.1.6"] [uri "/api"]
 [unique_id "157662.538784"] [ref "v13,15t:urlDecodeUni"]
```

**Comment by dune73** [comment]
Thank you. This works for me know.

For the record, the JSON payload has the following Hex:

```
$> echo "{\"Details\":\"(异常)社保;\"}"  | hexdump -C
00000000  7b 22 44 65 74 61 69 6c  73 22 3a 22 28 e5 bc 82  |{"Details":"(...|
00000010  e5 b8 b8 29 e7 a4 be e4  bf 9d 3b 22 7d 0a        |...)......;"}.|
```

@HudsonWu : Are you able to do a rule exclusion yourself, or do you need support?

**Comment by wilton-wu** [comment]
Thank you, There are still a few questions: 
  + Can I just remove the match of the keywords (`1)on;`)  in the rule? and how?
  + How this problem arises?

**Comment by wilton-wu** [comment]
## Debug Logs

```
[9]  T (0) t:utf8toUnicode: "json.Details"
[9]  T (0) t:urlDecodeUni: "json.Details"
[9]  T (0) t:removeNulls: "json.Details"
[9] multiMatch is enabled. 1 values to be tested.
[9] Target value: "json.Details" (Variable: ARGS_NAMES:json.Details)
[9] detected SQLi: not able to find an inject on 'json.Details'
[9]  T (1) t:utf8toUnicode: "(%u5f02%u5e38)%u793e%u4fdd;"
[9]  T (2) t:urlDecodeUni: "(8)>ۻ"
[9]  T (2) t:removeNulls: "(8)>ۻ"
[9] multiMatch is enabled. 3 values to be tested.
[9] Target value: "(\xe5\xbc\x82\xe5\xb8\xb8)\xe7\xa4\xbe\xe4\xbf\x9d;" (Variable: ARGS:json.Details)
[9] detected SQLi: not able to find an inject on '(异常)社保;'
[9] Target value: "(%u5f02%u5e38)%u793e%u4fdd;" (Variable: ARGS:json.Details)
[9] detected SQLi: not able to find an inject on '(%u5f02%u5e38)%u793e%u4fdd;'
[9] Target value: "(\x028)>\xdd;" (Variable: ARGS:json.Details)
[4] detected SQLi using libinjection with fingerprint '1)on;' at: '(8)>ۻ'
[7] Added DetectSQLi match TX.0: 1)on;
[9] Matched vars updated.
```

Above is debug logs, In addition to the valid characters (`(异常)社保;`, was translated into`(%u5f02%u5e38)%u793e%u4fdd;`), there are other characters (`(8)>ۻ`). Where do these characters come from?

**Comment by fgsch** [comment]
`(%u5f02%u5e38)%u793e%u4fdd` gets translated to (\x028)>\xdd by urlDecodeUni.
`%u5f02` -> `02`, `%u5e38` -> `8`, `%u793e` -> `>`, `%u4fdd` -> `dd`.

As @dune73 said, can you confirm the unicode mapping tables are set up correctly?

**Comment by wilton-wu** [comment]
Thank you, I see. That means, if my application try and do best-fit mapping like this, then the rule is valid ; otherwise, the rule is a false positive (relatively speaking), just do a rule exclusion.

If there are false positives because of unicode mapping, check and modify the `unicode.mapping` file, or just remove related characters:  `t:utf8toUnicode` from the rule.

**Comment by dune73** [comment]
Yes, that's a good summary. Don't be shy about rules that don't work for your setup.
