### ISSUE TITLE
Modsec rule causes nginx cu spin up a lot of worker processes

### ISSUE THREAD

**Issue by davidbalazs** [SpiderLabs/owasp-modsecurity-crs#1649]
### Describe the bug

Hi there, we run Nginx in a Docker container as a sidecar in a pod in a Kubernetes cluster.
We have the ModSec module (version 3.0.3) enabled for Nginx.
In our Nginx configuration, we set the number of worker processes to be 16 (we have 16 cpu cores on our machines):
```
    worker_processes 16;
    events {
      worker_connections 1024;
    }
```

- With modsec **disabled**, it all works fine, we can see in the access logs that requests are processed fine, there are 16 worker processes running and the memory usage is not higher than 200-300MB.

- However, when the modsec is **enabled**, the initial number of worker processes in nginx is 16, but over a period of 12 hours, the number of worker processes increases whenever a given modsec rule is matched by an HTTP request (in our case it is ruleID: 920350).

The number of worker processes increases until the memory limit (2GB, set at a kubernetes level) is met (at that point, nginx started up to 500 worker processes!)

When it hits the memory limit, nginx stops handling requests (according to the access log, we cannot see any requests being handled anymore). Furthermore, the issue is causing the entire machine where the nginx container is running to crash.

**My question is**: is there something at the modsec level that causes nginx to spin up a lot more worker processes (around 500) than configured (16) when the modsec rule 920350 matches http requests? Could it be a resource leak?

### Steps to reproduce

Start nginx with modsec enabled and ensure that ruleID: 920350 is present.
Configure nginx to use maximum 16 worker processes (or a similar, fixed number)
Start multiple HTTP requests that match that given rule (ID: 920350) 

### Expected behaviour

Nginx will not spin up more than 16 worker processes in total.

### Actual behaviour

Over a period of 12 hours, nginx will spin up up to 500 worker processes if the given modsec rule matches requests, even when secrules_engine is set to "secrules_engine":"DetectionOnly"

### Additional context

Nginx version:
nginx version: nginx/1.15.4 built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) built with OpenSSL

**Comment by dune73** [comment]
Sorry for the inconvenience @davidbalazs. The way you describe this, it sounds a lot like a ModSecurity bug. Performance on libModSecurity3 is certainly a problem, but this is even more severe.

I do not see anything pointing to a problem with the rule set though, so I will close this bug report for CRS. But I suggest you turn to ModSecurity and open a bug report there.
