### ISSUE TITLE
[DOS protection]Why can't a request be made after 600 seconds, It is still shielded

### ISSUE THREAD

**Issue by sule01u** [SpiderLabs/owasp-modsecurity-crs#1652]
### [DOS protection]Why can't a request be made after 600 seconds, It is still shielded
SecAction \
 "id:900700,\
  phase:1,\
  nolog,\
  pass,\
  t:none,\
  setvar:'tx.dos_burst_time_slice=60',\
  setvar:'tx.dos_counter_threshold=100',\
  setvar:'tx.dos_block_timeout=600'"
owasp-modsecurity-crs/crs-setup.conf
owasp-modsecurity-crs/rules/REQUEST-912-DOS-PROTECTION.conf

### Steps to reproduce

201 consecutive requests were made, the first 200 normal requests were made
the 201th blocked
after 10 minutes
another request, still unable to request
after a day, still cannot be made

### Expected behaviour

The request should be made normally after 600s

### Actual behaviour

It's always shielded

### Additional context

owasp-modsecurity-crs v3.3

**Comment by airween** [comment]
Hi @BigTree975, thanks for the report - could you provide the details of your environment? Eg.: webserver version, ModSecurity version.

**Comment by BigTree975** [comment]
The image used by my virtual machine is CentOS-7-x86_64-Minimal-1810.iso
Modsecurity v3
nginx-1.15.12

**Comment by sule01u** [comment]
@airween 
我的虚拟机使用的映像是CentOS-7-x86_64-Minimal-1810.iso
Modsecurity v3
nginx-1.15.12

**Comment by airween** [comment]
Hi @BigTree975,

I'm sorry to say, but your ModSecurity version doesn't support the `expirevar` action, which is responsible for deleting a variable (in a collection, eg. an IP address). Without that, the pushed IP address stay in collection while you restart your engine.

Please check out the documentation:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#expirevar

_**Supported on libModSecurity**: TBI_

I close this issue, this isn't CRS bug.
