### ISSUE TITLE
merge conflict with git pull origin master

### ISSUE THREAD

**Issue by Steve8291** [SpiderLabs/owasp-modsecurity-crs#1653]
### Describe the bug

I keep getting merge conflicts even after cloning a new repo.

### Steps to reproduce
Clone the repo.
Try to pull master.
`git clone git@github.com:SpiderLabs/owasp-modsecurity-crs.git`
`cd owasp-modsecurity-crs`
`git pull origin master`

Lots of errors similar to:
> From github.com:SpiderLabs/owasp-modsecurity-crs
>  * branch            master     -> FETCH_HEAD

> Auto-merging util/rule-management/verify.rb

> CONFLICT (modify/delete): util/regression-tests/tests/modsecurity_crs_20_protocol_violations.tests deleted in HEAD and modified in 56cad3ac424d77a1f7b05a0758b7877d05b59fea. Version 56cad3ac424d77a1f7b05a0758b7877d05b59fea of util/regression-tests/tests/modsecurity_crs_20_protocol_violations.tests left in tree.

> CONFLICT (modify/delete): slr_rules/modsecurity_crs_46_slr_et_xss_attacks.conf deleted in HEAD and modified in 56cad3ac424d77a1f7b05a0758b7877d05b59fea. Version 56cad3ac424d77a1f7b05a0758b7877d05b59fea of slr_rules/modsecurity_crs_46_slr_et_xss_attacks.conf left in tree.
. . .
> Auto-merging README.md
> CONFLICT (content): Merge conflict in README.md
> Auto-merging CHANGES
> CONFLICT (content): Merge conflict in CHANGES
> Automatic merge failed; fix conflicts and then commit the result.

**Comment by fgsch** [comment]
master does not contain the latest changes.  You should be using the v3.3/dev branch instead, which is the default if you clone this repo.

Out of curiosity, why are you doing a `pull origin master` after cloning?
