### ISSUE TITLE
Proposal to add 'tag' metadata to all CRS detection rules

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#167]
The CRS rules can be a bit heavy-handed, so I maintain some exceptions for particular APIs. Usually, I use `ctl:ruleRemoveTargetByTag` to suppress checking some targets. Using tags is much more effective than hardcoding long and potentially changing rule ids in `ctl:ruleRemoveById`.

However, it appears some CRS entries do not have a tag associated with them. An example is rule `950018` (Universal PDF XSS URL Detected) which has caused some false positives for me.

The presence of tag-less rules complicates writing exceptions. In ModSecurity, a rule without a tag is immune to `ctl:ruleRemoveTargetByTag` (which is a good feature). Therefore, we can only modify the rule's behavior by hacking the CRS or hardcoding its id. Both of these workarounds are less scalable.

In the absence of categorization, even a placeholder tag like `OWASP_CRS/OTHER` would be very helpful.

**Comment by lifeforms** [comment]
Thanks :) I've verified that in CRS3 all primary rules have a tag now, so this can be closed!

**Comment by dune73** [comment]
Good one. It's time I start to work with `ctl:ruleRemoveTargetByTag` as well.
