### ISSUE TITLE
DOS protection is invalid

### ISSUE THREAD

**Issue by sule01u** [SpiderLabs/owasp-modsecurity-crs#1723]
DOS protection is invalid, The same IP can be an unlimited number of requests, any other protection can work normally.

I use fstack + nginx-1.16.0 + mod security v3 + owasp-modsecurity-crs v3 ,has anyone had the same problem

Linux kernel mode can be protected normally

**Comment by BigTree975** [comment]
- crs-setup.conf
![屏幕快照 2020-03-17 20 34 48](https://user-images.githubusercontent.com/33783361/76856712-c7813580-688e-11ea-8b8a-e6c7e218e982.png)



- Fifth request
dpdk-fstack
![屏幕快照 2020-03-17 20 31 59](https://user-images.githubusercontent.com/33783361/76856569-7c672280-688e-11ea-9285-2f1c5621f328.png)

linux-kernel
![屏幕快照 2020-03-17 20 32 19](https://user-images.githubusercontent.com/33783361/76856613-9274e300-688e-11ea-87b3-fada048a7a90.png)
