### ISSUE TITLE
Block QQGameHall in UA

### ISSUE THREAD

**Issue by theMiddleBlue** [SpiderLabs/owasp-modsecurity-crs#1730]
![image](https://user-images.githubusercontent.com/4454961/78125397-4474e900-7411-11ea-89e5-e6b084fd7649.png)

we should add `QQGameHall` to 913100 (scanners-user-agents.data). Unfortunately that's not a "scanner" but we have not a different category yet... What do you think about it?

(thanks Daniel Stenberg @bagder)

**Comment by bagder** [comment]
I've blocked "QQGameHall" from the curl site from where the above screenshot comes from. That's the full user-agent string this thing uses. Still weird since it is supposedly the name of a game launcher...

**Comment by dune73** [comment]
I'd be happy to merge anytime, @theMiddleBlue.

**Comment by theMiddleBlue** [comment]
thanks @dune73 and @bagder, I'm going to open a PR.

**Comment by dune73** [comment]
Closing this in favor of PR #1731, which was been merged.
