### ISSUE TITLE
Rule id 950107 and IIS url encoding

### ISSUE THREAD

**Issue by tailianos** [SpiderLabs/owasp-modsecurity-crs#180]
On version 2.2.9 the rule id 950107 creates false positives due to different handling on the IIS url encoding by the core ruleset and modsec engine.
The regex REQUEST_URI "\%((?!$|\W)|[0-9a-fA-F]{2}|u[0-9a-fA-F]{4})"   identifies a substring containing IIS url encoding (eg. %u03b7) nevertheless the operator "validateUrlEncoding" can only handle url encodings "%FF". As a result in a IIS url encoding exists the rule will always trigger.
The issue occurs both on 2.7.7 modsec version and on the new one 2.8.0

**Comment by dune73** [comment]
@zimmerle : Is this a ModSecurity issue and we can close it for CRS?

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
