### ISSUE TITLE
ModSecurity: Found another rule with the same id

### ISSUE THREAD

**Issue by Roger-Man** [SpiderLabs/owasp-modsecurity-crs#183]
Hi,

Current CRS-master version(2.2.9) has multiple rules with the same id.

The problem is that same rules(logically with same ids) are duplicated In the following files:
\slr_rules\modsecurity_crs_46_slr_et_joomla_attacks.conf
\slr_rules\modsecurity_crs_46_slr_et_lfi_attacks.conf
\slr_rules\modsecurity_crs_46_slr_et_rfi_attacks.conf

These rules are starting from line 212 of \slr_rules\modsecurity_crs_46_slr_et_lfi_attacks.conf id:2008822 and goes on for the rest of the rules in the file.

As I mentioned these are same rules duplicated over multiple files and logically they can have same id. But the new mechanism of the modsecurity won't allow activating those files together.

P.S.
This problem forms a chain in the following files:

these files conflict together:
\slr_rules\modsecurity_crs_46_slr_et_phpbb_attacks.conf
\slr_rules\modsecurity_crs_46_slr_et_sqli_attacks.conf

and these files together::
\slr_rules\modsecurity_crs_46_slr_et_sqli_attacks.conf
\slr_rules\modsecurity_crs_46_slr_et_wordpress_attacks.conf

and also these files together::
\slr_rules\modsecurity_crs_46_slr_et_wordpress_attacks.conf
\slr_rules\modsecurity_crs_46_slr_et_xss_attacks.conf

--regards

**Comment by Oneiroi** [comment]
Still this seems to be an issue, whilst I can see @rcbarnett comment about "run one or the other" being somewhat valid, given today looking at the latests ruleset I can see this would lead to exclusion of rules.

Taking wordpress as an example, were I to disable the conf file and run the lfi && rfi rules, then rule **2004011** would not be enabled "ET WEB_SPECIFIC_APPS WordPress SQL Injection Attempt"

So I took to looking at this a little more with some frankly awfully rough bash script.

Taking lfi rules as a set the following rules would be excluded if I were to disable lfi and run only the application specific configurations

```
/usr/share/modsecurity-crs/activated_rules# grep '# (' ./modsecurity_crs_46_slr_et_lfi_attacks.conf | awk '{print $2}' | while read id; do grep $id *.conf; done | awk '{print $2}' | sort | uniq -c | sort -nk1
      1 (2008652)
      1 (2009018)
      1 (2010803)
      1 (2011572)
      1 (2011573)
      1 (2011574)
      1 (2011936)
      1 (2012012)
      1 (2012354)
      1 (2012947)
... ids with count > 2 truncated

```

Thus it does not appear (at least from my very rough checks) that any one of the sets is to be considered the "master set" as each has unique rules not present in the other.
