### ISSUE TITLE
False negative from Xssed.com (libinjection XSS)

### ISSUE THREAD

**Issue by jzy2000** [SpiderLabs/owasp-modsecurity-crs#187]
Tested libinjection XSS lib using payload from Xssed.com, 4700 in link below were missed by libinjection, please review.
https://www.dropbox.com/s/8s0wnbp81ulek5d/get-4xxxx-send-ready_403%282%29.txt

**Comment by dstelter** [comment]
I am interested in this experiment. Unfortunately the dropbox link is expired/deleted. Could you reupload the file?

Is there a more elegant way to get the Xssed.com payload besides crawling their entire website one-by-one?

**Comment by dune73** [comment]
I am pretty sure, there are false negatives in libinjection. However, that would constitute an upstream problem and bugs should probably be filed [there](https://github.com/client9/libinjection).

It is kind of OK to submit false negatives for libinjection here and we can try and sort it out with @client9, but then we need concrete examples. Unfortunately, the link posted by the original author was long gone before I entered the project. 

So I am closing this for now.
