### ISSUE TITLE
"Bad robots" rule (id 990012) blocks all Requests from new Gmail Image Proxy

### ISSUE THREAD

**Issue by spl83** [SpiderLabs/owasp-modsecurity-crs#188]
Since Dezember 2013 Google announced that Gmail will load external images using a proxy. -> http://googlesystem.blogspot.de/2013/12/more-about-gmails-proxy.html

The Google Proxy appand "(via ggpht.com GoogleImageProxy)" to the User-Agent header: 

--2f77756a-B--
GET /es/v1120/img/email/unterschrift_gk_kmu.gif HTTP/1.1
User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9.0.7) Gecko/2009021910 Firefox/3.0.7 (via ggpht.com GoogleImageProxy)

So, every Request from the GoogleImage Proxy get be blocked:

Message: Access denied with code 403 (phase 2). Matched phrase "via" at REQUEST_HEADERS:User-Agent. [file "/app/bdirekt/home/komfort/config/apache/mod_security/core_ruleset-2.2.7-17/base_rules/modsecurity_crs_35_bad_robots.conf"] [line "
27"] [id "990012"] [rev "2"] [msg "Rogue web site crawler"] [data "via"] [severity "WARNING"] [ver "OWASP_CRS/2.2.7"] [maturity "9"] [accuracy "9"] [tag "OWASP_CRS/AUTOMATION/MALICIOUS"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [ta
g "PCI/6.5.10"]

So, you possibly need to remove the tag "via" from modsecurity_35_bad_robots.data

Kindly Regards
Sascha Platte

**Comment by dune73** [comment]
This false positive is gone with Core Rule Set 3.0. Please update.

Closing this.
