### ISSUE TITLE
new ext for modsecurity_crs_10_ignore_static

### ISSUE THREAD

**Issue by quenenni** [SpiderLabs/owasp-modsecurity-crs#190]
Some common extensions I think we can add to this file:
- Images: tiff
- Documents: ods / fods / odt / fodt / odp / fodp / odg / docx / xlsx / rtf / csv / ppt / pptx / pps / ppsx
- Media files: ogg / ogm / mp4 / flac / ape / wav / mkv

**Comment by dune73** [comment]
The treatment of static files has changed for Core Rule Set 3.0. The optional configuration for static files is now prepared in crs-setup.conf in the 900260, which is commented out by default.

Also, the only place where these static files play a role is in the DoS protection in rule 912150.

If you want to create a pull request - after all those years - then please go ahead.

P.S. Sorry for taking so long. I only joined the project long after your submissions.

**Comment by fzipi** [comment]
@dune73 Has any sense to have this open? Isn't already documented so we can close this one?

**Comment by fzipi** [comment]
I think we can close this one. Not @quenenni or @superkully have commented here in a prudential period of time.
