### ISSUE TITLE
False posive SQL-Injection with windows guids

### ISSUE THREAD

**Issue by m1stegmann** [SpiderLabs/owasp-modsecurity-crs#196]
Rule id 981173 matches normal windows guids like 8543DA3F-A72E-45DD-96C5-16954D05D375
Guids are often use as parameters.

**Comment by csanders-git** [comment]
The rule you mentioned is infamous for false positives. It has been removed in version 3.0.0 (dev branch). It was replaced with other SQL protections specifically @detectSQLi.  I have confirmed that windows GUIDs do not trigger on the 3.0.0 chain (http://www.modsecurity.org/crs-demo.html?test=8543DA3F-A72E-45DD-96C5-16954D05D375). Hopefully this solves your issue. Sorry for the long delay. Feel free to reopen if you think there is an issue.
