### ISSUE TITLE
False positive SQL-Injection

### ISSUE THREAD

**Issue by m1stegmann** [SpiderLabs/owasp-modsecurity-crs#197]
rule id 981247 matches normal Urls like
/login/?ReturnUrl=%2faltersvorsorge%2f
because of „alter“ as subscring oft he parameter „ReturnUrl“

**Comment by shrv** [comment]
Yes, there are flashing, but in my opinion, it is better to have a false alarm than to miss the alter table.

create an exclusion rule, something like

SecRule REQUEST_LINE "rx (?i: ReturnUrl =%2faltersvorsorge)" "phase: 2, t:none, pass, nolog, id: 'xxxxxx', ctl: ruleRemoveById = 981247"

**Comment by dune73** [comment]
Confirm: CRS3 still has this false positive in the default installation (after the rule renumbering, the rule id is now 942360).

Minimal request triggering the rule:

```
curl "localhost/index.html?ReturnUrl=%2falter"
```

We really try to avoid false positives for the default installation (Paranoia Level 1), however, this might be hard here. Tagging it for consideration.

**Comment by lifeforms** [comment]
This regexp is quite funky, but as a quick win it seems we can safely add `\b` word separators to the keywords such as `alter`. This would not solve the minimal request but would solve the problem reported by OP (and probably many others in future).

**Comment by dune73** [comment]
Let's do that then for the next 3.0 release.

**Comment by lifeforms** [comment]
A fix for this problem has been proposed in #739 and barring any problems it will be included in 3.0.1 release. Better late than never, right? ;) Thanks for submitting the problem!
