### ISSUE TITLE
quotes in uploaded filenames

### ISSUE THREAD

**Issue by quenenni** [SpiderLabs/owasp-modsecurity-crs#199]
Hello,

It appears modsec doesn't like filenames with single quotes in them.

I have that error:
```
[Mon Oct 20 16:00:48 2014] [error] [client xxx.xxx.xxx.xxx] ModSecurity: Access denied with code 44 (phase 2). Match of "eq 0" against "MULTIPART_STRICT_ERROR" required. [file "/etc/modsecurity/modsecurity.conf"] [line "81"] [msg "Multipart request body failed strict validation: PE 0, BQ 0, BW 0, DB 0, DA 0, HF 0, LF 0, SM , IQ 1, IQ 0, IH 0, IH 0"] [hostname "www.xxx.be"] [uri "/ecrire/"] [unique_id "VEUVf09jyzIAAAbkFlcAAABI"]
```

The 'IQ 1'  is the "%{MULTIPART_INVALID_QUOTING}" var that was set to 1 and thus triggered the MULTIPART_STRICT_ERROR rule.

Unfortunately, single quotes  are often used in french.

After digging on the net, I noticed people complain about false positives with this rule (MULTIPART_STRICT_ERROR) and the suggestions are to not block anymore but just log these transactions.

I would like to just remove the "MULTIPART_INVALID_QUOTING" test (that increments the "MULTIPART_STRICT_ERROR") in order to keep the other tests active.

But I couldn't find where these tests are (/etc/modsecurity  /usr/share/modsecurity-crs/) or how I could update the rule to achieve what I want... or even if it's something that can be done.

Any idea how I can do that?
Thanks.

Another thing:
The rule "SecRule MULTIPART_STRICT_ERROR "!@eq 0"  can be found in 2 separate files and I have the impression it's not on purpose:

1 - /etc/modsecurity/modsecurity.conf (line 67)
```
SecRule MULTIPART_STRICT_ERROR "!@eq 0" \
"phase:2,t:none,log,deny,status:44,msg:'Multipart request body \
failed strict validation: \
PE %{REQBODY_PROCESSOR_ERROR}, \
BQ %{MULTIPART_BOUNDARY_QUOTED}, \
BW %{MULTIPART_BOUNDARY_WHITESPACE}, \
DB %{MULTIPART_DATA_BEFORE}, \
DA %{MULTIPART_DATA_AFTER}, \
HF %{MULTIPART_HEADER_FOLDING}, \
LF %{MULTIPART_LF_LINE}, \
SM %{MULTIPART_SEMICOLON_MISSING}, \
IQ %{MULTIPART_INVALID_QUOTING}, \
IQ %{MULTIPART_INVALID_PART}, \
IH %{MULTIPART_INVALID_HEADER_FOLDING}, \
IH %{MULTIPART_FILE_LIMIT_EXCEEDED}'"
```
2 - /usr/share/modsecurity-crs/base_rules/modsecurity_crs_20_protocol_violations.conf (line 106)
```
SecRule MULTIPART_STRICT_ERROR "!@eq 0" \
        "phase:2,t:none,block,msg:'Multipart request body failed strict validation: \
PE %{REQBODY_PROCESSOR_ERROR}, \
BQ %{MULTIPART_BOUNDARY_QUOTED}, \
BW %{MULTIPART_BOUNDARY_WHITESPACE}, \
DB %{MULTIPART_DATA_BEFORE}, \
DA %{MULTIPART_DATA_AFTER}, \
HF %{MULTIPART_HEADER_FOLDING}, \
LF %{MULTIPART_LF_LINE}, \
SM %{MULTIPART_SEMICOLON_MISSING}, \
IQ %{MULTIPART_INVALID_QUOTING}, \
IH %{MULTIPART_INVALID_HEADER_FOLDING}, \
IH %{MULTIPART_FILE_LIMIT_EXCEEDED}',id:'960914',severity:2,setvar:'tx.msg=%{rule.msg}',setvar:'tx.id=%{rule.id}',tag:'RULE_MATURITY/7',tag:'RULE_ACCURACY/8',tag:'https://www.owasp.org/index.php/ModSecurity_CRS_RuleID-%{tx.id}',setvar:tx.anomaly_score=+%{tx.critical_anomaly_score},setvar:tx.protocol_violation_score=+%{tx.critical_anomaly_score},setvar:tx.%{rule.id}-PROTOCOL_VIOLATION/INVALID_REQ-%{matched_var_name}=%{matched_var}"
```

The n°1 is the one always triggered. I'm not sure the n°2 is ever triggered afaik.
You can notice few differences between the two. The n°1 has no id and throw a status 44, and n°2 doesn't have the "MULTIPART_INVALID_PART".

As I have a Debian Stable server, I don't have the latest versions (modsec & rules), so maybe that's already fixed. Sorry if it's the case.

libapache2-modsecurity                        2.6.6-6+deb7u2 
modsecurity-crs                               2.2.5-2

**Comment by quenenni** [comment]
New server, libapache2-mod-security2 v2.8.0-2~bpo70+1, latest rules via git, and still that same problem.
It happens often to upload files with a single quote in the name. That's normal in french.

I can modify the rule in modsecurity.conf to have what I need (by re-writing the rule and removing the ' in the test), but I can't do anything about MULTIPART_STRICT_ERROR tested in modsecurity_crs_20_protocol_violations.conf because it's incremented outside the rules.

Is there any way I can remove the check on the ' in the filename.

Thanks.

**Comment by dune73** [comment]
@quenenni: thanks for reporting this.

Yes, French speakers are in a bad situation. I agree that single quotes in filenames can not be avoided if you have non-tech-savy users, so you run into false positives.

Still, this rule makes a lot of sense. Coming back to your 2014 (sorry for not responding), this is one of the few rules that come with the ModSecurity package as recommended rule. And it is a key rule of the ModSecurity Core Rules (this project here).

Your fix is not working. MULTIPART_STRICT_ERROR "@gt 1" will never match. It's a different way of disabling the rule.

What you should instead is: 
- Introduce an additional security barrier to make sure you can trust the uploaded file (if possible). I would probably check for the existence of a session cookie or something. 
- Check the various flags in a chained rule with the exception of %{MULTIPART_INVALID_QUOTING}. If they are all 0, then you disable rule 960914.

Something along the following:
```
SecRule MULTIPART_BOUNDARY_QUOTED "@eq 0" "id:...,phase:2"
  SecRule MULTIPART_BOUNDARY_WHITESPACE "@eq 0" "chain"
  SecRule MULTIPART_DATA_BEFORE "@eq 0" "chain"
   ...
SecRule MULTIPART_FILE_LIMIT_EXCEEDED "@eq 0" ,"ctl:ruleRemoveById=960914"
```
I have not tested this, but I think this is a fairly safe way to work around your problem. With the weakness that you open yourself to evasion attacks via quotes in filenames.

**Comment by quenenni** [comment]
Thanks a lot for your help and explanation @dune73 .

I'll check into your solution.

**Comment by dune73** [comment]
I am 100% with you: MULTIPART_STRICT_ERROR is very painful if you do hosting as it tends to attract false positives like yours.

Please let us know if it worked.

As a sidenote: If you struggle with False Positives (and who does not), it may be the time to try out the dev tree 3.0.0-rc1. It is in a state that works nicely in production now and > 90% of FPs are gone. Really.

**Comment by quenenni** [comment]
Your solution works nicely.. Much appreciated.

I put the complete rule in case someone else need it too.

I kept the first one (id: 70000 that recreate the id:960000 and remove the test on the quote)**
I removed the second one (id:70001)
I created a new one based on your input:
```
SecRule MULTIPART_BOUNDARY_QUOTED               "@eq 0"         "id:70001,phase:2,chain,pass,ctl:ruleRemoveById=960914"
  SecRule MULTIPART_BOUNDARY_WHITESPACE         "@eq 0"         "chain"
  SecRule MULTIPART_DATA_BEFORE                 "@eq 0"         "chain"
  SecRule MULTIPART_DATA_AFTER                  "@eq 0"         "chain"
  SecRule MULTIPART_HEADER_FOLDING              "@eq 0"         "chain"
  SecRule MULTIPART_LF_LINE                     "@eq 0"         "chain"
  SecRule MULTIPART_INVALID_QUOTING             "@eq 1"         "chain"
  SecRule MULTIPART_INVALID_HEADER_FOLDING      "@eq 0"         "chain"
  SecRule MULTIPART_FILE_LIMIT_EXCEEDED         "@eq 0"
```

One strange thing though.
I had to remove the line:
```
SecRule MULTIPART_SEMICOLON_MISSING           "@eq 0"         "chain"
```
from the rule. If not, I have this error on apachectl configtest:
```
Error creating rule: Unknown variable: MULTIPART_SEMICOLON_MISSING
```
Strange because "MULTIPART_SEMICOLON_MISSING" is part of the rule 960914

Also, it is not compulsory to put all these line.
As I only need to test the quote in the filename, this simpler rule is good enough (the other variables are still test for the value 0 and the request blocked if not):
```
SecRule MULTIPART_INVALID_QUOTING               "@eq 1"         "id:70001,phase:2,pass,ctl:ruleRemoveById=960914"
```

-------------------------

** I tried to update the rule id:960000 instead of recreating it but failed to do so:

1. SecRuleUpdateTargetById 960000 !FILES_NAMES "'"
2. SecRuleUpdateTargetById 960000 !FILES_NAMES:'
3. SecRuleUpdateTargetById 960000 !FILES_NAMES:"'"
4. SecRuleUpdateTargetById 960000 !FILES_NAMES:\'
5. SecRuleUpdateTargetById 960000 FILES_NAMES|FILES "[\";=]"
6. SecRuleUpdateTargetById 960000 FILES_NAMES|FILES:"[\";=]"

And the errors are:
1. Error to update target - [] is not valid target
2. ModSecurity: Error parsing rule targets to append variable
3. ModSecurity: Error parsing rule targets to append variable
4. ModSecurity: Error parsing rule targets to append variable
5. Error to update target - [\xc0^\xf9]\xf6\x02] is not valid target (the part within the [ ] changes on every configtest)
6. Error to update target - [FILES_NAMES|FILES] is not valid target

Any hint on how to achieve this?

**Comment by quenenni** [comment]
> As a sidenote: If you struggle with False Positives (and who does not), it may be the time to try out the dev tree 3.0.0-rc1. It is in a state that works nicely in production now and > 90% of FPs are gone. Really.

Nice. I didn't see it.
I'll give a go. 
Thanks for the info

**Comment by dune73** [comment]
It's `MULTIPART_MISSING_SEMICOLON`.

Your rule update to 960000 looks interesting. Not sure this can work, but be sure to try out regex identifiers. What you try is fixed names and they don't match and give you the listed format errors.

**Comment by quenenni** [comment]
Hoo Yes.. Thanks. It comes from our old version.
The reverse name comes from the Debian package in Wheezy (libapache2-modsecurity (2.6.6-6+deb7u2)).

I checked, in Debian Jessie or Wheezy backports, the name is correct (libapache2-modsecurity (2.8.0-2~bpo70+1))

In Wheezy, the file /etc/modsecurity/modsecurity.conf-recommended contains:
```
SecRule MULTIPART_STRICT_ERROR "!@eq 0" \
"phase:2,t:none,log,deny,status:44,msg:'Multipart request body \
failed strict validation: \
PE %{REQBODY_PROCESSOR_ERROR}, \
BQ %{MULTIPART_BOUNDARY_QUOTED}, \
BW %{MULTIPART_BOUNDARY_WHITESPACE}, \
DB %{MULTIPART_DATA_BEFORE}, \
DA %{MULTIPART_DATA_AFTER}, \
HF %{MULTIPART_HEADER_FOLDING}, \
LF %{MULTIPART_LF_LINE}, \
SM %{MULTIPART_SEMICOLON_MISSING}, \
IQ %{MULTIPART_INVALID_QUOTING}, \
IQ %{MULTIPART_INVALID_PART}, \
IH %{MULTIPART_INVALID_HEADER_FOLDING}, \
IH %{MULTIPART_FILE_LIMIT_EXCEEDED}'"
```

**Comment by quenenni** [comment]
> Your rule update to 960000 looks interesting. Not sure this can work, but be sure to try out regex identifiers. What you try is fixed names and they don't match and give you the listed format errors.

Sorry, but I not sure what you mean by "regex identifiers"?
Do you have an example.

If not, it's not so important. The way I did first is working just fine.
I just wanted to test these updating rules (like SecRuleUpdateTargetById). I'm still bad when trying to implement them.

**Comment by Cartman34** [comment]
So, for now, what is the best solution ?
I need to allow single quotes in file names, our apps are protected against bad file names, as we just ignore it. (or warn me about security breach pls)

**Comment by dune73** [comment]
We no longe rhave this rule in Core Rule Set 3.0. But ModSecurity still advertises the rule as a recommended rule. This makes sense, but single quotes in file names won't go away. So if you want to allow them, you should either modify the recommended rule, or write a rule exclusion. See the CRS documentation for guidance.

**Comment by Cartman34** [comment]
So, should I disable the rule 200003 to remove the ModSecurity recommended rule ? Everything will be ok and the system will stay protected by other rules ?
I tried to get more documentation but ModSecurity and CRS things are making me crazy, I am unable to find useful informations, all of these is only made for experts.

**Comment by dune73** [comment]
No, 200003 is a substantial part of the security. Removing it harms the security. There are no other rules that cover this aspect of the payloads. It would be better to write client-side code (javascript) that would remove the single quote form the filename before the submission.

Are you saying that my tutorials at https://www.netnea.com/cms/apache-tutorials/ are really not comprehensible at all? That's a bit of a blow as I have spent weeks writing them...

**Comment by Cartman34** [comment]
It seems we cant rename a file before the browser send it using Javascript, or maybe by using AJAX request but it requires to recode the overall upload process.

I spent years developing and publishing Open Source applications that I am the only one to use, so... :D
I think you made a great job, I hope you didn't do it alone. But I don't want to be an expert of CMS, I am using about 7 different technologies to ensure the security of this server, I try to not spend several days* to read dozens of page of documentation (there is other documentation thant your tutorials on this topic) and to fix one rule in one of these securities, this is why I request help..
*I won't be paid for it.

**Comment by dune73** [comment]
I had hoped renaming was possible. That sucks. But I guess what you can do is catch it before the upload and warn users they should rename the file?

Seriously, I see your problem. I do not like the way ModSecurity handles this single quote thing. But there is little that we can do to help you. It is an unsolved problem with languages that use single quotes in filenames. Ignoring these rules might be the best bet from a usability standpoint. But it really lowers your defenses. Sorry that there is no real solution right now.
