### ISSUE TITLE
PARANOID_MODE used/documented inconsistently

### ISSUE THREAD

**Issue by ronaldploeger** [SpiderLabs/owasp-modsecurity-crs#201]
The comments in "modsecurity_crs_42_tight_security.conf" mention to enable "PARANOID_MODE" to activate the containing rules but one containing rule does not even check for "PARANOID_MODE" therefore I guess the comment is obsolete

There is one rule in "modsecurity_crs_20_protocol_violations.conf" which does check if "TX:PARANOID_MODE" is set but there is no SecAction in "modsecurity_crs_10_setup.conf.example" to which can be uncommented to set "PARANOID_MODE".

**Comment by zinoe** [comment]
Verified this. As we are currently working on a new paranoia mode (https://www.owasp.org/index.php/OWASP_ModSec_CRS_Paranoia_Mode) for v3.0.0-rc1 and 2.2.9 seems not to provide any paranoia functionality, I guess this rule comment can be removed.

**Comment by dune73** [comment]
Agreed. It's obsolete in 3.0 (and was hardly ever active in 2.2.X)
