### ISSUE TITLE
Rule 958230 increases tx.anomaly_score too early

### ISSUE THREAD

**Issue by ronaldploeger** [SpiderLabs/owasp-modsecurity-crs#202]
The OWASP Core Ruleset file „modsecurity_crs_20_protocol_violations.conf“ contains the following rule:

    SecRule REQUEST_HEADERS:Range|REQUEST_HEADERS:Request-Range "(\d+)\-(\d+)\," "chain,capture,phase:2,rev:'2',ver:'OWASP_CRS/2.2.9',maturity:'6',accuracy:'8',t:none,block,msg:'Range: Invalid Last Byte Value.',logdata:'%{matched_var}',severity:'4',id:'958230',tag:'OWASP_CRS/PROTOCOL_VIOLATION/INVALID_HREQ',setvar:'tx.msg=%{rule.msg}',setvar:tx.anomaly_score=+%{tx.warning_anomaly_score},setvar:tx.%{rule.id}-OWASP_CRS/PROTOCOL_VIOLATION/INVALID_HREQ-%{matched_var_name}=%{matched_var}"
        SecRule TX:2 "!@ge %{tx.1}"

When you send a request with a „Range“-HTTP-Header with the value

    bytes=642560-643071, 643072-643583, 643584-644095, 644096-644607, 644608-645119, 645120-645631, 645632-646143, 646144-646655, 646656-647167, 647168-647679, 647680-648191, 648192-648703, 648704-649215, 649216-649727, 649728-650239, 650240-650751, 650752-651263, 651264-651775, 651776-652287, 652288-652799, 652800-653311, 653312-653823, 653824-654335, 654336-654847, 654848-655359, 655360-655871, 655872-656383, 656384-656895, 656896-657407, 657408-657919, 657920-658431, 658432-658943, 658944-659455, 659456-659967, 659968-660479, 660480-660991, 660992-661503, 661504-662015, 662016-662527, 662528-663039, 663040-663551, 663552-664063, 664064-664575, 664576-665087, 665088-665599, 665600-666111, 666112-666623, 666624-667135, 667136-667647, 667648-668159, 668160-668671, 668672-669183, 669184-669695, 669696-670207, 670208-670719, 670720-671231, 671232-671743

the first SecRule of the chained rule will match and increase the anomaly score even though the second SecRule of the chained rule does not match. The anomaly score should be increased in the second SecRule.

**Comment by rcbarnett** [comment]
Fixed here: https://github.com/SpiderLabs/owasp-modsecurity-crs/commit/302c39438d286cfbf6978b1e37a610bda9ef4ffa

**Comment by mailtoyogeshpatel** [comment]
In our scenario we could not determine which document has a problem and blocked by mod security.
I can only say that we are opening pdf file from browser.I am not sure which type of documents has such bytes range which violets the rule.
How to identify such range and what i need to change in rule to allow more range.
