### ISSUE TITLE
SQL False Negative - filter bypass

### ISSUE THREAD

**Issue by tim--c** [SpiderLabs/owasp-modsecurity-crs#206]
```
Version: Core ModSecurity Rule Set ver.2.2.9
Configuration: default configuration, SecRuleEngine On, all base_rules enabled
```

```
OS: Debian
PHP: 5.5.6-1
MySQL: 5.5.33-1
```

The following strings can be used to bypass filters in SQL queries (such as on unsecured login pages):
```
foo' or true #
foo' or false #
```
This doesn't seem like a major issue, but you do filter out simpler stuff like `' #` (interestingly, `foo' or 123 #` is also filtered), so I thought I report it (I tried it a while ago via mail, but did not get a response).

**Comment by rcbarnett** [comment]
Thanks for reporting this issue.  Looks like these SQLi payloads are caught by the new @detectSQL operator rules in CRS v3.0.0 -
https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0.0-dev/rules/REQUEST-42-APPLICATION-ATTACK-SQLI.conf#L27-53

Here is an online demo showing it catch your example payloads -
http://www.modsecurity.org/crs-demo.html?test=foo%27+or+true+%23

All Matched Rules Shown Below:
981261	SQL Injection Attack Detected via LibInjection
 	Matched s&1c at ARGS:test
981261	SQL Injection Attack Detected via LibInjection
 	Matched s&1 at ARGS:test

**Comment by csanders-git** [comment]
Closing issue due to available fix
