### ISSUE TITLE
INSTALL instructions up to date ? 

### ISSUE THREAD

**Issue by AC90** [SpiderLabs/owasp-modsecurity-crs#215]
(Platform : NGINX on Linux
ModSecurity : v2.9.0)

Trying to install CRS with modsecurity and I'm having trouble following the INSTALL instructions. Specifically, can't find : 
 1) - Reference to 'SecRuleEngine setting (On by default)' - don't see this in the modsecurity_crs_10.setup.conf file.
 2) - The 'SecDefaultAction' directive in modsecurity_crs_10.setup.conf file. 
 3) - Any reference to PARANOID_MODE variable

Am I missing / misunderstanding something ? Are there any nginx specific install notes somewhere pls ?

Tks Alex

**Comment by csanders-git** [comment]
Where did you find the instructions. We highly recommend you use the 3.0.0-dev branch. The settings you are looking for are in the main modsecurity config file (not included as described in the comments )

#
# -- [[ Recommended Base Configuration ]] ------------------------------------------------- 
#
# The configuration directives/settings in this file are used to control
# the OWASP ModSecurity CRS. These settings do **NOT** configure the main
# ModSecurity settings such as:
# 
# - SecRuleEngine
# - SecRequestBodyAccess
# - SecAuditEngine
# - SecDebugLog
#
# You should use the modsecurity.conf-recommended file that comes with the
# ModSecurity source code archive.
#
# Ref: https://github.com/SpiderLabs/ModSecurity/blob/master/modsecurity.conf-recommended 
#

There is no more paranoid mode in the 3.0.0 branch. 

Hopefully this helps.
