### ISSUE TITLE
Using two separators on one web page

### ISSUE THREAD

**Issue by shrv** [SpiderLabs/owasp-modsecurity-crs#221]
Good day.

Do I understand correctly that parse URL and request body occurs even before beginning to apply the rules that were connected.

And I can not modsec use Lua to modify the URL string and replace it on the same separator as in the body of the request?

Maybe it makes sense to consider the option of entering two SesArgumentseparator - for the URL and the body.
Understand a rare case, but this also happens

**Comment by csanders-git** [comment]
Yes your understanding seems correct. The request is split up into different collections. Those collections are not mutable.

**Comment by shrv** [comment]
Thank you, then I will think about replacing the separator to send the request to the WAF
