### ISSUE TITLE
v3.0.0-dev  rule 981243

### ISSUE THREAD

**Issue by shrv** [SpiderLabs/owasp-modsecurity-crs#226]
Good afternoon.
Please help.
Rule 981243 is a false-positive.
For example, take your search query - Положение по бухгалтерскому учету "Расходы организации" (ПБУ/99),
Match in rule It is this part of the request "Расходы организации" (ПБУ/99

I assume that the problem is the same as described in issues 708
https://github.com/SpiderLabs/ModSecurity/issues/708

My attempts to modify the rules led to that rule simply ceased to work at all. :)

Can help with modification?
Thank you.

**Comment by xformerfhs** [comment]
Same here. Any argument that contains Unicode characters is blocked (e.g. "Vereinbarung+nach+§11+BDSG.pdf", where it balks about "\xa711").

**Comment by xformerfhs** [comment]
Sorry, not "Unicode characters" but any character with an encoding greater or equal \x80.

**Comment by csanders-git** [comment]
So what are we thinking about as a fix for these types of issues?

**Comment by dune73** [comment]
I have recreated the request as:

```
curl localhost -d 'x=Положение по бухгалтерскому учету "Расходы организации" (ПБУ/99)'
```

This no longer triggers an alert in the default installation of the Core Rule Set 3.0. When raising the Paranoia Level to 2, I get an alert on 942370. However, that might have to do with the use of the special character in the payload. Furthermore, we expect users to be able to handle casual false positives themselves. If you need information, then please check out the [tutorial here](https://www.netnea.com/cms/apache-tutorial-8_handling-false-positives-modsecurity-core-rule-set/).

Also the subsequent report added here by @xformerfhs is solved in the CRS3 default installation.

I am closing this now.
