### ISSUE TITLE
rule 981176 Alert and Block based on Anomaly Scores

### ISSUE THREAD

**Issue by shrv** [SpiderLabs/owasp-modsecurity-crs#227]
good afternoon.
I have a question logging chain rules.
For example, the rules 981176

SecRule TX:ANOMALY_SCORE "@gt 0" \
    "chain,phase:2,id:'981176',t:none,deny,status:412,log,msg:'Inbound Anomaly Score Exceeded (Total Score: %{TX.ANOMALY_SCORE}, SQLi=%{TX.SQL_INJECTION_SCORE}, XSS=%{TX.XSS_SCORE}): Last Matched Message: %{tx.msg}',logdata:'Last Matched Data: %{matched_var}',setvar:tx.inbound_tx_msg=%{tx.msg},setvar:tx.inbound_anomaly_score=%{tx.anomaly_score}"
        SecRule TX:ANOMALY_SCORE "@ge %{tx.inbound_anomaly_score_level}" chain
                SecRule TX:ANOMALY_SCORE_BLOCKING "@streq on" chain
                        SecRule TX:/^\d+\-/ "(.*)"
 

I understand correctly that the entry in the log occurs when a rule has worked in the chain and it is a phrase log?
i.e. rules for 981,176 log record should be worked when the first rule in the chain (TX:ANOMALY_SCORE "@gt 0")?
I understand you correctly?

Now I see the logs that record occurs only when triggered the second rule in the chain when it reaches the threshold for blocking(TX:ANOMALY_SCORE "@ge %{tx.inbound_anomaly_score_level}"). 
Here is an example of the log (the threshold is not reached).

--e7b82951-A--
[22/Apr/2015:14:02:03 +0300] VTd-q8JpgwQAATJQ8UYAAACN xx.xx.xx.xx 51293 127.0.0.1 80
--e7b82951-B--
HEAD /cons/rtfcache/xxxxxxxxxxxxxxxx HTTP/1.0
Host: xxxx.xxxxxxxxx.ru
X-Real-IP: xx.xx.xx.xx
X-Forwarded-Host: xx.xxxxxxx.ru
X-Forwarded-Server: xx.xxxxxxx.ru
X-Forwarded-For: xx.xx.xx.xx
Connection: close
Cookie: CID=wmmDC1S4sx03EVNtA3GgAg==; _ga=GA1.2.1792929628.1392637678; __utma=1.1792929628.1392637678.1396251698.1398174443.4; __utm
v=1.|1=Visitors=All=1; 
User-Agent: Microsoft Office Existence Discovery

--e7b82951-F--
HTTP/1.1 200 OK
Content-Type: application/vnd.ms-excel
Content-Length: 33280
Cache-Control: max-age=86400
Last-Modified: Wed, 22 Apr 2015 10:26:49 GMT
Accept-Ranges: bytes
ETag: "cbecb2d7e67cd01:0"
X-Powered-By: ASP.NET
Connection: close

--e7b82951-E--

--e7b82951-H--
Message: Operator EQ matched 0 at REQUEST_HEADERS. [file "/xxx/xxx/xxxx/apache24/modsec/base_rules/modsecurity_crs_21_protocol_anom
alies.conf"] [line "47"] [id "960015"] [rev "1"] [msg "Request Missing an Accept Header"] [severity "NOTICE"] [ver "OWASP_CRS/2.2.9"
] [maturity "9"] [accuracy "9"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_ACCEPT"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10
/A7"] [tag "PCI/6.5.10"]
Apache-Handler: proxy-server
Stopwatch: 1429700523605438 7437 (- - -)
Stopwatch2: 1429700523605438 7437; combined=2742, p1=258, p2=2372, p3=1, p4=66, p5=44, sr=64, sw=1, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.7.7 (http://www.modsecurity.org/); OWASP_CRS/2.2.9.
Server: Apache/2.4.12 (FreeBSD)
Engine-Mode: "DETECTION_ONLY"

--e7b82951-Z--

It's uncomfortable, I would like to be able to see how many points scored request is in the log, but do not count manually.
Something that can sdleat would still points scored before the threshold also been made in the log?
Thank you.

**Comment by csanders-git** [comment]
hey @shrv :)
you can put logic in similar to the logic used in the DOS rules... see https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0.0-dev/rules/REQUEST-12-DOS-PROTECTION.conf#L14-L21

Here they set a var that expires in 60 seconds effectively showing up in each minute. Might be what you're looking for.

**Comment by shrv** [comment]
It's all my bad English, and why I was taught in school German :)

No, I do not seek it.

I wish that in the logs saw how many points scored request not only when he reached the threshold. But when it is not reached.

I hope it is clear to get questions :)

**Comment by shrv** [comment]
@csanders-git 
Try just words :)
there is a chain
SecRule TX:ANOMALY_SCORE "@gt 0" \
"chain,phase:2,id:'981176',t:none,deny,status:412,log,msg:'Inbound Anomaly Score Exceeded (Total Score: %{TX.ANOMALY_SCORE}, SQLi=%{TX.SQL_INJECTION_SCORE}, XSS=%{TX.XSS_SCORE}): Last Matched Message: %{tx.msg}',logdata:'Last Matched Data: %{matched_var}',setvar:tx.inbound_tx_msg=%{tx.msg},setvar:tx.inbound_anomaly_score=%{tx.anomaly_score}"
SecRule TX:ANOMALY_SCORE "@ge %{tx.inbound_anomaly_score_level}" chain
SecRule TX:ANOMALY_SCORE_BLOCKING "@streq on" chain
SecRule TX:/^\d+-/ "(.*)"

In the first rule "log,msg:'Inbound Anomaly Score Exceeded (Total Score: %{TX.ANOMALY_SCORE}, SQLi=%{TX.SQL_INJECTION_SCORE}, XSS=%{TX.XSS_SCORE}): Last Matched Message: %{tx.msg}',logdata:'Last Matched Data: %{matched_var}',setvar:tx.inbound_tx_msg=%{tx.msg},setvar:tx.inbound_anomaly_score=%{tx.anomaly_score}"

When should enroll in the log? When triggered, the first rule? Or the entire chain?
I hope so clear :)

**Comment by shrv** [comment]
decided.
Sorry for the awful English

**Comment by csanders-git** [comment]
Haha, thanks @shrv
