### ISSUE TITLE
REQUEST_FILENAME

### ISSUE THREAD

**Issue by jambock** [SpiderLabs/owasp-modsecurity-crs#232]
Hi Guys,

I'm running some really old owasp crs (2.2.0) and looking to upgrade to 2.2.9 or possibly 3.0.0, however I noticed a number of big differences and just want to clarify a couple of things.

1 - REQUEST_FILENAME is not used on sqli,xss,generic attacks rules anymore. Unless I'm mistaken, 2.2.9 will not block sql injections on url fragments. For example, if rewrite rules are being used to mask the query string: http://www.example.com/private/users/11224321 instead of http://www.example.com/private/users?id=11224321

2  - REQUEST_COOKIES and REQUEST_COOKIE_NAMES are now present on most rules. I found that the this greatly affects the performance of mod_security in general if the request has too many cookies (30 +). 
I have tried adding  SecRuleUpdateTargetByTag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION" "!REQUEST_COOKIES:/._/|!REQUEST_COOKIES_NAMES:/._/" to my configs and while it stops inspecting the cookies, it doesn't improve the performance. I believe SecRuleUpdateTargetByTag is not working effectively. My only solution is removing all mentions of REQUEST_COOKIES from the rules, unless there is a better way.

Thanks

**Comment by zinoe** [comment]
@jambock, do you have some actual test results on the cookie performance?

The `ModSecurity Handbook` states:

> ARGS is a collection that contains all request parameters, regardless of where they appear in request.

When does your rewriting happen?

> Unless I'm mistaken, 2.2.9 will not block sql injections on url fragments.

Did you test this?

**Comment by dune73** [comment]
You might have a point with the REQUEST_FILENAME, the REQUEST_URI and PATH_INFO not being covered correctly. We need to look into these. Opening a separate issue.

The alledged performance problem might exist, but 30 cookies is excessive. If the problem exists, it's something we can not really handle within the CRS, it's a ModSec problem.

Closing this.
