### ISSUE TITLE
Duplicate rule numbers

### ISSUE THREAD

**Issue by RamblaGnu** [SpiderLabs/owasp-modsecurity-crs#234]
Duplicate rule numbers

The slr_rules seem to have a lot of duplicate rule numbers.  Can those be renumbered?

# service httpd configtest
Syntax error on line 213 of /etc/modsecurity/slr_rules/modsecurity_crs_46_slr_et_lfi_attacks.conf:
ModSecurity: Found another rule with the same id

# service httpd configtest
Syntax error on line 1238 of /etc/modsecurity/slr_rules/modsecurity_crs_46_slr_et_sqli_attacks.conf:
ModSecurity: Found another rule with the same id

**Comment by csanders-git** [comment]
Sorry for the long delay.
The SLR rules are grouped in a way that is meant to be applied selectively. You may select either attack types (xss,lfi,sqli,etc) or applications (joomla, wordpress,etc). The overlapping ID's are likely because you included the entire directory.
