### ISSUE TITLE
False positive with SMF Forum System

### ISSUE THREAD

**Issue by WHK102** [SpiderLabs/owasp-modsecurity-crs#236]
SMF (simplemachines.org) use serialized cookies and launch alert in mod security:

[Sat Jul 04 20:52:15 2015] [error] [client 192.168.1.39] ModSecurity: Access denied with code 403 (phase 2). Pattern match "([\\\\~\\\\!\\\\@\\\\#\\\\$\\\\%\\\\^\\\\&\\\\*\\\\(\\\\)\\\\-\\\\+\\\\=\\\\{\\\\}\\\\[\\\\]\\\\|\\\\:\\\\;\\"\\\\'\\\\\\xc2\\xb4\\\\\\xe2\\x80\\x99\\\\\\xe2\\x80\\x98\\\\`\\\\<\\\\>].*?){8,}" at REQUEST_COOKIES:smf_session_data. [file "/etc/httpd/conf/crs/activated_rules/modsecurity_crs_41_sql_injection_attacks.conf"] [line "157"] [id "981172"] [rev "2"] [msg "Restricted SQL Character Anomaly Detection Alert - Total # of special characters exceeded"] [data "Matched Data: \\x22 found within REQUEST_COOKIES:smf_session_data: a:4:{i:0;s:1:\\x221\\x22;i:1;s:40:\\x22aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\\x22;i:2;i:1000000000;i:3;i:2;}"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "8"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"] [hostname "test.com"] [uri "/index.php"] [unique_id "VZh-v38AAAEAAAd-BO8AAAAC"]

**Comment by dune73** [comment]
Sorry for taking so long to address this.

This is a typical false positive which comes with the use of the CRS. You can suppress it easily with the following tuning rule:

    SecRuleUpdateTargetById 981172 "!REQUEST_COOKIES:smf_session_data"  

Please note that this tuning rule is meant to go into your config file _after_ the CRS inclusion statement. Please do not edit your CRS files, Keep your edits out of these files, so you can later replace the CRS files more easily.

I am going to close this now.
