### ISSUE TITLE
about rules for wordpress

### ISSUE THREAD

**Issue by hy05190134** [SpiderLabs/owasp-modsecurity-crs#237]
I have seen so many rules towards WP in modsecurity_crs_46_slr_et_wordpress_attacks.conf(A), but I also find that some rules towards WP in modsecurity_crs_46_slr_et_sqli_attacks.conf(B) or modsecurity_crs_46_slr_et_xss_attacks.conf(C). But I doubt that rules in A take more detail info than B or C which just say like "uri  match /xxxxx/xxx.php and have params name  xxxxx", so I wonder why just offer these rules in B or C?

**Comment by csanders-git** [comment]
These are an old subset of the commercial rules that typically trail the actual commercial rules by (up to ) several years. Typically one is meant to deploy by either attack types (xss, sql) or by application (wordpress), not both. Attack types are more general in case the user is attempting to secure wordpress and something else, think like an hosting provider.
