### ISSUE TITLE
rules with no operator

### ISSUE THREAD

**Issue by hy05190134** [SpiderLabs/owasp-modsecurity-crs#238]
SecRule ARGS:edit "(?i:edit\x3d.+(script|onmouse[a-z]+|onkey[a-z]+|onload|onunload|ondragdrop|onblur|onfocus|o     nclick|ondblclick|onsubmit|onreset|onselect|onchange|style\x3D))" "ctl:auditLogParts=+E,setvar:'tx.msg=ET WEB_SPECIFIC_APPS FireStats window-add-excluded-ip.php Cross Site Scripting Attempt',setvar:tx.anomaly_score=+%{tx.critical_anomaly_score},setvar:'tx.%{rule.id}-WEB_ATTACK/WORDPRESS-%{matched_var_name}=%{matched_var}'"

It doesn't have operator in the rule above, can it mean just match -d 'edit=xxxx' rather than 'edit=edit=xxxx' which  just in the whole regex string?

**Comment by hy05190134** [comment]
(script|onmouse[a-z]+|onkey[a-z]+|onload|onunload|ondragdrop|onblur|onfocus|o nclick|ondblclick|onsubmit|onreset|onselect|onchange|style\x3D)    should be (script|onmouse[a-z]+|onkey[a-z]+|onload|onunload|ondragdrop|onblur|onfocus|o nclick|ondblclick|onsubmit|onreset|onselect|onchange|style)\x3D?

**Comment by csanders-git** [comment]
Yes, this looks like a mistake, but I am not sure where you found this as there is no ID listed

**Comment by hy05190134** [comment]
slr_rules/modsecurity_crs_46_slr_et_wordpress_attacks.conf  so many rules have e.g. 

# (2011256) SpiderLabs Research (SLR) Public Vulns: ET WEB_SPECIFIC_APPS FireStats window-add-excluded-ip.php      Cross Site Scripting Attempt                                                                                  
 
 SecRule REQUEST_LINE "@contains /wp-content/plugins/firestats/php/window-add-excluded-ip.php" "chain,phase:2,b     lock,t:none,t:urlDecodeUni,t:htmlEntityDecode,t:normalisePathWin,capture,logdata:'%{TX.0}',severity:'2',id:201     1256,rev:2,msg:'SLR: ET WEB_SPECIFIC_APPS FireStats window-add-excluded-ip.php Cross Site Scripting Attempt',tag:'web-application-attack'"                                                                                  
 
SecRule ARGS:edit "(?i:edit\x3d.+(script|onmouse[a-z]+|onkey[a-z]+|onload|onunload|ondragdrop|onblur|onfocus|onclick|ondblclick|onsubmit|onreset|onselect|onchange|style\x3D))" "ctl:auditLogParts=+E,setvar:'tx.msg=ET WEB_SPECIFIC_APPS FireStats window-add-excluded-ip.php Cross Site Scripting Attempt',setvar:tx.anomaly_score=+%{tx     .critical_anomaly_score},setvar:'tx.%{rule.id}-WEB_ATTACK/WORDPRESS-%{matched_var_name}=%{matched_var}'"

**Comment by hy05190134** [comment]
@csanders-git  please check, 3q

**Comment by hy05190134** [comment]
@csanders-git  another question? the last char \x3D actually mean "=", why not put outside of style) rather than style\x3D) ?
