### ISSUE TITLE
Rule 950006 does not include word boundaries and leads to a lot of false positives

### ISSUE THREAD

**Issue by xformerfhs** [SpiderLabs/owasp-modsecurity-crs#240]
Rule 950006 should defend against command injections. However it does not take word boundaries into account and so it finds in a base 64 encoded string "...lF3B3h+CD/0xFsD/LXi.." the command "CD/" which is obviously wrong.

CRS version is 2.2.9.

**Comment by csanders-git** [comment]
This rule has been removed as of CRS v3RC1. this whole sequence of detection mechanisms for RC1 have been redone by @lifeforms and are not quite as vague as they were.
