### ISSUE TITLE
Rule 958291 blocks byte ranges starting with 0 which contradicts RFC2616

### ISSUE THREAD

**Issue by xformerfhs** [SpiderLabs/owasp-modsecurity-crs#242]
Rule 958291 blocks byte ranges starting with 0 which contradicts RFC2616. So this rule contradicts the HTTP specification.

CRS version is 2.2.9.

**Comment by csanders-git** [comment]
This rule has been removed from CRS v3rc1 for the exact reason you are describing. Thank you for the issue report.
