### ISSUE TITLE
Rule 981231 misses word boundaries and leads to lots of false positives

### ISSUE THREAD

**Issue by xformerfhs** [SpiderLabs/owasp-modsecurity-crs#245]
Rule 981231 misses word boundaries and blocks a parameter which contains "...5XkA5SY--5ND7Xmxho59mg7wjchWWQcng2YNg..." where it finds an SQL comment "--". Obviously this is wrong and adding correct word boundaries would make it work correctly.

CRS version is 2.2.9.

**Comment by dune73** [comment]
This is now 942440 PL2.

However, the example given no longer triggers this rule. Closing this.
