### ISSUE TITLE
Rule 981255 is missing word boundaries and leads to lots of false positives

### ISSUE THREAD

**Issue by xformerfhs** [SpiderLabs/owasp-modsecurity-crs#246]
Rule 981255 is missing word boundaries and blocks a parameter "menuTab_tabmenu_ClientState: {"selectedIndexes":["0"],"logEntries":[],"scrollState":{}}" because it finds "select" in there. Obviously this is wrong and adding word boundary recognition would make it work correctly.

CRS version is 2.2.9.

**Comment by dune73** [comment]
Confirming this FP for rule 942190 after the CRS3 rule id renumbering.

Here is how to trigger:

```
$> cat /tmp/data
a=menuTab_tabmenu_ClientState: {"selectedIndexes":["0"],"logEntries":[],"scrollState":{}}
$> curl localhost -d "@/tmp/data"
```

It's a PL1, so this is an FP we want to fix (or try at least)

**Comment by csanders-git** [comment]
There's a bigger underlying issue here as well and that is the lack of spot support for JSON.

**Comment by dune73** [comment]
Sorry, I do not understand you. "Lack of spot support for JSON"?

**Comment by dune73** [comment]
Solved in PR #679. Still not sure what @csanders-git meant above. Closing nevertheless.

**Comment by csanders-git** [comment]
hey @dune73 I meant that it isn't possible to parse a part of a request (for instance a single parameter) as JSON. You must either do everything or nothing... something that will be worked on in v3

**Comment by dune73** [comment]
Now I get it. Good point. This has affected me as well.
