### ISSUE TITLE
Rule 981319 is missing word boundaries and leads to lots of false positives

### ISSUE THREAD

**Issue by xformerfhs** [SpiderLabs/owasp-modsecurity-crs#247]
Rule 981319 is missing word boundaries and finds an "xor" operator in the base 64 encoded parameter value "...NDg9yuib-DLZnwcNi4soXoR5irfrXJz6lMgCSiXr7d5HK5FJHWcwyFwoT7RL...". Obviously this is wrong and adding the appropriate word boundary recognition would make it work correctly.

CRS version is 2.2.9.

**Comment by hcanning2014** [comment]
double pipe in url causes redirect 302
![bruno12](https://cloud.githubusercontent.com/assets/6403224/10089819/2cf76ae0-62f6-11e5-9ecf-5885e7dfe7b7.jpg)

**Comment by csanders-git** [comment]
Sorry about the long time to reply, whenever i looked at this i just looked at 3.x i'll merge that change back to 2.2.9.

**Comment by csanders-git** [comment]
Thanks for the bug report!
