### ISSUE TITLE
Rule 981246 is missing a left word boundary and there is a problem with "+" characters

### ISSUE THREAD

**Issue by xformerfhs** [SpiderLabs/owasp-modsecurity-crs#250]
Rule 981246 is missing a right word boundary. It refuses a long base64 encoded string that contains the characters "...4pwMhuygEh+JNor+sDWhbCiJs4WfPu+Hr..." because it finds an "or " there. Note the space after the "or". So there are two problems:
1. There is no check for a word boundary on the left side. The characters are "JNor+" and "JNor" is _not_ "or".
2. It misinterprets the base64 "+" characters as spaces.

**Comment by xformerfhs** [comment]
I meant "is missing a left word boundary". Sorry.

**Comment by dune73** [comment]
This is gone in CRS3. The rule has been renumbered to 942340 and the regex no longer triggers with the payload in question.

I tried:

```
curl "localhost/?x=4pwMhuygEh+JNor+sDWhbCiJs4WfPu+Hr"
```

Closing this now.
