### ISSUE TITLE
Rule 959073 is missing a left word boundary and leads to lots of false positives

### ISSUE THREAD

**Issue by xformerfhs** [SpiderLabs/owasp-modsecurity-crs#252]
Rule 959073 finds a SQL injection attack in the file name "Xamplemin (Manchester).pdf". It claims that there is the SQL function "min" in there! OK, there is "min(...)" _BUT_ there are some letters before the "min" which clearly indicate that this is not the "min" function. There is a word boundary check missing on the left.

**Comment by xformerfhs** [comment]
CRS version is 2.2.9.

**Comment by xformerfhs** [comment]
Well, this was working wrongly all the time here. Maybe I made a typo and meant "Xamplemin(manchester).pdf". Did you check with no space between "min" and "("?

Regards,
Frank

**Comment by lifeforms** [comment]
This sort of data would frequently give FP in CRS 2.x, but we are trying to not make this happen in CRS 3.x.

As it stands, a default installation of CRS 3.x will not fire on this payload.

However, CRS 3.x in *paranoia level 2 or higher*, will block it. It's caught by rule 942410, which is the renumbered version of rule 959073. So, your reported problem is still there in CRS 3, but it will only affect users running with a higher paranoia level.

I think it's straightforward to improve this rule but not totally trivial.

- First, we should definitely check for a word boundary at the start of the command.
- However, the regexp also seems to contain some subpatterns like `@@version` which can't have a word boundary at the start. If we simply insert `\b` those keywords will never match. So, we need to split those off to a separate rule.
- To maintain the regexp we need tooling to decompress it. I could make it but it would take a couple of hours.
- Add some tests for this FP and the true positive case.

**Comment by dune73** [comment]
Good plan @lifeforms. And thanks for the quick update @xformerfhs. I agree we should tune this FP at the CRS  level if possible. But running on PL2, fixing this rule is no longer urgent.

**Comment by dune73** [comment]
We overlooked this FP because it was assigned the 3.1 tag before we decided the next release would be 3.0.1. Bullocks.

**Comment by dune73** [comment]
This popped up too late for 3.0.1, which is a pity, but we have two other tricky issues and we are too late to put more focus on this finding.

**Comment by franbuehler** [comment]
I found this old issue, which is also affected by the rule 942410.
The word boundary at the beginning of the command is now there (since my PR #791).
@lifeforms example, `@@version`, is not affected by this new `\b`.
Maintain regexp: in issue #811 you will see the disassembled form of the regexp.
So I think this issue could be closed as well.

**Comment by lifeforms** [comment]
Further discussion in #811!
