### ISSUE TITLE
long/complex passwords and sql injection attack detection.

### ISSUE THREAD

**Issue by Stoatwblr** [SpiderLabs/owasp-modsecurity-crs#254]

**Comment by Stoatwblr** [comment]
(Using RHEL6 and the EPEL mod_security_crs_extras package)

I've run into this due to long passwords (current recommendations are 6 words, etc etc) with - separaters.

User: foo
Pass: bar-blah-frink-frotz-buzz-boink

triggers this response.

--0393ce06-H--
Message: Access denied with code 403 (phase 2). Pattern match "([\\~\\!\\@\\#\\$\\%\\^\\&\\*\\(\\)\\-\\+\\=\\{\\}\\[\\]\\|\\:\\;\"\\'\\\xc2\xb4\\\xe2\x80\x99\\\xe2\x80\x98\\`\\<\\>].*?){4,}" at ARGS:login_password. [file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_crs_41_sql_injection_attacks.conf"] [line "170"] [id "981173"] [rev "2"] [msg "Restricted SQL Character Anomaly Detection Alert - Total # of special characters exceeded"] [data "Matched Data: - found within ARGS:login_password: bar-blah-frink-frotz-buzz-boink "] [ver "OWASP_CRS/2.2.6"] [maturity "9"] [accuracy "8"]
Action: Intercepted (phase 2)
Apache-Handler: application/x-httpd-php
Stopwatch: 1442599630169624 3261 (- - -)
Stopwatch2: 1442599630169624 3261; combined=1897, p1=174, p2=1696, p3=0, p4=0, p5=27, sr=37, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.7.3 (http://www.modsecurity.org/); OWASP_CRS/2.2.6.
Server: Apache/2.2.15 (Red Hat)
Engine-Mode: "ENABLED"


The (obvious) point to make is that passwords (actually passphrases these days) can be very long (Linux allows up to 128 characters) and contain almost anything including spaces.

Which in turn means the SQL injection test needs to be tuned to handle it, or attempts to beef up security may result in users starting to get odd 404 errors that are hard to debug.

**Comment by csanders-git** [comment]
This rule has since been remove due to problems just like this. We recommend that you upgrade to the 3.x ruleset branch v3.0.0-dev. You'll find that there are no longer problems like this. If you have specific suggestions to solve this issue we are more than willing to patch it. Thank you for your ticket and feel free to open it again if you find that this is not a satisfactory answer.
