### ISSUE TITLE
 rule 981319 - double pipe in url causes redirect 302

### ISSUE THREAD

**Issue by hcanning2014** [SpiderLabs/owasp-modsecurity-crs#256]
double pipe in url causes redirect 302. Had to disable rule for url to work. See pic
![bruno12](https://cloud.githubusercontent.com/assets/6403224/10089835/61f0abf8-62f6-11e5-9585-ca6ddc32c183.jpg)

**Comment by thanhk43** [comment]
May i know the tool you are using for view log ?

**Comment by issnteacher** [comment]
Whm feature

**Comment by issnteacher** [comment]
Browse https://documentation.cpanel.net/plugins/servlet/mobile#content/view/1507933

**Comment by thanhk43** [comment]
thanks you.

**Comment by csanders-git** [comment]
@issnteacher sorry for the long delay in response. The issue with this is how we would alter this rule to prevent this. In fact, in SQL the double pipe is used for string concatination. So something like the following "SELECT 'A'||'B'||'C'||'D';" is valid SQL and could be used in an injection. We might increase the amount of combinations is looks for from one to two but it would still trigger on your example. Any ideas?

**Comment by issnteacher** [comment]
This is a question for @Bruno17 the developer.
https://github.com/Bruno17/MIGX/pull/11

**Comment by csanders-git** [comment]
@issnteacher i'm not sure i understand that reference link

**Comment by issnteacher** [comment]
Bruno built the plugin that creates that url that triggers the rule. He may revert.

**Comment by csanders-git** [comment]
ahhh I see... in general we first attempt solve the problem but in this case it seems like this pattern is not very common within parameters and is of some use to retain. As a rule of thumb we rarely allow exceptions for particular parameters from applications unless they are extremely likely to cause the false positive on a wide scale basis (google analytic s for instance). In cases where it is one application we do encourage individuals to attempt to address it at the development side (which it seems like is what you are attempting). Alternatively it is always possible to add an exception... see https://www.trustwave.com/Resources/SpiderLabs-Blog/ModSecurity-Advanced-Topic-of-the-Week--(Updated)-Exception-Handling/. Of course when adding an exception you should be careful to try and either modify the rule or add another rule such that you don't introduce a security vulnerability within that area that you added an exception.
