### ISSUE TITLE
Nginx memory usage

### ISSUE THREAD

**Issue by rz300** [SpiderLabs/owasp-modsecurity-crs#257]
I do not know the issue or not, but when rules turn on, nginx begins to use a lot of RAM. When i "turn off" rules, memory usage back to normal. May be my nginx settings are wrong. though i tested server without activated rules memory usage about 10-15% and with rules it becomes 40-45% and grows with time to 85%-90% and system goes to swap.

**Comment by zimmerle** [comment]
Hi @rz300  whats the version of ModSecurity that you are trying to use?

**Comment by rz300** [comment]
2.9 with 3.0 owasp rules.

**Comment by csanders-git** [comment]
@zimmerle and @rz300 this sounds similar enough to https://github.com/SpiderLabs/ModSecurity/issues/550 that i am going to close this here and we can move this over to the Modsecurity github. @rz300 can you provide your system information on that issue page?

**Comment by zimmerle** [comment]
Hi @csanders-git, 

It seems to me that the issue SpiderLabs/ModSecurity#550 represent this very same problem. I think we are fine to feed the SpiderLabs/ModSecurity#550 with more information. However, I think it will be fixed by v3.

Thanks!

**Comment by csanders-git** [comment]
@zimmerle i'd rather just put it on your stack instead of mine :-P

**Comment by zimmerle** [comment]
@csanders-git on my backlog already :) that should be easy with ModSecurity v3 the issue is probably gone. I will measure the memory consumption.

**Comment by rz300** [comment]
what kind of system information you interested in?

**Comment by csanders-git** [comment]
@rz300 You can find libmodsecurity (v3) along with the additional information you'll need on how to use it at https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity. As for information to put into that report it'd be interesting to know computer specs, memory consumption with and without rules... requests being made etc.
