### ISSUE TITLE
Bad bots missing

### ISSUE THREAD

**Issue by toby78** [SpiderLabs/owasp-modsecurity-crs#258]
-AhrefsBot 
-PiplBot;+http://www.pipl.com/bot
-GrapeshotCrawler/2.0; +http://www.grapeshot.co.uk/crawler.php)

**Comment by csanders-git** [comment]
I assume these are too be added as scanners?

**Comment by csanders-git** [comment]
@toby78 just want to verify this before i push a patch.

**Comment by toby78** [comment]
AhrefsBot is a SEO crawler to discover links, keywords etc. mostly used by competive websites.Which is not in your interest - and worst is robots.txt is either ignored or only updated every couple of weeks/months/years.
PiplBot is a crawler specialized on private data / data about people such as usernames, names, location etc..ethically questionable
Grapeshot Crawler is a project from a university to analysis the context of a website - either without or with commercial interest or cooperations with advertising agencies - in any case not necessary and additional stress for a server.

**Comment by csanders-git** [comment]
sounds good and these are detectable by the user agents you gave above without the dash in front? or should i go scour the web for examples

**Comment by csanders-git** [comment]
Added your contributions to the 3.x branch thank you for your feedback :)

https://github.com/SpiderLabs/owasp-modsecurity-crs/commit/11d7b65710d4ec17739bf0416b4699494b4a3449
