### ISSUE TITLE
Broken regex in 2011256

### ISSUE THREAD

**Issue by p0pr0ck5** [SpiderLabs/owasp-modsecurity-crs#259]
Regex in question:

`(?i:+(script|onmouse[a-z]+|onkey[a-z]+|onload|onunload|ondragdrop|onblur|onfocus|onclick|ondblclick|onsubmit|onreset|onselect|onchange|style\x3D))`

The '+' following the opening case-insensitive non-capture does not proceed a quantifiable group. This is in the Wordpress-specific SLR ruleset.

**Comment by csanders-git** [comment]
I'm going to close this because it's taken care of with the previous merge. If this is wrong please reopen it :)
