### ISSUE TITLE
RESPONSE-50-DATA-LEAKAGES-PHP wrong order

### ISSUE THREAD

**Issue by emphazer** [SpiderLabs/owasp-modsecurity-crs#261]
Hello, 

Rhel7 / Apache2.4

the httpd demon doesnt start with the following error 
AH00526: Syntax error on line 24 of /etc/httpd/modsecurity.d/activated_rules/RESPONSE-50-DATA-LEAKAGES-PHP.conf:
Error parsing actions: Unknown action: \\
if you change the rule order like in the other rules it will work.
and i found there are some free spaces at the beginning instead of tabs.

 
-=[ PHP Error Message Leakage ]=-

SecRule RESPONSE_BODY "@pmf php-errors.data" \
        "phase:response,\
	rev:'3',\
	ver:'OWASP_CRS/3.0.0',\
	maturity:'9',\
	accuracy:'9',\
	t:none,\
	capture,\
	ctl:auditLogParts=+E,\
	block,\
	msg:'PHP Information Leakage',\
	logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\
	id:'970009',\
	tag:'application-multi',\
	tag:'language-php',\
	tag:'platform-multi',\
	tag:'attack-information disclosure',\
	tag:'OWASP_CRS/LEAKAGE/ERRORS_PHP',\
	tag:'WASCTC/WASC-13',\
	tag:'OWASP_TOP_10/A6',\
	tag:'PCI/6.5.6',\
	severity:'ERROR',\
	setvar:'tx.msg=%{rule.msg}',\
	setvar:tx.outbound_anomaly_score=+%{tx.error_anomaly_score},\
	setvar:tx.anomaly_score=+%{tx.error_anomaly_score},setvar:tx.%{rule.id}-OWASP_CRS/LEAKAGE/ERRORS-%{matched_var_name}=%{tx.0}"`

greetings,
chris

**Comment by csanders-git** [comment]
This is likely not an issue with our rules but a known issue with apache prior to 2.4.11 see the bug release here: https://bz.apache.org/bugzilla/show_bug.cgi?id=55910

**Comment by emphazer** [comment]
but it will work without problems if you just change the order

# this is yours 

SecRule RESPONSE_BODY "@pmf php-errors.data" \
	"msg:'PHP Information Leakage',\
	id:'970009',\
	phase:response,\
	ver:'OWASP_CRS/3.0.0',\
	rev:'3',\
	maturity:'9',\
	accuracy:'9',\
	t:none,\
	capture,\
	ctl:auditLogParts=+E,\
	block,\
	severity:'ERROR',\
	logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\
        tag:'application-multi',\
        tag:'language-php',\
        tag:'platform-multi',\
        tag:'attack-information disclosure',\
	tag:'OWASP_CRS/LEAKAGE/ERRORS_PHP',\
	tag:'WASCTC/WASC-13',\
	tag:'OWASP_TOP_10/A6',\
	tag:'PCI/6.5.6',\
	setvar:'tx.msg=%{rule.msg}',\
	setvar:tx.outbound_anomaly_score=+%{tx.error_anomaly_score},\
	setvar:tx.anomaly_score=+%{tx.error_anomaly_score},setvar:tx.%{rule.id}-OWASP_CRS/LEAKAGE/ERRORS-%{matched_var_name}=%{tx.0}"

# and i changed it in the same way you do normally in your other rules

SecRule RESPONSE_BODY "@pmf php-errors.data" \
"phase:response,\
rev:'3',\
ver:'OWASP_CRS/3.0.0',\
maturity:'9',\
accuracy:'9',\
t:none,\
capture,\
ctl:auditLogParts=+E,\
block,\
msg:'PHP Information Leakage',\
logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\
id:'970009',\
tag:'application-multi',\
tag:'language-php',\
tag:'platform-multi',\
tag:'attack-information disclosure',\
tag:'OWASP_CRS/LEAKAGE/ERRORS_PHP',\
tag:'WASCTC/WASC-13',\
tag:'OWASP_TOP_10/A6',\
tag:'PCI/6.5.6',\
severity:'ERROR',\
setvar:'tx.msg=%{rule.msg}',\
setvar:tx.outbound_anomaly_score=+%{tx.error_anomaly_score},\
setvar:tx.anomaly_score=+%{tx.error_anomaly_score},setvar:tx.%{rule.id}-OWASP_CRS/LEAKAGE/ERRORS-%{matched_var_name}=%{tx.0}"`

**Comment by emphazer** [comment]
just compare the rule order with the following 2 rules id:'970902' & id:'970015' 
you will see that there is a difference
;-)

normally you begin phase:response & rev ... and not with msg: & id.

greetings
chris

**Comment by csanders-git** [comment]
I understand that you changed the rule such that it made this function properly for you... you could have also added a space before the line continuation and it would have worked. My understanding is this is still the same Apache bug you are trying to fix... It has all to do with how things are added into a buffer within configuration files. If this works for you great, but you'll understand if we don't push a patch to the main branch to address an apache issue I assume.

**Comment by emphazer** [comment]
we opened a backport patch request for rhel7 httpd 2.4.6
https://bugzilla.redhat.com/show_bug.cgi?id=1378946

looks good. maybe they gonna fix it soon!
