### ISSUE TITLE
Experimental rules should standardise on a consistent path for external files

### ISSUE THREAD

**Issue by jstangroome** [SpiderLabs/owasp-modsecurity-crs#262]
There are three experimental rule files which use three different paths to their lua scripts:

1. https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/c63affc9dfa6294ecf8782ae4d1f1fb2c9fd5a18/experimental_rules/modsecurity_crs_48_bayes_analysis.conf#L15
1. https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/c63affc9dfa6294ecf8782ae4d1f1fb2c9fd5a18/experimental_rules/modsecurity_crs_16_scanner_integration.conf#L32
1. https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/c63affc9dfa6294ecf8782ae4d1f1fb2c9fd5a18/experimental_rules/modsecurity_crs_55_response_profiling.conf#L11

And there is another experimental rule file which uses two different paths to lua scripts in the same file:

* https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/c63affc9dfa6294ecf8782ae4d1f1fb2c9fd5a18/experimental_rules/modsecurity_crs_48_bayes_analysis.conf#L13-L15

There are also two experimental rule files which use two different paths to reference the GeoIP database:

1. https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/c63affc9dfa6294ecf8782ae4d1f1fb2c9fd5a18/experimental_rules/modsecurity_crs_11_proxy_abuse.conf#L24
1. https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/c63affc9dfa6294ecf8782ae4d1f1fb2c9fd5a18/experimental_rules/modsecurity_crs_61_ip_forensics.conf#L34

And neither of these GeoIP database paths match the setup.conf example path:

* https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/c63affc9dfa6294ecf8782ae4d1f1fb2c9fd5a18/modsecurity_crs_10_setup.conf.example#L175

While these are experimental rules, and some have comments suggesting that the user should adjust the paths to suit their environment, can we have a default path that is consistent and then easy to bulk find and replace?

**Comment by csanders-git** [comment]
that sounds acceptable to me is there a path that you think makes sense @jstangroome ?

**Comment by jstangroome** [comment]
@csanders-git I'm somewhat new to the ModSecurity ecosystem but given the variety of platforms that ModSecurity supports, perhaps relative paths should be used (where the directives allow relative paths).

Eg, a rule file in the `experimental_rules` directory could refer to its Lua file via `../lua/myscript.lua`.

Or if the relative path support is inconsistent, perhaps use the base `/opt/modsecurity/` path as used in ModSecurity's own recommended configuration file in several places:

https://github.com/SpiderLabs/ModSecurity/blob/master/modsecurity.conf-recommended#L153

**Comment by csanders-git** [comment]
So after a lot of research it seems that 'exec' has to have a full path (on some OS's)... but i'm fine with changing the LUA stuff to match the stuff we have to be under the /opt/modsecurity/owasp-modsecurity-crs/lua/[data] where relative paths are not possible this seems to be the best solution. Otherwise we should use relative paths to allow things to work out of the box... i'm going to make sure in 3.x that relative paths will work for exec and scripts. How does this sound?

**Comment by zimmerle** [comment]
Hi @csanders-git,

In fact, every "external resource access" should follow the same policy for path resolution. There is no sense to do something different for each operator or resource, unless there is a corner case (which I don't think is the case here).

Currently in version 3 we have a "function" to map external resources path. Let's make sure the Lua implementation will use that function.

@csanders-git opened the issue SpiderLabs/ModSecurity#956

**Comment by csanders-git** [comment]
so you saw that did you @zimmerle  :-P

**Comment by zimmerle** [comment]
@csanders-git ;)

**Comment by jstangroome** [comment]
Sounds good.

**Comment by dune73** [comment]
Given this was limited to experimental rules we dropped for CRS3.0 and given the ModSecurity project is addressing this, I will close this issue
