### ISSUE TITLE
Block searchmetrics

### ISSUE THREAD

**Issue by toby78** [SpiderLabs/owasp-modsecurity-crs#264]
User-agent: SearchmetricsBot should be added to list of scanners.

**Comment by csanders-git** [comment]
Mozilla/5.0 (compatible; SearchmetricsBot; http://www.searchmetrics.com/en/searchmetrics-bot/)

**Comment by csanders-git** [comment]
Added and tested in commit https://github.com/SpiderLabs/owasp-modsecurity-crs/commit/ee03433e4e1f23783212ed6ed7d04fb2d951dd90 Thank you.
