### ISSUE TITLE
HTTP Query is not urlencoded (security problem)

### ISSUE THREAD

**Issue by WHK102** [SpiderLabs/owasp-modsecurity-crs#268]
For example: crs is connected to database log with exp reg to match content, injection sql by logs of crs example:

Change user agent to nikto and request: http://secure.com/"] [unique_id "');drop tables;-- -

Log output: [Mon Nov 16 13:49:08 2015] [error] [client x.x.x.x] ModSecurity: Access denied with code 403 (phase 2). Matched phrase "nikto" at REQUEST_HEADERS:User-Agent. [file "/home/x/crs/activated_rules/modsecurity_crs_35_bad_robots.conf"] [line "20"] [id "990002"] [rev "2"] [msg "Request Indicates a Security Scanner Scanned the Site"] [data "nikto 3.9"] [severity "CRITICAL"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "9"] [tag "OWASP_CRS/AUTOMATION/SECURITY_SCANNER"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "lapinturita.cl"] [uri "/\\\\"] [unique_id \\\\"');drop tables;-- -"] [unique_id "VkolJMBjCQ8AAH8FpyAAAAAg"]

[uri "/\\\\"] is validate as "/\"
[unique_id \\"';drop tables;-- -"] is validate as ';drop tables;-- -
Now, save this with vulnerable code: insert into crs_logs ... values ('1', '');drop tables;-- -

Some people say that filter the field unique_id if only alphanumeric ?, the answer here.

Solution: display query string in urlencoded mode or escaped correctly the quotes to prevent spoof fields.

**Comment by dune73** [comment]
@WHK102: Sorry for taking that long to address this. Let's sort this out!

Unfortunately, I am not totally sure about your initial request and your description is not 100% clear to me (I'm not a native speaker either).

Please tell me your request on a single line on it's own. Ideally as markdown code example. That way everything is clear.

What I get so far, this is a loginjection vulnerability, which mimics a ModSecurity log entry to execute an sql injection on the DB holding ModSecLogs. Is that interpretation correct?

**Comment by csanders-git** [comment]
@dune73  I am getting the same thing and the solution is to encode sensitive chars within the log. I think we should address this but it would be a ModSecurity issue. It should also be possible to fuck with JSON logs in this way :-X

**Comment by dune73** [comment]
@csanders-git : So we open a ModSec issue and close this for CRS?

**Comment by csanders-git** [comment]
yeah I just didn't have the time when i wrote that doing it now :)

**Comment by csanders-git** [comment]
This has been opened as a ModSecurity ticket:
https://github.com/SpiderLabs/ModSecurity/issues/1185

**Comment by WHK102** [comment]
Sorry, yes, is a mod security issuse. Normaly in access_log when encoding packet (by example %01) the apache write in log the value in hexadecimal \x01 not the byte and "][" characters write in urlencode but in mod security write it in plain text, no have escape character to "][".

Example parse log in mod security with CRS:

    #!/bin/bash

    validlog='\sModSecurity\:\sAccess\sdenied\swith\scode\s403\s'
    patternlog='^\[.*?\]\s\[error\]\s\[client\s(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\].*?\s\[id\s"(.*?)"\].*?\[severity\s"(.*?)"\]\s\[ver\s.*?\[maturity\s"(.*?)"\]\s\[accuracy\s"(.*?)"]\s\[.*?\[hostname "(.*?)".*?\[uri "(.*?)"\].*?\[unique_id\s"(.*?)"\]'

    while read line; do

        if [[ $line =~ $validlog ]]; then 

            [[ $line =~ $patternlog ]]
                res_remote_addr="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}.${BASH_REMATCH[3]}.${BASH_REMATCH[4]}"
            ....
            sql_remote_addr=$(hexdump -ve '1/1 "%02x"' <<< $res_remote_addr)
            ...
            mysql -u $mysql_user -p$mysql_password -e "INSERT INTO ...`

Now, test the url: 
http://localhost/'"><script>false-positive-here;"]%20[severity%20"none

This inject the severity into log and broken format and broken parser.

Now, the unique_id is a integer parameter and i decide put the value into sql query without escape filter, the param cause the inject into sql query.

Other systems using the log in SQL format can have the same security problem.

**Comment by csanders-git** [comment]
@WHK102  Please respond to the new issue on ModSecurity with that information :)

**Comment by fzipi** [comment]
@WHK102 Sorry to tell you I was testing a migration and the repo you commented isn't operational.

I'm pasting your comments here!

Hello, sorry for the delay. I speak Spanish, if someone speaks the language it would be more fluent to explain the situation, I use the google translator.

Apache httpd uses a defined format to create logs and these are respected by multiple event correlation systems and data parsing as `goaccess` through the combined format. But how do you prevent a value like the user agent from breaking that format using whitespace or special characters?: Apache http use literal hexadecimal values or backslash escape secuence.

By example:

    "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\""

The combined log format use the user agent enclosure into quotes, but what happen when the user agent contains quotes?

The original example log:

    46.222.54.164 - - [19/Apr/2020:15:38:37 -0400] "GET /" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"

The try hacking log using quotes on user agent `Demo" Breaked "Demo`:

```bash
$ ncat --crlf -v example.com 80
Ncat: Version 7.60 ( https://nmap.org/ncat )
GET / HTTP/1.1
Host: example.com
User-Agent: Demo" Breaked "Demo
Connection: Close
```

The `access_log` line writed by httpd says:

    200.120.76.187 - - [19/Apr/2020:15:42:08 -0400] "GET / HTTP/1.1" 200 5660 "-" "Demo\" Breaked \"Demo"

External applications that use the log to interpret their content should use this type of character escape sequence to avoid falsifying fields in the log.

This is what (until the day I made the report) mod security crs does not do, it does not apply the character escape sequence used by httpd.
