### ISSUE TITLE
Access denied with code 400 (phase 2). Match of "eq 0" against "REQBODY_ERROR" required

### ISSUE THREAD

**Issue by mailtoyogeshpatel** [SpiderLabs/owasp-modsecurity-crs#271]
in mod security we have a following rule 

SecRule REQBODY_ERROR "!@eq 0" \
"id:'200001', phase:2,t:none,log,deny,status:400,msg:'Failed to parse request body.',logdata:'%{reqbody_error_msg}',severity:2"

in which situation we get the following mod security log 

Message: Access denied with code 400 (phase 2). Match of "eq 0" against "REQBODY_ERROR" required. [file "D:/tools/Apache2.4.x/conf/extra/highq/modsec/modsecurity.conf"] [line "132"] [id "200001"] [msg "Failed to parse request body."] [data "Error reading request body: Client went away."] [severity "CRITICAL"]
Action: Intercepted (phase 2)

**Comment by csanders-git** [comment]
See the following post.... https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#REQBODY_ERROR ... this error is the result of a request body processor failure. It can be a result of a number of different issues. In general this is typically leading up to a situation where ModSecurity is unable to process the request properly

**Comment by mailtoyogeshpatel** [comment]
How i can disable logging (nolog) for logdata "[data "Error reading request body: Client went away."]",
is there any way to disable logging based on logdata?

**Comment by csanders-git** [comment]
This is a rather complicated question, but of course you can do it. You would need to add 'nolog' the original rule  (200001). After doing this you would store the output of the rule in a variable, similarly to how we are doing this with logdata (tx.myvar:'%{reqbody_error_msg}'). You would then add a rule that would log only on a match of the data you desired for instance.
SecRule TX:myvar "!@contains Client went away" "log,etc"

Hopefully this helps.

**Comment by mailtoyogeshpatel** [comment]
Do we need to chain the original rule?

**Comment by mailtoyogeshpatel** [comment]
i tried it in following way but not working:

SecRule REQBODY_ERROR "!@eq 0" \
"id:'200001',chain,phase:2,t:none,nolog,deny,status:400,msg:'Failed to parse request body.',logdata:'%{reqbody_error_msg}',severity:2,setvar:tx.myvar:'%{reqbody_error_msg}'"
	SecRule TX:myvar "!@contains Client went away" "log"

**Comment by csanders-git** [comment]
i'm sorry if this wasn't clear but my code was just an example. there are things you must specify in addition to "log" for any rule to work. How i set forth the rule logic this shouldn't be chained. If you are unfamiliar with rule logic please see online resources such as the reference manual or the modsecurity handbook.
