### ISSUE TITLE
Rule 981004 false positive in WordPress Admin

### ISSUE THREAD

**Issue by Clorith** [SpiderLabs/owasp-modsecurity-crs#274]
With WordPress 4.4.1, rule 981004 is triggering on the backend (/wp-admin) and blocking access due to inline JavaScript utilizing `.fromCharCode`.

**Comment by dune73** [comment]
Let's get this sorted out. Could you please provide the Error-Log Entry / Alert created by ModSecurity?

**Comment by Clorith** [comment]
WordPress sorted this internally for 4.4.2 as the rule ended up being adopted by other ModSecurity rule providers, but for clarity it was tracked internally at https://core.trac.wordpress.org/ticket/35412

The reported output was:
> Rule Message: Potential Obfuscated Javascript in Output - Excessive fromCharCode
Event: Pattern match "(?i)(String\\.fromCharCode\\(.*?){4,}" at RESPONSE_BODY
Data: Matched Data: String.fromCharCode(55356,56806,55356,56826),0,0),d.toDataURL().length>3e3):\x22diversity\x22===a?(e.fillText(String.fromCharCode(55356,57221),0,0),c=e.getImageData(16,16,1,1).data.toString(),e.fillText(String.fromCharCode(55356,57221,55356,5
Tag: OWASP_CRS/MALICIOUS_CODEbugtraq,13544

With the notification
> Rule Message: Outbound Anomaly Score Exceeded (score 4): The application is not available
Event: Operator GE matched 4 at TX:outbound_anomaly_score 

This can safely be closed on this end if you wish.

**Comment by dune73** [comment]
@Clorith, thank you very much for the additional infos.

It is true, that the rule very restrictive. Still, I do not know of many false positives outside of your problem. If you see this rule or any other rule trigger excessively, you may want to open an issue and we can think about moving them into the new/future paranoia mode for CRS 3.0.

See https://www.owasp.org/index.php/OWASP_ModSec_CRS_Paranoia_Mode where this problem has been reported too.

Generally it is very good to see WP being used together with ModSec. False positives are hard to avoid, but they can be worked around. I would not mind supporting cooperation in this regard.

I am closing this now.
