### ISSUE TITLE
Duplicate configuration Core Rule Set Quick Setup

### ISSUE THREAD

**Issue by slvxstar** [SpiderLabs/owasp-modsecurity-crs#275]
owasp-modsecurity-crs/INSTALL

1)
`$ ln -s /usr/local/apache/conf/crs/modsecurity_crs_10_setup.conf activated_rules/modsecurity_crs_10_setup.conf`

2)
  `<IfModule security2_module>`
      `Include conf/crs/modsecurity_crs_10_setup.conf`
      `Include conf/crs/activated_rules/*.conf`
  `</IfModule>`

**Comment by csanders-git** [comment]
2)
