### ISSUE TITLE
Default rule set doesn't really work with Cyrillic websites

### ISSUE THREAD

**Issue by vgvassilev** [SpiderLabs/owasp-modsecurity-crs#277]
Hi,
  Thanks for working on this useful project.

  We are running websites (mostly drupal) with Cyrillic charsets (win-1251). Some of the websites have Cyrillic URLs. A few days ago we have installed modsecurity 2.2.7 and the rules oswasp-modsecurity-crs. We have followed the web tutorials how to set them and we have enabled only the base rules, i.e.

```
...
IncludeOptional /etc/modsecurity/modsecurity.conf
IncludeOptional /etc/modsecurity/modsecurity.d/owasp-modsecurity-crs/modsecurity_crs_10_setup.conf
Include "/etc/modsecurity/modsecurity.d/owasp-modsecurity-crs/base_rules/*.conf"
...
```

Everything goes belly up: we get false positives from a lot of rules (sql injection, inbound, outbound, correlation, generic and so on) saying something along the lines:

```
[Mon Jan 18 19:25:28.634360 2016] [:error] [pid 29382] [client 77.85.38.228] ModSecurity: Access denied with code 403 (phase 2). Pattern match "([\\\\~\\\\!\\\\@\\\\#\\\\$\\\\%\\\\^\\\\&\\\\*\\\\(\\\\)\\\\-\\\\+\\\\=\\\\{\\\\}\\\\[\\\\]\\\\|\\\\:\\\\;\\"\\\\'\\\\\\xc2\\xb4\\\\\\xe2\\x80\\x99\\\\\\xe2\\x80\\x98\\\\`\\\\<\\\\>].*?){5,}" at ARGS_NAMES:ajax_page_state[css][public://ctools/css/fd76320edfa0f84e8737e52c3ec79263.css]. [file "/etc/modsecurity/modsecurity.d/owasp-modsecurity-crs/base_rules/modsecurity_crs_41_sql_injection_attacks.conf"] [line "159"] [id "981173"] [rev "2"] [msg "Restricted SQL Character Anomaly Detection Alert - Total # of special characters exceeded"] [data "Matched Data: ] found within ARGS_NAMES:ajax_page_state[css][public://ctools/css/fd76320edfa0f84e8737e52c3ec79263.css]: ajax_page_state[css][public://ctools/css/fd76320edfa0f84e8737e52c3ec79263.css]"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "8"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"] [hostname "www.izbirambg.dev.solid-consult.com"] [uri "/bg/views/ajax"] [unique_id "Vp0gCH8AAQEAAHLGuCn-@--3"]
[Mon Jan 18 19:25:39.692334 2016] [:error] [pid 29382] [client 77.85.38.228] ModSecurity: Access denied with code 403 (phase 2). Pattern match "\\\\W{4,}" at ARGS:name. [file "/etc/modsecurity/modsecurity.d/owasp-modsecurity-crs/base_rules/modsecurity_crs_40_generic_attacks.conf"] [line "37"] [id "960024"] [rev "2"] [msg "Meta-Character Anomaly Detection Alert - Repetative Non-Word Characters"] [data "Matched Data: \\xd0\\x92\\xd0\\x9f\\xd0\\x9c\\xd0\\x98 found within ARGS:name: \\xd0\\x92\\xd0\\x9f\\xd0\\x9c\\xd0\\x98"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "8"] [hostname "www.izbirambg.dev.solid-consult.com"] [uri "/user/login"] [unique_id "Vp0gE38AAQEAAHLGuHn-@--4"]
```

This is coming from the web URL, which are not with English.

I've read the discussions in #708 and #220 and a few other resources. I don't see a way out. What is your advice, can we fix those issues somehow? Or should we stop using modsecurity (which we really don't want to).

Many thanks,
Vassil

**Comment by vgvassilev** [comment]
Reading some more #233 #151 #143, it seems this is a fundamental issue to the system with these charsets... I hope there is a solution...

**Comment by dune73** [comment]
@vgvassilev thank you very much for your report here and the references to the other issues connected to this one.

We are well aware, that the CRS and non-Lating charsets do not work very well together. However, most of the problems are gone with the CRS3 for the default install and the new optional rule exclusion file for drupal easing things even more (I will be publishing an additional tutorial on drupal integration on [netnea.com](https://netnea.com) in the next few days.

I am closing this now and ask you do open new issues with example payloads that trigger CRS3 rules. We will then try and make the CRS comply with non-Latin payloads for 3.1 or so (or 3.0.x if it's simple to fix).
