### ISSUE TITLE
modsecurity_35_bad_robots.data match with Google Plus

### ISSUE THREAD

**Issue by vynt-kenshiro** [SpiderLabs/owasp-modsecurity-crs#280]
Hello,

If I use modsecurity_35_bad_robots.data rule for filter bad robots, ModSecurity will match with user-agent from Google Plus (Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy). I think it's better remove "via" keyword from modsecurity_35_bad_robots.data

**Comment by csanders-git** [comment]
This has been removed from the version 3.0 stuff already - I will accept a pull request if you make it with the change for 2.x
