### ISSUE TITLE
NGINX friendly instructions please ????

### ISSUE THREAD

**Issue by udf2457** [SpiderLabs/owasp-modsecurity-crs#282]
How does :- 

> 3) Add the following line to your httpd.conf (assuming
>      you've placed the rule files into conf/crs/):
> 
>         <IfModule security2_module>
>                 Include conf/crs/modsecurity_crs_10_setup.conf
>                 Include conf/crs/activated_rules/*.conf
>         </IfModule>

Work in the context of NGINX ?

e.g.

```
location / {
           ModSecurityEnabled on;
           ModSecurityConfig /etc/nginx/conf.d/modsecurity.conf;
           proxy_pass http://XXXXXX:YYYY;
           proxy_read_timeout 180s;
        }
```
Adding an extra ModSecurityConfig directive doesn't work, and "include" doesn't work either.

I hope you're not going to tell me to cat it all into one big file ?  :-(

**Comment by csanders-git** [comment]
you can include a .config file and put the includes in that file :) tell me if that works.

**Comment by udf2457** [comment]
Unless I've missed it (https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual), there seem to be no Include directives supported in the mosecurity config format ?

**Comment by csanders-git** [comment]
This is a service that is provided technically by APR (to my understanding) as a result it isn't really 'part of modsecurity' In the v3 version this is an explicit directive of the language. Did this solve your problem? I can add something along these lines to the wiki if it did.

**Comment by udf2457** [comment]
Hi,

I'm not sure you "get it".

As per the ModSecurity manual, the plugin for NGINX only enables two directives in the NGINX config files _ ModSecurityEnabled_ (on/off) and _ModSecurityConfig_ (name of the modsecurity config file to load).

I have tried multiple ModSecurityConfig parameters, but the ModSecurity plugin for NGINX only allows one to be specified.

As previously outlined to you, as per the ModSecurity docs, there appears to be no Include directive permissible in the ModSecurity config format.

Therefore I am at a loss as to how I should go about "put the additional includes in that file" ?  Since I can't call includes from either NGINX or the ModSecurity master conf itself.

**Comment by csanders-git** [comment]
Please see the issue in ModSecurity repo for solution
