### ISSUE TITLE
Rule 960035 false positive in mailman

### ISSUE THREAD

**Issue by JanKrohn-Khalibre** [SpiderLabs/owasp-modsecurity-crs#287]
Mailman subscribers whose email address has a .com extension can't modify their settings or unsubscribe.
Details here: https://forums.cpanel.net/threads/mailman-user-options-redirects.526131

**Comment by csanders-git** [comment]
Can you provide us with a request that is triggering this rule? The actual output of the rule etc don't seem to be in the attached link.

**Comment by JanKrohn-Khalibre** [comment]
Correct. All the data is in the ticket referenced in the last forum post...
Here we go:

Request is for example:
https://heidoc.net/mailman/options/vyrso-90_heidoc.net/subscriber%40gmail.com

Apache log produces error:

[Mon Feb 22 02:19:11.326187 2016] [:error] [pid 18708] [client 208.74.121.106] ModSecurity: Access denied with redirection to http://heidoc.net/ using status 302 (phase 2). String match within ".asa/ .asax/ .ascx/ .axd/ .backup/ .bak/ .bat/ .cdx/ .cer/ .cfg/ .cmd/ .com/ .config/ .conf/ .cs/ .csproj/ .csr/ .dat/ .db/ .dbf/ .dll/ .dos/ .htr/ .htw/ .ida/ .idc/ .idq/ .inc/ .ini/ .key/ .licx/ .lnk/ .log/ .mdb/ .old/ .pass/ .pdb/ .pol/ .printer/ .pwd/ .resources/ .resx/ .sql/ .sys/ .vb/ .vbs/ .vbproj/ .vsdisco/ .webinfo/ .xsd/ .xsx/" at TX:extension. [file "/usr/local/apache/conf/modsec_vendor_configs/OWASP/rules/REQUEST-20-PROTOCOL-ENFORCEMENT.conf"] [line "417"] [id "960035"] [rev "2"] [msg "URL file extension is restricted by policy"] [data ".com"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "Host: heidoc.net"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS/POLICY/EXT_RESTRICTED"] [tag "WASCTC/WASC-15"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "heidoc.net"] [uri "/mailman/options/vyrso-90_heidoc.net/subscriber@gmail.com"] [unique_id "Vsq2b6z1BN4AAEkUsTYAAAAE"]

**Comment by csanders-git** [comment]
ahh this is an interesting problem, thank you for reporting it. .com is also the extension for native dos executables.  The best way may be to just remove .com but i'm trying to think if there is a better solution. Thoughts?

**Comment by JanKrohn-Khalibre** [comment]
None of the other file extensions is also a top level domain, so indeed, removing .com would solve the issue. It would be unfortunate though to lose security related to .com files...
The only alternative I can think of would be allowing .com only if the URL contains /mailman/

**Comment by dune73** [comment]
I've seen this false positive in various contexts several times. For me it's a classical example of a false positive which needs to be dealt with in local tuning rules.
Here:
     # ModSec Rule Exclusion: 960035 : URL file extension is restricted by policy (severity: 5 CRITICAL)
      SecRule REQUEST_FILENAME "@beginsWith /mailman/" \ "phase:2,nolog,pass,id:10000,ctl:ruleRemoveTargetById=960035;TX:extension"

**Comment by zinoe** [comment]
I will add a comment, pointing to "ruleRemoveTargetById" for this rule.

**Comment by zinoe** [comment]
As @dune73 stated, modsec already offers the tools to handle such a problem. Therefore I think this issue can be closed.

**Comment by dune73** [comment]
@zinoe, I do not mind adding more comments to the rulebase, as long as they help inexperienced users deal with issues.

As for _this_ issue, I am closing now.

**Comment by zinoe** [comment]
@dune73, I somewhat agree with you. We should actually provide as much help as possible for inexperienced users. But isn't that what a knowledge-base is for?

**Comment by dune73** [comment]
When it get too extensive, then a link to the knowledge-base is the right step to take things further. But if it's a single tuning-rule proposal, then I think a comment is the right thing to do.
This assumes however, that a user upon seeing a false positives opens the rule file and follows the comments.

**Comment by zinoe** [comment]
It definitely makes sense, I do not 100% agree though. But then, this is the first Open Source project I participate in, so still learning to think more "open" ;)

Nevertheless, I'll add the comment coming this week.
