### ISSUE TITLE
php-function-names.data additions

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#290]
In 3.0.0-rc1, `php-function-names.data` is missing some functions seen a lot in malware/web shells. For example: ` gzinflate`, `gzdecode`, `gzuncompress`, `strrev`, `zlib_decode`... They are highly specific to malware, quick win to add these.

**Comment by dune73** [comment]
I second that.

**Comment by csanders-git** [comment]
I've developed a list of 886 functions based on the PHP source code.
[phpOut.txt](https://github.com/SpiderLabs/owasp-modsecurity-crs/files/228320/phpOut.txt)

Can you guys think of a criteria whereby we want to choose which ones we want to include?
This would be much easier if we had a contains that didn't include substrings 

I was thinking of running them against a typical dictionary to see how commonly each appears as part of anther word does this seem like a valid approach?

**Comment by dune73** [comment]
That's a good list. I dreamed of that contains variant before...
Looking through your list, I think the most risky false positives are function names as "each" or "sleep", which are words on their own - but they can appear within other words as well.

The dictionary approach sounds good. We could use that to group the list - and possibly php-function-names.data.

**Comment by lifeforms** [comment]
Merged into #338 mega-issue.
