### ISSUE TITLE
Parentheses in php-function-names.data

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#291]
In `php-function-names.data`, some common words are affixed with a parenthesis, like `eval(`.

This attempts to reduce false positives, but this can lead to easy evasion. For instance, the following strings are equivalent to the PHP parser:

```
eval(
eval (
eval\t(
eval  /*this is a comment*/   (
```

I don't think we can have regexps in a data file (is this correct?) If we can't, I recommended to move function names which easily cause false positives -- such as `eval`, `system` -- to a different data file.

On this data file, the rules should only cause a block when the `(` character is found. We should not just match on the function name only, in order to prevent false positives. We can apply a little regexp to get rid of evasions.

It will incur the cost of an extra data file to separate the pure functions from the other keywords.

(The list also contains `include(`, but include is not a function and does not need parenthesis, e.g. the following is idiomatic PHP which will not be detected with a bracket:
`include 'foo.php'`

But `include`, like its brother `require`, is a common English term. If we want to protect against it, I'm afraid we will have to write a separate rule for it that does regexp magic to check it's a valid include statement. We will hit too much FP if we should just match on those plain words without including more elaborate regexp, so without a specialized rule we will probably have to ditch those words from the data set. At the other hand their use and level of maliciousness is lower than the 'evil functions’ as most people will have PHP configured to not allow URL include. So this could be seen as lower priority.)

**Comment by dune73** [comment]
The idea with the chained "("-check sounds neat to me.

**Comment by lifeforms** [comment]
Merged into #338 mega-issue.
