### ISSUE TITLE
Add PHP specific files to lfi-os-files.data

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#295]
The list of LFI common strings (`lfi-os-files.data`) misses some common PHP evergreens such as:

```
wp-config.php #Wordpress
config.yml #Symfony
config_dev.yml #Symfony
config_prod.yml #Symfony
config_test.yml #Symfony
parameters.yml #Symfony
routing.yml #Symfony
security.yml #Symfony
```

We should add some common ones to the list. It should not be hard to find more of them for other popular CMS and frameworks.

**Comment by lifeforms** [comment]
Some other fun ones I found were `sftp-config.json` (Sublime Text metadata file containing passwords) and `Web.config` (ASP.NET)

**Comment by dune73** [comment]
Good plan.

**Comment by lifeforms** [comment]
Pull request is in #316.

Currently, the LFI data file contains mostly pretty long paths, which protects against false positives. I have only used bare filenames (e.g. not prefixed with slashes or path names) if the files are likely to be in the current working directory, such as `wp-config.php` (Wordpress).

Other additions are welcome, and we should review the app landscape regularly, but this is a good start that matches a good number of mass scans.

**Comment by csanders-git** [comment]
Based on the closed merge is this one complete as well (atleast for RC1)?

**Comment by lifeforms** [comment]
Yes!

**Comment by csanders-git** [comment]
u've made great progress :)
