### ISSUE TITLE
Question about a none existed security issue (so i think)

### ISSUE THREAD

**Issue by avifatal** [SpiderLabs/owasp-modsecurity-crs#296]
Hi,
I have got the error bellow that blocked a page in my wordpress site:
I dont see anywhere in the response body of the path  "/category/beauty/"  the tag <% . 

1. how can i clean this up if i dont find the problem within the response body? 
2. the specific mod security installation is defending a lot of sites, some are asp.net, disabling this rule will bypass potential problems with .net sites.

Thanks

`[Mon Feb 29 17:58:16.729682 2016] [:error] [pid 23643:tid 140427344656128] [client *********] ModSecurity: Access denied with code 403 (phase 4). Match of "rx (?:\\\\b(?:(?:i(?:nterplay|hdr|d3)|m(?:ovi|thd)|r(?:ar!|iff)|(?:ex|jf)if|f(?:lv|ws)|varg|cws)\\\\b|gif)|B(?:%pdf|\\\\.ra)\\\\b)" against "RESPONSE_BODY" required. [file "/etc/apache2/modsecurity-crs/base_rules/modsecurity_crs_50_outbound.conf"] [line "39"] [id "970903"] [rev "2"] [msg "ASP/JSP source code leakage"] [data "Matched Data: <% found within RESPONSE_BODY: \\x1f\\x8b\\x08\\x00\\x00\\x00\\x00\\x00\\x00\\x03$\\x8d\\xb1\\x0a\\xc20\\x14E\\xe7\\xf6+\\x9eo\\x8f\\xa1\\xab&]Z\\x07A\\xd0\\xa1\\x8bch_\\x93@\\x9a\\xc6\\xf8\\x94\\xfa\\xf7\\x1a\\x9c.\\xe7p\\xe0\\xaa]\\x7f\\xed\\x86\\xfb\\xed\\x04\\x8e\\x97\\xd0\\xd6\\xaa\\x0cL>k\\xcc\\x1c\\x10\\x82\\x89V\\xa3#q\\xbe`[W\\xca\\x91\\x99 \\xe5u\\xf6\\x81~\\x9e9\\x1d\\xa4\\xb4K\\xb2\\xfb5[\\xb9\\xcdQ6M\\x09+\\xb5\\x10\\x1b(\\x81\\xa0\\xc7\\xcb\\xbf5vkd\\x8a,\\x86O\\x22\\x84\\xf1O\\x1a\\x996\\x96\\xe5\\xf5\\x08\\xa33\\xf9I\\xac\\xbf\\x00\\x00\\x00\\xff\\xffT\\x8f;\\x0e\\xc20\\x10D{..."] [severity "ERROR"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "9"] [tag "OWASP_CRS/LEAKAGE/SOURCE_CODE_ASP_JSP"] [tag "WASCTC/WASC-13" [hostname "hostname.com"] [uri "/category/beauty/"] [unique_id "VtRql38AAAEAAFxbFQYAAAAY"]
`

**Comment by dune73** [comment]
@avifatal, I can not really tell you where your RESPONSE_BODY contains the said regex, but I am sure with close to absolute certainty that it's there.

I suggest you disable this rule for this path on the RESPONSE_BODY. i.e.:

      # ModSec Rule Exclusion: 970903 : ASP/JSP source code leakage (severity: 4 ERROR)
      # -> Disable rule for RESPONSE_BODY on given path
      SecRule REQUEST_FILENAME "@beginsWith /category/"\ 
      "phase:2,nolog,pass,id:10000,ctl:ruleRemoveTargetById=970903;RESPONSE_BODY"

If this is still too broad, you can chain the rule with a hostname pre-condition, which limits it's scope to a single hostname.
