### ISSUE TITLE
Modsecurity regex and filename

### ISSUE THREAD

**Issue by vincentcox** [SpiderLabs/owasp-modsecurity-crs#302]
I am trying to create modsecurity rule which needs to block a request when a parameter doesn't meet a certain regex.
Let's take an email regex as example:` (^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)` 
and for the parameter: email
location of the page (needs to be included in the rule): /signup.php 
So if someone posts a get request like: "/signup.php?email=alert..." it will be blocked. 
What should this rule look like?
This is what I tried:
`SecRule FILES_NAMES|FILES "['/signup.php";=]" ARGS:email "!@rx ^(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)$" block`

**Comment by csanders-git** [comment]
Hey @vincentcox ,here you would need to chain the rules together. something ike
SecRule REQUEST_URI "@contains signup.php" "id:1,t:none,block,chain"
SecRule ARGS:email "!@rx wtvr" "t:none"

**Comment by vincentcox** [comment]
```
SecRule REQUEST_URI "@contains signup.php" "id:1,t:none,block,chain"
SecRule ARGS:email "!@rx ^/(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)/" "t:none"
```
doesn't seem to work (it still passes ?email=illegal// )

**Comment by vincentcox** [comment]
the regex seems to work though... https://regex101.com/r/pB1qA3/1

**Comment by csanders-git** [comment]
try separating the rules and testing them one at a time seeing if they trigger.. i just wrote that on the fly, didn't test it :)

**Comment by vincentcox** [comment]
Phew, after some time trail and error'ing I found something that worked:
```
SecRule REQUEST_URI "@contains signup.php" "id:1,phase:2,log,deny,status:503,msg:'custom email hack detected',chain"
SecRule ARGS:email "!@rx (^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)" "t:none"
```

Thanks for pointing me in the right direction! This thread can be closed!
