### ISSUE TITLE
language-mutli typo

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#303]
Many rules have a typo `tag:'language-mutli'`, do a simple search/replace to `multi`.

**Comment by zinoe** [comment]
I will look into this. Please assign.

**Comment by csanders-git** [comment]
Wow this is totally my fault, sorry guys - should be a simple find and replace but again - sorry.

**Comment by csanders-git** [comment]
@zinoe, do you want to be assigned this?

**Comment by zinoe** [comment]
@csanders-git yes, please assign

**Comment by dune73** [comment]
@csanders-git I tried to assign @zinoe, but github would not let me. 
(When doing "Assign somone to this issue", his name simply did not show up and when typed, it could not be highlighted for selection)

Is this a permission problem?

**Comment by csanders-git** [comment]
@dune73 not quite sure where the problem is i have the same issue

**Comment by zinoe** [comment]
@dune73 @csanders-git 

A quick search did not bring up anything substantial.

from: https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/

> You can only create assignments for yourself, collaborators on personal projects, or members of your organization with read permissions on the repository.

What type of repository is this? Do I probably need to be a member or collaborator?

**Comment by csanders-git** [comment]
Thanks for the merge @zinoe, i'm closing this issue. Keep up the good work. If you're curious about other ways to get involved reach out to me or @dune73 -- or just join the IRC channel :)
