### ISSUE TITLE
981319 -- Severity and anomaly score don't match

### ISSUE THREAD

**Issue by std0ut** [SpiderLabs/owasp-modsecurity-crs#304]
Haven't checked v3, but in 2.2.9 for CRS_41_sqli, rule 981319 shows a severity of "2" (critical), but the anomaly score is only incremented by the "notice" score when the rule matches.

**Comment by csanders-git** [comment]
This is also present in 3.0.0-rc1.

**Comment by csanders-git** [comment]
Looks like this issue has been with us for a long time. would you like to submit a pull request for the change or would you like me to @std0ut ?

**Comment by std0ut** [comment]
Hi Chaim, 

If you don't mind, it might be better/faster if you do it, since I'm a relative github newb...

**Comment by csanders-git** [comment]
I can do it - Thank you for reporting it - i'll mention you in my pull :).

**Comment by csanders-git** [comment]
Patched thank you @std0ut
