### ISSUE TITLE
Process to update GeoLiteCity.dat regularly

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#305]
We should update `crs/util/geo-location/GeoLiteCity.dat`. The new one is 1.9MB and the version in CRS is 1.7MB.

Since IPv4 space is depleted, there is a lot of movement in geolocations due to address trading, so we should create a process to keep it regularly updated.

**Comment by csanders-git** [comment]
I'll keep this open because as soon as we get the regression tests working we can make that part of it -- Actually i'm going to spin up an instance for testing CRS right now - i'll send you an email soon. Updated the existing one though :)

**Comment by dune73** [comment]
Cool

**Comment by csanders-git** [comment]
I've written a quick script that pulls down the latest repo and then also the latest maxmind. It will fail if they are out of sync. @lifeforms What do you think, should I automate the replacement or depend on us in order to fix it manually?

**Comment by csanders-git** [comment]
I've implemented checks on our buildbot but the current options are. We either supply a setup script that checks this and downloads the latest one (which i think is maybe not a 3.0 change but a 3.1 change) or we just manually update it ever release. Thoughts?

I honestly like the setup script idea but I do think that for 3.0-rc1 it is a bit much to tackle :)

**Comment by dune73** [comment]
I do not really have an opinion. Just decide on this together with @lifeforms.

**Comment by csanders-git** [comment]
@lifeforms any issue with moving this to beyond 3.0?

**Comment by lifeforms** [comment]
@csanders-git I'd still like to have a go at it and have time scheduled for it next weekend. Maybe we should have a quick IRC meet on the remaining open points and timelines?

**Comment by csanders-git** [comment]
I think that'd be great! and we can update timelines for each of these open issues and ultimate burndown goals. When are you free @dune73 / @lifeforms ?

**Comment by lifeforms** [comment]
@csanders-git I'm good every day except Friday

**Comment by csanders-git** [comment]
Lets shoot for tmrw at some point I think the real issue will be lining up your and @dune73 's schedules. I'm free pretty much any time.

**Comment by dune73** [comment]
Thursday afternoon MET sounds good. 4pm?

**Comment by lifeforms** [comment]
16:00 MET = 17:00 CEST = ack!

**Comment by csanders-git** [comment]
Reading that as 11:00am EDT - tmrw (today). I better get some sleep :) See you guys on IRC.

**Comment by lifeforms** [comment]
Going to make a simple update script so people can pull new versions if they like. If people like it, we can add more features to it later.

**Comment by csanders-git** [comment]
Possibly check out the update script I have at https://github.com/SpiderLabs/OWASP-CRS-Documentation/blob/master/install.rst

**Comment by lifeforms** [comment]
Closing this as the discussion is now going on in #464.
