### ISSUE TITLE
Run PHP rules on all URIs

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#310]
When testing against the PHP rules in CRS 3, I found a lot of false negatives.

Part of this is because the CRS does a pre-check on the request URL in rule 933000. If the URL does not end in some extensions, the checks are skipped:

```
SecRule REQUEST_BASENAME "!@pm .php .phps .php4 .php5 .inc .phtml .tpl .cgi" \
        "phase:request,\
        t:none,t:lowercase,\
        nolog,\
        pass,\
        tag:'application-multi',\
        tag:'language-PHP',\
        tag:'platform-multi',\
        tag:'attack-PHP injection',\
        id:'933000',\
        skipAfter:END_PHP_CHECKS"
```

URLs ending in `.php` are a rare sight today. Modern PHP frameworks generate pretty URLs and use rewriting. So we must assume that any URL is possibly routed to a PHP script.

I recommend to run the PHP rules on all URLs, just like we do with other injection detections.

So I'd suggest to just remove the pre-check rule and the marker.

Notes:

- I've tried to match on `SCRIPT_FILENAME` but this variable isn't always successful; plus it might be an Apache-specific variable so it might not work for other webservers.
- If we're worried about performance of this rules section, there are various avenues for improvement, like combining separate data files.

**Comment by dune73** [comment]
I never liked that skip.

To follow up on your note, maybe a switch in 900024 would make sense.

**Comment by lifeforms** [comment]
Merged the fix.
