### ISSUE TITLE
Improve PHP variable injection attack rule (958980/933130)

### ISSUE THREAD

**Issue by zinoe** [SpiderLabs/owasp-modsecurity-crs#324]
As part of the CRS3 paranoia project, we will be discussing possible [stricter siblings](https://www.owasp.org/index.php/OWASP_ModSec_CRS_Paranoia_Mode#Stricter_siblings_for_existing_rules) for some rules. The goal of this series of issues is to discuss the exact details.

This issue brings up rule 958980 (2.2.x) / 933130 (3.0.0-rc1). Information on the proposed changes can be found [here](https://www.owasp.org/index.php/OWASP_ModSec_CRS_Paranoia_Mode_Sibling_958980).

Please add your thoughts, proposals or concerns in the comment section.

**Comment by lifeforms** [comment]
Hmm, rule 933130 is [currently not chained in 3.0.0-rc1](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0.0-rc1/rules/REQUEST-33-APPLICATION-ATTACK-PHP.conf#L127).
It was probably a typo in the wiki.
This issue can be closed!
