### ISSUE TITLE
Improve PHP function injection attack rule (958977/933110)

### ISSUE THREAD

**Issue by zinoe** [SpiderLabs/owasp-modsecurity-crs#326]
As part of the CRS3 paranoia project, we will be discussing possible [stricter siblings](https://www.owasp.org/index.php/OWASP_ModSec_CRS_Paranoia_Mode#Stricter_siblings_for_existing_rules) for some rules. The goal of this series of issues is to discuss the exact details.

This issue brings up rule 958977 (2.2.x) / 933110 (3.0.0-rc1). Information on the proposed changes can be found [here](https://www.owasp.org/index.php/OWASP_ModSec_CRS_Paranoia_Mode_Sibling_958977).

Please add your thoughts, proposals or concerns in the comment section.

**Comment by lifeforms** [comment]
This has been addressed as part of the big PHP function issue #338.
For 3.0, all rules will run at standard paranoia level, but maybe based on user feedback we will introduce more paranoid rules later.
