### ISSUE TITLE
Improve OS command injection attack rule (950907/932100)

### ISSUE THREAD

**Issue by zinoe** [SpiderLabs/owasp-modsecurity-crs#327]
As part of the CRS3 paranoia project, we will be discussing possible [stricter siblings](https://www.owasp.org/index.php/OWASP_ModSec_CRS_Paranoia_Mode#Stricter_siblings_for_existing_rules) for some rules. The goal of this series of issues is to discuss the exact details.

This issue brings up rule 950907 (2.2.x) / 932100 (3.0.0-rc1). Information on the proposed changes can be found [here](https://www.owasp.org/index.php/OWASP_ModSec_CRS_Paranoia_Mode_Sibling_950907).

Please add your thoughts, proposals or concerns in the comment section.

**Comment by csanders-git** [comment]
I think that this should be closed in favor of the EXTREMELY well put together
https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/318
thoughts?

**Comment by lifeforms** [comment]
@csanders-git Yeah, stricter siblings will be a focus in solving #318. It's one of the possible approaches. I'll do some more benchmarking and tweaking and then we can decide. Let's close this one and continue over there!

**Comment by dune73** [comment]
Makes sense.
