### ISSUE TITLE
Improve SQL injection attack rule (950001/942150)

### ISSUE THREAD

**Issue by zinoe** [SpiderLabs/owasp-modsecurity-crs#328]
As part of the CRS3 paranoia project, we will be discussing possible [stricter siblings](https://www.owasp.org/index.php/OWASP_ModSec_CRS_Paranoia_Mode#Stricter_siblings_for_existing_rules) for some rules. The goal of this series of issues is to discuss the exact details.

This issue brings up rule 950001 (2.2.x) / 942150 (3.0.0-rc1). Information on the proposed changes can be found [here](https://www.owasp.org/index.php/OWASP_ModSec_CRS_Paranoia_Mode_Sibling_950001).

Please add your thoughts, proposals or concerns in the comment section.

**Comment by dune73** [comment]
942150 is a PL2 rule that does a @.pmf and then a chained regex. The idea is to look into a stricter sibling for this rule at PL3 or PL4.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
