### ISSUE TITLE
False positive with SMF Forum System

### ISSUE THREAD

**Issue by WHK102** [SpiderLabs/owasp-modsecurity-crs#331]
[Tue Apr 05 15:01:25.067849 2016] [:error] [pid 26326] [client 190.101.13.170] ModSecurity: Access denied with code 403 (phase 2). Pattern match "\\\\W{4,}" at ARGS:admin_pass. [file "/home/androidlatinos/crs/activated_rules/modsecurity_crs_40_generic_attacks.conf"] [line "37"] [id "960024"] [rev "2"] [msg "Meta-Character Anomaly Detection Alert - Repetative Non-Word Characters"] [data "Matched Data: ********** found within ARGS:admin_pass: **********"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "8"] [hostname "androidlatinos.com"] [uri "/index.php"] [unique_id "VwP9dRs57cRZtOmSKcwYtwAAABs"]

The admin panel send a mask of password and other field with real password.

**Comment by dune73** [comment]
Handling false positives is a standard when working with the Core Rules. Please check the documentation on how to disable this rule in this specific case.

I suggest     
```
SecRuleUpdateTargetById 960024 "!ARGS:admin_pass"
```

(to be placed _after_ the CRS include.-
