### ISSUE TITLE
modsecurity_crs_46_av_scanning.conf huge performance problem

### ISSUE THREAD

**Issue by Matesack** [SpiderLabs/owasp-modsecurity-crs#336]
Hi,

 we installed mod_security few weeks ago, just to use it for upload file av scan. We have 5 webnodes with apache and we are using only this one rule modsecurity_crs_46_av_scanning.conf. But the use cases with upload fields in our application are now terribly slow. Before mod_security it took 10 seconds for form with 10 fields for upload and now with this rule and mod_Security on is takes 1minute and 20 seconds. Can somebody help us with this performance issue? 

Thanks a lot!

**Comment by csanders-git** [comment]
You need to keep in mind what is happening - It is actually running through a user land AV. This will ALWAYS be slow. In general though you should check your server performance metrics and try to determine if you AV can be made to run faster.
