### ISSUE TITLE
OWASP CRS 3.0.0 RC1 Master Ticket

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#343]
Please add issues that you think need to be addressed

**Comment by csanders-git** [comment]
Please note that I am using ZenHub to organize this.

**Comment by dune73** [comment]
My take are basically all the remaining stricter siblings:
- #321 (pull request waiting)
- #323 (almost done, but feedback/confirmation needed)
- #322 
- #324 (Walter?)
- #325 (Walter?)
- #326 (Walter?)
- #327 
- #328 

I think these need to go into an RC1. The rest can probably wait until after the RC1:

I think the testing needs to be sorted out.
Like Walter, I would like use to provide better documentation.

Generally, I would rather have a major release when it's ready and we are sure it's ready. Then rushing it without enough testing.

**Comment by lifeforms** [comment]
Quick additions:

- #273 
- #289 
- #294 
- #305
- #318 
- #338

I'll go through the open issues this weekend to check for stuff that's missing or can be closed already.

**Comment by dune73** [comment]
Not yet, an issue, but the multiple RESPONSE-50-* files should be renamed to make them distinguishable from one another.

Also, I am not 100% convinced, that adding a "9" in front of these numbers in the filenames would be such a bad idea. It may be a bit irritating at first sight, but as soon has you have seen an actual rule with it's ID, it would make sense immediately.

Furthermore, I would like to have a consistent rule layout across all the files. The actions should come in the same order in every rule. Order to be defined. Talked to @csanders-git about this lately.

**Comment by lifeforms** [comment]
YAY on rule layout and formatting.

I also want the QA tool working before we start user testing (I just learned a bit of Python so I can take this over if Chaim doesn't have the time for it) and a good test set.

**Comment by dune73** [comment]
CRS 3.0rc1 uses the multimatch action in 3 rules. I think this needs to be revised. There must be more instances, where this is useful.

WIth paranoia mode and more stats, it might be useful for CRS to make good use of the accuracy and maturity fields.

**Comment by csanders-git** [comment]
@lifeforms I can share with you what I have now. You can tell me what you think.

@dune73 - I think you're right it would be good to use all the features to better describe rules.

**Comment by dune73** [comment]
I did a parallel install of CRS 2.2.X and 3.0rc1. There are surprisingly few id collisions. By sorting out RESPONSE-50-* files, we can make all of them go away, which I think would be highly beneficial.
(What I do in my parallel setup is sending 20% of requests to CRS 2.2.X, 20% to CRS 3.0rc1->PL1, 20% to CRS 3.0rc1->PL2, etc.)

**Comment by lifeforms** [comment]
My final sweep:

#319
#382
#383
#368
#381

**Comment by lifeforms** [comment]
#384

**Comment by csanders-git** [comment]
I have made major strides on the documentation portion today. The major remaining sections are 'exceptions', 'configuration', and 'anomaly mode'; I hope to have these done by tmrw.
https://github.com/SpiderLabs/OWASP-CRS-Documentation/

**Comment by csanders-git** [comment]
I am closing this issue in favor of the Milestone feature of Github -- We were young and didn't understand :)
