### ISSUE TITLE
Improve DoS protection rules against race condition (981048/912040)

### ISSUE THREAD

**Issue by loudly-soft** [SpiderLabs/owasp-modsecurity-crs#346]
It has been reported in the [owasp-modsecurity-core-rule-set mailing list](https://lists.owasp.org/pipermail/owasp-modsecurity-core-rule-set/2013-September/001449.html) that the DOS protection rules can trigger false positives.  The audit log would report:

> Warning. Operator GE matched 2 at IP:dos_burst_counter. [file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_crs_11_dos_protection.conf"] [line "44"] [id "981049"] [msg "Potential Denial of Service DoS)  Attack from X.X.X.X - # of Request Bursts: 5"]

However, counting the actual number of requests made by the IP during the purported burst time slice in Apache access_log, the number would show that it's less than the specified burst counter threshold (`tx.dos_counter_threshold`) so it's a false alarm.

While the report was submitted 3 years ago in 2013, I'm encountering the same problem since I started working with ModSecurity recently.  I have tracked the issue down to [rule 981048](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/master/experimental_rules/modsecurity_crs_11_dos_protection.conf) as a result of concurrent requests.  In short, `ip.dos_burst_counter` would jump from 0 to ≥ 2 while handling concurrent requests, therefore, causing a block erroneously.  The gory details can be found on my [blog](http://loudly-soft.blogspot.fi/2016/05/modsecurity-anti-automation-rule-set_27.html).  In the meantime, I have patched the problem by replacing rule 981048 with 2 chained rules to ensure that `ip.dos_burst_counter` doesn't jumped from 0 to ≥ 2 and trigger a false alarm.

```
#
# Check DOS Counter (Tick)
# If the request count is greater than or equal to user settings,
# we then set the burst counter to 1 if it's 0
# 
SecRule IP:DOS_COUNTER "@ge %{tx.dos_counter_threshold}" "chain,phase:5,id:'981048',t:none,nolog,pass"
SecRule &IP:DOS_BURST_COUNTER "@eq 0" "setvar:ip.dos_burst_counter=1,expirevar:ip.dos_burst_counter=%{tx.dos_burst_time_slice},setvar:!ip.dos_counter"

#
# Check DOS Counter (Tock)
# If the request count is greater than or equal to user settings,
# we then set the burst counter to 2 if it's 1
# 
SecRule IP:DOS_COUNTER "@ge %{tx.dos_counter_threshold}" "chain,phase:5,id:'981050',t:none,nolog,pass"
SecRule &IP:DOS_BURST_COUNTER "@ge 1" "setvar:ip.dos_burst_counter=2,expirevar:ip.dos_burst_counter=%{tx.dos_burst_time_slice},setvar:!ip.dos_counter"
```

So far, the patch has been working on my server (in detection mode) with ModSecurity 2.8.  I'm wondering if anybody else has bumped into this problem and came up with a fix.  If not, does anyone see anything wrong with my patch?   Thanks in advance.

**Comment by dune73** [comment]
@loudly-soft Thank for this detailed analysis. Unfortunately, your issue came in after the Pull Request for the DoS rule overhaul was submitted. That new DoS rules are now part of CRS3 and I suspect they still carry the error. I do not have the time to set up a test scenario. If you are still interested in helping us to fix this, then please try it out against CRS3.

**Comment by csanders-git** [comment]
Hmm this is actually something we should carefully consider -- good blog post. As @zimmerle is fond of noting, local collections have all sorts of underlying problems with timing when using threaded web servers. The suggestion made in the blog may (probably will) still be applicable for the updated rules.

**Comment by loudly-soft** [comment]
Sorry guys, web security isn't my line of work so my contribution will be limited.  Having said that, I spent some time today coding this PHP test script.  I tested it against CRS3 on ModSecurity 2.8 and I see the same problem (on Amazon EC2 AMI linux).  I don't have time to install and test against the newer versions of ModSecurity.  I’m guessing unless the rules are atomic in the newer versions, the results will be the same.

``` php
<?php
/**
 * This PHP script contains 2 tests for OWASP CRS-3 DOS protection rules.
 * The first test attempts to trigger false positives due to race condition.
 * The second test triggers false positives when paranoid level is higher than 1.
 *
 * It assumes the following values are set in crs-setup.conf for test 1:
 *
 *    setvar:'tx.dos_burst_time_slice=10'
 *    setvar:'tx.dos_counter_threshold=30'
 *    setvar:'tx.dos_block_timeout=90'
 * 
 * By above definition, a qualifying burst contains 30 requests in a 10 second interval.
 *
 * For test 2, the following additional value is assumed in crs-setup.conf:
 *
 *    setvar:tx.paranoia_level=2
 *
 * Both tests will attempt to trigger false positives without producing such bursts.
 *
 * Before running the script, set the url variable to a web server IP address.
 * When the script runs, a partial response header is printed on screen for each request:
 *
 *    response#1: HTTP/1.1 200 OK
 *
 * If there are no false positives, all responses should return "HTTP/1.1 200 OK".
 *
 * Before running the script again, clear the following files to reset ModSecurity internal counters:
 *
 *    ip.pag
 *    ip.dir
 *    global.dir
 *    global.pag
 *
 */

$url = "http://X.X.X.X/";


function flood($url, $totalBots, $idx) {
    $idx = $totalBots * $idx + 1;

    // create the multiple cURL handle
    $mh = curl_multi_init();
    $chs = array();
    for ($i=0; $i<$totalBots; $i++) {
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HEADER, true);
        curl_setopt($ch, CURLOPT_FRESH_CONNECT, true);
        curl_multi_add_handle($mh, $ch);
        $chs[] = $ch;
    }

    // execute the handles
    $running = null;
    do {
        curl_multi_exec($mh, $running);
    } while ($running);

    // close the handles
    foreach ($chs as $ch) {
        curl_multi_remove_handle($mh, $ch);
    }
    curl_multi_close($mh);

    // retrieve response and output header
    foreach ($chs as $i=>$ch) {
        $response = curl_multi_getcontent($ch);
        echo "response#" . ($idx+$i) . ": " . substr($response, 0, 15);
        echo "\n";
    }
}


/**
 * The first test attempts to trigger race condition.
 */
echo "running test#1...\n";

// send 29 requests with 1 second interval in between
for ($i=0; $i<29; $i++) {
    flood($url, $totalBots=1, $i);
    sleep(1);
}

// sleep for longer than dos_burst_time_slice (10) seconds
sleep(15);

// send 5 consecutive bursts, each burst has 5 simultaneous requests
for ($i=0; $i<5; $i++) {
    // if you're (un)lucky, requests are blocked
    flood($url, $totalBots=5, $i);
}


/**
 * sleep for longer than dos_block_timeout (90) seconds before running next test
 */
echo "sleeping 100 seconds to reset ModSecurity counters...\n";
sleep(100);


/**
 * The second test attempts to trigger a false positive when PL>1
 */
echo "running test#2...\n";

// send 40 requests with 1 second in between.
for ($i=0; $i<40; $i++) {
    // 32nd request and on are blocked
    flood($url, $totalBots=1, $i);
    sleep(1);
}
```

**Comment by dune73** [comment]
Thank you very much @loudly-soft.

This will do. I'll assign to myself and dig into it again.

**Comment by dune73** [comment]
The proposed fix by @loudly-soft is part of the PR #735 aiming to be part of CRS 3.0.1.

**Comment by lifeforms** [comment]
Discussion on IRC: @franbuehler and @lifeforms will do a quick test if DDoS checks are working well, if so will merge for 3.0.1.

**Comment by lifeforms** [comment]
Closing this in favor of the PR #735, please continue any discussion there! Thanks for the report!
