### ISSUE TITLE
Rule 981245 triggers false positives on certain "complex" cookie values

### ISSUE THREAD

**Issue by OrySegal** [SpiderLabs/owasp-modsecurity-crs#35]
The following section of the regular expression:

(?:[\"'`´’‘]\s*?[^?\w\s=.,;)(]+\s*?[(@\"'`´’‘]_?\s_?\w+\W+\w)

Will match on the following values:
- "|name=value"
- "-1<2"
- '-a-b-c'

And so forth.

I'm nor certain what this specific section is trying to achieve, so I can't offer a fix.

**Comment by dune73** [comment]
With the renumbering taking place, 981245 is now 942260.

In the end, @rcbarnett's idea was not put into practice. But the rule has been moved to Paranoia Level 2 and is thus no longer part of the default installation. At PL2, we expect people to be able to handle casual false positives.

If the regex is still a widspread problem, we need to investigate further, but for now, I am closing this.
