### ISSUE TITLE
Test suite for the rule sets?

### ISSUE THREAD

**Issue by agentzh** [SpiderLabs/owasp-modsecurity-crs#350]
Sorry if I've missed anything obvious, but is there an official test suite for all the rules in this repository? It would be the best way to validate every single rule here I think :)

**Comment by csanders-git** [comment]
We are working on that actively. Currently there are some regression tests and we are developing a new one currently see https://github.com/fastly/ftw. If you want to help we are always looking for more tests.

**Comment by agentzh** [comment]
@csanders-git Thanks for the link! We'll see what we can do about adding more tests :)

**Comment by dstelter** [comment]
I have also built a test runner (incidentally also in Python) that can run a custom ModSecurity test suite (derived during development to verify edge cases of the implementation) as well as compare the detection results of two implementions (ModSecurity and your own one, usually).

I haven't found time yet to clean it up for publishing (MIT), but if anyone's interested I'll happily share preliminary results. Just drop me a PM. :-)

**Comment by dune73** [comment]
@dstelter You have a custom rule language implementation? Public?
