### ISSUE TITLE
docker wordpress

### ISSUE THREAD

**Issue by mokrea** [SpiderLabs/owasp-modsecurity-crs#356]
Hi,

I installed modsecurity on wordpress in docker. (docker run --name test -p 80:80 wordpress)

and I installed modsecurity 
apt-get update && apt-get install libapache2-mod-security2

I added owasp-modsecurity-crs and when I tried access the browser I received a Forbidden message. (http://teste.ifpr.edu.br)

modsec_audit.log output:

tail -f /var/log/apache2/modsec_audit.log                                                                                          
Action: Intercepted (phase 2)
Stopwatch: 1466017940579444 3912 (- - -)
Stopwatch2: 1466017940579444 3912; combined=3301, p1=170, p2=3096, p3=0, p4=0, p5=35, sr=11, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.8.0 (http://www.modsecurity.org/); OWASP_CRS/2.2.9.
Server: Apache/2.4.10 (Debian) PHP/5.6.21
Engine-Mode: "ENABLED"

--2d22456f-Z--

--6c46de64-A--
[15/Jun/2016:19:15:48 +0000] V2GpZKwRAAMAAACrSGIAAAAC 200.17.98.254 52849 172.17.0.3 80
--6c46de64-B--
GET / HTTP/1.1
Host: teste.ifpr.edu.br
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,pt;q=0.6,fr;q=0.4,it;q=0.2,es;q=0.2
Cookie: _ga=GA1.3.2017482713.1436368224; wordpress_test_cookie=WP+Cookie+check; wordpress_logged_in_792692138800b5a0ef4cb6777deb67d2=admin%7C1466187911%7CB7l8QU99Rb0u2VZdQ2xtMxlVpxTUmGpCTq9qxoBEdFw%7Ce04b36c5aed2a490ad64e342a5e93c36ed87c187050f92b0b9956905b01a4548; wp-settings-1=editor%3Dhtml%26align%3Dcenter%26m9%3Do%26m4%3Do%26m5%3Do%26m8%3Dc%26m7%3Dc%26m6%3Do%26libraryContent%3Dbrowse; wp-settings-time-1=1466015126; __utma=204504520.2017482713.1436368224.1465995503.1466015848.12; __utmb=204504520.2.10.1466015848; __utmc=204504520; __utmz=204504520.1465924753.9.3.utmcsr=teste.ifpr.edu.br|utmccn=(referral)|utmcmd=referral|utmcct=/; __utma=114453378.2017482713.1436368224.1465927692.1466015848.4; __utmb=114453378.2.10.1466015848; __utmc=114453378; __utmz=114453378.1465913152.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _pk_id.1.ccf3=39c958f60d1fb22f.1465913152.4.1466017032.1466015848.; _pk_ses.1.ccf3=*

--6c46de64-F--
HTTP/1.1 403 Forbidden
Content-Length: 209
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1

--6c46de64-E--

--6c46de64-H--
Message: Access denied with code 403 (phase 2). Pattern match "([\\~\\!\\@\\#\\$\\%\\^\\&\\*\\(\\)\\-\\+\\=\\{\\}\\[\\]\\|\\:\\;\"\\'\\\xc2\xb4\\\xe2\x80\x99\\\xe2\x80\x98\\`\\<\\>].*?){8,}" at REQUEST_COOKIES:wp-settings-1. [file "/etc/modsecurity-crs/base_rules/modsecurity_crs_41_sql_injection_attacks.conf"] [line "157"] [id "981172"] [rev "2"] [msg "Restricted SQL Character Anomaly Detection Alert - Total # of special characters exceeded"] [data "Matched Data: & found within REQUEST_COOKIES:wp-settings-1: editor=html&align=center&m9=o&m4=o&m5=o&m8=c&m7=c&m6=o&libraryContent=browse"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "8"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"]
Action: Intercepted (phase 2)
Stopwatch: 1466018148675611 4585 (- - -)
Stopwatch2: 1466018148675611 4585; combined=3493, p1=328, p2=3127, p3=0, p4=0, p5=38, sr=26, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.8.0 (http://www.modsecurity.org/); OWASP_CRS/2.2.9.
Server: Apache/2.4.10 (Debian) PHP/5.6.21
Engine-Mode: "ENABLED"

--6c46de64-Z--

--bf0ce859-A--
[15/Jun/2016:19:15:49 +0000] V2GpZawRAAMAAACrSGMAAAAC 200.17.98.254 52849 172.17.0.3 80
--bf0ce859-B--
GET /favicon.ico HTTP/1.1
Host: teste.ifpr.edu.br
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
Accept: */*
Referer: http://teste.ifpr.edu.br/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,pt;q=0.6,fr;q=0.4,it;q=0.2,es;q=0.2
Cookie: _ga=GA1.3.2017482713.1436368224; wordpress_test_cookie=WP+Cookie+check; wordpress_logged_in_792692138800b5a0ef4cb6777deb67d2=admin%7C1466187911%7CB7l8QU99Rb0u2VZdQ2xtMxlVpxTUmGpCTq9qxoBEdFw%7Ce04b36c5aed2a490ad64e342a5e93c36ed87c187050f92b0b9956905b01a4548; wp-settings-1=editor%3Dhtml%26align%3Dcenter%26m9%3Do%26m4%3Do%26m5%3Do%26m8%3Dc%26m7%3Dc%26m6%3Do%26libraryContent%3Dbrowse; wp-settings-time-1=1466015126; __utma=204504520.2017482713.1436368224.1465995503.1466015848.12; __utmb=204504520.2.10.1466015848; __utmc=204504520; __utmz=204504520.1465924753.9.3.utmcsr=teste.ifpr.edu.br|utmccn=(referral)|utmcmd=referral|utmcct=/; __utma=114453378.2017482713.1436368224.1465927692.1466015848.4; __utmb=114453378.2.10.1466015848; __utmc=114453378; __utmz=114453378.1465913152.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _pk_id.1.ccf3=39c958f60d1fb22f.1465913152.4.1466017032.1466015848.; _pk_ses.1.ccf3=*

--bf0ce859-F--
HTTP/1.1 403 Forbidden
Content-Length: 220
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1

--bf0ce859-E--

--bf0ce859-H--
Message: Access denied with code 403 (phase 2). Pattern match "([\\~\\!\\@\\#\\$\\%\\^\\&\\*\\(\\)\\-\\+\\=\\{\\}\\[\\]\\|\\:\\;\"\\'\\\xc2\xb4\\\xe2\x80\x99\\\xe2\x80\x98\\`\\<\\>].*?){8,}" at REQUEST_COOKIES:wp-settings-1. [file "/etc/modsecurity-crs/base_rules/modsecurity_crs_41_sql_injection_attacks.conf"] [line "157"] [id "981172"] [rev "2"] [msg "Restricted SQL Character Anomaly Detection Alert - Total # of special characters exceeded"] [data "Matched Data: & found within REQUEST_COOKIES:wp-settings-1: editor=html&align=center&m9=o&m4=o&m5=o&m8=c&m7=c&m6=o&libraryContent=browse"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "8"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"]
Action: Intercepted (phase 2)
Stopwatch: 1466018149156873 4090 (- - -)
Stopwatch2: 1466018149156873 4090; combined=3309, p1=185, p2=3087, p3=0, p4=0, p5=36, sr=12, sw=1, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.8.0 (http://www.modsecurity.org/); OWASP_CRS/2.2.9.
Server: Apache/2.4.10 (Debian) PHP/5.6.21
Engine-Mode: "ENABLED"

--bf0ce859-Z--

**Comment by lifeforms** [comment]
Hi @mokrea,

it seems that the WordPress cookie is hitting CRS rule 981172. The cookie value has many special characters, which can be an indication of an attack. That's clearly not the case though, so it's a false positive. False positives happens from time to time, which is why we're working on CRS3, which should improve by a lot! But, that's not out yet, so for now, the best thing is probably to make a whitelist entry for this cookie in your Apache configuration.

For instance, you can add this to your Apache configuration:

```
SecAction \
	"id:1234567,phase:1,t:none,nolog,pass,\
		ctl:ruleRemoveTargetById=981172;REQUEST_COOKIES:wp-settings-1"
```

This will make sure that rule 981172 will ignore this specific cookie.

You can repeat this process for other cookies and parameters if you run into other false positives.

**Comment by mokrea** [comment]
@lifeforms 

Thanks
