### ISSUE TITLE
Rule ids with quotes and rule ids without quotes

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#360]
Either we go with quotes, or we go without quotes. Right now the system is mixed.

**Comment by csanders-git** [comment]
i'd say we go without quotes... putting quotes around it leads to the thought that they can be numeric (which won't break modsec, but will break secruleremovebyid range)

**Comment by dune73** [comment]
Exactly my thought. Thanks.

**Comment by csanders-git** [comment]
i'll track down all the offenders today and make a P/R

**Comment by dune73** [comment]
Wow. You are swift!

**Comment by csanders-git** [comment]
Closing due to merge.
