### ISSUE TITLE
Small issues with 3.0.0 (re-)numbering

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#361]
@csanders-git did the right thing with the renumbering and luckily (or by employing a very smart system), we are in a situation where it is almost possible to load CRS 2.2.9 and 3.0.0rc1 in parallel with no rule id collisions (which is in fact very neat for the transition from 2.2.9 to 3.0.0).

Very few collisions persists and I think we could get rid of them easily:
* 950011: Paranoia branching rule in RESPONSE-50. Find different empty ID close by.
* 950012: dito
* 950018: dito
* 950110: Rule collision in one of the rules in RESPONSE-50-DATA-LEAKAGES.conf: Find different empty ID close by.
* 950120: Rule collision in one of the rules in RESPONSE-50-DATA-LEAKAGES-IIS.conf: Rename rule file.

The last collision points to the fact, that we have 4 files with the number 50 in the with no apparent reason. I think the 4 specific leakage files should be moved to 52, 53 and 54.

Usually, the numbers of the SecRules in a file start with 9XX100. There are a few exceptions:

* 910000: odd numbered rule
* 912000: odd numbered rule
* 941000: odd numbered rule
* 912010: odd numbered rule
* 912020: odd numbered rule
* 950021: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950022: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950023: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950024: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950025: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950026: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950027: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950028: paranoia branch (due to multiple RESPONSE-50 rule files)
* 912030: odd numbered rule
* 950031: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950032: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950033: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950034: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950035: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950036: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950037: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950038: paranoia branch (due to multiple RESPONSE-50 rule files)
* 912040: odd numbered rule
* 950041: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950042: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950043: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950044: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950045: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950046: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950047: paranoia branch (due to multiple RESPONSE-50 rule files)
* 950048: paranoia branch (due to multiple RESPONSE-50 rule files)

That's all that sprang to my mind.

I'd like to do a pull request which fixes these issues (and updates the re-numbering index file of course).

What do you think?

**Comment by csanders-git** [comment]
I think this is a great idea -- perhaps with the labeling of platform it might be less useful to have file 50 split out ... then again it makes it easy to disable it however we can disable based on tag. Of course the easier way is simply to relabel them as different numbered files (as you suggested). Either way I think it should be pretty straight forward. Def worth the PR, good insight

**Comment by dune73** [comment]
Thanks for the thumbs-up. Will prepare PR.

**Comment by csanders-git** [comment]
you may wish to wait a few minutes till I push the quote/nonquote PR since it will conflict slightly (maybe) but eitherway

**Comment by dune73** [comment]
Yes, absolutely. And the PR for this one should go over quickly as well. It touches on too many things.

**Comment by dune73** [comment]
I'll hold back with the PR until #359 is merged or there will be conflicts.

**Comment by csanders-git** [comment]
I think this is ready to be closed :)
