### ISSUE TITLE
setup.conf: use phase:1 instead of phase:request?

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#364]
In an earlier version of PR #359, I hit a bug, as the setup.conf variable (900015) only had effect when it was set in `phase:1` instead of `phase:request`. Rule 912021 is checking this variable in phase:1, so the setup.conf variable had to be in `phase:1` too, otherwise the variable is not yet set.

At an earlier time, I've also experienced a problem with setup.conf variables being inactive. This problem had the exact same mechanism but different circumstances. (I had symlinked all the rule files in one dir, and uppercased `REQUEST/RESPONSE` files in CRS3 were sorted above my `modsecurity_crs_10_setup.conf`. This caused the CRS to run through phase 2 *before* the setup.conf was run. Arguably the last case was user incompetence...)

Whichever you may judge the causes ;) Using `phase:1` in setup.conf prevented breakage/bypass. I think using `phase:request` in setup.conf might make the CRS more brittle than it needs to be.

We would really have to be careful never to ever use `phase:1` in the CRS. But @dune73 introduced a rule in it, and it might happen again, maybe we will even need phase:1 rules for special reasons (I don't know if it's needed in DoS rule case though I imagine if a user has separated the phases, using phase:1 will help them drop an attacker faster). Maybe we should change rule 912021, but I think we should consider looking at the setup too. We might miss the next instance of this problem.

The new setup.conf style is to use `phase:request` everywhere while setting variables, but in my opinion we should consider reverting to use `phase:1` as an extra security measure, so that the variables are always set first. Or maybe we should forbid any CRS rule to use phase:1? Maybe we should apply both measures? In any case, mixing the two phases in setup.conf seems ugly and hard to understand for a user.

**Comment by dune73** [comment]
Thank you for opening this discussion.

I am all for phase:1 for all variables.

Personally I also think people should not work with setup.conf at all, but that's a different topic. 

I'm very skeptical with regards to using "phase:request" instead of "phase:2", but I am OK with using this as it is the convention now. But there are going to be more rules in phase:1 in the future (e.g.,  anomaly score check at the end of phase 1) and this only works with all the variables being available from the start.

**Comment by csanders-git** [comment]
My major concern is that we document whatever our decision is. Generally I think request/response makes it slightly more readable and therefore i'd prefer that where possible. Of course if it makes sense to change all of setup.conf for usability issues that is something we should do as long as we make sure to document the preferred usage of rules along with the reasons for deviation within setup.conf

**Comment by lifeforms** [comment]
PR is in #378.

**Comment by lifeforms** [comment]
PR accepted, thanks for the review Chaim!
