### ISSUE TITLE
Rule 920310 (CRS3): False positive on exotic UA

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#366]
The rule 920310 (CRS3) checks for empty Accept Header.

I am seeing now empty accept headers in production from an exotic probably ms-exchange-related user-agent::
```
Entreprise/6.5.0.177 CFNetwork/758.4.3 Darwin/15.5.0
```
It's a GET for /autodiscover/autodiscover.xml. I do not really know what this is all about, nor do I know the UA nor it's components (well, outside of Darwin, obviously).

The rule contains a chain and has a pmf operator to avoid false positives. The pmf checks for AppleWebKit and Android right now.

Possible solution:
- Move rule to higher paranoia level (Maybe it's overkill for PL 1)
- Add string to pmf: probably "CFNetwork" and not "Entreprise" as it comes with a typo, which could be fixed anytime and because Enterprise is a very broad term (unlike CFNetwork).

Thoughts?

**Comment by csanders-git** [comment]
It seems like it has something to do with apples network abstraction library. Is this coming from an IOS device? While it is a false positive is it something that warrants adding a modification to the rules for?

**Comment by dune73** [comment]
I think it must be a group of IOS devices, but I am not totally sure.

This is coming from my first CRS 3.0 prod site, where it is one of the top 5 FPs remaining (FPs way down when compared to CRS 2.2.9). The site is a public B2C drupal site with > 1M hits/d. If it happens here, it could happen to any other server as well.

We currently suppress FPs for Android, so I think handling this one is warranted as well.

**Comment by lifeforms** [comment]
If it requests /autodiscover/autodiscover.xml, it's an Outlook client trying to fetch mail server settings for the domain. The User-Agent says it's the iOS version, when you use CFNetwork on newest iOS you'll get a default User-Agent of `YourApp/YourVersion CFNetwork/758.4.3 Darwin/15.5.0`. Whitelisting seems great. I'd add `Ent(er|re)prise` in case they fix the typo later.

**Comment by dune73** [comment]
Thanks for the explanation @lifeforms. So do you advise to whitelist the following?

`@pmf AppleWebKit Android Enterprise Entreprise`

**Comment by lifeforms** [comment]
@dune73 Great!

**Comment by dune73** [comment]
PR in #367

**Comment by csanders-git** [comment]
So why is it hitting your server if its looking for outlook?

**Comment by lifeforms** [comment]
@csanders-git When Office365 users check a @foo.com email and you run http://foo.com they will do this :( I have lots of exclusion rules for them because they are hitting 404 rate limits and keep getting their office ips blocked.

**Comment by csanders-git** [comment]
i'm just not sure how generic this white list is, it seems like a pretty specific instance but i'll bow to your experience here. I would say that we shouldn't make this overly generic with enterprise AND this misspelling... I would say though that the CFNetworks bit seems to be more unique.

**Comment by dune73** [comment]
Outlook and friends do all sorts of crazy things with auto discovery. I remember one product where it was hardcoded to go to foo.example.com (forgot what foo was exactly). But foo.example.com was already taken by a different service. Hilarity ensued.

@csanders-git : I have a preference for CFNetworks as well for the same reason as you. @lifeforms?

**Comment by lifeforms** [comment]
@dune73 But CFNetwork is used by lots of clients that do send normal Accept header though, just grep a log for it, it's common for many iOS apps including Safari itself. I would recommend `Entreprise/` then, as in:

```
SecRule REQUEST_HEADERS:User-Agent "!@pm AppleWebKit Android Entreprise/" \
```

I found a bug in this rule though. Do you spot it, @dune73? I sent it to you as a gotcha for the book ;) `REQUEST_HEADERS:User-Agent` variable will only match if this variable exists. If the client did not send a User-Agent header, then the chain rule will never match. So you can evade rule 920310 by omitting the User-Agent header. So by not sending User-Agent, you can evade the Accept rule. I wonder what a good construction will be to prevent this.

**Comment by dune73** [comment]
;) That's covered in a comment in the comments to the rule. It would take a 2nd rule chain to solve that problem. So I think it is OK to say that missing User-Agent will be caught be different rule.

As for the term to add to the pmf, I feared that would be the case. `Entreprise/` is maybe a good defensive choice.

**Comment by dune73** [comment]
@lifeforms good idea. I prefer to keep this more fundamental issue separate from the little update in PR #367. I have thus opened issue #370.

We have quite a few PR open now. So let's simplify things and advance in little steps.

**Comment by csanders-git** [comment]
I think this too is closed by our recent mergers
