### ISSUE TITLE
Make setup.conf.example great again

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#368]
Discussion about possible improvements to default settings:

- [x] Shouldn't we make anomaly scoring mode the default? It's probably the best and most informative for most users. Supporting two modes means two modes need to be tested, and it adds to the maintenance. I think Christian and I both use anomaly mode, so the other mode is not really being tested regularly. It's also another difficult choice to make for a new user.
- [x] Doing a redirect as the default action causes redirect loops in case of cookie based alerts, wacky clients, weird Host headers etc., because when the client has redirected, the same conditions apply, and they will get another hit. ([User complaint about this problem](http://lists.owasp.org/pipermail/owasp-modsecurity-core-rule-set/2016-June/002177.html)) I think we should offer the redirect as a commented-out alternative to returning an error 403, but warn users of this possible problem.
- [x] The default `tx.sql_injection_score_threshold=15` seems rather high, now that we have removed a lot of rules, and we depend on detectSQLI which might only give off one alert for a complete injection. Personally I like running with 5...
- [x] The default `tx.xss_score_threshold=15` looks rather high too, the same goes here.
- [ ] Maybe we should rename this file in line with the other renamings as well? (It still contains `_10_` marker which is no longer used)

Suggestions for comment improvements:

- [ ] If we offer multiple options, we should put all the options there as examples, but commented-out, so people can just swap them in. For example: scoring mode
- [ ] References to old config file names should be replaced, like `modsecurity_crs_30_http_policy.conf`
- [ ] All non-trivial variables should have a comment or explanation.
- [x] 900022: Explain that listing countries will only give a WARNING level alert, and not block.
- [ ] Explain why we are using phase:1 in the setup. (see #364)
- [ ] Review all the rule explanations to check for further improvements.
- [ ] Review which settings are only used in PL2 or higher, and explain this in their comments, for example `tx.max_num_args`

**Comment by csanders-git** [comment]
I think this makes alot of sense -- and I love the title. I'm not sure I know what a better threshold should be though

**Comment by dune73** [comment]
Hmm. Hard questions. My problem: I do not have a qualified opinion as I do not work with setup.conf at all. Integration with the rest of the rules is not really well documented, etc.

When I look over the file I have even more concerns and the reasons I do not work with setup.conf are more fundamental. But I have a hard time writing it down. 

I'm certainly for scoring by default. I do not think default->redirect is viable unless you really know what you are doing. I do not like the granular thresholds by category, as I do not see people setting educated granular limits (I set the granular limits very high and work with the general limit afterwards). Renaming the file should go together with a better documentation for newbies ("How to get started"). I am not sure the multiple-options-in-comments idea is easier to read and work with ( but I would need to see it live to be sure). References need to be fixed of course (at least something we can all agree on), more explanations welcome. The whole block/pass should be reconsidered. Now that we have Paranoia Levels, I would move the pass stuff to higher PL and make it blocking. But maybe it's better to look at the individual rule instead of a quickfix. phase:1 for everyone! (have you guys ever thought about actually pushing all the rules which can work in phase:1 (method, headers, cookies, query string) into phase 1?. Yes we need a review. Why the exception with `tx.max_num_args`? Only because we do not need it in phase:1? It's perfectly OK to write a rule checking max number of query string arguments in phase 1.

So all in all not really a qualified opinion on this, but many grumpy prejudices.

<Taking a deap breath and pausing for 10 minutes>

I have this feeling that setup.conf comes last: When the rules are really done, the setup.conf will be much easier to write. We will have a clearer idea of what we want to do with the rules and how setup.conf can help with that standard use case.

**Comment by lifeforms** [comment]
Thanks for the comments. Yes, let's do this last.

Setting of the scoring thresholds should be a data based decision. My goal is that CRS3 sensitivity is non-inferior to CRS2. When we finish the first iteration of the rules for 3.0.0, I plan to do a big capture of positive traffic in CRS2, and replay this against CRS3 at default settings to see how the old and new scores correlate. My initial feeling is that scores for SQLi are a bit lower in CRS3, but this could be superstition.

**Comment by csanders-git** [comment]
@lifeforms and @dune73  I know we have had some discussion about even using Setup.conf. We have also had some discussion about automatic configuration scripts. Perhaps this is a situation where we (i'm willing to do it), should write a setup script that asks users questions needed to configure the setup.conf and also updates things like geoip. Thoughts?

**Comment by dune73** [comment]
@lifeforms : CRS3 scores are clearly lower right now. This has to do with the consolidation of rules, namely SQLi in favor of libinject. [https://www.netnea.com/cms/2015/12/20/modsec-crs-2-2-x-vs-3-0-0-dev/](https://www.netnea.com/cms/2015/12/20/modsec-crs-2-2-x-vs-3-0-0-dev/ ) showed this and all I have seen so far confirm this.

Right now, CRS2 compares to CRS3 with PL2-3, actually closer to 3.

I do not think this is a problem in itself as it only matters if you leave the threshold on the same level. The problem I see are new false negatives with PL1. They are clearly on my menu list.

@csanders-git : such a script could be a solution. But I would like to see it in a bigger context: Documentation, default usage scenarios, blog posts, etc. Like I said above: I feel it is too early for me to discuss these things. This is not meant to stop you, it's just that I won't be of much help.

**Comment by csanders-git** [comment]
I certainly think that the default should be changed to anomaly scoring -- esp with all the data you guys have added. Additionally the redirect can be REALLY annoying esp for new users. The only caveat to think about is that we'll run into problem where people will try and 'detect' the WAF by looking for 403 requests. I honestly don't have a problem with that I just find such things really stupid and it makes me want to push people off a cliff.

In general I think a configuration script, with strong defaults, would be really interesting as it would make understanding (along with documentation, obviously) the choices that need to be made by the end user. I know @lifeforms you have assigned this to yourself, does this mean your working on it or can I take a stab at it?

**Comment by dune73** [comment]
@csanders-git As it happens, I have a ModSec CRS reconnaissance blog post in the queue. Is this the sort of info which could push me off the cliff? Not sure I understand you correctly.

**Comment by lifeforms** [comment]
@csanders-git I assigned the setup change issues to myself to not forget it. Thanks for the input. I think a configuration script might be useful, I haven't really thought about it yet. Would it generate a setup.conf, rewrite an existing setup.conf? If you have some idea I'd love to see it. Maybe we could combine it with some upgrade function into a 'CRS tool'. (`crs setup` / `crs upgrade`)

**Comment by lifeforms** [comment]
The country list comment is not correct. It says:

```
# If you are sure, you are not getting any legitimate requests from a given 
# country, then you can disable all access from that country via this variable.
```

But in actuality the rule gives a WARNING, it's not CRITICAL. Update the comment at minimum, but we could also make the severity tweakable from the setup, since actually blocking countries would be a useful feature.

**Comment by csanders-git** [comment]
I desperately would like to use anomaly scoring by default but I think it muddles our mantra of everything can be configured out of the setup.conf as users will have to find REQUEST-49 and change the disruptive action (and RESPONSE-59 for the matter). any thoughts on how to get around this?

**Comment by lifeforms** [comment]
@csanders-git I always like a 403, and I configure a nice error page with Apache's `ErrorDocument`. The beauty of `ErrorDocument` is that it can give a friendly page, do an internal Apache redirect (so doesn't suffer) to a relative URL, or even send a 302 redirect to an absolute URL. So, I have never needed the CRS to configure this.

If we want to make this tweakable from the CRS, we *could* do it. We could add a variable for it in the setup:

```
# Which action to take when a request is blocked.
# Valid tx.block_action values are: 'error', 'redirect', 'drop'.
# - In case of 'error', the response code in tx.block_error_code is sent (often 403, 406 or 409).
#   You can use Apache's 'ErrorDocument' directive to configure a friendly error page or URL.
# - In case of 'redirect', the browser will be redirected to an absolute or relative URL,
#   by default this is the root of the current site.
# - In case of 'drop', the connection will be dropped immediately.
#   This is unfriendly to users, but might help a bit with webserver load when under heavy attack.
SecAction \
 "id:900026,\
  phase:1,\
  nolog,\
  pass,\
  t:none,\
  setvar:tx.block_action=error,\
  setvar:tx.block_error_code=403,\
  setvar:tx.block_redirect_url=/"
```

Then in REQUEST-49 and RESPONSE-59, on blocking score, we can jump to a special rule marker, which implements rules doing the following pseudocode:

```
if tx.block_action == 'redirect'
	if tx.block_redirect_url matches '^https?://'
		redirect:'%{tx.block_redirect_url}'
	else
		redirect:'//%{request_headers.host}/%{tx.block_redirect_url}'
elseif tx.block_action == 'drop'
	drop
else
	deny,status:%{tx.block_error_code}
```

This would not be completely trivial to implement though.

If we can make the jump to this rule the default in `SecDefaultAction` (not actually sure) then we could make the configurable blocking action act in the same way for non-anomaly mode too.

But, in my opinion, it could be much easier to just have the user pick one error code, defaulting to 403, and do any friendly error handling and possible redirection outside CRS.

**Comment by csanders-git** [comment]
Yeah i think that is probably the best action and 403 does seem to make the most amount of sense. Once slight wrinkle although I don't think its big enough to prevent this is that on the fedora instance of Apache the default welcome.conf file overwrites the 403 to be ErrorDocument 403 /.noindex.html which is really the default apache welcome site.

**Comment by dune73** [comment]
I'd opt for default `anomaly-scoring->block->deny->403->ErrorDocuments` as you guys seem to agree.

If we can accomodate for redirect and non-anomaly-scoring setups from outside REQUEST-49 as well, then that's even better.

`949190` and all the other threshold rules in REQUEST-49 have this triple chain ending in something along the line of 
`SecRule TX:/^\d+\-/ "(.*)"`

This construct allows to do a msg action with `...Last Matched Message: %{tx.msg}`.

This depends on every CRS rule doing something like:

`setvar:'tx.msg=%{rule.msg}',setvar:tx.%{rule.id}-OWASP_CRS/WEB_ATTACK/SQL_INJECTION-%{matched_var_name}=%{matched_var}"`

There is some beauty in this technique. But honestly, I am not sure it is worth the hassle. It is expecially cumbersome on people writing custom rule trying to hook up onto the CRS anomaly scoring. They will raise the scores, but ignoring ``SecRule TX:/^\d+\-/ "(.*)"`` and thus not setting the variable outlined above, they have successfully disabled the blocking of the ruleset thanks to the chain never matching.

What do you guys think about this?

**Comment by csanders-git** [comment]
I still don't really understand the whole technique... we were just talking about in the #383 ... wouldn't it still just read the last set tx.msg without regard for tx.ruleidetc if we got rid of all those?

**Comment by csanders-git** [comment]
Default will be 403, and default status will be anomaly mode. We need a var to change disruptive in 49 and 59

**Comment by lifeforms** [comment]
On the topic of threshold defaults: They are working as a logical AND. So the default `tx.inbound_anomaly_score_threshold=5` will block incoming stuff with threshold 5+ and can be left as-is. Other granular thresholds will get removed in a separate issue.

**Comment by csanders-git** [comment]
Add warning for CRS version older than 2.8

**Comment by csanders-git** [comment]
Ok i've been putting together the PR for default anomaly scoring and trying to get a var to work. It turns out everything we need isn't available. Really we need ctl:ruleupdateactionbyid but we don't have that. It can be done by putting a SecRuleUpdateActionById in REPSONSE-999 but at that point its not helpful.

I tried macro expansion for actions, as we expected no go. We could make some weird like if statement with an argument that is macro expanded for like status and redirect but that'd be classless.

I think I have come up with an evil plan though. Granted it'll make it easy for people to identify ModSec sites, but that's another problem. We make the default actions of the two blocking-coor rules a redirect back to the host. redirect=%{request_headers.host}?someuniqueparam=someuniquevalue

We then write a rule in the setup.conf that checks for that uniqueparam/value and if we see it we let the user set what they want to happen.

Is it perfect... no - but will it work, maybe.

**Comment by lifeforms** [comment]
Chaim and I discussed the configurable blocking actions on IRC last week, but weren't able to come up with a viable solution yet.

I am very much against doing a redirect and catching that redirect again - anything that would cause more webserver load is just a very unusual thing to do for a WAF in the default settings.

I thought of some other hack by doing a jump back to a predefined section, but the skip action does not allow us to do that.

A major operation on all the CRS rules is not an option.

So I'm still in favor of my original position - let us just block with a 403 by default. It's a logical response, it's the semantic way. People can either override this with a nice ErrorDocument, or if they really want something different, they can still edit the CRS.

But, we could also still do the trick with a configurable action I suggested [here](https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/368#issuecomment-228866525). However, in my opinion, it's something that could be added later, in user demand. We could see how people respond to CRS3.0. Maybe almost nobody will need it?

**Comment by csanders-git** [comment]
haha so is it a 403 on anomaly mode? or a SecDefaultAction 403 on standard?

**Comment by csanders-git** [comment]
@lifeforms this should be a somewhat quick change for me, i'm just verifying that for 3.0 we're going to set the action in REQUEST-949  mode to deny,status:403. I'll add lots of details within the setup.conf about this change, I already have some of that written up in fact. Sound right?

**Comment by lifeforms** [comment]
@csanders-git I'm confused, I think we don't need to change anything for the blocking? My ModSec already gives a 403 at this point. Can we do `SecDefaultAction status:403` in setup instead, so people can at least still tweak the error code?

**Comment by csanders-git** [comment]
wow -  yeah... didn't even think about that. I guess they can do alot if there is no deny.... kinda convenient.

**Comment by lifeforms** [comment]
I'd have to test though. Shall I take a stab at cleaning up the example conf next weekend?

**Comment by csanders-git** [comment]
yeah i'll try and push a blurb and that change after testing. i'm sure there is lots of cleaning that you'll find beyond that :-P

**Comment by lifeforms** [comment]
@csanders-git OK! When are you planning to work on it? I'll have time in the weekend. So, if you want to kick off, the best time is before that, and then I'll merge and continue. Otherwise, no problem and I'll just start with my housecleaning of the setup conf in the weekend, and you can take it from there later.

**Comment by csanders-git** [comment]
probably later tonight :)

**Comment by csanders-git** [comment]
bad news @lifeforms ... SecDefaultAction: pass,status:404 won't work... apparently when you override pass it gets rid of status too... RUDE. Looks like we'll have to specifiy it in the file.

**Comment by lifeforms** [comment]
GRRRRRR

**Comment by lifeforms** [comment]
Discussion is now going on in #463.
