### ISSUE TITLE
Rule 960034 (CRS2; http protocol version check) is not part of CRS3

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#371]
The rule was removed in CRS3. I see it returning in a higher PL, possibly 3.

HTTP/2 needs to be added, of course.

**Comment by lifeforms** [comment]
This is now 920430, or am I looking wrong?

**Comment by dune73** [comment]
Did not spot it when I first looked at `IdNumbering.csv`. Sorry for the inconvenience.
