### ISSUE TITLE
Update allowed HTTP versions

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#372]

**Comment by csanders-git** [comment]
This came up in a recent training but is there a reason we keep these in the setup.conf.

**Comment by dune73** [comment]
HTTP/0.9 is gone for good. But I am regularly seeing HTTP/1.0 in the wild. Mostly load balancers or availability monitors that want to test for the IP address without caring for the servername. HTTP/1.0 lets you submit a HTTP request without providing a Host header, that's why it is still in use.

So I think we need to accept HTTP/1.0 at PL 1, then trigger an alert at a higher PL.

But Removing 0.9 makes a lot of sense in my eyes.

**Comment by csanders-git** [comment]
If that's the case maybe when we make setup.conf great again we remove 0.9 and just leave 1.0 for people to remove if they want... guess we also need to think about 2

**Comment by dune73** [comment]
Let's hear what @lifeforms has to say. Other than that I agree with you. Also on the fact, that 
HTTP/2 has to be added.

**Comment by lifeforms** [comment]
What is the reason to block HTTP/0.9? There could be simple clients (like embedded devices) using this. I admit I use it sometimes telnetting to port 80 when I'm lazy. I haven't surveyed if there would be impact from blocking it. I do see very light use of it in logs, but I'd have to look closer to see if this is legitimate or bot activity.

I notice, however, that when you use HTTP/0.9, the CRS3 will already match on rule 920280 (warning) and 920320 (notice). So de facto we may are already be blocking these clients, depending on user's configured threshold.

I think use of HTTP/0.9 might fall into the same category as not sending a Host header. Maybe notice severity. Unless there's a security reason to disallow it.

As for HTTP/2, I don't know the behavior of `mod_h2` well enough to know what info it will send us. I don't even have it enabled in my production Apache builds. I could experiment a bit at the end of July.

**Comment by lifeforms** [comment]
**HTTP 2**: I've experimented with HTTP/2 on Apache 2.4. I tried it in cleartext upgrade mode, cleartext direct mode, and over TLS. The reported version is always `HTTP/2`. CRS3 complains about it by default.

**HTTP 0.9 revised**: I checked out a bit of logs, though only over a short period. HTTP/0.9 seems to be extremely rare. The instances I found were shitty bots. So, I would say, the chance of blocking legitimate traffic is small enough, and we'll block some bots, which is great. Also, by disabling an old protocol, we simplify operations and we might prevent old, forgotten code paths to exhibit bugs. So, now I'm leaning towards blocking 0.9. What also helps: if a user might get rare problems, they can tweak the setting anyway.

So, my recommendation would be:

- Add HTTP/2 to the allowed versions
- Remove HTTP/0.9 from the allowed versions

The line would thus read:

`  setvar:'tx.allowed_http_versions=HTTP/1.0 HTTP/1.1 HTTP/2', \`

**Comment by csanders-git** [comment]
I'll make a PR right now.

**Comment by lifeforms** [comment]
Very nice!

Now a remaining thing not fully discussed yet is @dune73 proposal to add an alert for HTTP/1.0 at higher PL. First just like with HTTP/0.9 the use of HTTP/1.0 will already trigger a warning for missing Host header. (HTTP/1.0 does not include the Host header) So it will already have a score to start with. Another alert might push it over the blocking limit, and then, a user might reasonably think, "well I've bloody allowed HTTP/1.0 in my setup.conf, so why is the CRS blocking it then?" So, from my perspective, hardcoding a HTTP/1.0 check can cause confusion in combination with existing CRS features, and won't add THAT much, so I'd say shrug forget it. If people hate HTTP/1.0, they can remove it from allowed_versions.

**Comment by csanders-git** [comment]
@lifeforms I agree with you here.... this is why we have this as a configuration directive. Changing the defaults should always have a lot of discussion but I think we've made it pretty general by leaving HTTP 1.0 - I really don't expect to see any legit 0.9 traffic and if there is some then it is just a matter of updating the configuration.

**Comment by dune73** [comment]
Agreed: The beaviour would be inconsistent and the security gain is not high at all. Pulling back my proposal.
