### ISSUE TITLE
Improve potential SQL injection authentication bypass

### ISSUE THREAD

**Issue by istais** [SpiderLabs/owasp-modsecurity-crs#375]
It may be possible to perform authentication bypass using the following vectors:

`or exists (select 1)`

In order to perform the attack, the web application must implement the authentication control using an SQL injection as the following:

select \* from users where username = $_GET['u'] and password = $_GET['p];

The issue is similar to #341 however no knowledge is required about the web application

Currently, rule 959070 attempts to block this attack

exists\s(\sselect|select\Sif(null)?\s(|select\Stop|select\Sconcat|system\s(|\b(?i:having)\b\s+(\d{1,10})|'[^=]{1,10}')"

**Comment by dune73** [comment]
Confirm this evades 959070 and corresponding CRS3 rule 942380. Actually neither libinject nor any other rule is able to see this sqli. The payload above does not trigger any rule at all.

**Comment by dune73** [comment]
Thank you for pointing out exactly where this should be blocked.

How about extending this to:

`exists\s(\sselect|select\Sif(null)?\s\(|select\Stop|select\Sconcat|system\s\(|\b(?i:having)\b\s+(\d{1,10})|'[^=]{1,10}'|\(\s?select\s\d)`

**Comment by lifeforms** [comment]
Added to my list of things to discuss with libinjection author some time, but let's improve our regexp too.

**Comment by csanders-git** [comment]
@dune73 this was a serious concern with how it was used in v2 it being forked. In v3 it is required to be brought in as a submodule, so before you can compile it you must actually bring in an up to date copy from the repo. Has its negatives if an issue is introduced but also has its positives for situations like what we are talking about. I think the positives outweigh the negatives.

**Comment by dune73** [comment]
Agreed. Are there any plans to use the latest libinjection on ModSec2 as well?

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
