### ISSUE TITLE
913100 (CRS3) is not being evaluated

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#376]
This is odd. I tried to make this work, but 913100 is not being evaluated. It is not even appearing in the debug_log. ModSec jumps from 913012 to 913110.

This must be something obvious, but I do not see it.

**Comment by csanders-git** [comment]
Testing it over here it seems to work fine. Got the following

[Sat Jun 25 19:03:32.712975 2016] [:error] [pid 13917] [client 127.0.0.1:47178] [client 127.0.0.1] ModSecurity: Warning. Matched phrase "dirbuster" at REQUEST_HEADERS:User-Agent. [file "/etc/httpd/modsecurity.d/owasp-crs/rules/REQUEST-13-SCANNER-DETECTION.conf"] [line "55"] [id "913100"] [rev "2"] [msg "Request Indicates a Security Scanner Scanned the Site"] [data "Matched Data: dirbuster found within REQUEST_HEADERS:User-Agent: dirbuster"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "Host: localhost"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-reputation"] [tag "reputation-scanner"] [tag "OWASP_CRS/AUTOMATION/SECURITY_SCANNER"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"] [hostname "localhost"] [uri "/"] [unique_id "V28NxKef3521QogbV11VCgAAAAE"]

**Comment by csanders-git** [comment]
Using:
[Sat Jun 25 19:05:00.590515 2016] [:notice] [pid 14227] ModSecurity for Apache/2.9.1 (http://www.modsecurity.org/) configured.
[Sat Jun 25 19:05:00.590523 2016] [:notice] [pid 14227] ModSecurity: APR compiled version="1.5.2"; loaded version="1.5.2"
[Sat Jun 25 19:05:00.590530 2016] [:notice] [pid 14227] ModSecurity: PCRE compiled version="8.38 "; loaded version="8.39 2016-06-14"
[Sat Jun 25 19:05:00.590535 2016] [:warn] [pid 14227] ModSecurity: Loaded PCRE do not match with compiled!
[Sat Jun 25 19:05:00.590551 2016] [:notice] [pid 14227] ModSecurity: LUA compiled version="Lua 5.3"
[Sat Jun 25 19:05:00.590557 2016] [:notice] [pid 14227] ModSecurity: YAJL compiled version="2.1.1"
[Sat Jun 25 19:05:00.590562 2016] [:notice] [pid 14227] ModSecurity: LIBXML compiled version="2.9.3"

Server version: Apache/2.4.18 (Fedora)
Server built:   Jan  4 2016 08:15:18

**Comment by csanders-git** [comment]
wow my PCRE versions of out of sync ... lol I ought to fix that

**Comment by lifeforms** [comment]
I can't reproduce. Maybe it's ignored by some tag or id further in your configuration. Have you set `SecDebugLogLevel 9`?

`Message: Warning. Matched phrase "webvulnscan" at REQUEST_HEADERS:User-Agent. [file "/usr/local/etc/apache24/security2/activated_rules/REQUEST-13-SCANNER-DETECTION.conf"] [line "55"] [id "913100"] [rev "2"] [msg "Request Indicates a Security Scanner Scanned the Site"] [data "Matched Data: webvulnscan found within REQUEST_HEADERS:User-Agent: bla webvulnscan hehe"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-reputation"] [tag "reputation-scanner"] [tag "OWASP_CRS/AUTOMATION/SECURITY_SCANNER"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"]`

**Comment by dune73** [comment]
Thank you for checking this for me, guys. I found my error and I am not going to tell you how stupid my config is. #hidingfaceinshame.
