### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Shuro** [SpiderLabs/owasp-modsecurity-crs#38]
My apache error_log got many modsecurity-crs-logs, even with 
    SecDefaultAction "phase:1,pass,nolog,auditlog"
in my modsecurity_crs_10_setup.conf .

Seems like there are hard "log" parts in 
base_rules/modsecurity_crs_60_correlation.conf

**Comment by csanders-git** [comment]
Wow not sure why this is open -- yes that is one solution to removing them. Good catch on teh chain there where necessary. This design principle is also present in CRS 3 RC1 but correlations must be enabled
