### ISSUE TITLE
Refresh INSTALL file

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#381]
The `INSTALL` document is a bit rusty and can use a bit of love.

- Clarify exact steps to install
- Add minimum ModSecurity requirements (CRS3 depends on libinjection so it will perform very badly on installations that don't have it)
- Improve examples
- Improve formatting

This should be done last, after the defaults have settled.

**Comment by dune73** [comment]
Yes, this is a must.

I think we should sort out the setup.conf and then write `INSTALL` anew; inline with @csanders-git documentation and add a couple of blogposts around the release to cover various aspects.

**Comment by csanders-git** [comment]
:) Fortunately this should be the 'easy' part, comparative to alot of the design decisions we've had to make along the way.

**Comment by lifeforms** [comment]
PARTYCLOSE!
