### ISSUE TITLE
lfi-os-files.data: add some common files

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#382]
I'd suggest to add some entries to the LFI data.

First, some versioning related files and directories which may be lying around in web roots and allow attackers to retrieve source code, paths, settings, developer identities, possible hardcoded passwords, etc:
- `.git/`
- `.gitconfig`
- `.gitignore`
- `.hg/`
- `.svn/`

Also, some nice prizes for LFI:
- `.htaccess`
- `.htpasswd`

Ideally I'd check for these strings in `REQUEST_FILENAME` as well as parameters.

False positive possibility seems low to me, I have blocked these entries for a long time with no problems.

**Comment by dune73** [comment]
Totally agreed. 

Are you implying that the whole 930120 rule is fairly resistant to FPs, or do we need special precautions? I do not think I have seen FPs on this rule, but it's quite a long list.

**Comment by lifeforms** [comment]
@dune73 The (existing) LFI file list will definitely cause some FP if one talks about Unix administration in a blog comment... Like `.bashrc` or `.ssh/id_rsa.pub`. But that's pretty much a given. :(

**Comment by csanders-git** [comment]
also .bak files or files ending in ~ tend to be really fun to search for :)

**Comment by lifeforms** [comment]
Yeah, people simply love to save their stuff as  `old.htpasswd`, which can just be GETted. So a substring match is really the way to go.

**Comment by dune73** [comment]
ACK

**Comment by csanders-git** [comment]
also add to the list crossdomain.xml even thought we all hate flash there should never be an upload of this file :)

**Comment by lifeforms** [comment]
Yeah. It's not super urgent and the `.git` case needs a regexp to prevent FP so probably better to turn those into a separate rule. 3.1 sounds right.

**Comment by lifeforms** [comment]
Everything in #630 restricted file list should also be in LFI checks. Add a comment to keep them in sync.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
