### ISSUE TITLE
Add the reason for major version bum in 3.0

### ISSUE THREAD

**Issue by sathieu** [SpiderLabs/owasp-modsecurity-crs#385]
Hi,

There is currently 3.0.0 and 2.2.9 where 2.2.9 was released after 3.0.0. Why the version bump? (please add backward incompatible changes in CHANGES).

**Comment by dune73** [comment]
3.0.0 has not been released yet. 

v3.0.0-rc1 is the active development tree.
v3.0.0-dev is a former (abandoned?) development tree.

CRS3 is a major overhaul with a huge diff. It's safe to say that everything outside the regexes has been changed. This is going to be reflected in the CHANGES file. Eventually.

**Comment by sathieu** [comment]
But there is a release in https://github.com/SpiderLabs/owasp-modsecurity-crs/releases ?!

**Comment by dune73** [comment]
Indeed. This is odd. And 3 years old. Guess that was a test / error a long time ago.

@csanders-git: Can you remove that release somehow?

**Comment by csanders-git** [comment]
Github says I can but I can't seem to figure out how to do that quite yet... give me a few extra minutes to figure it out :-X

**Comment by csanders-git** [comment]
Figured it out 3.0 release tag is gone thanks @sathieu for the report. I will say that I think we are all REALLY excited for the RC1 of 3.x
