### ISSUE TITLE
Check for non native Referer header

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#386]
It should be pretty normal to assume that users will enter on a home page but this is likely to be a higher paranoia mode rule in any event still pretty interesting idea i think.

```
SecRule REQUEST_FILENAME "!@rx ^(\/index\.|\/+((\?|;).*)*$) "id:1234,chain"
   SecRule REQUEST_HEADERS:Referer "!@contains ://%{SERVER_NAME}/" ""
```

**Comment by csanders-git** [comment]
This is similar to a rule that @flameeyes uses in his own ruleset.

**Comment by Flameeyes** [comment]
Note that mine is mostly limiting itself to POST requests, which may also not correctly work for non-REST API kind of calls.

For just requesting pages, it's probably a bit too restrictive.

**Comment by csanders-git** [comment]
Interesting, Yeah REST API's would most assuredly not like this rule, without a really through client, but I think general sites would work alright and putting it up into a high paranoia level (4?) might would work well to generally force attackers to do more work when crafting CRSF type requests.

**Comment by Flameeyes** [comment]
For non-POST requests this would break deeplinking of articles.

On Wed, Jun 29, 2016 at 9:25 PM Chaim Sanders <notifications@github.com>
wrote:

> Interesting, Yeah REST API's would most assuredly not like this rule,
> without a really through client, but I think general sites would work
> alright and putting it up into a high paranoia level (4?) might would work
> well to generally force attackers to do more work when crafting CRSF type
> requests.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/386#issuecomment-229477229>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAEkUjfhT710lSAvxGhp7Q9STl3HFjcmks5qQtS0gaJpZM4JBhGj>
> .
>
-- 
Diego Elio Pettenò (aka Flameeyes)

**Comment by csanders-git** [comment]
Oh yeah it for sure would cause false positives on such direct links... such is the nature of the CSRF beast :-P. Great observation

**Comment by csanders-git** [comment]
It may be too false positive prone but worth the discussion -  we could create an 'tx.external_facing_sites' var that could act to allow easy configuration

**Comment by dune73** [comment]
This looks interesting. But I do not get the idea behind the rule. Too much negation for my brain perhaps. Could somebody explain it to me, please?

**Comment by csanders-git** [comment]
Haha @dune73 it is essentially saying if you didn't come from a page within our site (as judged by the referer header) and this isn't the index.xyz or / than your bad. As was so aptly pointed out this would break direct site access via things like links and also user agents that don't user refferer headers (thick clients for web services?). 
From a security perceptive it is ostensibly using the Referer header as a CSRF token (that while bad because user controlled, would stop many attackers)

**Comment by dune73** [comment]
Got it. Thanks.

This is a smart idea. It would obviously break on requests on deep links and the said REST/API calls, but that's why some tuning will be due in order to remove the rule for all requests targetting landing pages - or for all known good referers.

In the end, this is the essence of a high security rule for paranoia levels 3 or 4. If you look at the distribution of anomaly scores (slide 18 in http://www.slideshare.net/ChristianFolini/owasp-modsecurity-core-rules-paranoia-mode) you see that we are fairly even from PL2 to 4. So outside of CSRF attacks, this is also a rule likely to trigger on a wide range of scanners in higher PLs pushing PL3 and 4 higher.

**Comment by csanders-git** [comment]
@dune73 i'm glad you think it acceptable. Sometimes i exist in a little bit more of a crazy world. 
I took another look at the regex and you are right this could be a little more intelligent to allow parameters to be passed on the index page (even though this is somewhat unlikely)

^(\\index\.(\w{3,4})|\\)((\?|;).*)*$

**Comment by dune73** [comment]
Cool. I think github is messing with your regex. You want this, don't you?

```
^(\\index\.(\w{3,4})|\\)((\?|;).*)*$
```

**Comment by csanders-git** [comment]
@dune73 good call.

**Comment by dune73** [comment]
Hmm. I still think the regex is overly complicated.

A few remarks:
* REQUEST_FILENAME does not contain the query string. I think we can omit `\?` 
* REQUEST_FILENAME contains the path info though. A path info would lead to additional FPs.
* There is an implicit path normalisation happening on REQUEST_FILENAME between phase 1 and phase 2. Guess it is best to go with phase:1.
* I think we can allow `/index.do` as well. Thus `\w{2,4}`
* I do not know what the `;` is all about. Omitting it.
* Why don't you take the slash out of the first group if it is contained in both groups. That way you can get rid of the pipe.

Removing more syntactic sugar, I end up with:

```
SecRule REQUEST_FILENAME "!^/(index\.(\w{2,4}))?$" "id:1001,phase:1,deny,chain"
   SecRule REQUEST_HEADERS:Referer "!@contains ://%{SERVER_NAME}/"
```

Please check if this gives the same results and matches your intentions.

If this is aimed for PL2, we could introduce a variable for known/friendly referers. But I guess we would be forced to work with the regex operator on the 2nd SecRule.

For PL3 or PL4, I would expect the sysadmin to take care of this himself.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
