### ISSUE TITLE
Check for abnormal character escapes (-> \c, \d, etc.)

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#393]
The whitespace escapes are well known and perfectly acceptable: `\f, \t, \n, \r, \v, ...`.

But why would anybody escape `\c`? This smells like evasion and I think we should test for this practice.

Such a rule is probably something for PL 3 or 4.

**Comment by csanders-git** [comment]
do you have an example?

**Comment by dune73** [comment]
```
curl localhost -d "file=cat+/etc/pa\ssw\d"
```

is currently not triggering any rule in 3.0.0dev. It's going to be caught by the os file injection rule as soon as the new version is ready. But I think that `\s` and `\d` stinks and they should be detected. Backends tend to ignore these irrelevant backslashes depending on the parser. Even the ModSec transformations do.

**Comment by csanders-git** [comment]
I think that is a great idea :). In general I still think we should leave it for 3.1 so that we can get 2.x out of the master branch it really is QUITE out of date :-P

**Comment by csanders-git** [comment]
@dune73  btw when I labeled it beyond 3.0.0 if you feel strongly about it feel free to do it if you feel good about it :). My thinking is just that it shouldn't STOP a rc1 release. Hope that is clear :)

**Comment by dune73** [comment]
OK. Actually it's one of the additional rules which could give us a higher score in higher PLs. So I am aiming to do this for 3.0. If it's not ready when we go RC, then it's simply not in.

**Comment by dune73** [comment]
I have a working rule now:

```
SecRule ARGS:a                  '(?<!\Q\\\E)\Q\\\E[cdeghijklmpqwxyz123456789]'  "id:1001,phase:2,deny,log,msg:'Bogus backslash escape. Possible evasion attempt.'"
```

This was surprisingly tricky. I thought I could detect the backslish with `\b`, but this did not work. (Why?). So I had to resort to `\Q\\\E`. I want to allow escaped backslashes, thus a negative look-ahead group before this central part of the regex. And then followed by the list of visible characters and letters we do not want to see escaped.

The regex matches thus: One of the following letters escaped with a backslash, but only if the backslash is not escaped with a backslash.

We will thus trigger on an ARG containing `\c`. But not on `\n` or `\\c`.

Thoughts?

This will of course bring a fair number of false positives. Therefore, I see it in PL4.

**Comment by csanders-git** [comment]
Interesting. I wonder why there is such weird behavior. Do you have samples of malicious data?

**Comment by dune73** [comment]
No samples outside of the artificial 
```
curl localhost -d "file=cat+/etc/pa\ssw\d"
```

But absence of evidence is not evidence of absence, if I may quote Carl Sagan.

**Comment by csanders-git** [comment]
Alright, i'll add that to the unit tests. I can probably come up with a few more.

**Comment by dune73** [comment]
Thanks. Yes, it's fairly easy to come up with more examples:

`curl localhost -d "file=cat\000020\/e\tc\2f \pa\ss\wd\020\26"`

**Comment by dune73** [comment]
See PR in #474. Closing this issue now.
