### ISSUE TITLE
Publication: X-XSS-Nightmare by Masato Kinugawa

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#397]
Masato Kinugawa published an extensive slide collection on XSS and filter evasion techniques. We should look this through and check if we cover this or if not if we can adopt the rules so we do cover it.

http://www.slideshare.net/masatokinugawa/xxn-en

This is a new type of issue. Maybe we are OK, maybe not. But we need to check. And we need a way to keep track of all the publications which affect the CRS. So I am trying this out, labelling with the new tag "Published Research". The label could of course also be "Research", but then it sounds like "ModSec CRS Research", which it is not. 

Feel free to change the tag name or tell me that issues are the wrong place to keep track of research affecting CRS.

**Comment by lifeforms** [comment]
@dune73 I love this tag, we should definitely take an active approach to following the conferences. We're not experts at every topic so it's very possible we can learn some cool evasion techniques.

**Comment by dune73** [comment]
Thanks. I agree. 

It's a question of resources, I guess. 

But the least thing we can do is to keep track of the stuff that way. And if we take action, then we will have an archived report on each of these slides and what we make of it.

I think the title prefix "Publication" is also useful.

**Comment by csanders-git** [comment]
@dune73 I agree with walter, this is very helpful!

**Comment by dune73** [comment]
Thanks @csanders-git

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
