### ISSUE TITLE
Publication: Perform effective command injection attacks like Mr.Robot by Anastasios Stasinopoulos

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#398]
https://www.dropbox.com/s/om4yttb6nfix2hk/BSidesAth16_Perform_Effective_Command_Injection_Attacks_Like_Mr.Robot_Final.pdf

@lifeforms is having a go at this in #318 / 932100 (CRS3).

**Comment by lifeforms** [comment]
I've ran the commix scanner after #430 and so far our signatures seem to block it. Once we've put out 3.0 for testing, I'll contact the author to ask if he wants to share more tricks.
