### ISSUE TITLE
Improve rule 920100

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#404]
While reviewing this rule for regression testing I found it was not very good. It was also needlessly greedy and overly broad for instance GET / is valid.

My recommendation is to replace the regex with:

```
(?:(?i:(?:[a-z]{3,10}?)) +?(?:\w{3,7}?:\/\/[\w\-\.\/]+?(?::\d{1,5}){0,1}?){0,1}?\/[^?#]*?(?:\?[^#\ ]*?)*?(?:#[\S]*)*? +?|(?i)connect (?:(?:\d{1,3}\.){3}\d{1,3}?|(?:\w(?:\-|\.|\w)*)(?:\w|\.))(?::\d{1,5}){0,1}? +?|(?i)options +?\* +?)(?:HTTP\/[\d\.]{1,3})$
```

And update the documentation too:

```
#
# Validate request line against the format specified in the HTTP RFC
#
# -=[ Rule Logic ]=-
#
# Uses rule negation against the regex for positive security.  The regex specifies the proper
# construction of URI request lines such as:
#
#   METHOD ["http:" "//" host] [ ":" port ] / [ abs_path [ "?" query ]] HTTP/VERSION
#   CONNECT IP|DOMAIN HTTP/VERSION
#   OPTIONS * HTTP/VERSION
#
# It also outlines proper construction for CONNECT, and OPTIONS requests.  
#
# -=[ References ]=-
# http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.2.1
# http://capec.mitre.org/data/definitions/272.html
# https://tools.ietf.org/html/rfc2817#page-6
# 
```

**Comment by dune73** [comment]
Could you please elaborate on "overly broad for instance GET / is valid".

Also, I can not make this rule (or the one with your regex) trigger. At least not on the fly. Could you share a request triggering 920100?

**Comment by csanders-git** [comment]
The originally one will literally think GET / is valid without the HTTP/1.1 bit.

**Comment by csanders-git** [comment]
You need the full request line to trigger these:
So, ```Get / HTTP/1.1``` should work or any connect or any option or really anything :)

**Comment by lifeforms** [comment]
Haven't read the whole thread, but `GET /` is HTTP 0.9!

**Comment by csanders-git** [comment]
So Apache will actually return that with no HTTP headers at all. Just raw HTML. However it will internally append the HTTP 0.9 header

**Comment by csanders-git** [comment]
also @lifeforms boy am I glad you said that I looked up the HTTP 1 spec... how weird,  If the protocol version is not specified, the recipient must assume that the message is in the simple HTTP/0.9 format. Simple requests do not use headers on request or response. What kind of world is this??

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
