### ISSUE TITLE
920160 is not reachable in Apache

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#405]
It should be checked if this can be reached in Nginx or IIS. Generally apache returns a 400 if content-type is none numeric. Interestingly it doesn't even record that in the error log

**Comment by dune73** [comment]
I assume you are talking about content-length and not being numeric.

CRS3 920160 runs in phase 2 and as such is not being triggered, but the error log is present:
`[2016-07-14 13:22:17.010231] [http:info] 127.0.0.1:46746 V4d16X8AAQEAAEWwN8AAAAAA AH01587: Invalid Content-Length
`

If you shift the rule into phase 1, it is triggered OK here. PR?

**Comment by csanders-git** [comment]
Good to know, let me test... weird my Apache must just not like me :(

**Comment by dune73** [comment]
This has been fixed for CRS 3.1. Closing issue.
