### ISSUE TITLE
Update Rule Filenames Residuals

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#416]
Should we upgrade the paranoid mode names to reflect the new 9XX names?

Ex.

rules/REQUEST-943-APPLICATION-ATTACK-SESSION-FIXATION.conf:SecRule TX:PARANOIA_LEVEL "@lt 4" "phase:2,id:943018,nolog,pass,skipAfter:**END-REQUEST-43-APPLICATION-ATTACK-SESSION-FIXATION**"

**Comment by csanders-git** [comment]
And the SecMarkers obviously.

**Comment by csanders-git** [comment]
I'm gonna assume it really only makes sense to do this and start a PR.

**Comment by dune73** [comment]
This has been performed. Closing.
