### ISSUE TITLE
Cosmetic: Limit the documentation lines in 80 characters.

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/owasp-modsecurity-crs#420]
Hi,

Thank you for your work on this new version of the rules set. Just one quick comment: it will be good the have the documentation limited to 80 characters per line. Will be easy to read on the console.

**Comment by lifeforms** [comment]
I agree. I had to read my own rule comments and already got annoyed with the word wrapping.

**Comment by csanders-git** [comment]
This is a good idea. I'm going to make a script on the CI server called CRSLint it'll start by including checking for comment line length but I think eventually we should agree on things like tabs v spaces and order of actions. use of @rx etc.

**Comment by csanders-git** [comment]
Turns out that this is not as easy as it could be because python regex's are not PCRE compliant - i would have liked to pull in the 3.x parser to python :(

**Comment by dune73** [comment]
The crs-setup.conf.example file current does not have any comments longer than 80 chars outside of two filenames.

The rules files combined have 234 comment lines in this category, but 2/3 of them are between 80 and 100 chars. The ones longer than 100 chars are mostly references to CVEs that profit from the width.

While it is traditionally desirable to strive for narrow lines, there is also the conflicting interest to profit from wider terminal windows. Stying below 100 chars mostly seems a reasonable approach. Also given the 234 comment lines would be a fairly big PR nobody has been interested in doing those last 2.5 years.

I am therefore closing this issue. Please reopen, if there is a widespread need and somebody is willing to do create PR.
