### ISSUE TITLE
Update Range Section Length Rule Regex

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#421]
Old: `^bytes=(\d+)?\-(\d+)?\,\s?(\d+)?\-(\d+)?\,\s?(\d+)?\-(\d+)?\,\s?(\d+)?\-(\d+)?\,\s?(\d+)?\-(\d+)?\,`
New: `^bytes=(?:(?:\d+?)?\-(?:\d+?)?\,\s*?){5}`

Currently the regex is long and quite brittle. I have confirmed that any amount of whitespace (beyond just one space) passed a comma will be accepted and bypass this. Not sure we are entirely equivalent here but 

While this catches Range: bytes=-10,**-**, 21-30,31-40,41-50,51-500, I don't think this is used in practice at all.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
