### ISSUE TITLE
 Executing non-alphanumeric JavaScript without parenthesis

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#425]
http://centime.org/jsfree.html

**Comment by dune73** [comment]
I can't get this to work in my browser(s). But I assume it actually does work somehow.

If so, then I think 942430 and siblings will catch this from PL2 upwards. As it is an evasion technique, it is hard to identify generic markers.

One key element that is also used serially in JSFuck is `[]+!+[]`. I think this is a highly special string which is unlikely to produce too many FPs and could thus be incorporated in PL1.

**Comment by dune73** [comment]
Companion fork: http://centime.org/jsfsck/

Again, `[]+!+[]` is featured heavily all throughout.

**Comment by dune73** [comment]
And http://infosectoughguy.blogspot.ch/2016/09/cool-xss-tricks-with-anonymous_52.html is doing it in a similar way. Again, `[]+!+[]` is used repeatedly.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
