### ISSUE TITLE
Catch Bodies that end with CRLF

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#431]
Not sure if ModSecurity can do it properly but in any event this is invalid functionality that is accepted for compliance with HTTP 1.1 and bypasses some checks in Apache.

**Comment by dune73** [comment]
Like this?

```
SecRule REQUEST_BODY "@endsWith 0d0a" "id:1000,phase:2,t:hexEncode,pass,log,msg:'Request Body ends with CRLF'"
SecRule RESPONSE_BODY "@endsWith 0d0a" "id:1001,phase:4,t:hexEncode,pass,log,msg:'Response Body ends with CRLF'"
```

**Comment by csanders-git** [comment]
yeah but i'm not sure if Apache/Nginx/IIS will strip this out.

**Comment by csanders-git** [comment]
Some additional information -- http://stackoverflow.com/questions/30433224/is-there-a-crlf-after-the-message-body

Actually this came up as a result of a bug in https://github.com/fastly/ftw . It's an interesting issues because I was able to get Apache to respond to things it normally rejects.

**Comment by dune73** [comment]
It's certainly not stripping for RESPONSE_BODY. But I could not get curl to submit CRLF in the REQUEST_BODY. Would need to test with telnet / nc.

**Comment by lifeforms** [comment]
I haven't checked but I think this is probably not an issue. If the client sends more data beyond the `Content-Length`, the webserver parser should never append that to the body, but treat it as part of the next request line (in case of keepalive) or ignore it. So I don't think this situation is ever passed on to us.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
