### ISSUE TITLE
Cannot get 910000 (reputation) to work

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#442]
It seems that whatever traffic I send, my source ip is never getting blocked persistently.

I thought maybe I've had this rule disabled for testing and forgot about it, but I compared my setup.conf with example from master and found nothing.

Is there some other configuration that I need to do to enable it?

What should be the normal behavior of this rule? When would it be triggered? Or does the rule not do what I think it does?

ModSec version: 2.9.1 on FreeBSD

**Comment by lifeforms** [comment]
Additional info, ip.block SEEMS to be stored in collections, but it doesn't seem to be checked correctly on the subsequent requests.

Test:

- Send a request with `sqlmap` user-agent, notice in audit log that it sets ip.block
- Send another request from the same client with another user-agent: it's not blocked

Or is blocking tied to the user-agent of the client?

**Comment by csanders-git** [comment]
This is almost assuredly due to how the ip collection is initialized:

```
SecRule &TX:REAL_IP "@eq 0" \
  "id:'900021', \
  phase:1, \
  t:none, \
  initcol:global=global, \
  initcol:ip=%{remote_addr}_%{tx.ua_hash}, \
  setvar:tx.real_ip=%{remote_addr}, \
  nolog, \
  pass"
```

ua_hash is just the sha1 of the user-agent.

**Comment by csanders-git** [comment]
To quote @rcbarnett 

*Notice that our collections are using the client IP address in combination with the User Agent string value as the key to more uniquely identify clients and limit blocking innocent users.* With this persistent storage at our disposal, we can simply add a new variable to the collection if you want to block the client. You do so by adding a variable such as setvar:ip.block. You then have a rule that evaluates the existence of this variable and then denies access. The sample DoS rule from Recipe 14-2 uses this technique by checking for existence of a variable called IP:DOS_BLOCK.

It seems this is well intentioned, probably to avoid NAT situations, however this means that changing your user-agent will break this functionality. This is why you are seeing the results you are seeing.

**Comment by lifeforms** [comment]
OK, it's intended behavior then. Thanks for checking it out for me! Then I'm not crazy.

Would be nice to make this behavior switchable for 3.1 though! I'd personally much rather block the complete IP address. 

As of right now, the rules are also confused about it. A bad User-Agent now sets ip.block, but that does nothing - after all if the UA stays the same, next request the UA rule will also block that :) And if the client switches to another UA they are free to attack.

Closing this for now! :)

**Comment by csanders-git** [comment]
Yeah - this does rub my the wrong way, I agree. I see the logic in it -- A nessus scanner hits a site 3 times... after that blocked but really it'd be better to make the more unique IP+UA the default but allow  that to be easily configured.

**Comment by dune73** [comment]
Thumbs up on the idea to make it a configurable option in the future. Blocking the naked IP by default is too dangerous from my point of view. If you look at enterprises, a rogue client can lock out a whole partner enterprise via NAT.

It's a tricky rule and I think we should take it easy. I'm kinda disable this rule by default for my customers anyways.
