### ISSUE TITLE
Rule 941230 Update Regex

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#444]
Another issue with the regex not preventing newlines while looking for a tag. Again another microsoft regex

Orig Regex:
```(?i:<EMBED[ /+\t].*?((src)|(type)).*?=)```
Updated Regex
```
(?i:<embed[\s\/+].*?((src)|(type)).*?=)
```

**Comment by lifeforms** [comment]
Sounds good. Spaces in regexps are evil!

**Comment by csanders-git** [comment]
This is merged in both 2.x and 3.x
