### ISSUE TITLE
Update 941270 regex

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#446]
This regex is not vulnerable to the issues detected by vlads scripts but timing attacks in MySQL have more subtlety than the regex supports. I am suggesting updating the syntax to support 'OR' and 'AND' as well as not just things like ' 'BENCHMARK but also -BENCHMARK and +BENCHMARK as they are used in real attacks.

Old Regex:
`(?i:(?:(select|;)\s+(?:benchmark|if|sleep)\s*?\(\s*?\(?\s*?\w+))`

New Regex
`(?i:(?:(select|or|and|;|\'$).*?(?:\s+|\-|\+)(?:benchmark|if|sleep)\s*?\(\s*?\(?\s*?\w+))`

Test Cases:

 ProductID=1 OR SLEEP(25)=0 LIMIT 1-- 
 ProductID=1) OR SLEEP(25)=0 LIMIT 1-- 
 ProductID=1' OR SLEEP(25)=0 LIMIT 1-- 
 ProductID=1') OR SLEEP(25)=0 LIMIT 1-- 
 ProductID=1)) OR SLEEP(25)=0 LIMIT 1-- 
 ProductID=SELECT SLEEP(25)--
 SELECT BENCHMARK(1000000,MD5('A'));
SELECT \* FROM products WHERE id=1-BENCHMARK(100000000, rand())
SELECT \* FROM products WHERE id=1-IF(MID(VERSION(),1,1) = '5', SLEEP(15), 0)
SELECT if(1=1,’foo’,'bar’); — returns ‘foo’
SELECT BENCHMARK(1000000,MD5(‘A’));
SELECT SLEEP(5); # >= 5.0.12

In reality we'll need a stricter sibling for things like  '1-BENCHMARK(100000000, rand())'

Also we should change the comment from 'DetectsSQL benchmark and sleep injection attempts including conditional queries’' to 'Detects MySQL benchmark and sleep injection attempts including conditional queries’'. As more rules are needed for other platforms.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
