### ISSUE TITLE
Move 942390 (OR regexp) back to PL1?

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#448]
942390 (SQL Injection Attack) contains a regexp that detects sql OR.

It's been moved to PL2 in the paranoid project.

Christian mentioned this rule causes frequent FP. I wouldn't say it's frequent in my data, although it does cause some FP. I've checked it on the Reddit comments dataset and it hit 387 out of 126320 comments which is just around 0.3% though.

The thing is, this rule is necessary to block some trivial SQL injections like `id or 1`. This type of injection is **not** caught by libinjection (it has some anti-FP heuristics and I think it probably considers this signature too simple).

So for instance you can inject `foo=id+or+1` on CRS3 and retrieve all rows in a table.

To me the FP is acceptable in PL1 to prevent this, and I think I we should give it a try to block this syntax in PL1.

I could also discuss this signature with the libinjection project, but that would mean the fix will only be in a future ModSecurity version.

**Comment by lifeforms** [comment]
I tested how the CRS behaves on `AND` syntax. That was fortunately still caught in PL1 by rule 942390.

What's especially interesting is that rule 942390 is almost the same as 942400, only 942390 (PL2) checks `OR` and 942400 (PL1) checks `AND`.

However, 942400 seems to be an improved version. For instance, it does not contain spaces but `\s`. There are also other minor differences. Maybe these differences have improved the rule sufficiently so that it no longer causes the FP seen by @dune73 ?

Would bringing 942390 back to PL1 become more viable if we ported over these improvements from 942400 to 942390?

**Comment by dune73** [comment]
Do you have numbers for the updated 942390? I do not mind the rule in PL1 if the FPs are low enough. And if that would solve your `id` problem in PL1, it would be a big win, I suppose.

**Comment by lifeforms** [comment]
I looked wrong, 942400 is also in PL2 now. So at least they have the same treatment, which is consistent. Happy with that. Now it's still possible to move them back to PL1, or not.

942400 (AND) has 714 hits on Reddit, 942390 (OR) has 387 hits. So AND seems worse in terms of FP. I feel this is just about on the edge of being acceptable in PL1, seeing we don't have any other protection against this type of small SQLi. Haven't looked at regexp magic yet, but that's a too big project for now. Only thing doable now is either leave in PL2 or move to PL1.

Maybe improvements could be made in libinjection that would save us from having to activate these rules in PL1. [I created a issue upstream about small injections](https://github.com/client9/libinjection/issues/110). There are also some test cases I used.

**Comment by dune73** [comment]
As there is no more a strong urge to move this to PL1, I think the issue can be closed.

**Comment by lifeforms** [comment]
I'm not super happy about this situation, as these two regexp rules do seem to cover an area that libinjection is not covering. But, my gut feeling is that as SQLi constructs grow in complexity, libinjection becomes much more effective. So, with considerable reservation, closing this for now.

**Comment by dune73** [comment]
I see your point. Maybe libinjection can help fighting this.

Thanks for closing.
