### ISSUE TITLE
Move rule 942460 (Repetative Non-Word Characters) to PL3

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#449]
The dreaded rule 942460 (Repetative Non-Word Characters) now lives in PL2.

But it causes extreme amounts of FP. Of the Reddit comments dataset, 30% of the comments are positive for this rule.

Obviously this rate is much too large for PL2. On normal English texts, even in PL2 you should not get these numbers. The threat neutralized by the rule is also pretty amorphous. With libinjection and well protected evasion detection I think we've added a lot of specific parsing/heuristics to mitigate the possible need for this rule.

I would suggest: because of time contraints, right now just move the rule to PL3.

We could also consider siblings or we could leave that for a later update.

The rule also is missing some tags and a severity, which can be fixed at the same time.

**Comment by lifeforms** [comment]
I forgot to discuss this yesterday @dune73 @csanders-git What do you think? I can make a PR for it, moving the rule will be a very minor task. I think we should do it!

**Comment by dune73** [comment]
You are totally right to propose this. When we ran through the initial list of paranoia candidates, we simply moved everything to PL2, but of course, there are reasons to push certain rules to PL3 and I think this is one of them. We lose a bit of coverage at PL2, but add more reason to run PL3 and reduce a lot of FPs.

**Comment by csanders-git** [comment]
Sounds like a reasonable plan if you can get it in by the end of today.

**Comment by lifeforms** [comment]
Closing this, PR in #476.
