### ISSUE TITLE
DOS counter broken for files without dots

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#462]
In bda2fff9, DOS rule 912150 was changed to:

```
SecRule REQUEST_BASENAME "\.(.*)$" \
```

Therefore, only filenames matching this regexp (so files containing a dot) are being counted towards the DoS limits.

DoS protection is now not functioning for file names like `/`, `/contact` etc. and you can request an unlimited number of these without triggering DoS burst detection.

**Comment by csanders-git** [comment]
So is the solution to this just to make it...

```
.*(?:\.)(.*)|.*
```

?

**Comment by lifeforms** [comment]
Not sure actually, maybe `(?:\.(.*))?$` to make the whole thing optimal?

I don't know from the heart the behavior of `setvar:tx.extension=%{TX.1}` when nothing is captured though. It must be set for the chain rule to fire. I don't have time to check it out right now, but it should be easy to test.

**Comment by csanders-git** [comment]
let me take this on

**Comment by dune73** [comment]
Nice find. And good fix. Thank you guys.

**Comment by csanders-git** [comment]
Please see PR.
