### ISSUE TITLE
Add strict and less strict sibling for 942460 (Repetitive Non-Word-Char)

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#477]
942460 with a limit of 3 repetitive non-word chars has been moved to PL3 for v3.0.0.

For 3.1 we could look into a relaxed variant for PL2 and a stricter variant (Limit of 2?) for PL4.

Other possible strict siblings include an extension of ARGS to REQUEST_HEADERS.

**Comment by lifeforms** [comment]
2?? What are you... SATAN?

We could also think of a less strict sibling for PL2 maybe. Most of the FPs (checked informally) seem to be people posting sequences like `....` and `----`. We could exclude those characters from the match.

**Comment by dune73** [comment]
Sounds good. Not the SATAN part, I mean. :)

**Comment by dune73** [comment]
Also see PR #476.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
