### ISSUE TITLE
Soft fail for file uploads with filenames containing single quotes

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#483]
French filenames frequently contain single quotes. This will raise MULTIPART_INVALID_QUOTING and consequently also MULTIPART_STRICT_ERROR. We kicked our rule for CRS3, so this is now only covered in the recommended rules. But French users face a hard fail on these rules and I think it really is our problem.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
