### ISSUE TITLE
Introduce debug message to help with support requests

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#484]
I think about introducing an optional setup.conf variable. When set to on, a special rule triggers (possibly in connection with a special query string) which will then dump a message with key configuration variables (anomaly thresholds, paranoia level, sampling rate, restricted file extensions, modsec_build, etc.) I takes more than one rule to contain all, all the vars we might be interested in.

Users could then be asked to include these alerts in their support requests. This would give us access to these infos when responding to issues.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
