### ISSUE TITLE
Shift to phase:1 where possible; check anomaly score after phase:1

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#485]
Rule of thumb: What can be done in phase:1 ought to be done in phase:1. Maybe even pull the rules apart if we think this rule of thumb makes real sense.

Then at the end of phase:1, we can then at least optionally check the anomaly score and block the request. I'd say make it the default and provide an opt-out option for those who want to see all incoming request alerts.

The same holds true for phase:3/4, but probably less important.

**Comment by csanders-git** [comment]
I think this makes sense as we have some reported issues where Apache cuts off some invalid requests before ModSec gets to see it.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
