### ISSUE TITLE
Update SQL leakage errors

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#489]
List of errors in file 951 is outdated. Import new errors from https://raw.githubusercontent.com/sqlmapproject/sqlmap/master/xml/errors.xml

Note that the pre-check pmf data file must be updated too.

Every error message should also match the pmf data file.

**Comment by lifeforms** [comment]
unixODBC errors are missing, some examples:

```
[unixODBC][OpenLink][ODBC][Progress Server]Error in Network Daemon, SQL state 08801 in SQLConnect
[unixODBC][OpenLink][ODBC][Progress Server]Invalid packet length, SQL state k0k36 in SQLConnect
[unixODBC][OpenLink][ODBC]RPC: Remote system error, SQL state 08004 in SQLConnect
[unixODBC][OpenLink][ODBC]RPC: Unable to receive, SQL state 08004 in SQLConnect
```

Also PHP PDO SQLSTATE[12345], examples:

```
SQLSTATE[40001]: Serialization failure
SQLSTATE[23000]: Integrity constraint violation
SQLSTATE[HY000]: 
```

Seems to be that sqlstate is always 5 chars: A five-character SQLSTATE value ('42S02'). The values are taken from ANSI SQL and ODBC and are more standardized. Not all MySQL error numbers have corresponding SQLSTATE values. In these cases, 'HY000' (general error) is used. [source](https://dev.mysql.com/doc/refman/5.5/en/error-messages-server.html)

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
