### ISSUE TITLE
naming convention

### ISSUE THREAD

**Issue by failshell** [SpiderLabs/owasp-modsecurity-crs#49]
It would be nice if rules followed a stricter logic. It makes it harder (although not impossible) to automate the deployments of the CRS rules (im guessing the commercial rules have the same issue).

For example, the optional rule modsecurity_crs_42_comment_spam.conf has a data file named modsecurity_42_comment_spam.data. Forcing me to gsub the  file name to remove _crs.

It would be more elegant, and easier to configure using a CM tool like Chef/Puppet if rules file name matched their data file name.

**Comment by csanders-git** [comment]
so... going back through the issues list we have. I know this is REALLY delayed but to respond, we are starting to have quite a few data files for some rule files. It might still make sense to rename these files based on the file names but they'd be pretty long (and lowercased in CRS 3 RC1).  What's the use case here exactly? you want to remove or add specific data files based on the rule files that are included for performance reasons?

**Comment by dune73** [comment]
The rule files contain multiple rules. n of those will be based on a data file. It might make sense to start a data file with an indication of the rule file containing the rule which references the data file. But there will be multiple data files for the same rule file.

There are multiple naming criterias possible for the data file and it is really tricky to pick the right one.

One thing that I think we should do is introduce a common header in all data files with information about the rule that is using the data file. Right now you need to grep.

**Comment by dune73** [comment]
Let's look into this for v3.1.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
