### ISSUE TITLE
Purge GeoLiteCity.dat from Git

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#492]
To save space, purge `util/geo-location/GeoLiteCity.dat` from the v3.0.0-rc1 branch. Users who use geolocation can use the Python script in #464 to fetch the GeoIP country database periodically.

Procedure: https://www.owasp.org/index.php/OWASP_ModSec_CRS_Paranoia_Mode#Purging_a_file_completely_from_Git

Drawbacks: everyone who has the file checked out must do a new clone. Otherwise, if they pull and push, they will merge the file back into the repository.

**Comment by dune73** [comment]
I am ready for this fix. Just go ahead.

**Comment by lifeforms** [comment]
I prefer to wait with this operation until we have closed all PRs for 3.0.0. If I read the docs correctly, everybody must start over with a clean local clone, so it will be very inconvenient for people who are in the middle of PRs.

**Comment by csanders-git** [comment]
Right after you do that i'll add the repo links for the regressions and update the documentation repo.

**Comment by lifeforms** [comment]
Done!
