### ISSUE TITLE
Update rule files in INSTALL

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#493]
The `INSTALL` file points at old files like `REQUEST-00-LOCAL-WHITELIST.conf`. We now use `9xx` convention.

Do a new `ls` to get the new file names. Note that files have been added and shuffled around, so just a textual replacement is not enough.

**Comment by lifeforms** [comment]
- Renaming/search+replacing exclusions files

**Comment by dune73** [comment]
Moved to #510, where this issue is being fixed.
