### ISSUE TITLE
Add masscan to crawlers-user-agents.data

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#500]
I see the following UA:

```
masscan/1.0 (https://github.com/robertdavidgraham/masscan)
```

Rare and not overly aggressive. But let's add it for completeness.

**Comment by lifeforms** [comment]
Seems to be in `scanners-user-agents.data` though. Did it cause a false negative?

**Comment by dune73** [comment]
Yep. False negative because I did not realise I was watching a CRS2 server and I looked it up in the wrong CRS3 data file. Closing this.
