### ISSUE TITLE
Seek Best Practices Accreditation 

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#502]
https://bestpractices.coreinfrastructure.org

**Comment by dune73** [comment]
Sounds like fun. And not overly complicated.

**Comment by fzipi** [comment]
@csanders-git @dune73 Well, keeping up the fun I made the first attempt! https://bestpractices.coreinfrastructure.org/projects/1390.

I think there are a lot of things N/A to our project, but there are many that raised some good questions.

**Comment by csanders-git** [comment]
Thanks @fzipi many of these are probably have some areas to improve, a lot of which is in documentation :)

**Comment by dune73** [comment]
Thank you @fzipi. That looks so official. And also like we might have to add many more good governance practices and features...

If you can edit that entry, could you please
* have the website be https://coreruleset.org
* have the documentation link to that site too
* try and name the project closer to our real name. That is OWASP ModSecurity Core Rule Set. If it needs to be lowercase and hyphens, then it should be owasp-modsecurity-core-rule-set.

**Comment by fzipi** [comment]
@dune73 : shouldn't www.modsecurity.org/CRS/Documentation redirect to coreruleset.org somehow? It is confusing to have two "similar" sites, and there are no references between each other.

**Comment by fzipi** [comment]
Is there a public way to confidentially send a bug report? E.g. An email with gpg key public and a phrase like "If you detect something that needs to be handled in a private way, please email "confidential@coreruleset.org"?

**Comment by fzipi** [comment]
Also, we maybe have to include a way of download a release (not cloning) and maybe have it signed?

**Comment by fzipi** [comment]
Congratulations! According to the information that you've provided, your project has earned the CII best practices ‘passing’ badge. For more information, see this URL: https://bestpractices.coreinfrastructure.org/en/projects/1390

Please add your badge to your project and/or repository site; you've earned it:

In markdown you can add this: [![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/1390/badge)](https://bestpractices.coreinfrastructure.org/projects/1390)

In HTML you can add this: <a href="https://bestpractices.coreinfrastructure.org/projects/1390“><img src=”https://bestpractices.coreinfrastructure.org/projects/1390/badge"></a>

We strongly encourage you to add or improve justification text, including adding URLs that point to more information. If you have suggestions on how to improve the criteria or badge web application, please file an issue at: https://github.com/coreinfrastructure/best-practices-badge/issues If you made changes to your project to get a badge, please let us know via email at cii-badges-questions@lists.coreinfrastructure.org. One of our goals is to encourage projects to make some improvements. We put some of these reports on the public wiki; please let us know if you do NOT want the changes publicly posted at https://github.com/coreinfrastructure/best-practices-badge/wiki/Impacts Thank you, and congratulations.

--- David A. Wheeler, CII Best Practices Badge Technical Lead

**Comment by fzipi** [comment]
We can close this one!

**Comment by dune73** [comment]
Thank you for your time and dedication getting this done, @fzipi!
