### ISSUE TITLE
Add Static Based DOS Protection

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#504]
Should their be static file based DOS protection? is the overhead worth it for the average consumer? many consumers will be using caching servers here. High PL maybe? We'll look further into this for CRS 3.1. If you have feelings this is the place to be

Orig reported by @jschleus in #470

**Comment by dune73** [comment]
A strict sibling protecting static files as well sounds like a nice idea.

However, we need to be aware that ModSec DoS protection won't take you very far. It's much more effective to block ahead of the webserver / reverse proxy.

**Comment by csanders-git** [comment]
or block at the system level since you know... Apache has to be able to already handle the DOS for modsec to get it in most cases :-P

**Comment by csanders-git** [comment]
I'm gonna drop this idea as it's effectiveness level is minimal.
