### ISSUE TITLE
Add Mirroring protection 

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#505]
A quote from @jschleus in #470 

By the way I currently do first steps to experiment with two variations of REQUEST-912-DOS-PROTECTION.conf in order to protect my server against "mirroring" (downloading all or many of the offered often big files) by counting downloaded files (per IP; yes, that files are principally identifiable by file extension) and other "misuses" (shortly repeated downloads and also many partial downloads of a single file with a download volume exceeding the original file size by a factor of 3-30; maybe caused by erroneous browsers or ruthless download managers?) by counting bytes (per IP). I do that til now with some success asynchronously analyzing periodically the Apache log files with a script but hope that a modsecurity solution will work similar but react faster (although it seems less flexible and may cost more resources).

Can we add mirroring protection? Whats the performance trade off? how many FP will it cause? and more... stay tuned to this Issue for discussion of its inclusion in CRS 3.1

**Comment by dune73** [comment]
I think the arithmetic capabilities of ModSec are not good enough to pull this off ("factor of 3-30"). There are plenty of situations where a browser will show a weird behaviour in this regard. Or maybe this is a bad guess and a rule at a higher PL would work. It's certainly interesting.

My idea has always been to check the request rhythm. Users tend to browse in bursts (click, read, click again, read, ...). Mirroring scripts have a steady rhythm of requests after request. So I am really sure that the standard deviation of the time delta between requests would be much smaller for automatic agents than for browsers with real humans. But again: ModSec is not very good on math.

**Comment by dune73** [comment]
I think given the way we have positioned CRS and the continuing troubles with DOS protection, I think this is idea is nice, but out of scope for us. Also, we have not heard from @csanders-git about this for more than two years.

I suggest to close this issue.

**Comment by fzipi** [comment]
Agreed. This can be done using https://www.nginx.com/resources/wiki/modules/secure_download/ in nginx or maybe https://docs.unified-streaming.com/tutorials/security/apache-mod-auth-token.html for apache

Closing.
