### ISSUE TITLE
Any instance of "1=1" in an HTTP request or cookie triggers a "SQL Injection Attack" alarm

### ISSUE THREAD

**Issue by jkg011** [SpiderLabs/owasp-modsecurity-crs#51]
Please see http://bugs.jqueryui.com/ticket/8027

**Comment by csanders-git** [comment]
This is very delayed but still open and therefore deserves and answer. The rule that was causing this issue has been modified and the current release CRS v3rc1 no longer has thi problem. Both the following requests were tried

GET / HTTP/1.1
Host: localhost
User-Agent: Mozilla/4.0 (Windows XP 5.1) Java/1.7.0_13
Cookie: xyz=1%3d1


GET / HTTP/1.1
Host: localhost
User-Agent: Mozilla/4.0 (Windows XP 5.1) Java/1.7.0_13
Cookie: xyz=1=1

Netiher caused a FP. Thank you for the issue report and the patience :)
