### ISSUE TITLE
Do something about path parameters (-> /myapp;param=value/admin.php)

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#512]
Are they worth a rule? Certain forms worth a rule? Only at higher PLs?

Infos: 
- http://www.jtmelton.com/2011/02/02/beware-the-http-path-parameter/
- https://blog.qualys.com/wp-content/uploads/2012/08/Protocol-Level%20Evasion%20of%20Web%20Application%20Firewalls%20(Ivan%20Ristic,%20Qualys,%20Black%20Hat%20USA%202012)%20SLIDES.pdf

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
