### ISSUE TITLE
920310 (Missing Accept Header) firing on Exchange autodiscover (again)

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#515]
I see quite a few FPs from a variety of IPs for

``` 
"GET /autodiscover/autodiscover.xml HTTP/1.1" ... "Business/6.6.1.2 CFNetwork/758.5.3 Darwin/15.6.0"
```

We have talked about this a big deal in #366. It looks like Business was a synonym for Enterprise. At least they got the orthography right with this one.

**Comment by lifeforms** [comment]
`Business` :')

This is probably Skype for Business 6.6.1.2, but they are setting their user-agent wrong.

**Comment by lifeforms** [comment]
PR in #525.
