### ISSUE TITLE
920320 (Request Missing User-Agent) triggering a lot

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#516]
I had to remove this rule after triggering a lot from a variety of UA and IPs.

I propose to shift it to PL2.

This does not affect "Empty User Agent" 920330, btw.

**Comment by lifeforms** [comment]
Agree with moving to PL2. If you're paranoid, it might be a "nice to know". For most users, this alert will have very little value.

**Comment by dune73** [comment]
Closed in favor of PR #529.
