### ISSUE TITLE
LDAP Injection not being caught by the one rule

### ISSUE THREAD

**Issue by utdpauls** [SpiderLabs/owasp-modsecurity-crs#52]
See my post in the forum: https://sourceforge.net/p/mod-security/discussion/1298046/thread/684839f2/

Basically, rule id #950010 is catching injection attempts in the headers but not in the body.  An injection attempt embedded in a GET request is trapped, but an injection attempted embedded in a form field of a POST is missed.  I imagine this would take a new rule rather than an edit of 950010, but my modsecurity rule foo is rudimentary at best so I'm afraid I can't be of much help.

**Comment by fgsch** [comment]
This is long overdue. If this is still a problem please reopen it.
