### ISSUE TITLE
933160 (PHP Injection: High Risk Function Call) FP (very rare but still)

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#520]
This is a drupal site.

Matches
```
Matched Data: System (fermeture rotative et \\xc3\\xa0 clic) pour une s\\xc3\\xa9curit\\xc3\\xa9 maximale sur le terrain.&nbsp; Avec ses poign\\xc3\\xa9es confortables, isolantes et prolong\\xc3\\xa9es vers le bas pour une prise flexible, c'est le compagnon id\\xc3\\xa9al pour de longues randonn\\xc3\\xa9es \\xc3\\xa0 pied ou en raquettes.</p>\\x0d\\x0a\\x0d\\x0a<ul>\\x0d\\x0a\\x09<li>Mat\\xc3\\xa9riau: 100% carbone HM et aluminium 7075</li>\\x0d\\x0a\\x09<li>Poids: 430g (la paire)</li>\\x0d\\x0a\\x09<li>Longueur: r\\xc3\\xa9glable rapi... [hostname
```

**Comment by lifeforms** [comment]
Yeah, this will match `system(...)`. In PHP, any word may be a constant, so you could do the following:

```php
define('fermeture', 'uname -a');
system(fermeture);
```

Now, `system(fermeture rotative` can't be valid PHP, but we are limited in the regexp complexity for matching text between the parentheses. I have given this a few attempts but haven't come up with something that wasn't easily bypassed.

**Comment by csanders-git** [comment]
@lifeforms its not so much a constant as PHP will implicitly convert not quoted entities into strings ... IT"S A FEATURE!

**Comment by lifeforms** [comment]
@csanders-git Yeah it's both :)

**Comment by dune73** [comment]
This is covered by #603.
