### ISSUE TITLE
920220 (URL Encoding Abuse) should probably work on REQUEST_URI_RAW ...

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#524]
... not on REQUEST_URI.

**Comment by michaelgranzow-avi** [comment]
The REQUEST_URI has already been decoded, so the raw variable should be used for this check.
However, the regex is broken (see https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/422) - the should instead just apply validateUrlEncoding (no chaining needed).

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
