### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by LoreleiAurora** [SpiderLabs/owasp-modsecurity-crs#53]
After including this i am recieving the following error:
`Syntax error on line 52 of /etc/modsecurity/activated_rules/modsecurity_crs_20_protocol_violations.conf`

Any ideas what could be causing this?

**Comment by dune73** [comment]
Sorry for taking that long to address this.

The error was obviously due to an old ModSecurity version (<2.7.0) being incompatible with newer Core Rules. Distributions have mostly updated the ModSec module in the meantime, otherwise, try to upgrade ModSec.

I am closing this now.
