### ISSUE TITLE
are there any parser to parse modsecurity rule?

### ISSUE THREAD

**Issue by detailyang** [SpiderLabs/owasp-modsecurity-crs#530]
Hello, are there any parser to easily parse modsecurity rule to AST?

BTW, now i just using the ugly 'string  manipulate' transform modsecurity rule to the JSON :grin:.
I guess it's cool if we can provide the existing parser so that we can run the owasp-modsecurity-crs on other platform like nginx etc.

**Comment by dune73** [comment]
AST as in Abstract Syntax Tree?

**Comment by detailyang** [comment]
yep 😀

**Comment by lifeforms** [comment]
@detailyang ModSecurity rules are much more simple than an AST, they're more like a simple table... Could this help you? https://www.trustwave.com/Resources/SpiderLabs-Blog/ModSecurity-Python-Bindings--Parsing-ModSecurity-rules-from-Python/

**Comment by csanders-git** [comment]
@detailyang SecRules within libmodsecurity (see the modsecurity branch) has a full specified grammar - it should be trivial to generate an AST based off of the parser/lexer. Check it out!  https://github.com/SpiderLabs/ModSecurity/tree/libmodsecurity/src/parser

**Comment by csanders-git** [comment]
I'm going to close this but if you find this doesn't suit your needs, please reopen

**Comment by detailyang** [comment]
thank you, everyone! That is what i really need :)

**Comment by csanders-git** [comment]
@detailyang  -- it's what we do :). Hope you like what you find - we'd be happy to review anything you generate :)

**Comment by p0pr0ck5** [comment]
@detailyang where you ever able to develop anything from this? It seems like there's also some work being done upstream in https://github.com/SpiderLabs/ModSecurity/commits/v3/dev/parser, not sure if the intent here is to build a generic lexer/parser as part of libmodsecurity, or if this is just some refactoring. Would be cool to here if you've done something with this as I'd love to use a more formal approach to parser this DSL apart from ugly string manipulation (but lack the background to build something like this myself).
