### ISSUE TITLE
Rules to tackle impedience mismatch in ARGS_NAMES at higher PL

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#540]
The ModSec Handbook (in chapter 9: Impedience Mismatch) has a nice discussion of the problem which includes PHP accepting parameter names with whitespace in them just fine. As ModSecurity is more restrictive when it applies it's rules, you can work around ModSecurity rules  (usually local whitelisting rules and the like) and have PHP accept the parameter. Example:

```
http://xxx/students.php?studentid=1234567&%20studentid=1234567;drop%20table%20students
```

Here, ModSecurity sees two parameters, one legit and one not legit, while PHP ignoring the whitespace might see only one parameter with the latter one overwriting the former. CRS are likely to trigger on the SQLIi in the 2nd parameter. But ultimately, we want to detect any messing around with the parameter name.

So the idea is to provide rules at PL 3 and/or 4 which detect whitespace and maybe even whitelist allowed characters in parameter names.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
