### ISSUE TITLE
Error with CRS 3.0.0-rc1 "error parsing actions unknown action \\

### ISSUE THREAD

**Issue by dangelsaurus** [SpiderLabs/owasp-modsecurity-crs#544]
As is noted in [Continuation lines are broken during buffer resize Apache less than v2.4.11](https://bz.apache.org/bugzilla/show_bug.cgi?id=55910)  

> Handling of line wrapping is broken if "\" is the last character before buffer resizing. Right know that's the 206. character.

 v3.0.0-rc1 causes an issue particularly with Ubuntu 14.04 LTS with Apache 2.4.7 where you will randomly receive the follow error since rules have many more line breaks than previously.

`AH00526: Syntax error on line 35 of /etc/apache2/conf/crs/rules/<RULESET FILE HERE>:
Error parsing actions: Unknown action: \\
Action 'configtest' failed.`

simply adding a space or combining lines together solves the problem for the file in question... But with rc1 and rc2 gaining steam, I'm curious if this problem is worth noting officially in the release notes etc?

This is also documented [http://stackoverflow.com/questions/37369990/modsecurity-error-parsing-actions-unknown-action](http://stackoverflow.com/questions/37369990/modsecurity-error-parsing-actions-unknown-action) and in the mod-security-developers mailing list.

**Comment by dune73** [comment]
Good thinking @dangelsaurus. 

In fact a note has been placed in the KNOWN_BUGS (PR #543). But this occurred to us only after RC1 came out. It will be part of the full release, though.
