### ISSUE TITLE
973338 (XSS Filter) FP

### ISSUE THREAD

**Issue by gazbarg** [SpiderLabs/owasp-modsecurity-crs#546]
The rule triggers on an URL with arg `?session=akq7spsrc77bo8drc1l0jopho4`, which contains the string `src` and thus matches the `[\s\S]src[\s\S]` part of the regexp.
Shouldn't it be `\bsrc\b` instead (same change for each keyword) ? The 'space or not space' seems weird.

**Comment by lifeforms** [comment]
Thanks for the report.

The good news is this false positive is no longer present in CRS 3.0.0 which we are currently testing for its release around October. The bad news is, CRS 2.x is going into legacy mode and given limited resources we intend to do only critical security fixes to it. While this is an irritating FP, it is one of many known FPs in CRS 2.x. Would it be an option for you to test CRS 3.0.0? Besides drastically lowering FPs it should also improve your protection in many areas.

**Comment by dune73** [comment]
@gazbarg  I think it is best you either update your rule locally (as per your suggestion) or you disable it for the session parameter with 

```
SecRuleUpdateTargetById 973338 !ARGS:session
```
