### ISSUE TITLE
Detect Java code injection

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#550]
It could be worthwhile to add detection for Java code injection.

We could use a similar approach to PHP function detection by listing common class names and attack syntax.

Examples from a Struts vulnerability:
1. `http://host/struts2-blank/example/X.action?action:%25{(new+java.lang.ProcessBuilder(new+java.lang.String[]{'command','goes','here'})).start()}`
2. `http://host/struts2-showcase/employee/save.action?redirect:%25{(new+java.lang.ProcessBuilder(new+java.lang.String[]{'command','goes','here'})).start()}`
3. `http://host/struts2-showcase/employee/save.action?redirectAction:%25{(new+java.lang.ProcessBuilder(new+java.lang.String[]{'command','goes','here'})).start()}`

https://struts.apache.org/docs/s2-016.html

JSP webshells

https://github.com/tennc/webshell/tree/master/jsp

**Comment by fgsch** [comment]
Is this covered by https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.2/dev/rules/REQUEST-944-APPLICATION-ATTACK-JAVA.conf?

**Comment by dune73** [comment]
The three examples above all score 15 points and more in PL1 now. Closing this.

@lifeforms : Please re-open if you disagree.
