### ISSUE TITLE
Host header oddities

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#553]
http://www.icir.org/vern/papers/host-of-troubles.ccs16.pdf

This might not affect us so much but is worth the read depending on your deployment

**Comment by csanders-git** [comment]
Seems like we can add a rule to be more strict about host headers -- although most of the servers have fixed their implimentation. Things like spaces in host headers are bad ...

**Comment by lifeforms** [comment]
I have only skimmed this paper but I'm adding my notes about the Host header in this issue.

I think We should be strict about the Host header value. Right now you can even pass SQLi in the Host header without getting an alert. Multi-site CMS often interpret this header and use it in a database query.

Would there ever be a valid reason for a Host header value which is not a [valid DNS hostname](http://stackoverflow.com/questions/106179/regular-expression-to-match-dns-hostname-or-ip-address)? I think we might even be able to put a regexp check for the Host header in paranoia level 1.

If possible we should block on multiple Host headers, but I don't know if there are broken clients so we have to test this a bit.

**Comment by csanders-git** [comment]
I think valid DNS name might work well -- also note that this value may be used for transparent proxies - still think this will be a domain, but might be something else. It may also be an IP address.

**Comment by csanders-git** [comment]
it'd be nice to have an @validateURI function :-)

**Comment by dune73** [comment]
You see some weird things in host headers at times. So while being a useful rule, this needs testing.

IP addresses should be OK at PL1. Otherwise, I support the idea.

**Comment by lifeforms** [comment]
We do have rule 920350 in PL1 which explicitly rejects IP addresses though! (I recall that we had a semi-Holy War about it, but I would have sworn we've moved that rule to PL2 in the end... Guess not!)

**Comment by dune73** [comment]
Oops. At pl1? I second your memory though.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
