### ISSUE TITLE
Adopt the undocumented unconditionalMatch operator

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#554]
The undocumented operator `@unconditionalMatch` does exactly what you expect it to do.

Example Use:

```
SecRule REMOTE_ADDR "@unconditionalMatch" "id:1000,phase:1,pass,nolog,t:hexEncode,setvar:TX.ip_hash=%{MATCHED_VAR}"
```

We do empty regex matches quite a lot in situations similar to the example above. This means we match `@rx .` or something of the sort in order to fill `%{MATCHED_VAR}`. And this brings a substantial overhead, which can be avoided by the use of `@unconditionalMatch`.

Furthermore, I have a feeling it will - when combined with chain - allow for new rule constructs of the following form:

```
SecRule ARGS "@rx test" "id:1000,phase:1,pass,log,chain"
   SecRule MATCHED_VARS_NAME "@unconditionalMatch" "setvar:..."
```

I need to think about this some more, but this could potentially bring solutions to the problem, that the rule chains first loop over all ARGS of the first rule and then loop over the 2nd rule with all matched vars (instead of the 2nd rule immediately after the first match).  This "first rule loop first" results in the 2nd rule not knowing which ARGS it is working on. unconditionalMatch might help. Or maybe not.

**Comment by csanders-git** [comment]
im missing somethign what does it do?

**Comment by dune73** [comment]
It fills `MATCHED_VAR` faster than `@rx .` can.

Look at my first example filling `TX.ip_hash`. I do not think you can pull this off this fast without `@unconditionalMatch`.

**Comment by csanders-git** [comment]
ahh so i see -- it is the equivalent of SecAction except it has a variable, interesting - yes it would seem we should document this in the reference manual - -let me check the code to ensure

**Comment by csanders-git** [comment]
wow there is also @nomatch

**Comment by csanders-git** [comment]
haha ok to nomatch just forces the rule never to fire and unconditionalMatch forces it to fire (returns 0 or 1). Yeah this is pretty handy... because @rx .* is nasty. How have i never seen these :-P, good eye. @zimmerle you should make sure that these are in libmodsec also

**Comment by dune73** [comment]
It is funny, I wanted to have this operator for several weeks now and was thinking about doing a feature request.

Then yesterday as I was reading the debug_log I saw it displayed during the execution of SecAction. It seems this is used to implement SecAction via SecRule.

Then I googled it and found it is used by Ivan in the performance chapter in a recipe on page 192. (Actually next to `@noMatch` but I did not notice this yesterday. Thanks for pointing this out).

Somehow it felt like a x-mas gift or an archaeological discovery. ;)

**Comment by lifeforms** [comment]
A small, localized party is in order.

**Comment by fgsch** [comment]
This is documented now. 

Which rules can benefit from this? Let's try to work towards a PR or something actionable.

**Comment by dune73** [comment]
This was posted here for reference. Some hopes I had with this operator fainted (as I can't seem to solve the looping problem with it), but I use it so frequently in my own rules, that we no longer need this issue as reference.

If I see a benefit from using it in CRS, I would push it. It's more interesting when doing very complex rules or for debugging.
