### ISSUE TITLE
Skip RESPONSE_BODY checks for static files in PL1

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#562]
`SecRule RESPONSE_BODY "@rx ..."` is a resource hog on big files (css, js, png, you name it).

Performance issues are (most?) often fought by issuing a general `SecResponseBodyAccess Off` which is far worse then a selective exclusion of the said rules.

For PL1, I do not see the point in risking performance loss.

Two possible solutions:
- disable response body access selectively in phase 3 depending on the content-type.
- Skip the rule depending on the content-type in phase 4.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
