### ISSUE TITLE
Detect bots via numbers of request headers

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#565]
Bots and scanners and crawlers disguise their UA header. But one characteristic they also have in common is a lack of fantasy when it comes to other request headers: a low number of request headers might indicate the request was sent from a scanner / bot .

**Comment by csanders-git** [comment]
I do kinda wish we had more capability to do this type of like hamming distance type tests. But it'd be interested to see what the result of this would be:

Thinking

SecRule &RQUEST_HEADERS "@lt 5" "id:123,msg:'testing what this number should be'

**Comment by lt** [comment]
I hate your less than operator -_-

**Comment by csanders-git** [comment]
haha, @lt sorry my fault, forgive us for this syntax.

**Comment by dune73** [comment]
Yes probably. Maybe I'll run the following on some production server (note avoidance of the &lt operator. I mean I was tempted to add a @ here. :)

```SecRule &REQUEST_HEADERS "@unconditionalMatch" "id:124,pass,no,noauditlog,msg:'Number of request headers: %{MATCHED_VAR} for UA: %{REQUEST_HEADERS.User-Agent}'"```

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
