### ISSUE TITLE
ipMatch against list of datacenter IPs (clients should not be using these)

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#566]
https://github.com/client9/ipcat is a list of IP addresses of datacenters. The idea is that standard clients should not be using these IPs. Probably an idea for a higher PL.

**Comment by csanders-git** [comment]
not sure this is a great idea, some of the people who use ModSecurity are on this list. what is bad about a client hitting these IPs? are we thinking javascript based DOS?

**Comment by lifeforms** [comment]
@csanders-git More like hacked servers / botnets / malware spreaders... I'm blocking more and more virtual hosting ranges from GoDaddy etc. Client connections from there are pretty useless except for "Wordpress pingbacks" which is a misfeature by itself... So I think this idea has potential but it is definitely not for anyone, maybe not even at higher PL. Maybe we should rethink reputation management and add this under that banner (orthogonal to PL choice). Together with our possible future own dynamic blocklist ;)

**Comment by csanders-git** [comment]
Oh, i misunderstood - this is blocking incoming requests from hosting providers. no outgoing requests to hosting providers.

**Comment by dune73** [comment]
I am not sure this is a good idea either. But it's a thought...

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
