### ISSUE TITLE
Find a way to support Blocking Mode with higher PL in Detection-Only

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#567]
Say you run in PL1, threshold 5. If you raise the PL in order to tune it, your users will be blocked immediately. How can you stay at threshold 5 and get to see the PL2/3/4 alerts without blocking legitimate requests?

**Comment by csanders-git** [comment]
we could add a variable amount in the backend and make it either 0 (if they are enabled) or the negative version of the anomaly score thereby canceling their effect.

**Comment by dune73** [comment]
Would this mean to update every rule? Can you give an example?

**Comment by dune73** [comment]
https://twitter.com/ChrFolini/status/835195762870996992

-> Count anomaly scores separately per paranoia level and then report them, but only use the scores for the PL that are enabled. Under the line, this means to separate PL->rule-execution and PL->anomaly-score-blocking. You could thus run rules from PL3, but only use the scores of PL1 and PL2 for the blocking decision.

**Comment by emphazer** [comment]
is this issue or feature request still up to date?

**Comment by emphazer** [comment]
i close this issue because of inactivity.
