### ISSUE TITLE
Prepare mechanics to raise PL depending on GeoIP / Path etc.

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#568]
It seems worthwhile to run in PL1, but have foreign requests to your local B2B site turn at a higher PL.

Likewise, running in PL1, but the admin interface on `/admin` via a higher PL. Or maybe the other way around with the free-text support contact form in an otherwise locked down service.

Technically this is fairly easy. And preparing a mechanism to support this should not be a problem. But there is a practical problem that there will be less test traffic for these higher PL runs and thus less tuning. In the end, the application will likely be broken. And this might cripple the usefulness of this feature.

**Comment by csanders-git** [comment]
Are you thinking about as an example or as a setup comment? were you thinking like:

SecRule REQUEST_URI "@rx \/admin\/" "id:123,setvar:tx.paranoia_level=2, pass, nolog"

It can stritctly be anywhere after the orig paranoia check, and before the start of the bulk of the rules.

**Comment by dune73** [comment]
Yes, possibly like this.

But what about the practical problem I was talking of? I do not think an undertuned admin interface at PL2 is usable with strict limits.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
