### ISSUE TITLE
apache2 configtest fails (x2, fresh install)

### ISSUE THREAD

**Issue by eugenebann** [SpiderLabs/owasp-modsecurity-crs#569]
I haven't got time to search issues, so _there is a possibility that the below is already documented_, in which case I sincerely apologize. however, just in case, I am quickly mentioning two bugs which forced me to comment out two rules in order to successfully restart apache with MSORS (I know, lazy).

I am using Apache/2.4.7, Ubuntu 14.04.5 LTS, owasp-modsecurity-crs v3.0.0-rc2 branch

```
AH00526: Syntax error on line 56 of /etc/modsecurity/owasp-modsecurity-crs/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf:
Error creating rule: Failed to resolve operator: detectXSS
```
```
AH00526: Syntax error on line 36 of /etc/modsecurity/owasp-modsecurity-crs/rules/RESPONSE-950-DATA-LEAKAGES.conf:
Error parsing actions: Unknown action: \\
```

**Comment by dune73** [comment]
Thanks for reporting.

#1 looks like you are running the standard Ubuntu ModSec, which is likely 2.7.7. The `@detectXSS` operators was introduced with 2.8.0.  (See Prerequisites in INSTALL). 

#2 is a known Apache bug. You need to upgrade to Apache 2.4.11. See https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0.0-rc2/KNOWN_BUGS

**Comment by eugenebann** [comment]
Thanks a lot @dune73!

**Comment by deepakxoptimo** [comment]
I am getting below error

"AH00526: Syntax error on line 64 of ..crs/modsecurity-crs/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf:
Error creating rule: Failed to resolve operator: detectXSS"

I have installed mod security 2.9.1 on apache 2.4.6.Below are the data from apache error log file 

 ModSecurity: StatusEngine call: "2.9.1,Apache/2.4.6 (CentOS) Ope,1.4.8/1.4.8,8.32/8.32 2012-11-30,(null),2.9.1,0f4af4*********"

 ModSecurity: StatusEngine call successfully sent. For more information visit: http://status.modsecurity.org/


any suggestions?

**Comment by dune73** [comment]
That's very strange. detectXSS was introduced in 2.8.0, but your installation clearly says you are up to date.

But whatever it is, it is more of a ModSecurity than a CRS problem.

**Comment by deepakxoptimo** [comment]
Thanks for the reply. But what should I do now. Should I disable the rules where I am getting these kind of issues.

**Comment by csanders-git** [comment]
@deepakxoptimo did you compile modsecurity or install it from yum. Just for your info it's triggering https://github.com/SpiderLabs/ModSecurity/blob/v2/master/apache2/re.c#L2417 . This is strange

**Comment by deepakxoptimo** [comment]
I have used below command to install it 

sudo yum --enablerepo=epel install mod_security

**Comment by dune73** [comment]
Also see #785.
