### ISSUE TITLE
(minor) comment line-broken lines in REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example

### ISSUE THREAD

**Issue by eugenebann** [SpiderLabs/owasp-modsecurity-crs#570]
E.g. line 72 and line 82.

**Comment by dune73** [comment]
If I read your report correctly, you are talking about this pattern:

```
#SecRule REQUEST_FILENAME "@endsWith /wp-login.php" "id: 901001,phase:request,t:none \
  nolog,pass,ctl:ruleRemoveTargetByTag=OWASP_CRS;ARGS:pwd"
```

You mean that the 2nd line needs another `#` to mark it as a comment. But that is not the case. The backslash ending the first line extends the comment to the second line. Just like it would on an active line.

You should be able to Include this file in your configuration and Apache should start without any problems.

Please close this bug, if I was able to convince you - or explain if not.

**Comment by eugenebann** [comment]
Ah, my bad, just being pedantic. Apache had no problems of course, probably should adjust my vim settings. Sorry for the bother!

**Comment by dune73** [comment]
No worries.
