### ISSUE TITLE
941120 (XSS Filter) REQUEST_COOKIES:  FP suspicion and question

### ISSUE THREAD

**Issue by jschleus** [SpiderLabs/owasp-modsecurity-crs#571]
Not important but ... I found that the following  part of a Request Cookie

     PSN: VVQ Dk8OmLOX1ONZPdsLBw==

 matches rule 941120 (CRS3 RC2) with

     Matched Data: 1ONZPdsLBw=

Ok, that may be not the kind of string that the rule was built for so it may be a kind of FP but on the other side the requesting IP sent only that single request that seems not to be a really "wanted" (good) one so it seems something like a "true" FP or a "false" TP.

By the way the total Cookie string has a length of 7770  bytes (!) what brings me to the question if it would be meaningful to build a rule that checks (optionally) the length of the variable REQUEST_COOKIES against a given limit, especially for servers with short  cookie strings or even without any cookie usage.

**Comment by dune73** [comment]
That looks like bad luck on a cookie with an accidental hit. But then if you do a 7K long Cookie, you are effectively raising the chance for a false positive of course.

There is Apache's LimitRequestFieldSize of course, but it might make sense to have an artificial limit included with the core rules. Would you be interested to create an issue for this with the "CRS 3.1.0 rule candidate" label.

As for this particular case, I think we should just ignore it until we have clearer findings in this direction.

**Comment by jschleus** [comment]
Christian is right and so I close this issue but not without making two comments:

1) Some of the rules in REQUEST-941-APPLICATION-ATTACK-XSS.conf probably would benefit from some finetuning. For e.g. in the mentioned (ok, very rare) FP the matching pattern is principally just an integer before the quite general string "on" followed by some arbritray "word" characters and a "=". In rule 941130 I had avoid some more frequently found FPs by making some patterns more strict by delimiting some of the keywords for e.g. by a "\W".

2) With a hint of Christian I used basically the following "test" rules to inspect unexpected cookies. The a little bit arbitrary limit of 300 bytes was set after a first test run without that distiction since many
of the requests with cookies lengths lower this limit seem to be "normal" and interactively "human" generated,
```
# Ignore the only expected cookie string (Doxygen) on this site
SecRule REQUEST_HEADERS:Cookie "@rx ^doxygen_width=[1-9][0-9]{1,3}$" \
pass,\
nolog,\
skip:2"

SecRule REQUEST_HEADERS:Cookie "@le 300" \
"msg:'Unexpected cookie string (%{REQUEST_HEADERS.Cookie}) with length: %{matched_var} <= 300',\
t:length,\
pass,\
log,\
skip:1"


SecRule REQUEST_HEADERS:Cookie "@gt 300" \
"msg:'Unexpected cookie string with length over the given limit: %{matched_var} > 300',\
t:length,\
pass,\
log"
```
That rules run now over one week and I inspected some (but not all!) of the matches: Although I have no idea why that unexpected and completely server-unrelated cookies are sent (I suspect malware infected hosts or  unlikely errorneous browsers) and I saw a raw relation between the length of that unexpected cookies and the probability of the "badness" of the according requests I had the impression that the rules in the current simple form are not suited to deny requests without the risk of FPs  (moreover since the "bad" ones are mostly caught by other rules), at the most they can be used to add some anomaly score points.

So I have decided not to open a separate issue regarding "Unrelated and/or overlong cookies".

**Comment by dune73** [comment]
Hi @jschleus 

Unreleated cookies happen (that's the best theory I heard) when users surf a domain via port 80 over a commercial public WIFI access point and the network provider injects adware with cookies, making them look originating from a certain hostname / domain.

**Comment by jschleus** [comment]
Ok, but that cookies I would expect smaller than for e.g. the (arbitrary) 300 bytes limit. The longer ones seems sometimes like a collection of all cookies the browser  (of an  infected host?) has gathered.
But I am not an expert on this area.

**Comment by dune73** [comment]
Intriguing thought. Hm...
