### ISSUE TITLE
Directadmin

### ISSUE THREAD

**Issue by ben29** [SpiderLabs/owasp-modsecurity-crs#575]
Hi.
there is any guide or problem to fit it to Directadmin ?

**Comment by dune73** [comment]
I do not think there is a guide available. But there should not be a special issue if you
integrate it with the CRS3-rc1. There will be a few false positives, which you need to fix.

Please report them and we try and handle them in the crs project.

**Comment by lifeforms** [comment]
It should work fine with DirectAdmin. In fact, if you use DirectAdmin's custombuild option to compile your own Apache (which I would recommend), you can enable the custombuild option `modsecurity` to build and install the newest ModSecurity. I have used [this Puppet module](https://github.com/sensson/puppet-directadmin) to install DirectAdmin and ModSecurity via Puppet with success.
