### ISSUE TITLE
Block LFI/RFI using protocol schemes

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#577]
We have a rule in paranoia level 2 (931130) that blocks submitting `ftp://`, `http://` and `https://` URLs to prevent RFI.

However, we don't yet have a rule blocking `file://` URLs which may be abused for LFI. These URLs will read local files if the application does not have a scheme whitelist.

See for instance: https://blog.steve.fi/If_your_code_accepts_URIs_as_input__.html

1) I'd argue that `file:///` is probably vastly more indicative of bad behavior, and we could try blocking that in paranoia level 1.

2) More generally, we could match on all kinds of unknown protocols, e.g. `^[a-zA-Z]+://` to close any unknown holes due to obscure protocol schemes. I could see such a rule ending up in PL2 or maybe PL3.

**Comment by dune73** [comment]
Very good idea.

However, 931120 is PL1.

**Comment by lifeforms** [comment]
@dune73 Sorry, I meant 931130.

**Comment by dune73** [comment]
So your idea is basically:
* new rule 931130 for `file:///` at PL1
* old rule 931130 becomes 931131 at PL2
* new rule 931132 scans for other obscure protocols of the form `^[a-zA-Z]+://` in PL2 or PL3.

I second that. Personally I see some logic in putting the new rule in PL3 as it builds a clear cascade:
* PL1: deny `file:///`
* PL2: deny `ftp://`, `https://` etc.
* PL3: deny anything with `://`

**Comment by fgsch** [comment]
You also want numbers on the regexp for the scheme.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
