### ISSUE TITLE
Read only mode (paranoia level 5?)

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#591]
I've always wanted to offer some kind of super-paranoid "read only mode". Maybe this could be a future paranoia level 5?

In this mode, the CRS would:
- disallow http methods that submit data such as POST, PUT, DELETE, etc.
- disallow ARGS and ARGS_NAMES, so you can't submit query parameters (maybe excluding the utm ones)
- disallow request bodies
- disallow any unusual characters in the URI, allowing only a short list like `a-z A-Z 0-9 . - _ /`
- disallow any special characters in cookie names and values? (debatable; the user might not have control over which cookies are sent)

You could basically put this up for read-only sites, like newspaper sites, public facing content sites for large organizations, sites under current attack, etc. It could approach the security profile of a static site generator, but you will still be able to use any CMS you like.

You could whitelist your office IPs for the content managers, and if you still need to expose some endpoints requiring user input (like a search page or JSON API), you could specifically exclude those by doing `ctl:ruleRemoveRuleByTag=paranoia-level/5`.

I feel that this mode should take precedence over app exclusions. Otherwise, the app exclusions would create large (and publicly known) holes in this security profile. So, maybe this mode should be seen as something categorically different from the paranoia level system. At the other hand, this mode does feel like a natural progression after PL4, and I probably would also want to enable all the PL4 level strictness for URIs when using this mode (e.g. SQLi in URIs) to get extra alerts. Also, adding this mode into the PL system will allow a single knob to set all strictness properties of the CRS, which would allow for the easiest automation / deployment / GUI integration.

**Comment by dune73** [comment]
I like this. Obviously more thinking is needed, but the idea has some merits.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
