### ISSUE TITLE
Using on an existing log

### ISSUE THREAD

**Issue by adamziaja** [SpiderLabs/owasp-modsecurity-crs#604]
Hi, is possible to using this rules on an existing log? When I have just file access.log and want check with this rules for web attacks in forensics purposes.

**Comment by csanders-git** [comment]
Not using ModSecurity v2. But ModSecurity V3 is able to function in this respect by building a custom connector. I'd recommend the python bindings but they're currently non functional so you'd have to hook it in C.

**Comment by lifeforms** [comment]
Have to add that an access_log does not contain all necessary information though... (headers, cookies, and POST data are not missing) So it will definitely miss a lot of problems.

**Comment by dune73** [comment]
Personally, I work with an extended access.log and the error.log 99% of the time.

Extended Access Log:

```bash
LogFormat "%h %{GEOIP_COUNTRY_CODE}e %u [%{%Y-%m-%d %H:%M:%S}t.%{usec_frac}t] \"%r\" %>s %b \
\"%{Referer}i\" \"%{User-Agent}i\" %v %A %p %R %{BALANCER_WORKER_ROUTE}e %X \"%{cookie}n\" \
%{UNIQUE_ID}e %{SSL_PROTOCOL}x %{SSL_CIPHER}x %I %O %{ratio}n%% \
%D %{ModSecTimeIn}e %{ApplicationTime}e %{ModSecTimeOut}e \
%{ModSecAnomalyScoreIn}e %{ModSecAnomalyScoreOut}e" extended
```

**Comment by adamziaja** [comment]
ModSecurity V3 is also somewhere free to download and use with this rules?

**Comment by adamziaja** [comment]
Can I found some information how do this with V3?
