### ISSUE TITLE
cPanel and its GET /whm-server-status

### ISSUE THREAD

**Issue by CanadianJeff** [SpiderLabs/owasp-modsecurity-crs#620]
```
{
"type": "The rule generates false positive hit entries",
"rule_text": "SecRule &REQUEST_HEADERS:User-Agent \"@eq 0\" \"msg:'Request Missing a User Agent Header', severity:'NOTICE', phase:request, rev:'1', ver:'OWASP_CRS/3.0.0', maturity:'9', accuracy:'9', t:none, pass, id:'960009', tag:'application-multi', tag:'language-multi', tag:'platform-multi', tag:'attack-protocol', tag:'OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_UA', tag:'WASCTC/WASC-21', tag:'OWASP_TOP_10/A7', tag:'PCI/6.5.10', setvar:'tx.msg=%{rule.msg}', setvar:tx.anomaly_score=+%{tx.notice_anomaly_score}, setvar:tx.%{rule.id}-OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER-%{matched_var_name}=%{matched_var}, skipAfter:END_UA_CHECK\"\n",
"hits": [
{
"meta_offset": "0",
"http_version": "HTTP/1.0",
"meta_line": "317",
"meta_logdata": null,
"http_method": "GET",
"meta_severity": "NOTICE",
"timezone": "-420",
"meta_msg": "Request Missing a User Agent Header",
"http_status": "403",
"meta_file": "/etc/apache2/conf.d/modsec_vendor_configs/OWASP/rules/REQUEST-20-PROTOCOL-ENFORCEMENT.conf",
"justification": "Operator EQ matched 0 at REQUEST_HEADERS.",
"meta_id": "960009",
"meta_rev": "1",
"id": "1018",
"action_desc": "Warning.",
"path": "/whm-server-status",
"ip": "127.0.0.1",
"timestamp": "2016-10-19 09:05:02",
"host": null,
"meta_uri": null,
"handler": "server-status"
}
],
"message": "cpanel/whm automated requests trigger this"
}
```

**Comment by lifeforms** [comment]
Hi @CanadianJeff, thanks for the report. Indeed this is a potentially annoying rule.

In the newest CRS3 RC2 version, we have moved the rule, now numbered 920320 (Missing User Agent Header), to paranoia level 2. That means that by default, installations will no longer see this alert. We recommend to run paranoia level 2 only if you are prepared to have some false positive rule alerts, which you must tune yourself. In turn you get a lot of extra protections however.

I definitely recommend trying out our RC2 release. It has lots of improvements over the version you are now running. You can download a copy [https://github.com/SpiderLabs/owasp-modsecurity-crs/releases/tag/v3.0.0-rc2 from the releases page] or use the `v3.0.0-rc2` branch in git.

If you could help test the new version, it would be very welcome. While this alert will be solved for you, we are always looking for your other comments.

**Comment by CanadianJeff** [comment]
................

**Comment by CanadianJeff** [comment]
I installed this using cPanel internal WHM panel

http://httpupdate.cpanel.net/modsecurity-rules/meta_OWASP.yaml

**Comment by lifeforms** [comment]
@CanadianJeff Thanks for letting us know. I'm sure cPanel will update their packages to CRS 3.0.0 once it's released, which should hopefully be in the 2nd week of November. I think @csanders-git is in contact with cPanel so we will make sure to contact them about the update.

**Comment by CanadianJeff** [comment]
alot of noise yes

**Comment by csanders-git** [comment]
Yes I am in contact with them, i'll see if we can get a test account.
