### ISSUE TITLE
Bad command in config: Header

### ISSUE THREAD

**Issue by lilmike** [SpiderLabs/owasp-modsecurity-crs#625]
Hi,
I'm using nginx 1.11.5 and modsecurity 2.9.1 from the AUR in arch linux. I tried linking some rules from the owasp core ruleset to /etc/nginx/modsecurity.d/active_rules, but there's a few that cause nginx to not start. The only output I get is 'bad command in config: Header'. I've grepped, and it looks like there's about 2 files that use the Header command, but nginx/modsecurity/whichever doesn't seem to like it. Any thoughts?
Thanks,
-Michael.

**Comment by dune73** [comment]
Could you be more specific please.

Other than that, you seem to be working with the former CRS 2.2.X code branch. We are currently phasing out this old release and will be releasing CRS3 in the coming weeks. CRS3 are a lot easier to install and maintain than CRS2 (by a very, very wide margin).

The RC2 is currently out and it can easily be used in production. The only remaining issues are some unwanted false positives, but far fewer than those in your ruleset.

You can get CRS3-rc2 at https://github.com/SpiderLabs/owasp-modsecurity-crs/releases

**Comment by csanders-git** [comment]
You're almost for sure including some optional rule that was only built for Apache. NGINX doesn't support mod_headers and therefore it is complaining to you. Sorry about that

**Comment by lilmike** [comment]
Ah ok, that makes sense. Also upgrading to 3.0.0 rc2 fixed the errors :D. Now just to figure out why modsecurity is causing nginx to segfault... hmm. But that's another issue. Closing.
-Michael.

**Comment by dune73** [comment]
Thanks for reporting back @lilmike. And good luck with those segfaults.
