### ISSUE TITLE
False positives -- is the regex for 981247 a little loose?

### ISSUE THREAD

**Issue by Paladin** [SpiderLabs/owasp-modsecurity-crs#629]
Getting some matches to this rule from article/blog post slugs. Examples (trimmed to show the essential bits):

?2856-Update-2-3-9-on-Mavericks
?2613-Updated-iPad-now-cannot-login

Shouldn't the regex be constrained to match SQL keywords on word boundaries? Otherwise it yields false positives on slugs generated for articles titled ranging from "Joining Trade Unions" to "Selecting an Updated iPad" to "Inserting Generated Content With CSS"

Or am I missing something?

**Comment by csanders-git** [comment]
Hey @Paladin sorry about the slow response (I blame it on Halloween weekend here in the states :-) ). In any event, we have been hard at work reducing false positives in the CRS v3.0.0 branch and in fact what you have reported in one of the things we've addressed :). We have the release coming next week but you can check out RC2 at the release section https://github.com/SpiderLabs/owasp-modsecurity-crs/releases
