### ISSUE TITLE
Remove maturity, accuracy and possibly even version

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#631]
These values are not really managed in a consistent way and they eat up space in the alert message. 

The space in the alert message is limited and these values can get priority over tags in the error log. This means ModSec cuts away tags in order to save space. I would rather have the tags and dump these.

Or I am wrong and we need to talk.

**Comment by csanders-git** [comment]
I think accuracy is well summed up by the different PL's we have and i'm thinking that's where it came from - I don't much like adding it eitherway.
IT should be possible to use maturity, but again you're right not sure if we need to. Version i'd keep as it makes it very easy to determine quickly what ruleset users are using just by the rule they publish.

**Comment by dune73** [comment]
I confirm it is better to keep the action _ver_. But I am still convinced that _accuracy_ and _maturity_ should go.

**Comment by lifeforms** [comment]
Agreed.

**Comment by dune73** [comment]
Thanks.

**Comment by fzipi** [comment]
@dune73 I think per #878 this could be closed!

**Comment by dune73** [comment]
Agreed. Thank you for the heads up.
