### ISSUE TITLE
ModSecurity version 3 as part of the QA

### ISSUE THREAD

**Issue by zimmerle** [SpiderLabs/owasp-modsecurity-crs#637]
I've saw that we are running QA for every commit via Travis. I would like to know if that is possible to add ModSecurity version 3 as part of those tests as well.

Even if you don't consider ModSecurity version 3 to be the target for the QA itself, it would help a lot the development and `testing' of ModSecurity version 3.

**Comment by csanders-git** [comment]
Yes, we do intend to do so. There are some other steps first before we get there.
I'm going to need to upgrade my Ansible script to support v3 as well.

**Comment by lifeforms** [comment]
Would be great!

**Comment by fzipi** [comment]
@csanders-git Do you want me to create a container for this test?

**Comment by csanders-git** [comment]
https://gist.github.com/binaryanomaly/3f04758d6bd2a26f018fce2d05def9be
would be a good start but PRs are always accepted

**Comment by lifeforms** [comment]
This is definitely on the roadmap of our Travis experts. Currently however, ModSecurity v3 has some behavioral changes, or bugs, which make part of our test suite fail. While we have worked around some changes, it's not there yet. We will try to help on the ModSec GitHub to address the issues as best as we can.

**Comment by airween** [comment]
Just a poor self-promotion for this :). There is the [ftwrunner](https://github.com/digitalwave/ftwrunner), which does explicitly as it need - without any HTTP server. Of course, users (and developers too) need the correct result about _how-the-whole-system-works_, including HTTP server, engine and rule set. But we can use it as 1st step (eg. the runner faster than any other test suite).

**Comment by fgsch** [comment]
Travis includes modsec 3 tests for apache and nginx. 
Is there anything else to do in this issue?

**Comment by dune73** [comment]
Let's close this for now.

We run v3 on Travis and the experience will only get better when ModSec3 passes our test suite. We can then configure Travis to block on unit test failures.
