### ISSUE TITLE
Detection of CRLF in automatically URLDecoded elements

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#638]
Apache and Nginx tend to be really annoying about automatically URL decoding certain things. Not all applications will in fact do this. There is currently a problem where URLDecoding twice is actually a bit of a nasty issue see #590. CRLF is actually quite easy to detect in non-urldecoded entities because valid use of /r or /n must be encoded. This was an issue in #633 and the reason we had to split the rule into a second PL.

**Comment by lifeforms** [comment]
I think the mention of #633 in this issue is a misunderstanding; that issue was not related to encoding, the rule simply blocked (properly url-encoded) `%0d%0a` because of a risk of header injection through XSS.

**Comment by csanders-git** [comment]
well the issues are somewhat related. If Apache didn't automatically decode then we'd never have tolook for %0d%0a but rather raw \r\n. As encoded values in that sense wouldn't trigger header injection unless it was being decoded very early on in the process or via the DOM.

**Comment by lifeforms** [comment]
Do you mean that the rule was supposed to be against actual newline chars? I think those should lead to a new line in the HTTP protocol and not be interpreted as part of the args. But I admit I never looked into this. If that is a concern then maybe `REQUEST_URI_RAW` could be checked. (Something else I've never used ;) )

**Comment by csanders-git** [comment]
I assumed it was for header injection / request smuggling type attacks. If this is the case only a REAL \r\n would work. maybe i'm wrong though.

**Comment by lifeforms** [comment]
Could be right, I have little experience with those protocol related rules...

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
