### ISSUE TITLE
Drupal enduser FP in form_build_id (PL2)

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#641]
Got a Drupal FP in PL2:

```
POST / HTTP/1.1
Accept: text/html, application/xhtml+xml, */*
Referer: xxx
Accept-Language: nl-NL
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip, deflate
Host: xxx
Content-Length: 188
DNT: 1
Connection: Keep-Alive
Cache-Control: no-cache
Cookie: has_js=1

--14086562-C--
region=xxx&keyword=xxx&submit_programmes=xxx&form_build_id=form-F0xE38MsEMebdg_K6ukDU2Eg4VCFQy-vjKC62JCRkaU&form_id=xxx
```

Rule 942450 hit in PL2: `Message: Warning. Pattern match "(?i:(?:\\A|[^\\d])0x[a-f\\d]{3,}[a-f\\d]*)+" at ARGS:form_build_id. [file "/usr/local/etc/apache24/security2/crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "1089"] [id "942450"] [rev "2"] [msg "SQL Hex Encoding Identified"] [data "Matched Data: F0xE38 found within ARGS:form_build_id: form-F0xE38MsEMebdg_K6ukDU2Eg4VCFQy-vjKC62JCRkaU"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "8"] [accuracy "8"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-sqli"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"] [tag "WASCTC/WASC-19"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/CIE1"] [tag "PCI/6.5.2"] [tag "paranoia-level/2"]`

I don't know Drupal well enough, but it seems we might need to exclude this rule for all URIs, although we probably could depend on `&ARGS:form_id` being 1.

**Comment by dune73** [comment]
See PR #641.
