### ISSUE TITLE
Using on an existing log

### ISSUE THREAD

**Issue by adamziaja** [SpiderLabs/owasp-modsecurity-crs#645]
Hi, is possible to using this rules on an existing log? When I have just file access.log and want check with this rules for web attacks in forensics purposes. How can I do this? Is there some tutorial or something?

https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/604#issuecomment-251746238 - because we have now V3 :+1:

**Comment by dune73** [comment]
Apparently, you do not have the request bodies, but only the requestline + 2 headers in the access log.

It is probably easiest to extract the requests and fire them against a local CRS3 installation anew.

There is no tutorial or documentation though. However, with grep and sed and possibly awk, you can construct curl payloads on the fly and pull this off fairly easily. But again, you lack the request bodies.

**Comment by lifeforms** [comment]
A normal access.log only contains the requested URIs, and probably Referrer and User-Agent. It is missing a lot of data used in the blocking decision. For instance, the request body is not logged in an access.log, but also the cookies, Accept header, Host header, etc. (This is why the audit logging function of ModSecurity is very useful even if you don't block anything.)

It's possible to make a little shell script that will request the URIs from your access.log to a new server running CRS. It will probably be able to notice some URL-based attacks, but it will not be very complete...
