### ISSUE TITLE
Buggy advice in RESPONSE-999

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#648]
The file `RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example` has several bugs:
* It gives examples including "chain", which is no longer necessary and does not work.
* It quotes it's own file name wrong several times

**Comment by csanders-git** [comment]
Nice tag, i'll probably make a PR for this later today if you have no objections

**Comment by dune73** [comment]
No objections whatsoever.

**Comment by csanders-git** [comment]
Closed in favor of PR see #649
