### ISSUE TITLE
Consistent support for the "ver" action

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#650]
Many rules have support for the `ver` action, but far from all. Namely the 949 rules are lacking.

We should add consistent support.

**Comment by fzipi** [comment]
@dune73 Do you want to add the same version for all?

In that case, we may want to use a var and just reference it everywhere.

@airween Should be capable of changing everything in no time using the parser :)

**Comment by airween** [comment]
Sure! :)

I assigned this issue for myself, let's discuss about the details.

**Comment by dune73** [comment]
Let's discuss it at the meeting.

**Comment by annawinkler** [comment]
I'd like to help out with this one!

**Comment by fgsch** [comment]
Meeting outcome:  @airween with make sure this issue is solved together with Anna.

**Comment by airween** [comment]
There is a [table about occurrence](https://docs.google.com/spreadsheets/d/1x6tg8RyAELw0h4y1uoMEi3rPiLfrNFpK598kyXLtogs/edit#gid=119269151) of `ver` actions (and with values). The point is that all rule must have a `ver` action? And what would be the correct value now? `OWASP_CRS/3.2.0`?

**Comment by dune73** [comment]
Decision during the CRS project chat on March 2, 2020: @airween will bring some consistency to this.

https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/1683#issuecomment-593584538
