### ISSUE TITLE
Rule 942190 false positive

### ISSUE THREAD

**Issue by tomsommer** [SpiderLabs/owasp-modsecurity-crs#655]
```
Message: Access denied with code 406 (phase 2). Pattern match "(?i:(?:\\s*?(?:exec|execute).*?(?:\\W)xp_cmdshell)|(?:[\"'`]\\s*?!\\s*?[\"'`\\w])|(?:from\\W+information_schema\\W)|(?:(?:(?:current_)?user|database|schema|connection_id)\\s*?\\([^\\)]*?)|(?:[\"'`];?\\s*?(?:select|union|having)\\s*?[^\\s])|(?:\\wiif\\s ..." at ARGS:content. [file "/usr/local/apache2/conf/crs-rules/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "181"] [id "942190"] [rev "2"] [msg "Detects MSSQL code execution and information gathering attempts"] [data "Matched Data: \x22Select A found within ARGS:content: [Best_Wordpress_Gallery id=\x221\x22 gal_title=\x22Select Album\x22]"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "8"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-sqli"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"] [tag "WASCTC/WASC-19"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/CIE1"] [tag "PCI/6.5.2"]
```

**Comment by tomsommer** [comment]
Basically ARGS:content, ARGS:title and ARGS:data[wp_autosave][content] is a recipe for disaster within WordPress

**Comment by lifeforms** [comment]
We aim to cover these false alerts with the WordPress exclusions. Have you enabled the WordPress tweaks in `crs-setup.conf`? This should help! If this doesn't, please send us more full logs (can be anonymized) and we will investigate. Thanks!

**Comment by tomsommer** [comment]
I thought the exclusions were enabled by default, I have enabled them now. Thanks for the hint. Perhaps this is the correct way to fix these false positives, as adjusting the rules may be too much of a challenge.

**Comment by lifeforms** [comment]
There is a small chance that the exclusions might open up security holes in unrelated applications, so we don't enable them by default, but maybe we should. After all usability is important too and we should try not to waste your time. :) Thanks for the input. I'll close this for now, but if you still experience false positives, please comment again.
