### ISSUE TITLE
KNOWN_BUGS: Talk about missing YAJL/JSON support in ModSec binaries

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#659]
This is not a CRS bug, but a problem with the ModSec packaging; notably on Debian. But people will point to CRS, so let's add a remark.

**Comment by franbuehler** [comment]
I will work on this issue this week.

**Comment by csanders-git** [comment]
Sounds good. Sure you are aware but YAJL is optional in modsec 2.x. Weirdly I cannot find any documentation to say that.

**Comment by franbuehler** [comment]
Ok, thanks for your hint. Do you think I should mention it in KNOWN_BUGS?

What about this proposal?

```
Debian up to and including Jessie lacks YAJL/JSON support in ModSecurity, 
which causes the following error in the Apache ErrorLog or SecAuditLog:
'ModSecurity: JSON support was not enabled.'
JSON support was enabled in Debian's package version 2.8.0-4 (Nov 2014).
You can either use backports.debian.org to install the latest ModSecurity release 
or disable rule id 200001.
```

**Comment by csanders-git** [comment]
That looks good, i think it gets to the heart of the issue.

**Comment by csanders-git** [comment]
PR #702 solves this issue and has been merged, closing for consistency. Thanks all!

**Comment by edhgoose** [comment]
I've noticed this same issue occurs with Amazon Linux.  `yum info mod24_security` returns:

```
Available Packages
Name        : mod24_security
Arch        : x86_64
Version     : 2.8.0
Release     : 5.27.amzn1
Size        : 298 k
Repo        : amzn-main/latest
Summary     : Security module for the Apache HTTP Server
URL         : http://www.modsecurity.org/
License     : ASL 2.0
Description : ModSecurity is an open source intrusion detection and prevention engine
            : for web applications. It operates embedded into the web server, acting
            : as a powerful umbrella - shielding web applications from attacks.
```

And we get this error:

```
Message: JSON support was not enabled
Message: Access denied with code 400 (phase 2). Match of "eq 0" against "REQBODY_ERROR" required. [file "/etc/httpd/conf.d/mod_security.conf"] [line "73"] [id "200002"] [msg "Failed to parse request body."] [data ""] [severity "CRITICAL"]
Action: Intercepted (phase 2)
```

I'd be happy to add another comment to the KNOWN_BUGS, would you like me to open a PR as such?

**Comment by csanders-git** [comment]
@edhgoose this is a packaging issue with mod security. The packager has not included yajl. Unfortunately, this is not a crs issue. You can reach out to the mod security team but they will likely let you know that it is at the discretion of the packager. Fortunately, you can still compile modsec from scratch with yajl to get json support. Hope this helps.
