### ISSUE TITLE
Where did the Slowloris rule go?

### ISSUE THREAD

**Issue by theseion** [SpiderLabs/owasp-modsecurity-crs#667]
Hi,

2.9.2 included an experimental rule for Slowloris mitigation (https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/2.2.9/experimental_rules/modsecurity_crs_11_slow_dos_protection.conf). I can't find any similar provisions in 3.0.0. Is there a rational for abandoning that rule?

Also, using the rule from 2.9.2 does not seem to have any effect in 3.0.0 (I don't have much experience with the ModSecurity syntax, so I don't really know what the problem might be). Could someone suggest a solution for Slowloris Mitigation for 3.0.0?

**Comment by csanders-git** [comment]
Hello @theseion - we removed a number of the platform specific rules that were present in the 2x branch. A number of these were written by various people over time and were in various states of functionality depending on changes hence the name experimental. I'd be more than happy to work with you on building and testing these rules so we can include them in a future CRS 3 release. It'd be a fairly straight forward beginner project and i'd be around to work with you on it as well as answer any questions you might have if you're interested. let me know.

**Comment by theseion** [comment]
Thanks. I'll get back to you as soon as I find some spare time.

**Comment by csanders-git** [comment]
it's the biggest struggle :)

**Comment by theseion** [comment]
Hi @csanders-git,

I've tried to adapt the original Slowloris rule for CRS 3 (see below). I do have a couple of questions:
- The rules depend on the 408 Status generated by the `reqtimeout` module. I don't see, however, how one could deactivate the Slowloris rule dynamically (e.g. by setting a variable like paranoia level) and also prevent loading of the `reqtimeout` module. Possibly some combination of environment variable and `setenvif` could achieve that but it would add additional dependencies to the Apache setup. So how would you proceed there? Is there an alternative to using `reqtimeout`? Possibly using an additional rule?
- `expirevar` is set to 60 seconds. As far as I can tell, that value depends on the value chosen for the request timeout, hence it should probably be put into a variable. But that variable may then not be available when setting the request timeout. Again, this is a problem with the module mechanism and reqtimeout.
- The 60 second expiry seems rather arbitrary (2 * 30 seconds?). The documentation on `expirevar` is unclear to me: is the expiration timer reset every time the variable is set via `setvar`? Or only when the value changes? Or is it never reset? I would expect it to be reset every time the variable is set / updated (regardless of a change in the value).
- I have tried to set the correct tags etc. but am not sure at all that they are correct (I basically copied them from other rules). The ID's are still wrong of course.
- Do you have a policy regarding rule tests? Am I expected to write a test for the rule?
- I would have put this rule into the DoS protection file, but that file specifically deals with flooding only. So maybe this needs to go in its own rule file?



```# ------------------------------------------------------------------------
# OWASP ModSecurity Core Rule Set ver.3.0.0
# Copyright (c) 2006-2016 Trustwave and contributors. All rights reserved.
#
# The OWASP ModSecurity Core Rule Set is distributed under
# Apache Software License (ASL) version 2
# Please see the enclosed LICENSE file for full details.
# ------------------------------------------------------------------------

#
# -= Paranoia Level 0 (empty) =- (apply unconditionally)
#
#----------------------------------------------------------


#
# Rule set for detecting Slow HTTP Denial of Service Attacks. 
# 
# http://blog.spiderlabs.com/2010/11/advanced-topic-of-the-week-mitigating-slow-http-dos-attacks.html
#

# 
# Mitigate Slowloris-type slow HTTP attacks
#
SecReadStateLimit 100 

#
# Mitigate Slow HTTP POST attacks
#
# Must have the mod_reqtimeout module installed
# You should adjust the RequestReadTimeout body directive setting to a limit
# that will allow any legitimate slow clients or large file uplaods.
#
<IfModule reqtimeout_module>
	RequestReadTimeout body=30 
</IfModule>

SecRule RESPONSE_STATUS "@streq 408" \
	"phase:logging,\
	id:'981051',\
	ver:'OWASP_CRS/3.0.0',\
	rev:'1',\
	maturity:'1',\
	accuracy:'1',\
	tag:'application-multi',\
	tag:'language-multi',\
	tag:'platform-multi',\
	tag:'attack-dos',\
	severity:'warning',
	t:none,\
	nolog,\
	pass,\
	setvar:ip.slow_dos_counter=+1,\
	expirevar:ip.slow_dos_counter=60"

SecRule IP:SLOW_DOS_COUNTER "@gt 5" \
	"phase:1,\
	id:'981052',\
	ver:'OWASP_CRS/3.0.0',\
	rev:'1',\
	maturity:'1',\
	accuracy:'1',\
	tag:'application-multi',\
	tag:'language-multi',\
	tag:'platform-multi',\
	tag:'attack-dos',\
	severity:CRITICAL,\
	t:none,\
	log,\
	drop,\
	msg:'Client Connection Dropped due to high # of slow DoS alerts'"
```

**Comment by dune73** [comment]
@theseion : Thank you very much for your submission. This is very interesting and very welcome. It touches on various subjects we have talked about before and this gives more food for thought. Please expect to wait a while until this is merged. It is also possible that it will have to be altered to fit the general architecture (to give you an idea: we try to avoid introducing additional counters and depending on reqtimeout makes a lot of sense, but it is also nothing we usually do as we have to think of non-apache platforms too). So please do not let us shy you away, but stay connected so we can sort this out together. I for one like the idea of this rule and your update work.

Expirevar: The expiry time is defined when expirevar is issued. Then, when persistant storage is read, the current timestamp is compared to the expiry time defined for a variable. If that timestamp has passed, the variable is purged. Consequently, setvar does not affect expiry at all. Only expirevar does. 
You can follow the expiry handling in the debug log nicely on higher loglevels:

```bash
[rid#7fabd8016b00][/][5] Rule 19e5508: SecAction "phase:1,id:1000,pass,nolog,initcol:IP=%{REMOTE_ADDR}\""
[rid#7fabd8016b00][/][4] Transformation completed in 1 usec.
[rid#7fabd8016b00][/][4] Executing operator "unconditionalMatch" with param "" against REMOTE_ADDR.
[rid#7fabd8016b00][/][9] Target value: "127.0.0.1"
[rid#7fabd8016b00][/][4] Operator completed in 1 usec.
[rid#7fabd8016b00][/][9] Resolved macro %{remote_addr} to: 127.0.0.1
[rid#7fabd8016b00][/][9] collection_retrieve_ex: collection_retrieve_ex: Retrieving collection (name "ip", filename "/tmp//ip")
[rid#7fabd8016b00][/][9] collection_unpack: Read variable: name "__expire_KEY", value "1484522912".
[rid#7fabd8016b00][/][9] collection_unpack: Read variable: name "KEY", value "127.0.0.1\"".
[rid#7fabd8016b00][/][9] collection_unpack: Read variable: name "TIMEOUT", value "3600".
[rid#7fabd8016b00][/][9] collection_unpack: Read variable: name "__key", value "127.0.0.1\"".
[rid#7fabd8016b00][/][9] collection_unpack: Read variable: name "__name", value "ip".
[rid#7fabd8016b00][/][9] collection_unpack: Read variable: name "CREATE_TIME", value "1484519013".
[rid#7fabd8016b00][/][9] collection_unpack: Read variable: name "UPDATE_COUNTER", value "8".
[rid#7fabd8016b00][/][9] collection_unpack: Read variable: name "LAST_UPDATE_TIME", value "1484519312".
[rid#7fabd8016b00][/][9] collection_unpack: Read variable: name "xxx", value "7".
[rid#7fabd8016b00][/][9] collection_unpack: Read variable: name "__expire_xxx", value "1484519316".
[rid#7fabd8016b00][/][9] collection_retrieve_ex: Removing key "xxx" from collection.
[rid#7fabd8016b00][/][9] collection_retrieve_ex: Removing key "__expire_xxx" from collection.
[rid#7fabd8016b00][/][4] collection_retrieve_ex: Removed expired variable "xxx".
[rid#7fabd8016b00][/][4] collection_retrieve_ex: Retrieved collection (name "ip", key "127.0.0.1\"").
```

**Comment by dune73** [comment]
Two questions for you:
* You raise the counter on status code 408. Are not there additional reasons for 408? Purging a stale connection in keep-alive leads to a 408 for example (but I think ModSecurity is shortcut in this case)?
* Is not there an mod_reqtimeout error message you can access instead of status 408?

**Comment by theseion** [comment]
I simply copied that part from the original rule. The documentation on mod_reqtimeout does not mention any way to react to mod_reqtimeout specifically. AFAICT, it simply sets the response code to 408.

BTW, the most interesting feature of mod_reqtimeout is probably the ability to increase the timeout dynamically when data is being sent at a minimal data rate (currently not used by the rule). I don't know whether it's possible to implement either functionality (timeout / increase timeout w.r.t. data rate) with mod_security alone.

**Comment by dune73** [comment]
mod_reqtimeout is very elegant and I do not think you can implement something equally nice with ModSecurity. But ModSecurity can help blocking returning clients. Still, it will be better to block in front of ModSec on a dedicated network box as it is much faster. But the same is true for the whole bunch of DoS rule in CRS. However, if we bring back this Slowloris rule(s), they should be more foolproof then they used to be. 
Have you set up a test environment for this? Meaning: Can you test The logs and the behaviour with a slowloris / rudy / ... attack in the lab yourself?

**Comment by theseion** [comment]
Not yet. But I was planning to set up a test container an attack that. I'll do that in the next couple of days.

**Comment by dune73** [comment]
Cool. Let me know when you are ready. We can then continue to develop the future rule.

**Comment by theseion** [comment]
I now have a test container on which I can mess around. I've set up the regression tests for the CRS and it seems to work mostly. I do get 130 failures out of the 5582 tests, not sure whether that is an issue with my environment. Should all the tests succeed before I start testing the slowloris rule?

Looking at https://github.com/fastly/ftw/blob/master/docs/YAMLFormat.md I don't think I can write a test that will trigger the slowloris rule as I would need to be able to specify a timeout between stages (I think).

Let me know if there's anything more I should do regarding setup.

**Comment by csanders-git** [comment]
@theseion I work pretty heavily on the FTW project we can consider exactly what is needed (timeouts between stages) and then add it. Should be pretty stragiht forward. @zmallen

**Comment by theseion** [comment]
Nice!

**Comment by ossie-git** [comment]
Was this added to the CRS ruleset?  Also, unless I am mistaken, this just handles slow request headers + slow POST requests, not slow reading of the responses by the client (set the window to 0 or 1). Right?

**Comment by dune73** [comment]
@ossie-git No, this was not merged, it kind of stuck during the Winter and I do not know if @csanders-git did any additional work.

I doubt slow reading can be measured by something within Apache as the transfer is actually done by the kernel and not the server. But I might be mistaken there. However, I have never seen a ModSec rule pulling this off and I do not know how I would go about it myself.

Years ago, I experimented with an additional daemon that monitored access log and netstat status. That way the daemon was pretty much able to tell which IP addresses were doing request / response delay attacks.

**Comment by theseion** [comment]
I got stuck doing other stuff. Yes, this only covers slow requests (using the `reqtimeout` module). I'll probably not have the resources in the near future (i.e. to around the end of 2017) to continue working on this rule but I still plan to finish it eventually.

**Comment by csanders-git** [comment]
Not sure we should merge this into main line as it won't be supported on NGINX.

**Comment by dune73** [comment]
It's a nice rule pair, but given the limited use case, the existence of mod_reqtimeout and the missing support, I do not think we should add it to our rule base.

Thank you for your good work @theseion and the interesting conversation. Unfortunately, it does not really fit.

**Comment by theseion** [comment]
No worries. I haven't gotten around to working on the rule anyway. I'll close this issue.

Thanks for your help!

**Comment by dune73** [comment]
Thank you for your understanding @theseion.
