### ISSUE TITLE
Help to make a rule against mailing script spam

### ISSUE THREAD

**Issue by meatlayer** [SpiderLabs/owasp-modsecurity-crs#670]
Hello. 
There is a certain obfuscated spam script, which initially looks like this: http://pastebin.com/ecBTa7DK 
If you decipher/deobfuscate: http://pastebin.com/CWp7GAvZ 
By this script with a random name doing POST requests with encrypted base64: http://pastebin.com/i3f1KZQS 
If decode base64 signed key: http://pastebin.com/FKMZu7ex
Maybe someone knows which rule it is possible to do to block such POST requests? 
Something like this:
```
SecRule REQUEST_METHOD "@streq POST" "chain,phase:2,t:none,deny,status:403,msg:'Stop out spam',id:9999"
SecRule ARGS_POST:random "@pm @" t:base64Decode
```
Not really suitable because the base64 encrypted.
(sry for my bad english, is google translate)

**Comment by dune73** [comment]
They way I understand you submission @Rendername, is that you learned this scripted uploaded to a site is doing POST request and now you would like to detect that.

Would you like to detect the script being uploaded? Or would you like to stop the POST requests performed by the script.

Do you get any alert by the CRS3 for uploading of the script? I guess not, but maybe yes. What might be worth a try is ssdeep (https://www.trustwave.com/Resources/SpiderLabs-Blog/ModSecurity-Advanced-Topic-of-the-Week--Detecting-Malware-with-Fuzzy-Hashing/)

CRS3 is not yet supporting ssdeep, but we might support it in the future. In the meantime, you can preconfigure it to catch this script yourself.

**Comment by meatlayer** [comment]
I would like stop the POST requests performed by the script. 
But it's not real? Because POST args base64 encrypted.
Then maybe detect the script before uploading and deny this. But how?
Your link i will check, thank you.

**Comment by dune73** [comment]
CRS can not help you stop the outgoing requests.

The script upload check is indeed done via the link I submitted. Closing this now.

**Comment by csanders-git** [comment]
You can use @base64decode can decode that blob so that you can more easily run checks against it... but as @dune73 this would require creation of custom modsecurity rules. If you need help crafting those we can provide assistance but it isn't part of the core rule set :)
