### ISSUE TITLE
932140 (Remote Command Execution: Windows FOR/IF Command Found) FP on SAML data

### ISSUE THREAD

**Issue by jhaar** [SpiderLabs/owasp-modsecurity-crs#671]
Hi there

I'm running SimpleSAMLPhp as a SAML IdP behind mod_security-2.9.1 with the OWASP_CRS/3.0.0 ruleset and 932140 triggers on some SAML transactions

SAML involves large digitally signed PEM encoded blobs flying through via POST and I think the simple matching on 2chars really makes this rule likely to FP

Attached is an alert showing that rule hit some base64 encoded chars "if3q"

[saml-fp.txt](https://github.com/SpiderLabs/owasp-modsecurity-crs/files/647277/saml-fp.txt)

**Comment by csanders-git** [comment]
Hey @jhaar  this is an interesting issue. SAML is typically presented as XML although this doesn't look like that. Would it be possible to get the auditlog result?

**Comment by jhaar** [comment]
here you go


[modsec_audit.txt](https://github.com/SpiderLabs/owasp-modsecurity-crs/files/647872/modsec_audit.txt)

**Comment by lifeforms** [comment]
Wow, that is a crazy false positive. Seems like we should be able to nip this in the bud with the information you gave. Thanks a lot for submitting it! 

Are you okay for now, or would you like an example to exclude this rule for your app?

**Comment by jhaar** [comment]
nah - all good. BTW I've got another one - I've put that in separately - #675

**Comment by dune73** [comment]
Let's keep this open until we have really fixed it.

**Comment by dune73** [comment]
So what do we do with this and with #675? I get the feeling, these issues are part of a bigger group of false positives that involve 1-2 dozens of rules, some of them PL1, that may trigger on (seemingly) random data. 

Seemingly random data exists in the form of Base64 encoded payloads, client-side encryption of request parameters, etc.

I think we need to solve this at least for PL1. Whatever solving really means. With FOR/IF it looks really tough.

**Comment by lifeforms** [comment]
Going to take a look at this next week.

**Comment by lifeforms** [comment]
A fix is in #738 and will be included in CRS 3.0.1 maintenance release. Thanks for submitting the logs!

**Comment by RamananKR** [comment]
Hi ,
need help  about owasp 3.0 rules azure  policy 949110 980130

can you please  explain about advantage and  use-case  of  azure application gateway rule 949110 980130
