### ISSUE TITLE
Javascript evasions

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#672]
There is a research paper looking at multiple WAFs and how they are not covering the ECMAScript 6 / Javascript standard. 

https://www.oneconsult.com/en/web-application-firewall-bypass/

Unfortunately, the paper is in German. Maybe automatic translation works.

I doubt we are any better with regards to ES6. But we might cover most of this when we start to watch out for the typical JSF\*\*k patterns. Outside of JSF\*\*k, there are a few additional tricky cases.

**Comment by dune73** [comment]
First assessment:

```
1:
  alert`Oneconsult`;

  -> Score 13, but only at PL4

2:
  onerror=alert;
  throw `Oneconsult`;

  -> Score 13, but only at PL4

3:
  [][`constructor`][`constructor`]`$${`al`+[open+[]][0][11]+`rt`+[open+[]][0][13]+[`"`][0]+`Oneconsult`+[`"`][0]+[open+[]][0][14]}$```

  -> Score 5 in default Install (PL1), then it explodes

4: 
  SearchTerm=\\\"-`Oneconsult`,//

  -> Score 3 at PL3, PL4 >10

5: 
  SearchTerm=\\\"};%0A+[][`constructor`][`constructor`]`$${`al`%2b[open%2b[]][0][11]%2b`rt`%2b[open%2b[]][0][13]%2b[`"`][0]%2b`Oneconsult`%2b[`"`][0]%2b[open%2b[]][0][14]}$```+%0Aa={//SearchTerm=\\\"};%0A+[][`constructor`][`constructor`]`$${àl`%2b[open%2b[]][0][11]%2b`rt`%2b[open%2b[]][0][13]%2b[`"`][0]%2b`Oneconsult`%2b[`"`][0]%2b[open%2b[]][0][14]}$```+%0Aa={//

  -> Score 5 in default install

6:
  onerror//\
  //\\\//\
  =//\
  //\\\//\
  alert//\
  //\\\//\
  ;throw `Oneconsult`;

  -> Score 3 at PL3, 21 at PL4.

```

**Comment by csanders-git** [comment]
I was thinking of redoing the SQL rules but i'd prefer and this kinda sells it to redo the XSS rules first.

**Comment by lifeforms** [comment]
Javascript is crazy dynamic. I have lots of little undetected payloads lying around too. The metacharacter anomaly rule in high PL saves us from many of them. It would be awesome if we could have broader protection though. Definitely something I would like to spend time on in 2017 :)

**Comment by dune73** [comment]
Did a new review of the payloads above (including new PR #1161 JSFuck rules). I thought this useful since 3.1 brought slightly adjusted rules that used request parameters in a different way for some rules, which resulted in higher scores.

* Payload 1:  5/5/15/28
* Payload 2:  0/0/10/23
* Payload 3:  5/26/47/60
* Payload 4:  0/0/13/26
* Payload 5:  5/23/44/57
* Payload 6:  5/5/23/41

So the relevant remaining payloads are payload 2 and payload 4. 

Do you see any chance we can cover these in PL1 or PL2, or do we agree we won't be able to fix; so we can close the issue. Maybe opening an issue with libinject first.

**Comment by lifeforms** [comment]
I think for payload 2, we could add a blacklist of javascript event handlers: onerror, onload, etc. False positives could be a concern, but I'd be willing to try that out in production for a while to see if that's really a problem. In case of FP, we could create a sibling for the problematic ones at paranoia level 2.

I'm not really sure what we can do against payload 4.

**Comment by dune73** [comment]
On the bright side, I can't seem to have payload 4 execute. Do you have more luck?

Do you want to open an issue for payload 2 (I think we talked about this before) and we close this one here?

**Comment by lifeforms** [comment]
Yes I'm not sure if payload 4 contains anything dangerous by itself.

Want me to do a PR for payload 2? Looks like it could be a quick job.

**Comment by dune73** [comment]
That would be very cool. If it's easy, then please go ahead.

**Comment by dune73** [comment]
We detect Payload 2 with an anomaly score of 5 at PL2 with CRS 3.2. So closing this is kind of OK, I guess.
