### ISSUE TITLE
Command Injection without spaces

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#673]
https://twitter.com/coffeetocode/status/808415850919297026

The following injection is not detected by CRS3 up to PL4.
```
Parameter ls$IFS-l$IFS/
```

If anybody thinks this can be fixed for 3.0.1, then please re-label.

**Comment by csanders-git** [comment]
why not add $IFS to the detection list?

**Comment by dune73** [comment]
There might be additional strings. The tweet received quite a few interesting responses.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
