### ISSUE TITLE
Unable to allow a request method for a specific URL

### ISSUE THREAD

**Issue by craigafinch** [SpiderLabs/owasp-modsecurity-crs#678]
This question pertains to version 2.2.9. I realize that this version is out of date, but I believe this issue is still relevant, because packages for 3.x will probably not be available for RedHat and CentOS for quite a while.

I am attempting to allow a specific request method (DELETE) for a specific URL; I do _not_ want to enable this method site-wide. As a test, I confirmed that I can allow DELETE requests site-wide with the action ```tx.allowed_methods=GET HEAD POST OPTIONS``` in file ```modsecurity_crs_10_config.conf```. I then reverted that change, and attempted to add rules to ```/etc/httpd/conf.d/mod_security.conf``` to enable DELETE for a specific sub-domain:

```
    SecRule SERVER_NAME "^subsubdomain\.(subdomain\.)*domain\.com$" \
    "id:'200018',phase:1,t:none, \
    setvar:'tx.allowed_methods=GET HEAD POST OPTIONS DELETE', \
    pass, \
    msg:'Request %{REQUEST_FILENAME} allowed methods: %{tx.allowed_methods}'"

    SecRule SERVER_NAME "^subsubdomain\.(subdomain\.)*domain\.com$" \
    "id:'200019',phase:1,t:none,pass,ctl:ruleRemoveById=960032 \
    msg:'Disabled rule 960032 for %{SERVER_NAME}%{REQUEST_FILENAME}'"
```

These rules do not work, because they are not triggered by DELETE requests. It seems that DELETE requests are being blocked before these rules are even evaluated. I know that the pattern-matching in these rules is working, because the rules are triggered by other request methods.

The block message is:
```
--ab9b5070-H--
Message: Access denied with code 403 (phase 1). Match of "within %{tx.allowed_methods}" against "REQUEST_METHOD" required. [file "/etc/h
ttpd/modsecurity.d/activated_rules/modsecurity_crs_30_http_policy.conf"] [line "31"] [id "960032"] [rev "2"] [msg "Method is not allowed
 by policy"] [data "DELETE"] [severity "CRITICAL"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "9"] [tag "OWASP_CRS/POLICY/METHOD_N
OT_ALLOWED"] [tag "WASCTC/WASC-15"] [tag "OWASP_TOP_10/A6"] [tag "OWASP_AppSensor/RE1"] [tag "PCI/12.1"]
Action: Intercepted (phase 1)
Stopwatch: 1485231082376644 821 (- - -)
Stopwatch2: 1485231082376644 821; combined=250, p1=220, p2=0, p3=0, p4=0, p5=30, sr=72, sw=0, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.7.3 (http://www.modsecurity.org/); OWASP_CRS/2.2.6.
Server: Apache
Engine-Mode: "ENABLED"

--ab9b5070-Z--
```
Is it possible to allow a request method for a specific URL? If so, how?

**Comment by dune73** [comment]
Thanks for reporting @craigafinch.

To me, this sounds as if 960032 would be evaluated _before_ your rule 200018/19 at runtime. This may have to do with the order of your include files. If unsure, raise the debug log level to 5 or even 9 and do a single request. Then check the order of rule execution in the said log.

I am going to close this for now. If you find that your order of rules is correct and CRS2 is mistaken, then please reopen this issue and attach your debug log.
