### ISSUE TITLE
Include known Tor Exit node IPs in IP reputation filter

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#681]
Twitter user securityfu brings the following proposal:

```bash
By the way, when going over the CRS, I was surprised that the IP reputation section didn't cover Tor as Tor 
would be a natural choice (but slow) for someone hiding their tracks. It's quite simple to get Tor exit nodes 
(as these are published in a file). I could cook up a quick Python script to download the file, extract the IPs 
and add a rule to give them an anomaly score out of the box (but not block) if you would be interested in 
adding it.
```

**Comment by csanders-git** [comment]
Dune do you think we should add this? it's pretty simple but a pain to keep updated. Also along this line should we do a L2 rule that bans AWS etc?

**Comment by lifeforms** [comment]
I'm not sure how often Tor exit nodes are changing. If we could get them from a file, then it could be updated by the update script. But an alternative might be to use a real-time blacklist with the `@rbl` operator. Tor seems to have an [experimental RBL](https://www.torproject.org/projects/tordnsel.html.en), but there are also [third parties](https://www.dan.me.uk/dnsbl) running one.

**Comment by dune73** [comment]
RBL is fun, but it's harder to setup (FW rules, availability issues, what to do if you do not receive a reponse). So I personally opt to run with a local file, ideally updated via script, as @lifeforms point out.

But for me, this is only an idea for CRS3.1 so far. Together with dozens of other potential features.

**Comment by spartantri** [comment]
@lifeforms, @dune73, there is the 910110 for checking the ip against `ip_blacklist.data` which doesn't exists so we can repurpose it to be generic and create an empty file so people can add whatever they want, you may include a link to [tor-exit-addresses](https://check.torproject.org/exit-addresses) if you want, but having a blacklist of ip is not under the CRS scope, those things move a lot, so having a 7K+ ip list that changes so aften is not practical, plus there are plenty of different places to get good feeds, I would say better register to [critical stack intel](https://intel.criticalstack.com/) and get the feeds you like for free and load them into the `ip_blacklist.data` file.

**Comment by dune73** [comment]
Yes, I share your impression. It's probably out of scope.

On the other hand, people do not care about scope when they look at our project. They want the complete WAF from one place and not puzzle it together from a variety of projects. But maybe that's the role of real vendors to make CRS into a boxed product. Hard to tell.

If we could incorporate this feature with relative ease, disable it by default and provide an easy script to download the list and enable it, then we would add value at a small cost for the project. What I would rather avoid is a half-baked feature that makes people believe CRS is of crappy quality.
