### ISSUE TITLE
Errors on new install 

### ISSUE THREAD

**Issue by mgaulton** [SpiderLabs/owasp-modsecurity-crs#683]
I just rebuilt a Opensuse 42.2 LEAP using the RPMs in the repos and i can't get it started due to numerous errors that seem to be something is not handling pattern fragments that aren't complete statements. This is a sampling.

Any suggestiosn?

Feb 02 11:28:02 server6 start_apache2[26690]: httpd-prefork: Syntax error on line 177 of /etc/apache2/httpd.conf: Syntax error on line 103 of /etc/apache2/default-server.conf: Syntax error on line 6 of /etc/apache2/conf.d/owasp-modsecurity-crs.conf: Syntax error on line 301 of /etc/apache2/mod_security2.d/modsecurity_40_generic_attacks.data: /etc/apache2/mod_security2.d/modsecurity_40_generic_attacks.data:338: <input> was not closed.\n/etc/apache2/mod_security2.d/modsecurity_40_generic_attacks.data:301: <![cdata[> was not closed.

<![cdata[
<input

Feb 02 11:29:14 server6 start_apache2[29727]: httpd-prefork: Syntax error on line 177 of /etc/apache2/httpd.conf: Syntax error on line 103 of /etc/apache2/default-server.conf: Syntax error on line 6 of /etc/apache2/conf.d/owasp-modsecurity-crs.conf: Syntax error on line 1 of /etc/apache2/mod_security2.d/modsecurity_50_outbound.data: /etc/apache2/mod_security2.d/modsecurity_50_outbound.data:81: <jsp:> was not closed.\n/etc/apache2/mod_security2.d/modsecurity_50_outbound.data:15: <b>Version> was not closed.\n/etc/apache2/mod_security2.d/modsecurity_50_outbound.data:3: <title>Index> was not closed.\n/etc/apache2/mod_security2.d/modsecurity_50_outbound.data:1: <TITLE>Index> was not closed.

<jsp:

Feb 02 11:30:56 server6 start_apache2[2117]: httpd-prefork: Syntax error on line 177 of /etc/apache2/httpd.conf: Syntax error on line 103 of /etc/apache2/default-server.conf: Syntax error on line 6 of /etc/apache2/conf.d/owasp-modsecurity-crs.conf: Syntax error on line 1 of /etc/apache2/mod_security2.d/modsecurity_50_outbound.data: /etc/apache2/mod_security2.d/modsecurity_50_outbound.data:81: <jsp:> was not closed.\n/etc/apache2/mod_security2.d/modsecurity_50_outbound.data:15: <b>Version> was not closed.\n/etc/apache2/mod_security2.d/modsecurity_50_outbound.data:3: <title>Index> was not closed.\n/etc/apache2/mod_security2.d/modsecurity_50_outbound.data:1: <TITLE>Index> was not closed.

<b>Version Information:</b> does not match with a table name or alias name used in the query
<title>Index ofMicrosoft VBScript runtime (0x8

**Comment by csanders-git** [comment]
It looks like you have a < cdata > tag in there possibly from where you downloaded it. In any event these are the old rules (very old from the looks of it) I reccomend downloading the 3.0 ruleset and trying again :)

**Comment by mgaulton** [comment]
Thanks. I just used the repo set. I'll update :)
