### ISSUE TITLE
My rule writen by myself doesn't work,who can help me?

### ISSUE THREAD

**Issue by prince-java** [SpiderLabs/owasp-modsecurity-crs#688]
I want to intercept all the post requests which have the param of "insLockfile",such as:

URL:http://www.abc.com/index.php
Post Date:a=1&insLockfile=b

This request has the param "insLockfile",so I wrote this rule to intercept it:

SecRule REQUEST_BODY|ARGS_POST_NAMES|ARGS_POST "@contains insLockfile" "phase:1,deny,log,id:42"

But is doesn't work,who could tell me which part of this is wrong?

**Comment by dune73** [comment]
POST arguments are only available in phase:2. 

There are a couple of tutorials at https://www.netnea.com that address these basic tasks. You may want to take a look.
