### ISSUE TITLE
Test environment ?

### ISSUE THREAD

**Issue by vishaalgc** [SpiderLabs/owasp-modsecurity-crs#690]
Hi,

  Is there any official test suite where we can test each and every rule of crs if its working fine in my setup with modsecurtiy firewall ? For example, Like a script where i can give an exception to rule id 900001 and then send malicious request to my web application record it in IIS and further remove the exception and re send the request and test if the modsecurity is blocking it. And so for all the rule ids ? I believe its a good way to test all rule ids and my modsecurity setup. So can anyone help me how should i proceed ?

**Comment by csanders-git** [comment]
Yes, we are in the process of really using it in broader adoption however they can be found submoduled in the modsecurity-crs repo under utls. The quick link is available here: https://github.com/SpiderLabs/OWASP-CRS-regressions/tree/947a5ff5d17bed436fc42c804236300066f084ee
