### ISSUE TITLE
Add Gitter Support?

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#696]
It seems like most orgs are moving to use gitter over straight IRC because of the git button? Thoughts on deploying this for us? @dune73

**Comment by dune73** [comment]
Hearing this for the first time. If most orgs are making the shift, I live behind the moon, which is of course possible. :)
I do not mind giving it a shot. We meet in 3 hours, don't we?

**Comment by csanders-git** [comment]
yeah, are you suggesting we use gitter for that or how are we meeting?

**Comment by dune73** [comment]
You choose. I'd prefer to stick to irc for tonight. And @lifeforms is not yet on board.

**Comment by csanders-git** [comment]
I think i'd prefer IRC as well for now :).
