### ISSUE TITLE
Fight open redirects (or more general: user-input showing up in response headers)

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#699]
One of the first findings of the ZHAW research project is an open redirect undetected at PL4. So you have a request parameter and it pops up 1:1 in the `Location` header of the response.

Could there be a high PL rule that loops over all parameter and checks them against the `Location` header, or ideally against all response headers?

**Comment by csanders-git** [comment]
hmm interesting. Seems expensive but at a high level reasonable.

**Comment by dune73** [comment]
Exactly my thought when my partner shared the idea with me.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
