### ISSUE TITLE
a regex bug in XXX-ATTACK- SQL.conf in line 934

### ISSUE THREAD

**Issue by whuben** [SpiderLabs/owasp-modsecurity-crs#700]
the regex is intended to match the keyword "sp_xxx"(e.g.:sp_replwritetovarbin), but mistakes make it match the wrong keyword in the mode of "sp_sp_xxx", the part of the related regex is copied bellow:
`(?:s(?:elect\b(?:.{1,100}?\b(?:(?:length|count|top)\b.{1,100}?\bfrom|from\b.{1,100}?\bwhere)|.*?\b(?:d(?:ump\b.*?\bfrom|ata_type)|(?:to_(?:numbe|cha)|inst)r))|p_(?:sqlexec|sp_replwritetovarbin|sp_help|addextendedproc|is_srvrolemember|prepare|sp_password|execute(?:sql)?|makewebtask|oacreate)`

**Comment by dune73** [comment]
Thank you for reporting, @whuben.

I assume we are talking of rule 942410; PL2. I am not as familiar with this rule and unfortunately I do not totally understand the mistake in question. Could you please elaborate?

**Comment by whuben** [comment]
yes, it's the rule 942410. Intentionally, the regular expression in the rule wants to match some stored procedures of Microsoft SQL Server, such as "sp_replwritetovarbin, sp_help, sp_password", however, there is a mistake in the regular expression which makes it failed to match the stored procedures above, but match the wrong words such as "sp_sp_replwritetovarbin, sp_sp_help, sp_sp_password". So, u can just  delete the prefix "sp_" in the part of the regular expression `(?:s(?:elect\b(?:.{1,100}?\b(?:(?:length|count|top)\b.{1,100}?\bfrom|from\b.{1,100}?\bwhere)|.*?\b(?:d(?:ump\b.*?\bfrom|ata_type)|(?:to_(?:numbe|cha)|inst)r))|p_(?:sqlexec|sp_replwritetovarbin|sp_help|addextendedproc|is_srvrolemember|prepare|sp_password|execute(?:sql)?|makewebtask|oacreate)`  @dune73

**Comment by dune73** [comment]
Thank you for your clarification. Makes sense now.

**Comment by csanders-git** [comment]
@whuben do you have some examples using the sp both positive and negative so that I can add them to our unit test. I think it'll be something like
Good: EXEC sp_password NULL, 'yourpassword', 'sa'
Bad: EXEC sp_sp_password NULL, 'yourpassword', 'sa'

**Comment by whuben** [comment]
@csanders-git  sorry, I  don't have any test case for this bug. Just found this bug by reviewing the regex expressions.  But, I have tested the regex expression it's like this indeed.

**Comment by csanders-git** [comment]
Alright, i'll work on some test cases, good eye. Thank you, great job :)
The rule in question is: 942410 -- it's in paranoia level 2.

The regex is shall we say... dense. Anyway the issue is in the second half of the regex (slightly modified to be valid)

``` 
\W*?\(|\b(?:(?:s(?:elect\b(?:.{1,100}?\b(?:(?:length|count|top)\b.{1,100}?\bfrom|from\b.{1,100}?\bwhere)|.*?\b(?:d(?:ump\b.*?\bfrom|ata_type)|(?:to_(?:numbe|cha)|inst)r))|p_(?:sqlexec|sp_replwritetovarbin|sp_help|addextendedproc|is_srvrolemember|prepare|sp_password|execute(?:sql)?|makewebtask|oacreate)|ql_(?:longvarchar|variant))|xp_(?:reg(?:re(?:movemultistring|ad)|delete(?:value|key)|enum(?:value|key)s|addmultistring|write)|terminate|xp_servicecontrol|xp_ntsec_enumdomains|xp_terminate_process|e(?:xecresultset|numdsn)|availablemedia|loginconfig|cmdshell|filelist|dirtree|makecab|ntsec)|u(?:nion\b.{1,100}?\bselect|tl_(?:file|http))|d(?:b(?:a_users|ms_java)|elete\b\W*?\bfrom)|group\b.*?\bby\b.{1,100}?\bhaving|open(?:rowset|owa_util|query)|load\b\W*?\bdata\b.*?\binfile|(?:n?varcha|tbcreato)r|autonomous_transaction)\b|i(?:n(?:to\b\W*?
```

Notice explicitly as was mentioned above.
```
|p_(?:sqlexec|sp_replwritetovarbin|sp_help|addextendedproc|is_srvrolemember|prepare|sp_password|execute(?:sql)?|makewebtask|oacreate)| 
```
It does look like we can simply remove the 'sp_' prefix from affected elements (sp_replwritetovarbin,sp_help,sp_password)

**Comment by whuben** [comment]
thanks,@csanders-git , and the same bug in `xp_servicecontrol|xp_ntsec_enumdomains|xp_terminate_process`, also in rule 942410.

**Comment by dune73** [comment]
Attempted a PR in #707. Please check.
