### ISSUE TITLE
AirBnB bypass example

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#701]
https://buer.haus/2017/03/08/airbnb-when-bypassing-json-encoding-xss-filter-waf-csp-and-auditor-turns-into-eight-vulnerabilities/

Interesting bypass but won't bypass ModSecurity with CRS 3 on default level 1
920270 - Invalid character in request (null character)
941100 - XSS Attack Detected via libinjection
941120 - XSS Filter - Category 2: Event Handler Vector
941160 - NoScript XSS InjectionChecker: HTML Injection

You might be interested @dune73

**Comment by dune73** [comment]
It's a very interesting example and a strong attacker. ModSecurity might be stronger than the WAF in use at AirBnB, but then the attacker might try different bypasses. So I think in the end, we can only be the 1st line of defense. Without additional defenses, the attacker might easily succeed.
