### ISSUE TITLE
Create rule to forbid content-type application/octet-stream at PL2 or PL3 

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#709]
This takes up issue #657 which was partially solved for 3.0, but not for 3.1, where we want to create an additional rule.

Here is the original resolution from #657:
- Octet-Stream should be OK for PL1, but not for PL2 and higher.
- We want to stick to a single variable defining the tx.allowed_request_content_type allowed mime-types. This rules out defining multiple variables for various PLs and it also rules out rewriting the variable via ModSec in higher PLs.
- The solution is thus to include octet-stream in the default value. Then there is a new rule at PL2 (PL3?) that triggers an alert on Content-Type: application/octet-stream.
- A comment near the definition of tx.allowed_request_content_type indicates that octet-stream is included, but that there is a separate rule prohibiting it at higher PLs.
- There also has to be an commented out example showing how to circumvent the alert.

**Comment by foi** [comment]
Hi! Anybody solved this issue?

**Comment by dune73** [comment]
Partially, but not as thorough as the issues wishes for. See Link to merged PR.
