### ISSUE TITLE
Can't validate ARG in chain rule

### ISSUE THREAD

**Issue by divitoDBA** [SpiderLabs/owasp-modsecurity-crs#711]
I'm trying to evaluate and block GET/POST requests that don't have a given ARG for a certain URIs.

The following rule doesn't validate the "!@eq 1" line 
(REQUEST_URI and REQUEST_HEADERS work as expected when tested individually)

SecRule REQUEST_URI "(?i:(jwtpoc))" "phase:1,id:999955,block,log,deny,status:508,msg:'IP: %{REMOTE_ADDR} GET control panel URI',chain"
  SecRule  &ARGS:cualquiera "!@eq 1" "chain"
  SecRule &REQUEST_HEADERS:Referer "@eq 0"

I can validate both "@eq1" and "!@eq1" if I write a SecRule like the following one:
SecRule &ARGS:cualquiera "@eq 1" "id:999957,phase:2,pass,log,capture,msg:'param cualquiera found: %{MATCHED_VAR}'"

How can rule id 999955 achieve this goal?

Thanks!

**Comment by dune73** [comment]
Your rule 999957 works as advertised for me. You should test it again.

I am closing this as the issue is not related to the Core Rule Set project.

**Comment by divitoDBA** [comment]
But it doesn't work. Where do I go for help?

**Comment by csanders-git** [comment]
@divitoDBA I too was able to get your rule to work, interesting. we can in a limited fashion continue to help you but this is an underlying ModSecurity question. Perhaps the quickest route though would be to send out the question to the modsecurity-users mailing list.

In terms of general trouble shooting, have you tried triggering these rules separately to make sure the functionality is working as you expected it to?

**Comment by divitoDBA** [comment]
Yes, I can get the expected results if I write the rule this way: 

```
SecRule REQUEST_URI "(?i:(jwtpoc))" "phase:1,id:999955,block,log,deny,status:508,msg:'IP: %{REMOTE_ADDR} GET control panel URI',chain"
SecRule &ARGS:cualquiera "!@eq 1" 
```

Or this way: 

```
SecRule REQUEST_URI "(?i:(jwtpoc))" "phase:1,id:999955,block,log,deny,status:508,msg:'IP: %{REMOTE_ADDR} GET control panel URI',chain"
SecRule &REQUEST_HEADERS:Referer "@eq 0"
```

But, when the original rule is online the **SecRule &ARGS:cualquiera "!@eq 1"** validation is not being considered.  That's why I opened an issue as it's seems odd to me.

Thanks in advanced
