### ISSUE TITLE
Minor Typo: intiger = integer

### ISSUE THREAD

**Issue by bossloper** [SpiderLabs/owasp-modsecurity-crs#712]
intiger should be integer:

https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/34112fed0759daf4a2af3a12682c32d92203686a/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf#L192

**Comment by csanders-git** [comment]
closed in favor of PR #713
Thanks!
