### ISSUE TITLE
Missing transformation?

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#719]
@csjperon brought this issue up... it seems like it might be missing a needed transform

```SecRule REQUEST_URI|REQUEST_BODY "\%u[fF]{2}[0-9a-fA-F]{2}" \
  "msg:'Unicode Full/Half Width Abuse Attack Attempt',\
   id:920260,\
   severity:'WARNING',\
   rev:'2',\
   ver:'OWASP_CRS/3.0.0',\
   maturity:'6',\
   accuracy:'8',\
   phase:request,\
   t:none,\
   tag:'application-multi',\
   tag:'language-multi',\
   tag:'platform-iis',\
   tag:'platform-windows',\
   tag:'attack-protocol',\
   block,\
   setvar:'tx.msg=%{rule.msg}',\
   setvar:tx.anomaly_score=+%{tx.warning_anomaly_score},\
   setvar:tx.%{rule.id}-OWASP_CRS/PROTOCOL_VIOLATION/EVASION-%{matched_var_name}=%{matched_var}"

```
utftounicode outputs %uXXXX encoding - do we want to use utftounicode transformation here?

I think in fact this is a major oversight? Thoughts @dune73 @zimmerle

**Comment by dune73** [comment]
Yes, this seems to be an omission. 

Did you guys check what `t:utf8tounicode` does to unicode strings?

E.g, what is the result if `t:utf8tounicode` is applied to `%uXXXX`. Do we run the risk of obfuscating attacking payloads?

**Comment by fgsch** [comment]
It should pass the string as-is since it's valid ascii.

**Comment by dune73** [comment]
True. I tested this and can confirm. UTF8 with `%uXXXX` is not being affected by `utf8tounicode`.

**Comment by dune73** [comment]
Assigning this to @csanders-git as per last night's chat session.

**Comment by csanders-git** [comment]
So I did some testing, and some digging here. This rule emerges from a problem that ModSecurity was not able to map full or half width chars (https://www.trustwave.com/Resources/SpiderLabs-Blog/ModSecurity-Rule-for-Full-width/Half-width-Unicode-Evasion-Detection/). It looks as if this was here to explicitly prevent %uxxxx **as a literal string** from being interpreted by IIS before ModSecurity had unicode.mapping. It appears unicode mapping knows how to deal with such chars with the use of urldecodeuni. 

Apache isn't a very useful test platform here as it will automagically URL encode using the Hex UTF-8 bytes representation. So if i pass HALFWIDTH KATAKANA LETTER A - 0xFF71 (http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=FF71&mode=hex)  ... 

``` 
http://localhost/?cmd=ｱ ModSecurity will see  /?cmd=%EF%BD%B1 
```

I haven't tested with IIS which supposedly is the source of this issue. I'm not sure if we want to continue to block against this, doesn't seem to hurt anything since it doesn't seem to be a major source of false positives currently.

Some more reading:
https://www.owasp.org/images/7/75/OWASPIL2010-PracticalModSe-JoshAmishavZlatin.pdf

**Comment by dune73** [comment]
Are you suggesting you would want to remove the rule as it is probably no longer a vulnerability that is affecting a lot of our users?

**Comment by csanders-git** [comment]
this seems to be the case, testing with IIS now.

**Comment by dune73** [comment]
You got access to an IIS? Cool.

**Comment by csanders-git** [comment]
Looks like IIS still supports this type of encoding (IIS 8.0). At least at this point it seems as if we may want to keep that rule as it stands without the transformation.

![image](https://cloud.githubusercontent.com/assets/4632287/25449322/6cfa13ca-2a89-11e7-9643-4331f55d3a2d.png)

**Comment by dune73** [comment]
So there is still some stability in this world, after all.

**Comment by csanders-git** [comment]
Yup, so it seems... currently, with this information in mind, and the lack of FP we have received for this i'd recommend keeping this rule, as is.

**Comment by dune73** [comment]
I second that. But I suggest doing a PR to extend the documentation for the rule with the results of the research / thinking you did.

**Comment by csanders-git** [comment]
@dune73 i'm on it.

**Comment by dune73** [comment]
Good plan.
