### ISSUE TITLE
missing master.zip

### ISSUE THREAD

**Issue by maravento** [SpiderLabs/owasp-modsecurity-crs#722]
OWASP setup for Ubuntu 16.04
before:
	wget https://github.com/SpiderLabs/owasp-modsecurity-crs/archive/master.zip
	unzip master.zip
	sudo cp -fr owasp-modsecurity-crs-master/* /etc/modsecurity/
	sudo mv /etc/modsecurity/modsecurity_crs_10_setup.conf.example /etc/modsecurity/modsecurity_crs_10_setup.conf
	sudo ls /etc/modsecurity/base_rules | xargs -I {} sudo ln -s /etc/modsecurity/base_rules/{} /etc/modsecurity/activated_rules/{}
	sudo ls /etc/modsecurity/optional_rules | xargs -I {} sudo ln -s /etc/modsecurity/optional_rules/{} /etc/modsecurity/activated_rules/{}

Now: ????? (please fix it. Thanks)
	sudo git clone https://github.com/SpiderLabs/owasp-modsecurity-crs.git /usr/share/modsecurity-crs
	sudo cp /usr/share/modsecurity-crs/crs-setup.conf.example /usr/share/modsecurity-crs/crs-setup.conf
	sudo mv /usr/share/modsecurity-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example /usr/share/modsecurity-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
	sudo mv /usr/share/modsecurity-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example /usr/share/modsecurity-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf

**Comment by dune73** [comment]
Thank you for reporting.

I do not understand your problem. Where did you find the outdated information? Where do we have to change something. Please be explicit.

**Comment by maravento** [comment]
The first information is obsolete. So I ask for the second, which is in the INSTALL file.
PD: You change the installation method very often and that does not provide stability

**Comment by dune73** [comment]
Sorry for changing the install procedure. It was necessary for this major release. We hope to stick to this one now.
