### ISSUE TITLE
Add support for IP in integer form detection for 931100

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#730]
http://2130706433 would currently not be caught by 931100

**Comment by dune73** [comment]
Holy shit!? That's valid? I did not know this notation existed. What's the official name of this and does it work for IPv6 too?

**Comment by csanders-git** [comment]
very much valid, not sure what it's offical name is -- can't seem to find it anywhere but it is a pretty useful trick to obfuscate URLs

**Comment by dune73** [comment]
I'm scared.

**Comment by csanders-git** [comment]
Looks like hex http://0x1F0D4724  and octal also work.. http://0037.0015.0107.0044

**Comment by emphazer** [comment]
ASCII is also possible

The possibilities are listed here
https://www3.trustwave.com/support/kb/article.aspx?id=10537

This one is good
ht%74p://0%787F0%300001/

**Comment by fgsch** [comment]
Would this be a transformation to normalise all entries to an ip address or expand the regular expression? I can work on it.

**Comment by csanders-git** [comment]
A transformation is an interesting idea but wouldn't really work here... I think we'd have to expand the regex.

**Comment by fgsch** [comment]
The problem with the regex is matching e.g. 2130706433, otherwise it's pretty simple:

`+SecRule ARGS "^(?i)(?:ht|f)tps?:\/\/(\d+\.\d+\.\d+\.\d+|0x[a-z0-9]+)" \`

If you have any ideas I'm happy to look into them.

**Comment by spartantri** [comment]
This is a pretty complex item to address, it may be easier to catch `(?i)(?:ht|f)tps?` as hostnames/fqdn can also be used for the same purposes, it will also prone to false positives and negatives.

```
$ ping 0177.1
$ ping 134744072
$ ping 0x8080808
$ ping 010.0x0000008.00000010.8
$ ping 8.0x0000000000000080808
$ ping -c 1 `perl -e 'print 2.130706433*(10**9)'`  
$ ping -c 1 174'2'78'682'
$ ping -c 1 174.278682
$ ping -c 1 174.27.8682
$ ping -c 1 "17""42786""82"
$ ping -c 1 17"4278682"
$ ping -c 1 0xA."99".18'45'8
$ ping -c 1 10.6506522
$ ping -c 1 10.\6\5\0\6\5\2\2
$ ping -c 1 10.0"x"6348'1'A
$ ping -c 1 `\e\c\h\o \1\0\.\9\9\.\7\2\.\2\6`
$ /???/p?ng -c 1  `\e\c\h\o \1\0\.\9\9\.\7\2\.\2\6`
$ ping -c 1 `echo $((2#1010011000110100100000011010))`
$ /???/p?ng -c 1 `/???/ec?o $((2#1010011000110100100000011010))`
$ ping $((2#1010011000110100100000011010))

```
