### ISSUE TITLE
cPanel whm-server-status FP report

### ISSUE THREAD

**Issue by YbyMMbPh** [SpiderLabs/owasp-modsecurity-crs#731]
Centos 6.9
cPanel 64.0.12
Modsecurity Version 2.9.0
CRS v3.0/master Default install, all config files included.

1). Cpanel's WHM auto generates requests to /whm-server-status from 127.0.0.1 (triggers rule 920280, non-blocking, log only) Once every 5 minutes.

2). Also accessing WHM=>Server Status=>Apache Status page generates request to /whm-server-status from 127.0.0.1 (triggers rule 920280, non-blocking, log only)

3). WHM Plugin Munin-node auto generates requests to /whm-server-status?auto from 127.0.0.1 (triggers rule 920350, non-blocking, log only) Three times every 5 minutes.

**Sample Log for variation 1)**
--daa60036-A--
[13/Apr/2017:21:20:01 +1000] WO9e4SdWdpPd96@Uh1H1uAAAAIs 127.0.0.1 32938 127.0.0.1 80
--daa60036-B--
GET /whm-server-status HTTP/1.0

--daa60036-F--
HTTP/1.1 200 OK
Connection: close
Content-Type: text/html; charset=ISO-8859-1

--daa60036-E--

--daa60036-H--
Message: Warning. Operator EQ matched 0 at REQUEST_HEADERS. [file "/etc/apache2/conf.d/modsec_vendor_configs/myowaspcrs3/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "595"] [id "920280"] [rev "2"] [msg "Request Missing a Host Header"] [severity "WARNING"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_HOST"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"]
Apache-Handler: server-status
Stopwatch: 1492082401921587 5867 (- - -)
Stopwatch2: 1492082401921587 5867; combined=2972, p1=533, p2=1922, p3=67, p4=205, p5=159, sr=124, sw=86, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/); OWASP_CRS/3.0.0.
Server: Apache
Engine-Mode: "ENABLED"

--daa60036-Z--

**Sample Log for variation 2).**
--b54ce578-A--
[14/Apr/2017:09:54:30 +1000] WPAPtkNV6ls4CvTJ-J1rTAAAAIc 127.0.0.1 44968 127.0.0.1 80
--b54ce578-B--
GET /whm-server-status/ HTTP/1.0

--b54ce578-F--
HTTP/1.1 200 OK
Connection: close
Content-Type: text/html; charset=ISO-8859-1

--b54ce578-E--

--b54ce578-H--
Message: Warning. Pattern match "^/whm-server-status(\\/?)$" at REQUEST_FILENAME. [file "/etc/apache2/conf.d/modsec/modsec2.user.conf"] [line "10"] [id "8888777"] [msg "Matched 127.0.0.1 and matched whm-server-status with or without trailing slash. Disabling rules 920280 and 920350. filename=/whm-server-status/"]
Apache-Handler: server-status
Stopwatch: 1492127670194792 5467 (- - -)
Stopwatch2: 1492127670194792 5467; combined=1466, p1=601, p2=551, p3=58, p4=179, p5=75, sr=66, sw=2, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/); OWASP_CRS/3.0.0.
Server: Apache
Engine-Mode: "ENABLED"

--b54ce578-Z--

**Sample Log for variation 3).**
--9636be5f-A--
[13/Apr/2017:21:20:03 +1000] WO9e46ZgowLAX3XgFiBL0wAAAM0 127.0.0.1 32948 127.0.0.1 80
--9636be5f-B--
GET /whm-server-status?auto HTTP/1.1
TE: deflate,gzip;q=0.3
Connection: TE, close
Host: 127.0.0.1:80
User-Agent: munin/2.0.25 (libwww-perl/6.15)

--9636be5f-F--
HTTP/1.1 200 OK
Content-Length: 1256
Connection: close
Content-Type: text/plain; charset=ISO-8859-1

--9636be5f-E--

--9636be5f-H--
Message: Warning. Pattern match "^[\\d.:]+$" at REQUEST_HEADERS:Host. [file "/etc/apache2/conf.d/modsec_vendor_configs/myowaspcrs3/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "793"] [id "920350"] [rev "2"] [msg "Host header is a numeric IP address."] [data "127.0.0.1:80"] [severity "WARNING"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/IP_HOST"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"]
Apache-Handler: server-status
Stopwatch: 1492082403357429 3781 (- - -)
Stopwatch2: 1492082403357429 3781; combined=2207, p1=628, p2=1198, p3=53, p4=109, p5=147, sr=131, sw=72, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/); OWASP_CRS/3.0.0.
Server: Apache
Engine-Mode: "ENABLED"

--9636be5f-Z--

The following rule disables both rules for all variations of this request type.

```
# Rule to allow cPanel whm-server-status requests without log entry.
SecRule REMOTE_ADDR "@ipMatch 127.0.0.1" \
  "msg:'Matched 127.0.0.1 and matched whm-server-status with or without trailing slash. Disabling rules 920280 and 920350',\
  phase:1,\
  id:8888777,\
  t:none,\
  pass,\
  nolog,\
  chain"
    SecRule REQUEST_FILENAME "@rx ^/whm-server-status\/?$" \
      "t:none,\
      ctl:ruleRemoveById=920280,\
      ctl:ruleRemoveById=920350"
```

These false positives have a low impact (logged, non-blocking) to a large number of users (all cPanel admins).
With this exclusion rule in place modsec hit logs in cPanel become much more usable and useful for finding new false positives and attack patterns.
Not sure if it warrants a REQUEST-903.9003-CPANEL-EXCLUSION-RULES.conf 
file just for one rule. I have not yet been able to find any other FPs in cPanel or WHM interfaces.

I can see this FP has been raised before in #620 but I cannot see any rules addressing it in CRS v3.0/master.

**Comment by YbyMMbPh** [comment]
I have just updated the original report after discovering that version 2 had a trailing slash in the REQUEST_FILENAME.
The exclusion rule has also been updated to now match all 3 variations.

**Comment by YbyMMbPh** [comment]
I have just updated the exclusion rule regex so that the optional forward slash does not become a capture group.

**Comment by csanders-git** [comment]
@YbyMMbPh so what is the current exclusion, we can add them to the exclusions section.

**Comment by YbyMMbPh** [comment]
```
# Rule to allow cPanel whm-server-status requests without log entry.
SecRule REMOTE_ADDR "@ipMatch 127.0.0.1" \
  "msg:'Matched 127.0.0.1 and matched whm-server-status with or without trailing slash. Disabling rules 920280 and 920350',\
  phase:1,\
  id:905120,\
  t:none,\
  pass,\
  nolog,\
  chain"
    SecRule REQUEST_FILENAME "@rx ^/whm-server-status\/?$" \
      "t:none,\
      ctl:ruleRemoveById=920280,\
      ctl:ruleRemoveById=920350"
```

**Comment by csanders-git** [comment]
@dune73 thoughts on adding this as our next exclusion category?

**Comment by dune73** [comment]
Yes, sure. We did not talk about new exclusion categories in point releases. I think that would / should be possible, but I think it takes some level of assurance of basic coverage to add it.

@lifeforms: What do you think?

**Comment by csanders-git** [comment]
I was thinking for 3.1 but you're right we may be able to roll this into point releases.

**Comment by dune73** [comment]
As this is technically meant to cover FPs, we're even staying within the limits defined by our release policy. But what is even more important in my eyes is that we want to encourage the wider community to provide these rules and if we tell them to wait until the next major release, that's not very contribution-friendly.

**Comment by lifeforms** [comment]
A new exclusion category, requiring a config setting, and requiring Nginx/IIS users to modify their included files, would be a bit too much of a big change for a 3.0.1 type release for my personal taste.

However we could also treat it as a more generic case of tools requesting http://127.0.0.1/ (which will surely happen with many more tools) and we might consider not triggering these rules when the remote address is `127.0.0.1` or `::1`. If we'd add this as a chained check to the existing rules, we will solve these problems and we will surely catch more false positives. I think it's benign to get HTTP calls from 127.0.0.1 with a numeric or empty host header. I think there is precedent for ignoring such requests in the CRS too, as Apache's tooling already does requests to 127.0.0.1 to monitor its own status and we are already specifically excluding those. I just can't find that CRS rule right now.

**Comment by dune73** [comment]
That apache exclusion is in 905, 905110 to be exact. And there is a thread discussing the problems with the exclusions, namely in the case of 905100. #734.

You have a point with Nginx and IIS, though. Most annoying! Can we do any form of special treatment for these new exclusion categories? I mean we have not even forked 3.1, so we can't even point users to the files in that tree.

**Comment by emphazer** [comment]
@dune73 
Maybe we should focus on removing 920280, 920350 and responsebodyAccess on 905100 instead of disabling the whole engine...
/fpm-status is another good example for php-fpm status.

We are using munin too, thats why we had to remove this rules..

**Comment by csanders-git** [comment]
An interesting note if we add blanket exceptions for localhost is SSRF is still a viable issue. In most cases though i'd guess that the request outbound won't go through the WAF anyway.
Interesting thinking @dune73 and @emphazer, seems to be the best path for this issue. Additionally, I never thought about the difficulty of adding such exceptions would cause on non Apache (urgh)

**Comment by YbyMMbPh** [comment]
@csanders-git 
SecRule REMOTE_ADDR "@ipMatch 127.0.0.1" and
SecRule TX:REAL_IP"@ipMatch 127.0.0.1"
should NEVER be used as an indicator of trust.

I think the pseudo logic of the exclusion rule in this thread is relevant to the rewrite of rules 905100 and 905110.
Here is the approach I used.

-- Begin with a fast executing request filter so that this rule does not slow requests to which it not relevant.
-- SecRule REMOTE_ADDR "@ipMatch 127.0.0.1" 
-- This condition is fast but not trustworthy

--- Chain highly specific slower executing rules that identify the false positive request
`--- REQUEST_FILENAME "@rx ^/whm-server-status\/?$"`
--- This condition is pretty fast as regular expressions go, but slower that the first condition.

---- Do the minimum Action required to eliminate or mitigate the false positive.
---- ctl:ruleRemoveById=920280, ctl:ruleRemoveById=920350
---- Turn off 2 robot indicating rules (this action has low consequences)

**Comment by csanders-git** [comment]
So we decided this had to wait till 3.1 yes?

**Comment by dune73** [comment]
Yes, I think we will need to postpone this. But what could do is pointing users to additional new exclusion rules in the 3.1 tree (and subsequent trees). That way it's optional and people can still profit if they want. Ideally, this would also trigger some beta testing of new exclusions.

**Comment by CanadianJeff** [comment]
this issue has been going on for well over 1 year

**Comment by CanadianJeff** [comment]
I first reported this problem on Oct 19 2016
https://github.com/SpiderLabs/ModSecurity/issues/1232

**Comment by dune73** [comment]
Hi @CanadianJeff, you are right. This has been open far too long.

We do our monthly community chat on Monday and I added it to the agenda (-> #991).

In fact we have a general problem with not fixing issues that our users report. And we need a solution there.

**Comment by spartantri** [comment]
it would be good to have a process to validate all those exceptions and a standard way to address them to avoid irregularities, fake reports, etc

**Comment by dune73** [comment]
OK, here we are. So we talked things through in the meeting.

@emphazer promised to do a PR under the condition I write the requirements and the resolution. I have now read the chat log again and took a closer look at the comments above. @YbyMMbPh wrote up his reasoning in a beautiful way. But @lifeforms aimed at a more general solution. Looking through the chat log, I think @emphazer had something similar in mind on Monday, but I did not really see the point. The way @lifeforms is describing it, it makes sense and puts our decision into question (Why are even simple things soo hard?)

### Solution 1: Create a new rule exclusion category for cPanel (This is what we decided on Monday)

Take up the excellent description / recipe from @YbyMMbPh and create a new rule exclusion file / category for cPanel like we did for wordpress / drupal.

Advantage: Clean solution for exactly the problem reported above.
Disadvantage: No general solution, more FPs will surely appear. We create a new rule exclusion category but in fact we only cover a single aspect of it. People will assume cPanel won't have any FPs on CRS PL1 and we let them down when the first FP pops up.

### Solution 2: Add a chained condition on the offending rules (920280 / 920350) and make sure they no longer fire for localhost (This is what @lifeforms suggests)

Caution: make sure the condition / chained rules come in the right order to go easy on performance. See above for a good discussion of this by @YbyMMbPh.

Advantage: We do not need to create a new and incomplete rule category for cPanel. We could backport this to 3.0 without breaking any policy.
Disadvantage: We actually decided for solution 1 on Monday.

### So what do we do?

I usually stick to the policy that the people doing the work should also get to take the decisions. This boils down to @emphazer making the pick here. I will defend his decision.

**Comment by emphazer** [comment]
its finally done
