### ISSUE TITLE
Common Exception 905100 is broken

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#734]
The rule reads:

```
SecRule REQUEST_LINE "@streq GET /" \
```

This will never trigger as the protocol is missing and `@streq` is used.

Using `@beginsWith` and adding a space after the slash would fix it, BUT we would activate a common exception that would disable ModSec for GET requests from localhost to /, no matter what user-agent or referer or other funny tricks somebody is trying. So if an attacker manages to send a request from localhost ...

905110 is similar (and works!)

I suggest we fix 905100 and comment it out.

**Comment by emphazer** [comment]
I think that makes sense. 
Shall i change my PR for 905100 to
```
 "@beginsWith GET /\ " 
```
And comment it out?

**Comment by dune73** [comment]
I am torn.

We do not want users to edit the 905 file. Yet commenting something out is an invitation for the user to do just that. An update to the rule set would overwrite that change again.

On the other hand, I think such a far-reaching exception should not be enabled by default. 905110 is already quite risky if you ask me, but 905100 is even worse and maybe it would be better to kick out the rule completely.

@csanders-git: you reacted favorably on the commenting-out idea. What do you think about my concerns?

@emphazer: Please hold on until we are really sure what the right strategy is. Maybe @lifeforms also has something to add.

**Comment by emphazer** [comment]
@dune73 
Im with you. It looks like an invitation. 
If we choose to comment it out then we should add a warning comment.

**Comment by YbyMMbPh** [comment]
@dune73 
Hold on. 
"@streq GET /" 
appears to be exactly the string to be matched for this particular exception
See...
https://sourceforge.net/p/mod-security/mailman/message/23030180/ and
https://sourceforge.net/p/mod-security/mailman/message/19132564/
The logs in those conversations show...
--9286586f-B--
GET /

--9286586f-H--
as the request.

In these conversations Server: Apache/2.2.3 is mentioned so Apache may still make these requests in some configurations.
My server does not make these requests so I can not give more detail.
It would be great if someone whose Apache makes these requests, i.e. 
GET / from ip 127.0.0.1 or ::1
for rule 905100, and
GET / HTTP/1.0 from ip 127.0.0.1 or ::1
GET / HTTP/1.1 from ip 127.0.0.1 or ::1
OPTIONS * HTTP/1.0 from ip 127.0.0.1 or ::1
OPTIONS * HTTP/1.1 from ip 127.0.0.1 or ::1
for rule 905110
would provide logs for the requests. (especially while 905100 and 905110 are disabled)

I really dislike this rule though, disabling the ruleEngine is an extreme Action to deal with a false positive.

**Comment by dune73** [comment]
Thanks for pointing this out. Very puzzling. I do not think I have ever seen the "GET /".
Anybody has more experience here?

The change to `@beginsWith GET /<SPACE>` would break this, obviously. Hmm.

**Comment by ranvis** [comment]
Hi.
For "internal dummy connection" to HTTPS port, it had been changed on Apache 2.2.24 / 2.4.3.
```
$ echo | telnet 127.0.0.1 20223 > /dev/null # Apache 2.2.23
Connection closed by foreign host.
$ tail logs/ssl_request_log
[22/May/2017:00:15:25 +0900] 127.0.0.1 - - "GET /" 474

$ echo | telnet 127.0.0.1 20224 > /dev/null # Apache 2.2.24
Connection closed by foreign host.
$ tail logs/ssl_request_log
[22/May/2017:00:19:58 +0900] 127.0.0.1 - - "GET / HTTP/1.0" 362
```
modules/ssl/ssl_engine_io.c of https://github.com/apache/httpd/commit/b67aec5ed5fcb8646a4e81f96625877c1345781f / https://github.com/apache/httpd/commit/7cf9ed008a52579b96741a6af95c7177dc1abd6a
```diff
 /* Just use a simple request.  Any request will work for this, because
  * we use a flag in the conn_rec->conn_vector now.  The fake request just
  * gets the request back to the Apache core so that a response can be sent.
- *
- * To avoid calling back for more data from the socket, use an HTTP/0.9
- * request, and tack on an EOS bucket.
+ * Since we use an HTTP/1.x request, we also have to inject the empty line
+ * that terminates the headers, or the core will read more data from the
+ * socket.
  */
 #define HTTP_ON_HTTPS_PORT \
-    "GET /" CRLF
+    "GET / HTTP/1.0" CRLF
```
It used to return 400 Bad Request response body without headers because of the protocol HTTP/0.9.
hth.

**Comment by lkarsten** [comment]
I think 905100 and 905110 are user unfriendly.

In a configuration where requests are proxied by localhost (TLS termination, sandwiched web servers)  these rules effectively disable modsecurity by default. As a new user, I have no idea where to start looking. This, coupled with how debug logging is behaving, makes deploying CRS for new users hard.

Running CRS3.0 1b6c5aeca, libmodsecurity 0508395f8d5d988a0febdfaad17fd68ff92afa44 with modsecurity-nginx.

As I'm not running Apache, I have no need for these rules and would like them removed. Isn't there a User-Agent set on these probes that can exclude at least some of the breakage?

**Comment by csanders-git** [comment]
@lkarsten looking at the code it seems that they are using HTTP/1.0 (0.9 previously) purposely so they don't need to send headers (like host, or user-agent). I agree that this puts us in an interesting spot.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
