### ISSUE TITLE
A regex bug in 941190

### ISSUE THREAD

**Issue by whuben** [SpiderLabs/owasp-modsecurity-crs#737]
The wrong regex: (?i:<style.*?>.*?((@[i\\\\])|(([:=]|(&#x?0*((58)|(3A)|(61)|(3D));?)).*?([(\\\\]|(&#x?0*((40)|(28)|(92)|(5C));?))))) 
there is no ascii with value of  0x92, according to the context， the string "92" should be modified to "29" which point to the character ")"
The corrected regex should be : (?i:<style.*?>.*?((@[i\\\\])|(([:=]|(&#x?0*((58)|(3A)|(61)|(3D));?)).*?([(\\\\]|(&#x?0*((40)|(28)|(29)|(5C));?)))))

**Comment by csanders-git** [comment]
at first this does appear as a weakness but this regex also collects decimal i think, I'd argue that it needs to be improved to detect all variants in both hex and decimal form. Thoughts?

```
&#92;
```

**Comment by whuben** [comment]
that make sense, thank you.
