### ISSUE TITLE
Out of band communication / external service interaction going undetected at PL4

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#744]
This is a finding discovered via Burp and Wavsep by Damiano Esposito from Zurich University of Applied Sciences and Christian Folini, netnea.com.

* Application did DNS lookups and HTTP requests to a destination posted as payload.
* This will be very hard to detect via "target" parameter

```
GET /wavsep/active/RFI/RFI-Detection-Evaluation-GET-200Error/Case07-RFI-UrlClass-FilenameContext-Unrestricted-HttpURL-DefaultEmptyInput-NoProtocolReq-Read.jsp?target=2ehfpt7gxyu23j4dh1p71f2eo5u2uzir6it8hx.burpcollaborator.net HTTP/1.1
Host: espomodsecurity
Accept: */*
Accept-Language: en
User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0)
Connection: close
X-PL: 0
Referer: http://espomodsecurity/wavsep/active/RFI/RFI-Detection-Evaluation-GET-200Error/
Cookie: JSESSIONID=48BDE66262090C329859066F3E5A82C5; userinput=EmptyValue; info-cookie-no-http-only=test

HTTP/1.1 200 OK
Date: Sun, 12 Mar 2017 15:52:51 GMT
Server: Apache-Coyote/1.1
X-Unique-ID: WMVu038AAQEAADl8S48AAADI
Content-Type: text/html;charset=ISO-8859-1
Set-Cookie: JSESSIONID=2CE487839B230601AF095697754795A8; Path=/wavsep; HttpOnly
Content-Length: 61
Connection: close

<html><body>536afiapw19tm5g0y40trezjpspgkgjfigz</body></html>
```

The dump does not proof the external interaction. Burp does this by checking with burpcollaborator.net.

The interaction happened via HTTP (Out-of-band resource load), HTTP (External service interaction), DNS (External service interaction). But this does not really matter, I guess.

**Comment by spartantri** [comment]
@dune73,  there are many common words in Top Level Domains that will cause false positives, a PL4 rule that match things that look like valid domain could get this handled [TLD list](http://data.iana.org/TLD/tlds-alpha-by-domain.txt), notice that there are over 1500 TLD's

```
SecRule ARGS "@rx (?:(?:ht|f)tps?://)?(?:[a-zA-Z0-9\-]\.)+([a-zA-Z0-9\-])\.?/?" \
    chain,capture,block,t:urldecode
    SecRule TX:1 "@pmf topleveldomains.data"
```

For ip's its much more complicated as there is another issue on this but basically this can work as well
`SecRule ARGS "@rx (?:(?:ht|f)tps?://)?(?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2}?\.){3}(?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2}?)/?" block,t:urldecode`

Do we really want to address this? It is a very specific application issue.
