### ISSUE TITLE
SQLi rule 942410 could use word separators

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#761]
Got a false positive for `Zomerzangweek (9 t/m 12 jaar)`

`Message: Warning. Pattern match "(?i:(?:(?:s(?:t(?:d(?:dev(_pop|_samp)?)?|r(?:_to_date|cmp))|u(?:b(?:str(?:ing(_index)?)?|(?:dat|tim)e)|m)|e(?:c(?:_to_time|ond)|ssion_user)|ys(?:tem_user|date)|ha(1|2)?|oundex|chema|ig?n|pace|qrt)|i(?:s(null|_(free_lock|ipv4_compat|ipv4_mapped|ipv4|ipv ..." at ARGS:menu-item[-26][menu-item-title]. [file "/etc/apache2/security2/crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "961"] [id "942410"] [rev "2"] [msg "SQL Injection Attack"] [data "Matched Data: week ( found within ARGS:menu-item[-26][menu-item-title]: Zomerzangweek (9 t/m 12 jaar)"]`

Seems to me that we could look for a `\b` word separator at the start of the SQL keywords without ill effects.

The 942410 regexp is pretty daunting though. Let's hope we got the source for this regexp from Ofer.

**Comment by franbuehler** [comment]
I disassembled the list from regex 942410 so far to find the right place for the word boundary at the start of the sql keywords. I didn't find the original regex in the source.
The word boundary is only missing at this start. Later the word boundaries are present.

Proposal:

Before:
`(?i:(?:(?:s(?:t(?:d(?:dev(_pop|_samp)?)?|......`
After:
`(?i:(?:\b(?:s(?:t(?:d(?:dev(_pop|_samp)?)?|......`

A few test examples, which all match without word boundary.
With word boundary:
`Zomerzangweek (9 t/m 12 jaar)` -> no match
`Zomerzang week (9 t/m 12 jaar)` -> match
`xsubstr (` -> no match
`x substr (` -> match
`xsqrt (` -> no match
`x sqrt (` -> match
`xis_null (` -> no match
`x is_null (` -> match
`xuncompressed_length (` -> no match
`x uncompressed_length (` -> match
`xunix_timestamp (` -> no match
`x unix_timestamp (` -> match
`xucase (` -> no match
`x ucase (` -> match
`xlocate (` -> no match
`x locate (` -> match
`xlast(` -> no match
`x last (` -> match
`xmax (` -> no match
`x max (` -> match
`xmod (` -> no match
`x mod (` -> match
`xmonth (` -> no match
`x month (` -> match
`xreplace (` -> no match
`x replace (` -> match

What do you think about it?
I could make PR.

**Comment by dune73** [comment]
Thank you @franbuehler. I think you are about to fix the FP here. But additionally, the regex looks assembled from different sources with different levels of optimization. Cleaning this up for the 3.1 development looks very desirable and you seem to have walked half of that path already, so I think continuing and finishing this would be very welcome.

**Comment by csanders-git** [comment]
I can split off a 3.1/dev -- sounds like we're approaching a need.

**Comment by dune73** [comment]
Yes, I think it is time.

But we also need a policy (and step by step guide) how to backport fixes from 3.1/dev to 3.0/dev.

**Comment by franbuehler** [comment]
The FP should be resolved with PR 791.
And yes, @dune73, I've almost finished disassembling the regexp. I'll finish, test and then make a PR for 3.1/dev.

**Comment by franbuehler** [comment]
@dune73: I think this issue could be closed?

**Comment by dune73** [comment]
Think so too.

**Comment by DeepMalh44** [comment]
@franbuehler @dune73  hey guys we got a 942410 exception where it caught it where the match was " is (" basically it is a legitimate one for us as our businessType Arguments have a value which containg " is (" and now what we have to do here is to disable this 942410 rule on WAF.. you think this is correct? I know we can simply exclude the ARGS (businessType) but we may get more new Arguments :(.


RuleGroup | RuleId | Argument | MatchedExpression | Message | Count
-- | -- | -- | -- | -- | --
942-APPLICATION-ATTACK-SQLI | 942120 | ARGS:Account.Password | << | SQL Injection Attack: SQL Operator Detected | 2
942-APPLICATION-ATTACK-SQLI | 942410 | ARGS:Account.BusinessType | is | SQL Injection Attack | 1
942-APPLICATION-ATTACK-SQLI | 942410 | ARGS:Account.BusinessType.Caption | is | SQL Injection Attack | 1
