### ISSUE TITLE
DOS block rule does not expire

### ISSUE THREAD

**Issue by bjdijk** [SpiderLabs/owasp-modsecurity-crs#762]
Q1: In REQUEST-912-DOS-PROTECTION.conf, the ip.dos_counter is increased for every request made to a none static resource, As soon as it hits the threshold, ip.dos_burst_counter is set/increased by 1, which expires after ip.dos_burst_time_slice. So when we have a threshold of 100, and over a couple of days we reach 100, ip.dos_burst_counter=1. If PL is set to 1, it will only trigger when the dos_burst_counter = 2. Normally there will be enough time for the dos_burst_counter to expire. But in PL 2, it blocks immediately. I can hardly call this a DOS attack.

Shouldn't the expire be set on the ip.dos_counter, so that if you get more than x requests / time slice, and it contineous like that, you block?

Q2: is the also a rule which does something similar but sends to IP to a block list if it request to many non-existent resources?

**Comment by dune73** [comment]
Q1: This sounds as if the characteristics of your site does not match with the values you set. I suggest to reduce ip.dos_burst_time_slice to expire faster. Or raise the threshold. Or whitelist certain IP addresses, or remove the PL2 rule 912171 altogether.

Q2: No, there is no such rule. But I use such a rule on a private server in combination with fail2ban. The problem with many sites is, that 404 is far too frequent and this rule would be a major source of FPs. But maybe it's an idea for PL3.

**Comment by dune73** [comment]
Closing this now.

If you still think this is a rule problem and not one of your configuration, then please reopen this issue and provide additional arguments.

**Comment by Tensibai** [comment]
@dune73 Just spent a while understanding an issue occuring every 50 mins on a load test on our setup which is exactly this one, I'd suggest reopening.

My setup of Dos protection (pretty high):

```SecAction \
 "id:900700,\
  phase:1,\
  nolog,\
  pass,\
  t:none,\
  setvar:'tx.dos_burst_time_slice=5',\
  setvar:'tx.dos_counter_threshold=30000',\
  setvar:'tx.dos_block_timeout=60'"
```
What happens is that 912150 increase the collection counter on each request if the request is within the `SecCollectionTimeout 600`. 
The counter keeps increasing as long a there's requests within 10 minutes. 
Once the dos_counter is above dos_counter_threshold then the dos_burst is set to 1 and 912171 does the blocking for dos_block_timeout, the dos_burst_time_slice is not used when 912171 is used, it's only useful for 912170 (Paranoia Level 1).

In brief with configuration above: if counter gets > 30k with less than 10 minutes between requests then the IP get blocked for 60 seconds by rule 912171.

I suggest either increasing the numbers in 912170 and 912171 to respectively 3 and 2  so the burst counter has a chance to be reset by the `dos_burst_time_slice` or expiring the dos_counter after dos_burst_time to better match the idea of Dos Protection.

For now, I've disabled 912171, but that sounds counter productive and the behavior doesn't seems correct to me unless you wish to block an IP after N regular requests.

**Comment by spartantri** [comment]
Hi, @Tensibai rule execution order has nothing to do with numeric rule id, rules are executed in the order they are loaded into your configuration, also, we try to avoid as much as possible rule id changes on already existing rules as it usually causes issues in many deployments exceptions.

**Comment by Tensibai** [comment]
@spartantri I didn't ask for a rule number change, I asked for changing:

In [912171](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.2/dev/rules/REQUEST-912-DOS-PROTECTION.conf#L259):

`SecRule IP:DOS_BURST_COUNTER "@ge 1" \` by `SecRule IP:DOS_BURST_COUNTER "@ge 2" \`

In [912170](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.2/dev/rules/REQUEST-912-DOS-PROTECTION.conf#L229):

`SecRule IP:DOS_BURST_COUNTER "@ge 2" \` by `SecRule IP:DOS_BURST_COUNTER "@ge 3" \`

OR

In [912150](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.2/dev/rules/REQUEST-912-DOS-PROTECTION.conf#L174-L175)

Adding `expirevar:'ip.dos_counter=%{tx.dos_burst_time_slice}'"` along with the creation of the collection.
But I'm very less sure this would achieve what I expect, so the first option is most sensible for me.

**Comment by Tensibai** [comment]
As I've probably been unclear, the actual state with stock rules in Paranoia Level 2 is that with a regular stream of requests, the IP will be blocked after `dos_counter_threshold` requests regardless of the `dos_burst_time_slice` value.

**Comment by celesteking** [comment]
`dos_counter` never expires. This should be fixed either by rethinking the rule logic or by adding expiration time.
