### ISSUE TITLE
a regex bug in 942300

### ISSUE THREAD

**Issue by whuben** [SpiderLabs/owasp-modsecurity-crs#765]
the wrong regex: (?i:(?:\)\s*?when\s*?\d+\s*?then)|(?:[\"'`]\s*?(?:#|--|{))|(?:\/\*!\s?\d+)|(?:ch(?:a)?r\s*?\(\s*?\d)|(?:(?:(n?and|x?x?or|div|like|between|and|not)\s+|\|\||\&\&)\s*?\w+\()) 
just delete the extra ")"  in the end  of the regex

**Comment by dune73** [comment]
Thank you for reporting. This is subtle, but you could be right.

942300 is doing great in production, though. That proofs that PCRE can at least make some sense of it.

**Comment by dune73** [comment]
Assigned the new label "Buggy Rule" and hope others will chime in.

**Comment by csanders-git** [comment]
The regex seems to be working fine, all of the following trigger:
```
chr (4
/*! 5
" --
) when 4 then
nand f(
|| f(
&& f(
```
( https://regex101.com/r/0UUpYx/1 )
That being said... This claims to "msg:'Detects MySQL comments, conditions and ch(a)r injections'". It /*! isn't not MySQL (that's fine) but '#' is and that isn't detected... strange.

**Comment by whuben** [comment]
(?i:(?:\)\s*?when\s*?\d+\s*?then)|(?:[\"'`]\s*?(?:#|--|{))|(?:\/\*!\s?\d+)|(?:ch(?:a)?r\s*?\(\s*?\d)|(?:(?:(n?and|x?x?or|div|like|between|and|not)\s+|\|\||\&\&)\s*?\w+\())

**Comment by whuben** [comment]
sorry, my mistake，the regex is fine in the text of rule . but it's interesting that Github escapes the  "(?i:(?:\\)" to  “(?i:(?:)” in the beginning of the regex

**Comment by dune73** [comment]
I really decomposed this by hand yesterday and I thought @whuben was correct.

@csanders-git : Do we want to fix the `#`?

**Comment by csanders-git** [comment]
Looking at this other rules take account for that already.

**Comment by csanders-git** [comment]
to come full circle, i'd say no
