### ISSUE TITLE
Debug present code in 3.0.1 release

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#771]
During the treatment of #719 some debug code was committed to v3.0/dev in REQUEST-920. It seems this was done without PR and review. 

https://github.com/SpiderLabs/owasp-modsecurity-crs/commit/0faf986138a0ab088231a51869e8829ca9bd8be5

This triggers on every request here.

**Comment by dune73** [comment]
@lifeforms pointed out that I actually merged this.

https://github.com/SpiderLabs/owasp-modsecurity-crs/commit/c9ba8d8d168759921faea02d53ea5e01bca70c8d

So it seems @csanders-git created this version, then tagged the issue with "PR exists" and I somehow managed to merge this to v3.0/master and when we tested v3.0/dev it did not show up. It was only after the release that it appeared.

**Comment by dune73** [comment]
PR in #772.

**Comment by csanders-git** [comment]
I merged the PR. I can do a 3.0.2 release and mark 3.0.1 as a draft release. Are we ready to do that? Again sorry about this.

**Comment by dune73** [comment]
No worries. It seems to me you and I collaborated on this mess in a very un-fruitful way. We could never have done this alone. ;(

I am ready for 3.0.2. New formal release procedure at https://github.com/SpiderLabs/owasp-modsecurity-crs/wiki/Release-Procedure

I just got up and will now start the preparations for my talk and then attend the conference. So I am out for the rest of the day.

**Comment by dune73** [comment]
Fixed in release 3.0.2.
