### ISSUE TITLE
Issue with 3.0.1 (rule id 22)

### ISSUE THREAD

**Issue by angeloxx** [SpiderLabs/owasp-modsecurity-crs#773]
Hi, the rule id:22:
`
SecRule REQUEST_URI "(.*)" "msg:'got %{tx.0}',id:22,capture"
`
Blocks any requests if default action is deny. I suppose that is a typo because the id is very low (outside the CRS id range) anche the capture without pass blocks phase:2 if defaultAction is deny.

**Comment by csanders-git** [comment]
Thank you for this report, this was noticed by several people yesterday and we sincerely apologize for the inconvenience. We will be releasing 3.0.2 today to account for this issue.

**Comment by dune73** [comment]
Issue has been reported in #771. Closing this as a copy.

And sorry for the mess with the release. That is really annoying.
