### ISSUE TITLE
REQUEST-920-PROTOCOL-ENFORCEMENT.conf question

### ISSUE THREAD

**Issue by ljdzxx** [SpiderLabs/owasp-modsecurity-crs#776]
when access my page which include css path "/assets/js/layer/skin/layer.css", then catch a warning log as:

---NCoWfjju---H--
ModSecurity: Warning. Matched "Operator `Rx' with parameter `(.*)' against variable `REQUEST_URI' (Value: `/assets/js/layer/skin/layer.css' ) [file "/home/ray/owasp-modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "451"] [id "22"] [rev ""] [msg "got /assets/js/layer/skin/layer.css"] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [ref "o0,31o0,31v4,31"]

so what's wrong?sorry i'm a newer and is first time to use this.

**Comment by ljdzxx** [comment]
---F0MTc6q0---A--
[15/May/2017:17:06:47 +0800] 14948392071.000000 172.16.4.185 63551 172.16.4.185 443
---F0MTc6q0---B--
GET /assets/css/public.css HTTP/1.1
Host: www.test-linux.com
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Cookie: bdshare_firstime=1493776845998; ftmacaumarketcom=1; Hm_lvt_df178b58505d3b5dcde2e6b25bb0e19d=1494217705,1494477991,1494478271,1494824271; Hm_lpvt_df178b58505d3b5dcde2e6b25bb0e19d=1494836821; JSESSIONID=AA1907C880442527D83CBAD4047D2A4D
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Referer: https://www.test-linux.com/
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: zh-CN,zh;q=0.8,en;q=0.6,zh-TW;q=0.4

---F0MTc6q0---D--

---F0MTc6q0---F--
Server: nginx/1.10.3
Date: Mon, 15 May 2017 09:06:47 GMT
Content-Type: text/css;charset=UTF-8
Connection: keep-alive
Last-Modified: Tue, 02 May 2017 09:31:37 GMT
Vary: Accept-Encoding
ETag: W/"48160-1493717497000"
Accept-Ranges: bytes
Content-Encoding: gzip

---F0MTc6q0---H--
ModSecurity: Warning. Matched "Operator `Rx' with parameter `(.*)' against variable `REQUEST_URI' (Value: `/assets/css/public.css' ) [file "/home/ray/owasp-modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf"] [line "451"] [id "22"] [rev ""] [msg "got /assets/css/public.css"] [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [ref "o0,22o0,22v4,22"]

---------------------------------------------
the full log above

**Comment by franbuehler** [comment]
Thanks for your report.
This is a known issue, see #771 for further details.
Please upgrade to CRS 3.0.2.
