### ISSUE TITLE
published research claims libinjection issues

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#778]
https://medium.com/@d0znpp/how-to-bypass-libinjection-in-many-waf-ngwaf-1e2513453c0f

There is one minor evasion listed ONLY at PL1 (PL2 catches it): ?id=)-sleep(9999

Weird that it calls out modsecurity but CRS, which is the most common rule set doesn't limit itself to libinjection.

**Comment by dune73** [comment]
They generally mix the two projects. This time I think he only means to cover the engine. So he is correct.

A remark to point out CRS goes beyond Libinjection for good reasons would be nice though.

**Comment by dune73** [comment]
-> Maybe there is more research coming up: 
https://twitter.com/binitamshah/status/863648823373058048

**Comment by client9** [comment]
matching ticket is here:
https://github.com/client9/libinjection/issues/125

**Comment by client9** [comment]
that's great you are catching `)-sleep(9999` since libinjection won't like this form.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
