### ISSUE TITLE
Error creating rule: Failed to resolve operator: detectXSS" with mod security version 2.9.1

### ISSUE THREAD

**Issue by deepakxoptimo** [SpiderLabs/owasp-modsecurity-crs#785]
I am getting below error

"AH00526: Syntax error on line 64 of ..crs/modsecurity-crs/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf:
Error creating rule: Failed to resolve operator: detectXSS"

I have installed mod security 2.9.1 on apache 2.4.6.Below are the data from apache error log file

ModSecurity: StatusEngine call: "2.9.1,Apache/2.4.6 (CentOS) Ope,1.4.8/1.4.8,8.32/8.32 2012-11-30,(null),2.9.1,0f4af4*********"

ModSecurity: StatusEngine call successfully sent. For more information visit: http://status.modsecurity.org/

any suggestions?

**Comment by dune73** [comment]
It's a ModSecurity problem and not a CRS problem. But I honestly can't think of a reason for this error. `detectXSS` has been in ModSec since 2.8.0 and the library providing the operator, libinjection, is part of the ModSec sourcecode. So an unmet dependency is very unlikely.

Other thoughts?

**Comment by lifeforms** [comment]
I think your ModSecurity is compiled without libinjection support. This is required to run CRS3.

The best thing is to e-mail the ModSecurity mailing list, I think.
