### ISSUE TITLE
operator @validateByteRange config error

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/owasp-modsecurity-crs#787]
when I set the rule file "/etc/nginx/owasp-modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf" ID  about 920270  "SecRule REQUEST_URI|REQUEST_HEADERS|ARGS|ARGS_NAMES "@validateByteRange 0-255" \
  "phase:request,\
   rev:'2',\
   ver:'OWASP_CRS/3.0.0',\
   maturity:'9',\
   accuracy:'9',\
   block,\
   msg:'Invalid character in request (null character)',\
   id:920270,\
   severity:'CRITICAL',\
   t:none,t:urlDecodeUni,\
   tag:'application-multi',\
   tag:'language-multi',\
   tag:'platform-multi',\
   tag:'attack-protocol',\
   tag:'OWASP_CRS/PROTOCOL_VIOLATION/EVASION',\
   setvar:'tx.msg=%{rule.msg}',\
   setvar:tx.anomaly_score=+%{tx.error_anomaly_score},\
   setvar:tx.%{rule.id}-OWASP_CRS/PROTOCOL_VIOLATION/EVASION-%{matched_var_name}=%{matched_var}"" 

the ASCII is 0-255 0 is null character but Why also suggests this mistake blow-------->
"messages": [
            {
                "message": "Invalid character in request (null character)",
                "details": {
                    "match": "Matched \"Operator `ValidadeByteRange' with parameter `0-255' against variable `ARGS:plate_bottom' (Value: `\\xffffffe8\\xffffffaf\\xffffffb7\\xffffffe9\\xffffff80\\xffffff89\\xffffffe6\\xffffff8b\\xffffffa9' )",

![validate](https://cloud.githubusercontent.com/assets/17851645/26479728/0a34421a-4208-11e7-8b66-f93cda0ff270.png)

**Comment by dune73** [comment]
Hello @Hello-Linux, you are editing the rule file. I would advise against doing so as an eventual rule update will overwrite your changes. It is better to fight false positives with rule exclusions as explained in the CRS tutorials.
I am not sure what is amiss with your re-configuration and the alert, but it points to a ModSecurity problem and not Core Rule Set, as you trying out something that the Core Rule Set is not doing.

If you think this is a CRS problem, then please re-open this issue.

**Comment by Hello-Linux** [comment]
@dune73  I agree with you,but I want to know when I change the ASCII  about "@validatebyterange 0-255" ,Why again this mistake "
messages": [
{
"message": "Invalid character in request (null character)",
"details": {
"match": "Matched "Operator ValidadeByteRange' with parameter0-255' against variable "

**Comment by dune73** [comment]
I do not think I get you. The message field is exactly the message you have in your rule as msg, the match field is ModSec's interpretation of the operator (-> 0-255).

**Comment by csanders-git** [comment]
After reviewing this rule as well it seems to be operating as expecting. The rule is no looking for any valid ASCII char, instead it is looking explicitly for any valid ASCII char EXCEPT the null char. By changing the rule to include 0 (thereby making it all ASCII chars), you have changed the nature of rule -- hence the message disagrees.
