### ISSUE TITLE
Running upgrade.py throws unknown option `ff-only'

### ISSUE THREAD

**Issue by skidoosh** [SpiderLabs/owasp-modsecurity-crs#789]
Hi ladies/gents,

If I try to run upgrade.py on a cloned master I get the error:

crs: Git pull failed! Error: error: unknown option `ff-only'

The error is originating from the command ' git pull origin HEAD --ff-only'. Changing the command to ' git pull --ff-only origin HEAD' fixes the error.

I'm on Debian 8.8 with Git 2.1.4

**Comment by victorhora** [comment]
Hi @skidoosh,

Thanks for spotting this issue. I haven't noticed before when testing this on some of my VMs. It doesn't seem to happen on newer versions of Git:

![image](https://cloud.githubusercontent.com/assets/15767386/26734202/36d73420-478b-11e7-84fe-a4a97003b7fa.png)

But I've confirmed that the issue does happen with older versions of Git:

![image](https://cloud.githubusercontent.com/assets/15767386/26734259/61baee02-478b-11e7-93fb-b13d3f13a804.png)

So this should definitely  be fixed.

Do you want to submit a pull request with the fix or should I?

**Comment by skidoosh** [comment]
I'd love to! Never done it before so I'll read up on how to do it and get it in over the weekend.

**Comment by victorhora** [comment]
As this is already merged and tested I believe we could close this one @dune73 @csanders-git :)
