### ISSUE TITLE
Remove t:removeComments from 942100

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#796]
removeComments is being deprecated as there is really no good way to to deal with recursive type comments etc. As a result we should probably remove it from rule 942100

**Comment by fgsch** [comment]
Don't forget updating the wiki also :)

**Comment by victorhora** [comment]
Just to clarify t:removeComments is currently [supported in libModSecurity](https://github.com/SpiderLabs/ModSecurity/blob/v3/master/src/actions/transformations/remove_comments.cc) and I believe that at the time the reasoning to implement was to make sure that the CRS3 was loading and working fine with ModSec v3.

In anyways I've added a [small note](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#removeComments) to the reference manual about potential issues with this transformation and the fact that it could be deprecated in the future.

**Comment by dune73** [comment]
Closing this in favor of PR #825.
