### ISSUE TITLE
Logdata not set

### ISSUE THREAD

**Issue by fgsch** [SpiderLabs/owasp-modsecurity-crs#798]
A number of rules don't set logdata (see below). This makes debugging and troubleshooting difficult.

Agreed with @csanders-git to open an issue to get this fixed.

```
910100
920220
920230
920240
920250
920260
920270
920271
920272
920273
920274
920280
920290
920300
920310
920311
920320
920330
920340
920360
920370
920380
920390
920400
920410
949110
```

**Comment by dune73** [comment]
Wow, that's quite a list. Thank you.

I agree on the troubleshooting difficulty. Besides, I see this cleanup effort together with a general rule housekeeping: Reorder all actions, clean up the tagging, etc.

**Comment by fzipi** [comment]
@fgsch There are rules that are practically boolean: for example 9202(8|9)0, 9203(0|1|2|3|6)0, 920311 and 920250. What's are we going to log there? There is already a 'msg' for that rule...

I'm sending PR #980 which addresses the other rules.

**Comment by fgsch** [comment]
@fzipi The original conversation covered a few rules. 
I created the list programatically to include them all but in some cases it might be OK.

As for the rules you mentioned, it'd be nice if:

- For 920250, we log what was invalid
- For 920360, the actual length

**Comment by fzipi** [comment]
@fgsch Good, added those as well.

**Comment by fgsch** [comment]
@fzipi #980 has been merged so I guess we can close this?

**Comment by fzipi** [comment]
@fgsch Yes!
