### ISSUE TITLE
Why do some function is cancelled about CRS？

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/owasp-modsecurity-crs#799]
I want to know in 2.0 version have the two rule files 1.experimental_rules/modsecurity_crs_11_proxy_abuse.conf 
2.modsecurity_crs_11_brute_force.conf

but in 3.0 version I am not found this two files why? and I also want to know in the crs 3.0 version of the function are the two files contains?

and the @fuzzyHash  operator  for webshell have cancel in 3.0？

**Comment by dune73** [comment]
Hi @Hello-Linux,

CRS3 is a consolidation release but also one with new features. Consolidation means that some rules were removed. Most of them were removed from the development tree before the present maintainers of the project joined it. The reasons for the removal were usually that the rules are outside the scope of the project.

I suggest you look up the rules in question in the list at ./id_renumbering/IdNumbering.csv where the old ruleID and the new ruleID correspond. If it is missing there, then the rule is gone.

The fuzzy hash operator is not in use in CRS. But we are planning to include it. See issue #363.

**Comment by Hello-Linux** [comment]
@dune73  But I think the rules is very useful，for example the webshell rule，I don't understand why them are  beyond the scope of your project

**Comment by dune73** [comment]
Which one was that? (-> Please tell me the rule id)

**Comment by Hello-Linux** [comment]
@dune73  id:'950115'
		id:'981036
		id:'981037
		id:'981038
		id:'981039
		id:'981040
		id:'981041
		id:'981042
		id:'981043
		id:'950110'
		id:'950921'
		id:'950922'

**Comment by dune73** [comment]
```
950115: rule depends on additional scripts. Better do this yourself
981036-981043: Brute force stuff. Not sure why it was omitted. It is very close to ddos stuff, not really performing that great and probably not effective. Look into mod_qos if you need this
950110, 950921, 950922: Trojan detection: I take it they are outdated, but I am not really sure.  950922 is certainly very expensive performancewise.
```

**Comment by Hello-Linux** [comment]
@dune73 Now web attack way of webshell occupies a large part of, I wish modsecurity to increase this function,and I want to know about the rule 950115 that if I want to use this rule what should I do?

**Comment by dune73** [comment]
The rule is basically calling an external script that calls your antivirus software.

The 2nd edition of the ModSecurity Handbook at Feisty Duck explains this in detail and has an example for said script. The online reference manual also has such a script AFAIK.

**Comment by Hello-Linux** [comment]
@dune73     If I want to defense wenshell what should I do? I think the webshell is very  important

**Comment by dune73** [comment]
Your anti-virus will not help you against the web shell. I also think it is very important, but our project does not yet have rules to help you fight it. You need to secure your application itself and - if possible - disable all file uploads.

**Comment by Hello-Linux** [comment]
@dune73 But in this article that say it is passible “https://www.trustwave.com/Resources/SpiderLabs-Blog/ModSecurity-Advanced-Topic-of-the-Week--Detecting-Malware-with-Fuzzy-Hashing/”

**Comment by dune73** [comment]
Yes, ModSecurity has the functionality, but our Core Rule Set project does not yet support it. 

If you want to use the ModSecurity functionality you need to set this up yourself. The rules are described in said article. And then it goes on to say that you need a database of all webshells that you want to avoid. Getting or building this database is very hard or time consuming. 

If you manage to reach this goal, the Core Rule Set project would be very interested in your contribution of the database to our project, so we can support this functionality as well.
