### ISSUE TITLE
Rule 920460 is missing msg

### ISSUE THREAD

**Issue by fgsch** [SpiderLabs/owasp-modsecurity-crs#800]
Related to #798

**Comment by dune73** [comment]
Hey, that's my rule. Why did not anybody notice this!?

Do you want to try out a pull request yourself, or should I write it?

**Comment by fgsch** [comment]
I was planning to but go ahead if you want. I'm happy as long as it's fixed :)

**Comment by dune73** [comment]
No, I prefer if you do it. There is plenty of stuff for me 2do. :)
