### ISSUE TITLE
Rule 920440 has transformations applied incorrectly 

### ISSUE THREAD

**Issue by fgsch** [SpiderLabs/owasp-modsecurity-crs#801]
This rule has transformations on the top rule. This transformations should be on the bottom rule instead.

Discussed with @csanders-git

**Comment by victorhora** [comment]
Yup. I can see the transformations being applied at line [1057](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L1057) when it would make more sense on line [1077](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf#L1077)

Submit a PR? :)

**Comment by fgsch** [comment]
That's the plan :)
