### ISSUE TITLE
id:900500 Honey Pot causes the web server to slow down up to 25x times

### ISSUE THREAD

**Issue by pantaluna** [SpiderLabs/owasp-modsecurity-crs#802]
I'm testing the last release owasp-modsecurity-crs v3.0.2.

When I activate the Honeypot rule (with api key) in the config file **crs-setup.conf** then the web server becomes slower and slower and the web server uses more and more CPU and Memory; it almost grinds to a halt but it does not crash an apache2 process. Even the kswapd0 process starts consuming CPU time on this server with 16GB memory (and apache2 configured to consume about 500MB); also strange.

I use the simple Nikto vulnerability scanner to test new versions of packages such as yours; and I typically expect that it passes a test run of at least 72 hours without glitches.

# Environment:
owasp-modsecurity-crs **v3.0.2** [git clone]
Ubuntu 17.04 zesty
Apache/2.4.25 (Ubuntu) Server built:   2017-04-24T12:53:49
libapache2-mod-security2:amd64/zesty 2.9.1-2 uptodate
libpcre3:amd64/zesty 2:8.40-5~ubuntu17.04.1+deb.sury.org+1 uptodate

# Config crs-setup.conf
```
    SecHttpBlKey mysecrethoneypotapikey
    SecAction "id:900500,\
        phase:1,\
        nolog,\
        pass,\
        t:none,\
        setvar:tx.block_search_ip=1,\
        setvar:tx.block_suspicious_ip=1,\
        setvar:tx.block_harvester_ip=1,\
        setvar:tx.block_spammer_ip=1"
```

# Procedure
When Honeypot is off then each consecutive run of the Nikto vulnerability scanner takes about **10-15 seconds**. This is as expected.

When Honeypot is on, a run of Nikto takes cumulatively more time. First run: +-**117 seconds**. Second run: +-**349 seconds**. Third run: +-**500 seconds**. And the execution time increases accordingly for each run after that. During these runs the normal web requests are affected as well: they slow down accordingly.

```
#Bash
while true
do
	nikto -Display V -host http://www.server.com/folder/script.php
	sleep 1
done
```

# Question
Please help to improve this.

**Comment by csanders-git** [comment]
@rcbarnett any status on this project? i'd be willing to help to try and see where the slow down could be.

**Comment by dune73** [comment]
@csanders-git: Do we have access to the Honey Pot server or is this a feature we would rather deprecate? I never saw it gain much traction. Things might be different now that we are a real community.

**Comment by victorhora** [comment]
I'm curious about this issue. I'm thinking about the fact that when you enable the honeypot rule it ends up consuming that much CPU / Mem could be an issue with ModSecurity. Even if there's some issue with ProjectHoneypot it doesn't seem right.

@pantaluna do you think you could simply give it a try with [libModSecurity](https://github.com/SpiderLabs/ModSecurity-nginx) and report the results? This could give us at least a clue where the problem lies :)

**Comment by csanders-git** [comment]
I don't think it has much traction but there is a Honey pot server. I can try and dig up the credentials to access it by @rcbarnett was always the master of that domain. Any interest? @dune73 ?

**Comment by dune73** [comment]
Certainly interested. If you can get the credentials, please do. Otherwise we need to think about the future of this initiative.

**Comment by pantaluna** [comment]
@victorhora Thanks for the follow-up. I do not have an Nginx environment for testing (only Apache).

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
