### ISSUE TITLE
"PayLoadAllTheThings" collection of payloads

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#803]
Not sure we have an issue linking to this big collection (if we do, then please somebody close as duplicate. I am a bit in a hurry.)

https://github.com/swisskyrepo/PayloadsAllTheThings

**Comment by victorhora** [comment]
I couldn't find any other issue linking to this juicy list. Will come in handy for many I'm sure. Thanks for sharing :)

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
