### ISSUE TITLE
Use operator @beginsWith to resolve handle-false-positive error

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/owasp-modsecurity-crs#806]
@dune73  @yersinia  @ygrek  @FireFart  @koto To resolver the handle-false-positive about the request_url “/index.php?act=store” and  “/index.php?act=search". 
so I write in /etc/nginx/owasp-modsecurity-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf  like that "SecRule REQUEST_URI "@beginsWith /index.php?act=store" \
    "id:1001,phase:1,pass,nolog,\
     ctl:ruleRemoveById=920270"
SecRule REQUEST_URI "@beginsWith /index.php?act=store" \
    "id:1002,phase:1,pass,nolog,\
     ctl:ruleRemoveById=941160"
#ModSec Rule Exclusion: id:942100  :SQL Injection Attack Detected via libinjection
SecRule REQUEST_URI "@beginsWith /index.php?act=store" \
    "id:1003,phase:1,pass,nolog,\
     ctl:ruleRemoveById=942100"
#ModSec Rule Exclusion :949110   :Inbound Anomaly Score Exceeded
SecRule REQUEST_URI "@beginsWith /index.php?act=store" \
    "id:1004,phase:1,pass,nolog,\
     ctl:ruleRemoveById=949110"
#yandex.ru search Rule Exclusion id:920270
SecRule REQUEST_URI "@beginsWith /index.php?act=search" \
    "id:1005,phase:1,pass,nolog,\
     ctl:ruleRemoveById=920270"
#yandex.ru search Rule Exclusion id:920270
SecRule REQUEST_URI "@beginsWith /?act=search" \
    "id:1006,phase:1,pass,nolog,\
     ctl:ruleRemoveById=920270"
#yandex.ru search Rule Exclusion id:920270
SecRule REQUEST_HEADERS:referer "@contains act=search&keyword=" \
    "id:1007,phase:1,pass,nolog,\
     ctl:ruleRemoveById=920270"

But in my audit log I found a strange phenomenon like  blow screenshot
![error1](https://user-images.githubusercontent.com/17851645/27024021-9ea4eed6-4f87-11e7-8ead-1c229339bc79.png)
![error2](https://user-images.githubusercontent.com/17851645/27024022-9ecf6774-4f87-11e7-9b20-cf921b1bbe6b.png)

the request_uri is "/index.php?act=seller_center&op=statistics&rand=24954191" and my rule is "SecRule REQUEST_URI "@beginsWith /index.php?act=store" \
    "id:1004,phase:1,pass,nolog,\
     ctl:ruleRemoveById=949110"  but rule's uri is not match the  "/index.php?act=seller_center&op=statistics&rand=24954191" why the request return 200 http code not 403？？？
The operator beginwith is not a exact match？

**Comment by dune73** [comment]
@Hello-Linux: like mentioned in #810, I can not reproduce this error. I think you misconfigured something. The information you give is incomplete and I am confident the debug log will help you solve your problem.

There are now so many issues opened by you across multiple projects that fail to prove any malfunction. You have called several people to support you for free while we have real, reproduceable issues that need our attention - and time. I for one have spent several hours over the last few weeks trying to understand and solve your problems. 

Please check your configuration in detail and if you submit new bug reports, make sure you include a minimal configuration that helps to reproduce the bug (1 rule is enough) and the debug log proving the malfunction. Styling your message into a more readable format and maybe asking a friend to check your English would also help. It's hardly comprehensible at times.
New bugs to the CRS project from your account failing to include the necessary information and failing to meet the standard will be closed without further investigation as we assume it's a waste of time.
