### ISSUE TITLE
Use operator beginWith error

### ISSUE THREAD

**Issue by Hello-Linux** [SpiderLabs/owasp-modsecurity-crs#810]
When  I send a request_uri is "/index.php?act=seller_center&op=statistics&rand=24954191" and my rule is "SecRule REQUEST_URI "@beginswith /index.php?act=store"
"id:1004,phase:1,pass,nolog,
ctl:ruleRemoveById=949110" but rule id 1004  that his uri is not match the "/index.php?act=seller_center&op=statistics&rand=24954191"，and I found the request I send has match the rule that his id is 1004  why？ The operator beginwith is not a exact match？

**Comment by dune73** [comment]
Sorry, but I can not reproduce this error. Your rule and the configuration works as advertised.

This is not the first issue you are opening here. Please notice that this issue tracker is meant for Core Rule Set bug. Please report when you are really sure you have encountered a bug. When you do, then please submit the complete relevant configuration and the complete Audit log to help us understand what the matter might be.

**Comment by Hello-Linux** [comment]
@dune73 you can  see https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/806 in it   have the detailed introduction
