### ISSUE TITLE
Using a % sign as wildcard leads to false positives

### ISSUE THREAD

**Issue by bjdijk** [SpiderLabs/owasp-modsecurity-crs#824]
We have an app, which use a % sign as wildcard (matchall); i.e. %bcd% will match abcde and abcd and abcde etc.

If we pass this as a parameter %00250025% rule 920270 fires and sees a \x00 sequence (due to the t:urlDecodeUni). Looking into the code of modsecurity, this part causes the issue:

// msc_util.c

 if (i + 2 < input_len) {
                char c1 = input[i + 1];
                char c2 = input[i + 2];

                if (VALID_HEX(c1) && VALID_HEX(c2)) {
                    /* Valid encoding - decode it. */
                    *d++ = x2c(&input[i + 1]);
                    count++;
                    i += 3;
                    *changed = 1;

//

Of course, it is going to be a bit hard to work around this issue if you only have the string to look at. I was wondering if. I'm trying to find a good way to work around this issue, but I fail to see an opening except disabling the rule for certain request (with 942440, same issue). Or would replacing urlDecodeUni by utf8toUnicode a valid alternative?

**Comment by csanders-git** [comment]
Seems to be the same issue as https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/807
