### ISSUE TITLE
OWASP CRS 3.1 Feature Selection

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#829]
This ticket is designed to specify items from the 3.1 RC backlog (https://github.com/SpiderLabs/owasp-modsecurity-crs/milestone/4) and items of interest for developers for inclusion into CRS 3.1

**Comment by csanders-git** [comment]
- Rewrite support for CRS SQL detection [ @csanders-git ]

**Comment by franbuehler** [comment]
- Disassemble optimized regular expressions [ @franbuehler ]
