### ISSUE TITLE
False positive (941170, PL1)

### ISSUE THREAD

**Issue by quenenni** [SpiderLabs/owasp-modsecurity-crs#835]
Hello,

A request was blocked when sending an email from roundcube.
```
Rule Message: NoScript XSS InjectionChecker: Attribute Injection
```

But I don't want to post here the request as there are private infos in it.
Can I send somewhere the file for you to check where the problem is coming from?

Thanks

**Comment by dune73** [comment]
Thanks for reporting.

We do not need the full request, but the alert message with the private infos replaced with asterisks or something is the minimum.

**Comment by quenenni** [comment]
I can send you the full request, but not showing it here as there are mails adresses in it and it's a mail. 
The data modsec disliked is somewhere in the middle of all this. There are some special chars in the name associated with email adresses.
So I think it's better for you to have unchanged request.

Can I send you the request as a private msg?

**Comment by dune73** [comment]
Feel free to send it by mail to my address at netnea.

**Comment by dune73** [comment]
This is the minimal request triggering the rule in question:

```
$> curl curl localhost -d "test=Data%3A+%2C+Xxx%3E+%3Cxxxxxxxxx%40xxx.xx%3E" -
$> tail error.log
...
[2017-07-10 13:23:21.190812] [-:error] 127.0.0.1:39804 WWNjqX8AAQEAADQJ88sAAAAQ [client 127.0.0.1] ModSecurity: Warning. Pattern match "(?i)(?:\\\\W|^)(?:javascript:(?:[\\\\s\\\\S]+[=\\\\\\\\(\\\\[\\\\.<]|[\\\\s\\\\S]*?(?:\\\\bname\\\\b|\\\\[ux]\\\\d))|data:(?:(?:[a-z]\\\\w+\\\\/\\\\w[\\\\w+-]+\\\\w)?[;,]|[\\\\s\\\\S]*?;[\\\\s\\\\S]*?\\\\b(?:base64|charset=)|[\\\\s\\\\S]*?,[\\\\s\\\\S]*?<[\\\\s\\\\S]*?\\\\w[\\\\s\\\\S]*?>))|@\\\\W*?i\\\\W*?m\\\\W*?p\\\\W*? ..." at ARGS:test. [file "/home/dune73/data/git/crs-official/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf"] [line "300"] [id "941170"] [rev "3"] [msg "NoScript XSS InjectionChecker: Attribute Injection"] [data "Matched Data: Data: , Xxx> <xxxxxxxxx@xxx.xx> found within ARGS:test: Data: , Xxx> <xxxxxxxxx@xxx.xx>"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "1"] [accuracy "8"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-xss"] [tag "OWASP_CRS/WEB_ATTACK/XSS"] [tag "WASCTC/WASC-8"] [tag "WASCTC/WASC-22"] [tag "OWASP_TOP_10/A3"] [tag "OWASP_AppSensor/IE1"] [tag "CAPEC-242"] [hostname "localhost"] [uri "/"] [unique_id "WWNjqX8AAQEAADQJ88sAAAAQ"]
...
```

So this 
@quenni: Why have you not been able to reduce and submit this info here yourself?

**Comment by quenenni** [comment]
Because I wasn't sure what data exactly was causing the problem (usually, I do that).
Even after seeing your last post, I'm still not sure exactly what triggered this exception.

**Comment by dune73** [comment]
Something in that minimal payload. :) Actually, I think it takes the whole payload to trigger the fairly complex rule. I get the feeling it's a bit of bad luck. The `Data` at the start, issued by (roundcube), is very important, I think.

**Comment by quenenni** [comment]
Hmm.. Ok, now I understand better.
I tried myself to answer and forward mails from roundcube to my mail client.
The 'Data' in the message is 'Date' (as today's date) in Italian.
So for them, it will be pretty often to find 'data' there.
After that, is the chance to trigger the rest of the regular expr. high, I don't know. This expr is certainly not the easiest one to read.

I'll keep an eye on that problem.

Thanks a lot for having taken the time to help me.

**Comment by quenenni** [comment]
I think I identified the pattern that can trigger more often this rule:

* A mail client or webmail set in Italian (and all the others languages that translate 'Date' to 'Data'),
* Forward of a mail,
* If in the 'To:' field (or 'CC:', or even 'From:' I guess) from the original mail, you have a mail address formatted with a "real name" 
(ie: my name \<my.mail@blabla.org\>)

If you meet those 3 criteria, I think the expr will be often triggered.

I tried to keep only the part from the expr that was a match.
```
(?i)(?:data:(?:[\s\S]*?\b[\s\S]*?,[\s\S]*?<[\s\S]*?\w[\s\S]*?>))
(tested on https://regex101.com/)
```
If I didn't do any mistake, it shows how quickly this rule can be triggered in this situation.

On the other hand, the problem will only be in a webmail.
I think I'm going to disable it when using roundcube.
I'm not sure if this rule is important to keep in that context.

**Comment by dune73** [comment]
You are on the right track @quenenni. 

Generally, we want to avoid FPs at PL1, but this is highly special and unlikely to appear very often. We could create a roundcube rule exclusion package of course, but it ought to be a bit more than a single rule.

In the meantime, I think it is save to close this issue and hope nobody else bumps into 941170.
