### ISSUE TITLE
Setting Up Owasp crs rules Error creating rule: Failed to resolve operator: detectXSS on line 56

### ISSUE THREAD

**Issue by cruxster** [SpiderLabs/owasp-modsecurity-crs#836]
After adding Owasp crs rules restart apache giving this error in **REQUEST-941-APPLICATION-ATTACK-XSS.conf** file.

**AH00526: Syntax error on line 56 of /etc/apache2/modsecurity.d/rules/REQUEST-941-APPLICATION-ATTACK-XSS.conf:
Error creating rule: Failed to resolve operator: detectXSS
Action 'configtest' failed.
The Apache error log may have more information.**

Please help me to fix this issue

**Comment by dune73** [comment]
This sounds like you are using an old version of ModSecurity. detectXSS was introduced with 2.8.0.

**Comment by cruxster** [comment]
@dune73  i have installed updated version of Mod security 2.9.1 .but still problem exists.

**Comment by lifeforms** [comment]
@dune73 If you have compiled the package yourself, you need to compile it with the libinjection option. However this is default. Please check in Apache's error log if you are running the correct version now or if you might still have the old version running.

**Comment by dune73** [comment]
Unfortunately libinjection support is not advertised in the error log. But the ModSec version is.

But you can do strings on the library:

```
$> strings /apache/modules/mod_security2.so  | grep detect
detectiononly
Multipart: Invalid quoting detected: %s length %d bytes
Multipart: Invalid quoting detected: %s length %zu bytes
Invalid UTF-8 encoding: overlong character detected at %s. [offset "%d"]
detected SQLi using libinjection with fingerprint '%s'
detected XSS using libinjection.
IS_XSS: libinjection detected XSS.
detectSQLi
detectXSS
detect_utf8_character
msre_op_detectXSS_execute
msre_op_detectSQLi_execute
msre_op_detectSQLi_execute
msre_op_detectXSS_execute

```
