### ISSUE TITLE
Some rules use capture groups when it's not needed

### ISSUE THREAD

**Issue by fgsch** [SpiderLabs/owasp-modsecurity-crs#839]
It'd be nice if these are removed.

**Comment by dune73** [comment]
A PR would be highly welcome. Any takers?

**Comment by lifeforms** [comment]
I see a PR is in #838, let's discuss over there.

**Comment by dune73** [comment]
OK. Let's close this in favor of #838.

**Comment by fgsch** [comment]
I will continue this work via new PRs.
