### ISSUE TITLE
ID 921180/921170 won't ever fire?

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#846]
Once 921170 fires it will stop processing. Which means there will only ever be one paramcounter_ and it will only ever equal 1. so 921180 won't every fire.

SecRule ARGS_NAMES "." \
        "phase:request,\
        id:921170,\
        rev:'2',\
        ver:'OWASP_CRS/3.0.0',\
        pass,\
        nolog,\
        tag:'application-multi',\
        tag:'language-multi',\
        tag:'platform-multi',\
        tag:'attack-protocol',\
        tag:'paranoia-level/3',\
        tag:'CAPEC-460',\
        setvar:'TX.paramcounter_%{MATCHED_VAR_NAME}=+1'"

**Comment by YbyMMbPh** [comment]
At first appearances that would seem to be true, but when tested this rule works as intended.
I tested it with the request `http://theme.wamp/?a=1&a=2&a=3`
I edited 921170  to log and added a msg to it.
I set PL3
921170 fired 3 times.
921180 reported `[msg "HTTP Parameter Pollution (ARGS_NAMES:a)"]`
see log of this request.
[modsec_audit2.log.txt](https://github.com/SpiderLabs/owasp-modsecurity-crs/files/1256597/modsec_audit2.log.txt)

**Comment by csanders-git** [comment]
I'll add this too the unit tests and see if I can trigger it. Are you using NGINX, Apache or something else

**Comment by YbyMMbPh** [comment]
Not NGINX.
Producer: ModSecurity for Apache/2.9.2 (http://www.modsecurity.org/); OWASP_CRS/3.0.2.
Server: Apache/2.4.18 (Win32) PHP/5.6.19

**Comment by dune73** [comment]
Why would 921170 stop processing once it fires? That would be very odd.

Any luck with a unit test?

**Comment by fgsch** [comment]
This been open since 2017 without further comments. I think it's time to close it.
@dune73 ?

**Comment by dune73** [comment]
Closing this.
