### ISSUE TITLE
Rule ID 920430 won't ever fire

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#847]
In Apache it looks like even in Phase 1 we don't get access to the HTTP version if it is an unsupported one.

Request:
GET / HTTP/0.1
Host: localhost
user-agent: newpost
accept: true
Content-Length: 2

Expected Result:
Rule 920430 fires

Actual result:
400 Bad Request and ModSec doesn't fire rule.

**Comment by lifeforms** [comment]
A test case that triggers rule 920430 is `GET /`

This is HTTP 0.9, which is valid for Apache, but denied by us in CRS3 default config.

**Comment by lifeforms** [comment]
Closing this for now but if you disagree feel free to reopen :D

**Comment by csanders-git** [comment]
just gotta write a test that will trigger it
