### ISSUE TITLE
Rule 942100 false positive

### ISSUE THREAD

**Issue by ericwscott** [SpiderLabs/owasp-modsecurity-crs#854]
We are getting some valid input that is being flagged as SQL injection.  The particular input is a company name with an exclamation point and then an abbreviation in parenthesis also with the exclamation point.  For example: Yahoo! (Y!)

`
ModSecurity: Warning. detected SQLi using libinjection with fingerprint 'no(no' [file "C:\/Program Files/ModSecurity IIS/modsecurity_crs/owasp-modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "68"] [id "942100"] [rev "1"] [msg "SQL Injection Attack Detected via libinjection"] [data "Matched Data: no(no found within ARGS:OrganizationName: Yahoo! (Y!)"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "1"] [accuracy "8"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-sqli"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"] [tag "WASCTC/WASC-19"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/CIE1"] [tag "PCI/6.5.2"]
`

Any idea how to work around this without disabling rule 942100?  I don't want to white list specific arguments because this data is included in a large number of arguments throughout the application.  I would rather white list this specific libinjection fingerprint, but can't find any documentation on how to do it.

**Comment by csanders-git** [comment]
You could make a rule that changes the CTL of the enforcement of that rule for that parameter ONLY if it matches a regex for \(Y\!\).

**Comment by dune73** [comment]
It's a false positive within libinjection (-> https://github.com/client9/libinjection, CC: @client9). There is nothing we can do for you within CRS.

I think Chaim's proposal is probably the best path. Even if it's not very elegant.

**Comment by ericwscott** [comment]
Thank you.

**Comment by dune73** [comment]
You're welcome. And sorry there is very little we can do.

**Comment by csanders-git** [comment]
@ericwscott this would like something like the following
SecRule ARGS:OrganizationName "@rx ^Yahoo! \(Y!\)$ "id:123,phase:request,t:none,pass,nolog,ctl:ruleRemoveTargetById=942100;ARGS:OrganizationName"
