### ISSUE TITLE
Rule 218500 False positives

### ISSUE THREAD

**Issue by stephywells** [SpiderLabs/owasp-modsecurity-crs#856]
I am the lead developer of a WordPress plugin called Formidable Forms.
https://wordpress.org/plugins/formidable/

I've been working with our users who are having trouble with this rule, but have been unable to get version details. However, this issue recently started popping up in the last month.

This is the line I've narrowed the issued down to:
`<div>[if error][/if error]</div>`

Is there something we can do other than ask for hosts to disable this rule?

**Comment by dune73** [comment]
Hi @stephywells, sorry for the late response. And thank you for letting us know about these issue.

There is a lot that you can do to help us make this issue disappear.

When I submit the payload you mention, CRS 3.0.2 triggers the following rules in the highest paranoia setting.

<pre>
920273 PL4 Invalid character in request (outside of very strict set)
920273 PL4 Invalid character in request (outside of very strict set)
941320 PL2 Possible XSS Attack Detected - HTML Tag Handler
942431 PL3 Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (6)
942432 PL4 Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (2)
</pre>

Of these, only 941320 at paranoia level 2 is really relevant.

Could you please confirm that 941320 is the problem? This information is part of the alert message, likely in the error log of the webserver / reverse proxy / waf.

Once confirmed, we need context, so we can write a rule exclusion. Given you are working on WordPress, we can introduce this exclusion into our package of optional WordPress rule exclusions and the false positive will be gone from future CRS versions.

**Comment by YbyMMbPh** [comment]
Hello Stephy,
218500 is a Comodo rule id number.
This rule number is present in Comodo current version rule_set=1.135 as well as many previous versions.
The ruleset in this GitHub repository is the OWASP CRS 3 rule set.
Note: It is a different rule set.

I assume that to be pragmatic you are willing to change your plugin's requests to be able to pass through this rule.

218500 resides in the 24_SQL_SQLi.conf file.
When I pass the string...
`<div>[if error][/if error]</div>`
through the regex of rule 218500 the first match is for the partial string...
`or]</`
So by misspelling the word error (to errer) your string would pass through this rule.
In my test this misspelling was a non-match for the regex.

Also note: I used RegexBuddy to test this, using PCRE 8.40 UTF8.
This setting showed syntax errors in the regex of rule id 218500.
2 unescaped # characters and 1 wrongly escaped [\0-9a-h]
I escaped the 2 # characters and deleted the backslash in [\0-9a-h] before I could run the test.
So my test may not match reality.

**Comment by YbyMMbPh** [comment]
I ran a more realistic test. on a test system with...
Apache 2.4.18
Modsecurity 2.9.2
Comodo Rule Set version 1.135 (downloaded today)

The test request was `http://domain.com/test.php?abc=<div>[error][/error]</div>`
This hit rule 218500 generating the following audit_log data...
`Message: Access denied with code 403 (phase 2)`
`...`
`[id "218500"] [rev "7"] `
`[msg "COMODO WAF: SQLmap attack detected||domain.com|F|2"] `
`[data "Matched Data: or]</div> found within ARGS:abc: <div>[error][/error]</div>"]`
Note: the Matched Data value `or]</div>`

I then ran the request `http://domain.com/test.php?abc=<div>[errer][/errer]</div>`
and it passed through without issue.

This confirms what I suggested in my previous post, and may help guide you to a working solution.

**Comment by csanders-git** [comment]
@YbyMMbPh thanks for the invaluable feedback.

**Comment by stephywells** [comment]
Thank you @YbyMMbPh ! 

It doesn't look like that repo is active. https://github.com/sliqua-hosting/modsecurity/issues

@csanders-git, @dune73  would it be best if I open an issue there instead? Does this appear to be out of your hands?

**Comment by lifeforms** [comment]
It might still be our rule firing. I'm still very interested in the full error from the ModSecurity audit log...

**Comment by YbyMMbPh** [comment]
Hello Stephy, the repo you linked to is a single web host's (Sliqua Hosting) personally curated version of the Comodo rule set.
If you want to pursue a change to Comodo's main rule set then the place to start would be at their forum. It does appear to be monitored by the devs who maintain the rule set. You can find it [here](https://forums.comodo.com/free-modsecurity-rules-comodo-web-application-firewall-b223.0/).
To manage your expectations...
Many hosts do not auto update their Rules. This is due to the fear that a new rule may cause 1000s of support requests. So if you succeed in getting Comodo to change their rule to allow your string to pass it may take years for it to become active on all web hosts with Comodo rules.
Changing you own code could fix this for all your plugin's users in a week.
As lifeforms commented the modsec_audit.log of  http request that caused the False Positive is the starting point for someone to edit an existing rule or to create an exclusion rule to deal with the false positive. If you can get it please post it here as well as at Comodo's forum.

**Comment by csanders-git** [comment]
Seems like we have a pretty good consensus on this topic. If you have any additional questions or feedback, please feel free to reopen this topic.
