### ISSUE TITLE
Standard for spacing/tabs whitespace in rules?

### ISSUE THREAD

**Issue by fzipi** [SpiderLabs/owasp-modsecurity-crs#857]
Hi,

I'm trying to commit the rules to my own git, and there are many (issues with)different spacing/tabs/etc on multiple files.

Maybe trailing whitespace should be ignored for '*.data' files, but there are many other files have some issues like mixed spaces and tabs (space before tab in indent.), blank lines at EOF, etc.

Is there any standard for rule indenting?

Felipe.

**Comment by dune73** [comment]
Thank you for reporting @fzipi. We know about these shortcomings and there is currently a seperate project under way to fix this. Could you add your findings to the issue #808?

I a closing this in favour of said issue.
