### ISSUE TITLE
941160 FP - WordPress editor add media add image

### ISSUE THREAD

**Issue by YbyMMbPh** [SpiderLabs/owasp-modsecurity-crs#860]
As the title says, using WordPress version 4.8.1 and CRS-302-dev
If the user edits a page or post and uses the "Add Media" button to open the "Insert Media" frame, then selects an image, then clicks the "Insert into page" button. (standard insert image procedure)
then the resulting POST request triggers rule id 941160, blocking the request and causing the Image Insertion to fail.
This is at PL1.
Here is the log for this FP hit.
[modsec_audit.log.txt](https://github.com/SpiderLabs/owasp-modsecurity-crs/files/1255214/modsec_audit.log.txt)

I will attach a txt file with an exclusion rule for this False Positive.
[wp-941160-fp-add-image-from-editor.txt](https://github.com/SpiderLabs/owasp-modsecurity-crs/files/1255222/wp-941160-fp-add-image-from-editor.txt)

**Comment by csanders-git** [comment]
Thanks @YbyMMbPh, this is something we'll look into fixing. I want to verify that you have the Wordpress exclusions enabled.

**Comment by YbyMMbPh** [comment]
I can confirm that I do have the WordPress exclusions enabled.
I just double checked then re-ran the test.
The results were the same.

**Comment by lifeforms** [comment]
Thanks, I will look into this.

**Comment by darkkean** [comment]
@lifeforms any update regarding your investigation on this issue?

**Comment by lifeforms** [comment]
@darkkean Oops. Thanks for the ping. I will look at this in time for the 3.1 release cycle.

**Comment by lifeforms** [comment]
Thanks for the submission!

I created a PR in #1101 with small changes. Most notably, I changed the exclusion to `ctl:ruleRemoveTargetByTag=CRS`, so that the whole CRS is disabled on the content field `ARGS:html`. This ensures that the request also succeeds at higher Paranoia Level settings.

**Comment by msassmann** [comment]
When using WP 5.2.1 Rule 941160 is causing a false positive again. Wordpress Exceptions are enabled, using OWASP 3.1.
[modsec_audit.log](https://github.com/SpiderLabs/owasp-modsecurity-crs/files/3288190/modsec_audit.log)

**Comment by lifeforms** [comment]
@msassmann Hi Mario, would it be possible for you to open a new issue for this? This issue is closed already, so it's hard for us to keep track. I'm thinking you might have hit a bug in ModSec3, but it's hard to say right now. We should investigate further. Thanks in advance!
