### ISSUE TITLE
Checking out for nightly builds

### ISSUE THREAD

**Issue by willt** [SpiderLabs/owasp-modsecurity-crs#861]
Whats the best way to get checkout for nightly builds?
I plan on doing a nightly rpm build of rulesets  (if they changed) 
Do tags get updates? Should I be checking out tag 3.0.2 ?

**Comment by csanders-git** [comment]
Sorry for the slow reply, somehow this slipped through. Generally nightly builds for the current release are in the v3.0/dev branch (https://github.com/SpiderLabs/owasp-modsecurity-crs/tree/v3.0/dev).
