### ISSUE TITLE
Using numbers in rules for phases instead of names (Rule Cleanup)

### ISSUE THREAD

**Issue by fzipi** [SpiderLabs/owasp-modsecurity-crs#862]
From issue #859 by @victorhora:

Using phase numbers is actually easier for new users as all the examples from the reference manual, handbook and other sources use numbers. As there are only phase names for phases 2 ("request"), 4 ("response") and 5 ("logging") so with any rules that would be on phases 1 and 3 it would potentially confuse the user and in the end he would need to refer to the reference manual to understand why some rules have names on the phases and others don't.

Additionally, I think the names as they are now could confuse the user. One might think that "request" is for phase 1 but it is actually for phase 2 and I wouldn't be surprised if we have rules that are meant or could be inspected on a earlier phase but aren't because of the tricky phase names.

A quick look on the rules showed that we currently have a mix of both:

Rules that specify phase 1: 139
Rules that specify phase 2: 125
Rules that specify phase 3: 24
Rules that specify phase 4: 35
Rules that specify phase 5: 11

Rules that specify phase "request": 178
Rules that specify phase "response": 22
Rules that specify phase "logging": 5

So, I suggest we stick with numbers for new rules and maybe do a plan to change current rules back to numbers as well :)

**Comment by dune73** [comment]
I'm all for going with numbers. 

Troubling fact: there used to be a time where phase:1 and phase:3 were meant to disappear / be merged with phase:2 and phase:4. That was the time where the three phase names were introduced. But the two moribund phases did not get an name of their own.

Later the two phases were resurrected but no name was applied. The names are thus handicapped and numbers the preferred way to assign a phase to a rule. At least in my opinion.

**Comment by fzipi** [comment]
Well, PR #871 solves this one.

**Comment by victorhora** [comment]
Thanks for sharing that piece of ModSec history here @dune73. I honestly had no idea why we only have names for a few phases :)

Well that said, I think it would be fine to make a PR for ModSecurity to add phase names to all the phases, but then deciding on a name, pushing PRs for both v2 and v3 and then still not being able to use phase names on the CRS (backwards compatibility) tells we should indeed stick with numbers :)

Nice PR @fzipi :)

**Comment by dune73** [comment]
Initiating the merge of the two phases was one of the last things Ivan did for ModSec when he got fed up with people trying to access ARGS/ARGS_POST in phase:1. Ryan reinstated phase:1 to the former hook in 2.7.0 or so. It was a bit of a controversy back in the day. 

Honestly, I would have preferred for ModSec to refuse to run with ARGS/ARGS_POST in phase:1 and be done with it.

But nevermind, let's close this in favor of #871.
