### ISSUE TITLE
Getting page blocked under Anomaly score 

### ISSUE THREAD

**Issue by credhats** [SpiderLabs/owasp-modsecurity-crs#865]

**Comment by credhats** [comment]
logs shows ModSecurity: Access denied with code %d (phase 2). Matched "Operator `Ge' with parameter `%{tx.inbound_anomaly_score_threshold}' against variable `TX:ANOMALY_SCORE' (Value: `15' ) [file "/usr/local/owasp-modsecurity-crs-3.0.0/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "36"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 15)"] [data ""] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [hostname "x.x.x.x"] [uri "/"] [unique_id "150458832236.493207"] [ref ""], client:x.x.x.x, server: x.x.x.x, request: "GET /?param=%22%3E%3Cscript%3Ealert(1);%3C/script%3E HTTP/1.1", host: "x.x.x.x" 2017/09/05 01:12:02 [warn] 2617#2617: *2 [client x:x:x:x] ModSecurity: Access denied with code 403 (phase 2). Matched "Operator `Ge' with parameter `%{tx.inbound_anomaly_score_threshold}' against variable `TX:ANOMALY_SCORE' (Value: `15' ) [file "/usr/local/owasp-modsecurity-crs-3.0.0/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "36"] [id "949110"] [rev ""] [msg "Inbound Anomaly Score Exceeded (Total Score: 15)"] [data ""] [severity "2"] [ver ""] [maturity "0"] [accuracy "0"] [hostname "x:x:x:x"] [uri "/"] [unique_id "150458832236.493207"] [ref ""], client: xxxx, server:xxx

**Comment by spartantri** [comment]
Hi, why do you want to let this pass %22%3E%3Cscript%3Ealert(1);%3C/script%3E ? 
It is perfectly normal to have it blocked, if your question is what anomaly score exceeded means, then there are many rules that do not block immediately the transaction but increase multiple anomaly risk scores and then a rule that checks the scores to be greater or equal than the threshold will block it.

You can play with the scores and the thresholds to let a little room for your normal but weird web site stuff to work so it is more forgiving and if it gets to a score higher that what you would expect to be normal for your site then it will block the request.

**Comment by dune73** [comment]
Thanks @spartantri.

@credhats: I agree with spartantri. If you have more to add then please reopen this issue.
