### ISSUE TITLE
ModSecurity: Found another rule with the same id:2008938

### ISSUE THREAD

**Issue by AMKpeacemaker** [SpiderLabs/owasp-modsecurity-crs#875]
> AH00526: Syntax error on line 32 of /etc/modsecurity/modsecurity_crs_46_slr_et_phpbb_attacks.conf:
> ModSecurity: Found another rule with the same id
> 
> grep "id:2008938" *.*
> modsecurity_crs_46_slr_et_lfi_attacks.conf:SecRule REQUEST_LINE "@contains /include/global.php" "chain,phase:2,block,t:none,t:urlDecodeUni,t:htmlEntityDecode,t:normalisePathWin,capture,logdata:'%{TX.0}',severity:'2',id:2008938,rev:3,msg:'SLR: ET WEB_SPECIFIC_APPS Multi SEO phpBB pfad parameter local file inclusion',tag:'web-application-attack'"
> modsecurity_crs_46_slr_et_phpbb_attacks.conf:SecRule REQUEST_LINE "@contains /include/global.php" "chain,phase:2,block,t:none,t:urlDecodeUni,t:htmlEntityDecode,t:normalisePathWin,capture,logdata:'%{TX.0}',severity:'2',id:2008938,rev:3,msg:'SLR: ET WEB_SPECIFIC_APPS Multi SEO phpBB pfad parameter local file inclusion',tag:'web-application-attack'"
> modsecurity_crs_46_slr_et_rfi_attacks.conf:SecRule REQUEST_LINE "@contains /include/global.php" "chain,phase:2,block,t:none,t:urlDecodeUni,t:htmlEntityDecode,t:normalisePathWin,capture,logdata:'%{TX.0}',severity:'2',id:2008938,rev:3,msg:'SLR: ET WEB_SPECIFIC_APPS Multi SEO phpBB pfad parameter local file inclusion',tag:'web-application-attack'"

I´m kind of new to owasp-modsec-crs, so I have to apologize in advance if this is caused by my configuration and this "error" is already known. 
I added most of the your rules to my config to test them out, but I can´t start my apache2 because of this. Do I have to choose between lfi_attacks.conf, rfi_attacks.conf and phpbb.conf ?

kind regards
AMKpeacemaker

**Comment by dune73** [comment]
Hi @AMKpeacemaker,

This is an old version of CRS (-> CRS2). Given you are new an no constraints exist, please upgrade to CRS3 and get rid of this - and many other problems.

Regs,

Christian Folini

**Comment by AMKpeacemaker** [comment]
Thanks for your reply,
I wasn´t aware of using an old version.

Sorry for not realizing it by myself and the inconvenience

kind regards
AMKpeacemaker

**Comment by dune73** [comment]
No worries, mate. Glad to help. Please don't wait to report back when you encounter problems with CRS3.
