### ISSUE TITLE
content-types and body inspections bypasses

### ISSUE THREAD

**Issue by spartantri** [SpiderLabs/owasp-modsecurity-crs#883]
Check there is a body processor and body inspection whenever possible and when multipart body processor is in use the parts of the request may have different types of content which can be used for by passing eg xss inside xml file in a multipart post, the crs will inspect only the multipart and check no body processor errors exist but the xml structure is not validated as it is when application/xml is used, plus all other contents as well will skip CRS checks.
Modsec do not support multipart multi processors so it will be interesting to get a workaround to iterate through the parts and perform the appropriate checks

**Comment by csanders-git** [comment]
most of the processing body checks are provided as part of ModSecurity, if we can figure out a solution, it might make sense to add it over there.

**Comment by spartantri** [comment]
this is a modsecurity missing feature, so it maybe better to close this and add an issue under their github as the CRS can't do much without falling for very expensive checks or modsec source code changes.
