### ISSUE TITLE
Problem in rules 920190 and 943110

### ISSUE THREAD

**Issue by spartantri** [SpiderLabs/owasp-modsecurity-crs#895]
The #882 issue affects 920190 and 943110 as  well
920190 is for Range and Request-Range headers, if repeated only the first occurrence is inspected
943110 is for session fixation if Referer header is repeated only the first occurrence is inspected

Is there a valid reason to accept duplicated request headers? If so, which ones (maybe cookies)? Should we add a check for that at least in PL4, like a clone of 921170 but using REQUEST_HEADERS instead of ARGS_NAMES?

**Comment by fzipi** [comment]
I can confirm that these two rules are affected by that same ass #882 issue. Sorry about the delay.

**Comment by spartantri** [comment]
This problem could be fixed by adding REQUEST_HEADERS_NAMES to 921170 so duplicate headers are identified as HPP, what do you think? @csanders-git @fzipi @dune73

**Comment by dune73** [comment]
I am not really familiar with this issue, but multiple request headers of the same name is not really forbidden as far as I can see. Interpreting this as HPP at PL3 still sounds reasonable.

Where I have seen this in the past, I think, was overlong cookie headers being split. But I might be mistaken. Ideally you check if that is known and if yes, you do exclude the Cookie header.

Thank you for the initiative to close this (and many other) issues. Way to go.
