### ISSUE TITLE
POST  arrays trigger Pattern match "TX:paramcounter_(.*)" at TX:paramcounter_ARGS_NAMES:..

### ISSUE THREAD

**Issue by WebSabaki** [SpiderLabs/owasp-modsecurity-crs#902]
Good morning.

When trying to submit an array such as (so giving permission 1 and 2 to a user):
> csrf_token_name	"b7fc0fbbba854080c83d74d094f83a03"
> permissions[]	[2]
> 0	"1"
> 1	"2"

owasp rules trigger the following error

Message: Warning. Pattern match "TX:paramcounter_(.*)" at TX:paramcounter_ARGS_NAMES:permissions[]. [file "/etc/modsecurity/owasp-modsecurity-crs/rules/REQUEST-921-PROTOCOL-ATTACK.conf"] [line "340"] [id "921180"] [rev "2"] [msg "HTTP Parameter Pollution (ARGS_NAMES:permissions[])"] [data "Matched Data: TX:paramcounter_ARGS_NAMES:permissions[] found within TX:paramcounter_ARGS_NAMES:permissions[]: TX:paramcounter_ARGS_NAMES:permissions[]"] [severity "CRITICAL"] [ver "OWASP_CRS/3.0.0"] [maturity "7"] [accuracy "8"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-protocol"] [tag "paranoia-level/3"] [tag "CAPEC-460"]
Message: Warning. Pattern match "((?:[\\~\\!\\@\\#\\$\\%\\^\\&\\*\\(\\)\\-\\+\\=\\{\\}\\[\\]\\|\\:\\;\"\\'\\\xc2\xb4\\\xe2\x80\x99\\\xe2\x80\x98\\`\\<\\>][^\\~\\!\\@\\#\\$\\%\\^\\&\\*\\(\\)\\-\\+\\=\\{\\}\\[\\]\\|\\:\\;\"\\'\\\xc2\xb4\\\xe2\x80\x99\\\xe2\x80\x98\\`\\<\\>]*?){2})" at ARGS_NAMES:permissions[]. [file "/etc/modsecurity/owasp-modsecurity-crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"] [line "1325"] [id "942432"] [rev "2"] [msg "Restricted SQL Character Anomaly Detection (args): # of special characters exceeded (2)"] [data "Matched Data: [] found within ARGS_NAMES:permissions[]: permissions[]"] [severity "WARNING"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "8"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-sqli"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"] [tag "WASCTC/WASC-19"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/CIE1"] [tag "PCI/6.5.2"] [tag "paranoia-level/4"]

**Comment by dune73** [comment]
Thanks for reporting @WebSabaki.

It is likely this is triggered via the way ModSecurity (and our rules) handles post parameter arrays. It all boils down to looking like a parameter pollution from the perspective of rule 921180.

The only way around I see is creating a rule exclusion for this parameter array. 

Given this rule runs in PL3, you need to handle false positives for your setup. So this is annoying behaviour is kind of expected.

It might be worthwhile to add a remark about post parameter arrays into the comments of the pair 921170 / 921180. Opinions?

**Comment by WebSabaki** [comment]
I am not really familiar with 921180 so I will check into it.

For now, I asked for an update of the software to go without array-ed POST and it works fine. Still I will look at that

**Comment by dune73** [comment]
921170/80 are quite advanced. If you are able to understand how they work, then you have mastered ModSec to a very wide extent. :)
Otherwise, when you have a working solution that does away with the FP, then that's even better. :)
