### ISSUE TITLE
New malign User-Agent

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#904]
Just saw the following UA the first time for real.

We should add it to our list:

```
struts-pwn (https://github.com/mazen160/struts-pwn)
```

Heads-up to to @mazen160 for using a distinct UA for his scanner by default. Thank you man!

**Comment by mazen160** [comment]
Thanks @dune73!
Probably the string `struts-pwn` should be added to the `owasp-modsecurity-crs/rules/scanners-user-agents.data`

It's probably the third time to see it used in the public :)

**Comment by dune73** [comment]
Exactly my thinking.

I saw it used by an IP in Thailand. Can't tell you about the service unfortunately.

**Comment by mazen160** [comment]
I saw it in:
https://www.google.com/search?q=intext:"struts-pwn"+user-agent
It seems to be quite used a lot in mass-scans.

Also:
https://github.com/mazen160/struts-pwn/issues/4

**Comment by dune73** [comment]
Cool. Thanks. Looking fwd to see you in three weeks!

**Comment by mazen160** [comment]
Me too! :)
I will let you know how the process is going tomorrow

**Comment by spartantri** [comment]
Added to scanners-user-agents.data
