### ISSUE TITLE
DOS rule not work

### ISSUE THREAD

**Issue by 365moods** [SpiderLabs/owasp-modsecurity-crs#906]
**The DOS rule don't work and other rules(SQLI) are used normally
Verison:
ModSec branch: v3/master
ModSec-Nginx branch: master
owasp-modsecurity-crs branch: v3.0/master
Nginx: 1.12.0**

**Include rules**:
Include crs-setup.conf
Include rules/REQUEST-912-DOS-PROTECTION.conf
Include rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf

any idea? :-(

**Comment by dune73** [comment]
Thank you for reporting @365moods and thank you for providing all the details about your versions.

In order to assess this problem, we will need you exact setting of the following variables (disabled by default)

```
#  setvar:'tx.dos_burst_time_slice=60',\
#  setvar:'tx.dos_counter_threshold=100',\
#  setvar:'tx.dos_block_timeout=600'"
```

And the complete event / error log of the attack / test run.

**Comment by 365moods** [comment]
@dune73 

**SecAction \\
 "id:900700,\\
  phase:1,\\
  nolog,\\
  pass,\\
  t:none,\\
  setvar:'tx.dos_burst_time_slice=60',\\
  setvar:'tx.dos_counter_threshold=100',\\
  setvar:'tx.dos_block_timeout=600'"**

**Comment by 365moods** [comment]
@dune73 these variables are always set

**Comment by 365moods** [comment]
@dune73 help me

**Comment by 365moods** [comment]
@dune73 

In file REQUEST-942-APPLICATION-ATTACK-SQLI.conf, the following configuration is added ( SecRule REQUEST_BASENAME  ):

`
 
       "phase:5,\
        id:912150,\
        t:none,\
        t:lowercase,\
        log,\
        pass,\
        tag:'application-multi',\
        tag:'language-multi',\
        tag:'platform-multi',\
        tag:'attack-dos',\
        msg: '%{ip.dos_counter}',\
        capture,\
        setvar:tx.extension=/%{TX.1}/,\
        chain"
        SecRule TX:EXTENSION "!@within %{tx.static_extensions}" \
                "setvar:ip.dos_counter=+1"`

add msg option and following log details:
[file "owasp-modsecurity-crs-3.0-master/rules/REQUEST-912-DOS-PROTECTION.conf"] [line "146"] [id "912150"] [rev ""] **[msg ""]** [data ""] [severity "0"] [ver ""] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-dos"] [ref "o0,9o5,4v5,9t:lowercase"]

msg options is empty!!

**Comment by spartantri** [comment]
Hi @365moods , DOS won't work if the ip collection is not initiallized and that happens in `REQUEST-901-INITIALIZATION.conf` look for `initcol:ip` once the ip collection is initiallized then the counters may be tracked.

The counters are handled by the unique combination of ip and user agent hash, notice that this method is not perfect and the effectiveness would depend on consistency of those values, if you change the user agent with every request this will not be effective and you will have a potential problem with growing collections (I think it is 1008bytes per record), on the other hand if your clients are behind a NAT every client using the same user agent will affect adversely your counters and will hit the thresholds very fast and block the entire source network behind NAT (this happends also in some load balancer setups).

Use the conf as base but keep care to tailor it to your infra properly.

To see all the magic happening in the back, play with the debug level.

Have fun! Cheers!

**Comment by 365moods** [comment]
Hi @spartantri Get, Thank you so much~~

But, when configure `REQUEST-901-INITIALIZATION.conf`, i get fault msg:
```
kernel: nginx[425]: segfault at 7f98e4e69000 ip 00007f98e932da86 sp 00007fffc2641118 error 7 in libc-2.12.so[7f98e92a4000+18a000]
kernel: nginx[422]: segfault at 7f98e4e69000 ip 00007f98e932da86 sp 00007fffc2641118 error 7 in libc-2.12.so[7f98e92a4000+18a000]
kernel: nginx[423]: segfault at 7f98e4e69000 ip 00007f98e932da86 sp 00007fffc2641118 error 7 in libc-2.12.so[7f98e92a4000+18a000]
kernel: nginx[433]: segfault at 7f98e4e69000 ip 00007f98e932da86 sp 00007fffc26411c8 error 7 in libc-2.12.so[7f98e92a4000+18a000]
kernel: nginx[434]: segfault at 6a87000 ip 00007f98e932da48 sp 00007fffc26411c8 error 6 in libc-2.12.so[7f98e92a4000+18a000]
kernel: nginx[435]: segfault at 6a87000 ip 00007f98e932da48 sp 00007fffc26411c8 error 6 in libc-2.12.so[7f98e92a4000+18a000]
kernel: nginx[432]: segfault at 7f98e4e69000 ip 00007f98e932da86 sp 00007fffc2641208 error 7 in libc-2.12.so[7f98e92a4000+18a000]
kernel: nginx[441]: segfault at 7f98e1be8000 ip 00007f98e932da86 sp 00007fffc2641208 error 6 in libc-2.12.so[7f98e92a4000+18a000]
kernel: nginx[379]: segfault at 0 ip 000000000042af88 sp 00007fffc26415f8 error 6 in nginx[400000+16a000]
kernel: nginx[442]: segfault at 84d3518 ip 00007f98e931dafd sp 00007fffc26410d0 error 6 in libc-2.12.so[7f98e92a4000+18a000]
kernel: nginx[443]: segfault at 7f98e4e69000 ip 00007f98e932da86 sp 00007fffc26411a8 error 7 in libc-2.12.so[7f98e92a4000+18a000]
kernel: nginx[440]: segfault at 7f98e4e69000 ip 00007f98e932da86 sp 00007fffc2641208 error 7 in libc-2.12.so[7f98e92a4000+18a000]

```

**Comment by dune73** [comment]
Oops. Sorry for these problems @365moods. Nginx is not 100% stable with ModSecurity 2.x. The situation is improving with libmodsecurity 3.x which has been released as a preview. You should try out that.
Given it's a ModSec segfault issue, I am closing this as a CRS bug.

**Comment by spartantri** [comment]
Oops, I use little to no ngnix so I cannot help you much there but have you checked if the [data dir](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecDataDir) is writable for the webserver process and properly configured somewhere at server level?
`SecDataDir /path/to/di`r
