### ISSUE TITLE
Missing space before /I in 932140?

### ISSUE THREAD

**Issue by fgsch** [SpiderLabs/owasp-modsecurity-crs#911]
#738 addressed the FPs by adding a whitespace after the if but not before /I.

Should this:

```
"@rx \b(?:if(?:/i)?(?: not)?(?: exist\b| defined\b| errorlevel\b| cmdextversion\b|(?: |\().*(?:\bgeq\b|\bequ\b|\bneq\b|\bleq\b|\bgtr\b|\blss\b|==))|for(/[dflr].*)* %+[^ ]+ in\(.*\)\s?do)"
```

Be:

```
"@rx \b(?:if(?: /i)?(?: not)?(?: exist\b| defined\b| errorlevel\b| cmdextversion\b|(?: |\().*(?:\bgeq\b|\bequ\b|\bneq\b|\bleq\b|\bgtr\b|\blss\b|==))|for(/[dflr].*)* %+[^ ]+ in\(.*\)\s?do)"
```

@lifeforms ?

**Comment by dune73** [comment]
You mean before `/i` (not `/l`)? Stupid question, I know.

**Comment by marcstern** [comment]
spaces are optional in cmd.exe =>" */i"

**Comment by fgsch** [comment]
@dune73 yes, /i (or /I for the uppercase variant).
@marcstern you are right. Plus the cmdLine transformation removes the spaces before /.
