### ISSUE TITLE
Add notes on alert triggers / triggering payloads to comments of all the rules

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#918]
This is the target issue for the DINACon Hacknight on Friday October 20, 2017.

https://twitter.com/CoreRuleSet/status/919138876819759107

Use this issue for communication.

**Comment by spartantri** [comment]
What this is about? is it about explaining every rule or adding a curl command which will trigger the rule?

**Comment by dune73** [comment]
Basically yes. Might take a while though and the format is not clear at all. But once we have the FTW with the unit tests, a simple curl variant would be neat.

**Comment by fgsch** [comment]
Is there anything actionable on this issue or should be closed?

**Comment by dune73** [comment]
It is a separate sub-project, but I still think this would be very beneficial.

But you could argue that our test coverage is good enough and that we do not need this in the comments of the rules.

Opinions?
