### ISSUE TITLE
test 930120-2 failure for modesecurity 2.9.1

### ISSUE THREAD

**Issue by azhao155** [SpiderLabs/owasp-modsecurity-crs#919]
Hi
I am using nginx 1.11.5 and modsecurity 2.9.1 for testing, it's supposed to be 100% passing, but I did see some failure, here is one case:
Test case:930120-2
Test failed due to nothing printed in the error.log, I have configure the modesecurity as in the README,
looked into detail, this rule is find any requests have the symbol defined in the lfi-os-files.data and block it , the request in the test has /etc/passwd, it should be a valid one but it seems to be modsecurity didn't do anything, do you see the same issue? We do want to use this regression test as the effectiveness testing tool and try to resolve all the failure, thanks in advance

**Comment by dune73** [comment]
Sorry about your problems, @azhao155. 

I am not sure what test case you are referring too. Could you please tell me where `Test case:930120-2` is defined?

**Comment by azhao155** [comment]
Thanks for replying so quick 
the detail of the test is as following:

    test_title: 930120-2
    desc: Remote File Access Attempt (930120) from old modsec regressions
    stages:
    -
      stage:
        input:
          dest_addr: 10.0.5.4
          headers:
            Accept: image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, application/vnd.ms-excel,
              application/vnd.ms-powerpoint, application/msword, application/x-shockwave-flash,
              */*
            Accept-Encoding: gzip, deflate
            Accept-Language: zh-sg
            Content-Type: application/x-www-form-urlencoded
            Host: localhost
            Keep-Alive: '300'
            Proxy-Connection: keep-alive
            User-Agent: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)
          method: GET
          port: 12701
          uri: /index.php?file=News&op=/etc/passwd%00
          version: HTTP/1.1
        output:
          log_contains: id "930120"


and it's trying to trigger the rule 930120: which is as following:

SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "@pmf lfi-os-files.data" \
        "phase:request,\
        msg:'OS File Access Attempt',\
        rev:'4',\
        ver:'OWASP_CRS/3.0.0',\
        maturity:'9',\
        accuracy:'9',\
        capture,\
        t:none,t:utf8toUnicode,t:urlDecodeUni,t:normalizePathWin,t:lowercase,\
        block,\
        id:930120,\
        tag:'application-multi',\
        tag:'language-multi',\
        tag:'platform-multi',\
        tag:'attack-lfi',\
        tag:'OWASP_CRS/WEB_ATTACK/FILE_INJECTION',\
        tag:'WASCTC/WASC-33',\
        tag:'OWASP_TOP_10/A4',\
        tag:'PCI/6.5.4',\
        logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',\
        severity:'CRITICAL',\
        setvar:'tx.msg=%{rule.msg}',\
        setvar:tx.lfi_score=+%{tx.critical_anomaly_score},\
        setvar:tx.anomaly_score=+%{tx.critical_anomaly_score},\
        setvar:tx.%{rule.id}-OWASP_CRS/WEB_ATTACK/FILE_INJECTION-%{matched_var_name}=%{tx.0}"


Thanks

Yanshu

**Comment by dune73** [comment]
Thank you. I'll look into it.

**Comment by dune73** [comment]
Sorry for not acting on this.

We have some strange behaviours on NGINX that let a few dozen tests fail. I presume this falls into the same category.

We are also upgrading our Travis installation to cover all platforms. So we would discover problems as this in the future.

I'm therefore closing this (and we are currently axing old issues that went stale).
