### ISSUE TITLE
For discussion: Add CVEs and CWEs tags for all rules where appropriate?

### ISSUE THREAD

**Issue by fgsch** [SpiderLabs/owasp-modsecurity-crs#924]
It'd be great if all the rules that have CVEs and CWEs have them listed under their tags, and we agreed what format they should have (e.g. just the C[VW]E id, `C[VW]E-XXXX-YYYY`, the url to the C[VW]E, etc)

What do you guys think?

**Comment by dune73** [comment]
We have had this idea, that the whole tagging should be reviewed, reorganised and streamlined. This proposal is in line with this idea from my point of view and I would welcome this a lot.

**Comment by dune73** [comment]
We talked about this for a great length during the chat. Here are the important bits:

* The tagging used in CRS is not systematic. We would like to streamline it.
* Tags eat up space in the alert message and can be cut when the alert message is made to fit the Apache error.log line length. The less tags, the better. Everybody agreed on this.
* Many rules use WASC taxonomy, but that's probably dead.
* CVE might be fun, but the way the users and the project works and how CVEs hit the news, we'll always be late.
* CAPEC are an alternative to CWE that should be examined. It feels like CAPEC is the better option.
* We expect this to be very cumbersome work - and it's only worth it, when it is done completely covering all the rules.
* If we would be able to write the tags with the alerts, very interesting statistics could generated that would be of interest to a wider community far beyond ours.

We think the next step would be a brief concept what to do exactly. And if you were to write that, it would be very welcome.

**Comment by fzipi** [comment]
@dune73 created issue #486 before, which I think is related to this one.

**Comment by dune73** [comment]
Closing this in favour of #486.
