### ISSUE TITLE
Rule 942450 causes request with Ethereum address or transaction hash to be banned

### ISSUE THREAD

**Issue by pash7ka** [SpiderLabs/owasp-modsecurity-crs#951]
The rule 942450 uses "(?i:(?:\A|[^\d])0x[a-f\d]{3,}[a-f\d]*)+" regexp to identify SQL Hex Encoding which is considered as a possible SQL injection atack.
Unfortunately Ethereum addresses (like 0xc2d7cf95645d33006175b78989035c7c9061d3f9 ) and transaction hashes (like 0x653351a883a4a82512dbaceadd9d9ef266658547829a0d30d7aaf26647a144cb ) are also catched by this rule.
Can we make an exception for this hex strings with lenght of 40 and 66 symbols?

**Comment by dune73** [comment]
Thank you for reporting @pash7ka.

We are aware of issues with 942450 and discuss them in issue #833. I'm closing your report in favor of said issue.

**Comment by dune73** [comment]
Also, if you want to write a rule exception to make it go away, please take a look at the tutorials at https://netnea.com.
