### ISSUE TITLE
REG CRS VERSION info

### ISSUE THREAD

**Issue by glinkbalaji** [SpiderLabs/owasp-modsecurity-crs#958]
hello

we have  ‪CentOS Linux 7.4.1708 (Core)‬   Product | Plesk Onyx

we would like to know 

how to ckeck what is the crs version running now in my server 

and steps to upgrade it 

manoj

**Comment by dune73** [comment]
There are multiple ways:
*  You can look at the alerts being generated and then look them up in the rule reference: If it's on the left, it's CRS 2.x, it's on the right, it's CRS3 [https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/id_renumbering/IdNumbering.csv](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/id_renumbering/IdNumbering.csv)
* Open one of the config files
* Check the rule inventories at [https://www.netnea.com/cms/core-rule-set-inventory/](https://www.netnea.com/cms/core-rule-set-inventory/) and [https://www.netnea.com/cms/2016/01/17/most-frequent-false-positives-triggered-by-owasp-modsecurity-core-rules-2-2-x/](https://www.netnea.com/cms/2016/01/17/most-frequent-false-positives-triggered-by-owasp-modsecurity-core-rules-2-2-x/)
