### ISSUE TITLE
Error creating rule: Unknown variable: pk_ref)/

### ISSUE THREAD

**Issue by DopplerRedshift** [SpiderLabs/owasp-modsecurity-crs#963]
A similar bug was originally reported back in 2014, but it looks like another regex bug has made it back in to the repo. I'm using the latest master (3.0) as of November 16, 2017. This error occurs when parsing the modsecurity_crs_40_generic_attacks.conf rule set. The entire error message consists of the following:

AH00526: Syntax error on line 25 of /etc/httpd/crs/owasp-modsecurity-crs/base_rules/modsecurity_crs_40_generic_attacks.conf
Error creating rule: Unknown variable: pk_ref)/

It's no typo, the error does indeed contain the )/ on the end of pk_ref, so it seems like this is a regex issue.

**Comment by fzipi** [comment]
@DopplerRedshift There seems to be a confusion, because there is no file named like that in the v3.0/master branch (See https://github.com/SpiderLabs/owasp-modsecurity-crs/tree/v3.0/master/rules).

Could you please verify that?

**Comment by JReming85** [comment]
@DopplerRedshift You still have the old version installed, the new version recommended install isnt installed in /etc/modsecurity but in /etc/apache2/modsecurity.d

What ever guide you are using to install it is outdated, and you will need to either unlink the base_rules and change it to rules, or follow the recommended install guide in the INSTALL file

See https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/INSTALL 
Line 75 - Installing on Apache

**Comment by DopplerRedshift** [comment]
@fzipi Perhaps it is an older version, I was following a guide specifically for CentOS 7 (which I'm using) and it gave the following URL to obtain the latest master:

https://github.com/SpiderLabs/owasp-modsecurity-crs/tarball/master

I see that the URL you provided contains v3.0 specifically, so that must be where the confusion lies. I'll follow the installation guide that @JReming85 has provided for this instead. Thanks for setting me straight everyone :)

**Comment by DopplerRedshift** [comment]
Just confirmed - after downloading the file from the updated URL (and thus actually getting the latest version) and following the provided guide, Apache restarts without issue. Thanks again @fzipi and @JReming85!

**Comment by fzipi** [comment]
@DopplerRedshift You are very welcome!
