### ISSUE TITLE
Error creating rule: Unknown variable: pk_ref)/

### ISSUE THREAD

**Issue by derekneely** [SpiderLabs/owasp-modsecurity-crs#966]
Downloaded the latest master and we're seeing this issue when reloading Apache.

AH00526: Syntax error on line 25 of /etc/httpd/crs/owasp-modsecurity-crs/base_rules/modsecurity_crs_40_generic_attacks.conf:
Error creating rule: Unknown variable: pk_ref)/

Rhel7
Apache 2.4

**Comment by derekneely** [comment]
Actually, receiving this error with all references to pk_ref throughout the .conf files.

**Comment by derekneely** [comment]
Apologies for this. I regrabbed the repo and also used the ius version of mod_security and I'm all good now.

**Comment by csanders-git** [comment]
No problem, always good to make sure everything is working.
