### ISSUE TITLE
False possitive on kanboard

### ISSUE THREAD

**Issue by Dennis0001** [SpiderLabs/owasp-modsecurity-crs#968]
Hi,

i'm using kanboard (kanboard.net) and at some point in the application (kanboard website) mod_security create a false possitive.

**Information (what i do) when i get this false positive in kanboard**
Pressing the + (plus-sign) in the column header in a swimlane of a project it does notting.
browser logging shows:
GET http://www.<<removed>>/kanboard/?controller=TaskCreationController&action=show&project_id=2&column_id=7&swimlane_id=2 403 (Forbidden)

**some logging (i removed ip and hostname)**
[Sat Nov 18 18:52:31.283393 2017] [:error] [pid 23353:tid 140056194733824] [client xx.xx.xx.xx:50199]
[client xx.xx.xx.xx] ModSecurity: Access denied with code 403 (phase 2).
Pattern match "(?i:\\b(?:t(?:able_name\\b|extpos[^a-zA-Z0-9_]{1,}\\()|
(?:a(?:ll_objects|tt(?:rel|typ)id)|column_(?:id|name)|mb_users|object_(?:id|(?:nam|typ)e)|pg_
(?:attribute|class)|rownum|s(?:ubstr(?:ing){0,1}|ys(?:c(?:at|o(?:lumn|nstraint)s)|dba|ibm|
(?:filegroup|o ..." at ARGS_NAMES:column_id. [file "/usr/local/cwaf/rules/24_SQL_SQLi.conf"]
[line "18"] [id "211540"] [rev "12"] [msg "COMODO WAF: Blind SQL Injection Attack||www.|F|2"]
[data "Matched Data: column_id found within ARGS_NAMES:column_id: column_id"] [severity "CRITICAL"] [tag "CWAF"]
[tag "SQLi"] [hostname "www..nl"] [uri "/kanboard/"] [unique_id "WhBzX20w0EKU7QENe4CMFgAAAb4"]

**server**
Application version: 1.0.48
PHP version: 7.1.11
PHP SAPI: fpm-fcgi
OS version: Linux 2.6.32-042stab125.5
Database driver: mysql
Database version: 5.6.36

**mod_security defails:**
Current rules version 1.145 (Latest version)
CWAF plugin version 2.21 (Latest version)
Web Platform Apache
Apache version 2.4.29
Mod_security compatible yes
Mod_security loaded yes
Mod_security conf /etc/httpd/conf/extra/httpd-modsecurity.conf

**Comment by dune73** [comment]
Thank you for reaching out.

Unfortunately, you are hitting the wrong project. You are employing the ModSecurity rules from COMODO (-> ruleid: 211540, msg: COMODO WAF: Blind SQL Injection Attack).

This is the Core Rule Set project and our rules are in the range from 900000 onwards.

**Comment by dune73** [comment]
Following up: It looks like a standard false positive. It is likely you have to handle this yourself. I suggest you take a look at my tutorial on false positives at [netnea.com](https://www.netnea.com/cms/apache-tutorial-8_handling-false-positives-modsecurity-core-rule-set/).
The handling does not differ that much between COMODO and CRS.

**Comment by Dennis0001** [comment]
I'll will look in to that!
Thank you!
