### ISSUE TITLE
Masking PAN in logs

### ISSUE THREAD

**Issue by kozlovd** [SpiderLabs/owasp-modsecurity-crs#969]
Hello!
In OWASP CRS v2.2 there is file modsecurity_crs_25_cc_known.conf. It contains rules that masks PANs in modsecurity audit log. How this functionality can be achieved in CRS v3?

**Comment by dune73** [comment]
These rules are gone from CRS3.

However, the rule IDs are not used in CRS3. This means you can copy over the old rules into your configuration. Whereever you want to, but make sure the rules are executed before the CRS3 rules (as anomaly score evaluation happens at the end of phase 4 and you need to execute before that moment).
