### ISSUE TITLE
Definition of the remaining Policies for Best Practices Accreditation

### ISSUE THREAD

**Issue by fzipi** [SpiderLabs/owasp-modsecurity-crs#986]
This is related to #502. I've been filling the data for a new badge: [![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/1390/badge)](https://bestpractices.coreinfrastructure.org/projects/1390)

So here are the last bits to have 100% compliance with BPA.

* We maybe have to include a way of download a release (not cloning) (and maybe have it signed?)

I think we should have a proper release, which should be signed for integrity, and downloadable from github releases.

> If private vulnerability reports are supported, the project MUST include how to send the information in a way that is kept private.

Do we have a way to send us vulnerabilities (other than the issue tracker)? Does this makes sense at all? I'm thinking in a published email (or alias) with a public GPG for sending confidential issues, if needed. This should have low traffic, and in most cases from people who don't understand the real problem (and we end up forwarding to the issue tracker).

* New functionality testing

> The project MUST have a general policy (formal or not) that as major new functionality is added to the software produced by the project, tests of that functionality should be added to an automated test suite.

We need to have a general policy for including tests for new functionalities.

* Test policy justification

> The project MUST have evidence that the test_policy for adding tests has been adhered to in the most recent major changes to the software produced by the project.

So when we relase a new major, we need to have a proper set of test around, and evidence that they applied.

* Tests are added justification

> It is SUGGESTED that this policy on adding tests (see test_policy) be documented in the instructions for change proposals. [tests_documented_added]

We need to add to the `contributing.md` instructions for adding tests.

> There MUST be no unpatched vulnerabilities of medium or high severity that have been publicly known for more than 60 days. 

What this means for us? I know we don't have vulnerabilities, but we have evasion techniques. Do we need to document each possible evasion and warn users about it?

I can split each one in a particular issue, if needed.

**Comment by dune73** [comment]
Thanks for pushing this forward @fzipi. It's boring work, but it needs to be done. 

Here is my take on the open questions:

1 - Signed Releases: Yes, it seems we need to do that. I think they also ought to be listed on the website. Our rule update script also plays into this. 
2 - Security contact: We have an email address security@coreruleset.org. It forwards to contact@coreruleset.org, which forwards to @csanders-git, @lifeforms and me. If plain text email is not private enough, then there is no way around GPG. Not sure they insist on that, though. Personally, I think forwarding to the project co-leads would be enough. But we can also setup a security group if the three co-leads if you think something more formal is appropriate. What is missing is the documentation to this on the website.
3 - Testing policy : Should be easy to describe this in the contribution file
4 - Proof of testing policy : We're not there yet. Not all the tests are passing and once they are we can start to proof we write unit tests for new features.
5 - Testing policy again : I think this is essentially like 3
6 - Vulnerabilities : I would not rule out major vulnerabilities in the rule set. But I we need to separate them from major evasions, which is not really something we can cover. By definition, there will always be evasions. Also major ones depending on the perspective. But we can explain how the two things are different and that we do not have a major vulnerability in our rule base.

**Comment by fzipi** [comment]
I've added the email in the security contact.

**Comment by fzipi** [comment]
We should close this one. We already fixed the remaining steps!
