### ISSUE TITLE
January monthly meeting agenda

### ISSUE THREAD

**Issue by spartantri** [SpiderLabs/owasp-modsecurity-crs#991]
Happy 2018 to everyone!

Here are some items to discuss during our monthly chat:
- ML seems to be broken. This has been escalated to OWASP HQ by @dune73 today.
- PR #990: Java attacks : ready for review
- PR #989 
- PR #983 - @dune73 failed to test and merge this. Sorry.
- PR #982 - @dune73 failed to test and merge this. Sorry.
- PR #977 
- PR #926 - #949 from azhao155 regarding the tests
- PR #896 
- PR #881
- Issues generally: As mentioned last month we have a problem with open issues that we do not solve. We need a plan. (-> brought up by @dune73)
- Issue #986: Testing policy definition 
- Issue #974: Consider what to do with #974, pt 3.
- Issue #731: Get down to business with this issue  - open for over a year
- @spartantri: Had no time to do the check on t:lowercase vs rx ?i
- New rule idea by @spartantri: File upload check rules, I wrote today a new set of rules (~10) to do some checks on files (images and docs) to check if they are really the type of file and not a exe (MZ, ELF) in disguise (https://github.com/spartantri/owasp-modsecurity-crs/blob/v3.1/devFileUpload/rules/REQUEST-914-FILE-DETECTION.conf), it may be an interesting addition, currently at PL2 but may fit better in PL3 due to use of SecUploadKeepFiles, FILES_TMP_CONTENT, SecStreamInBodyInspection and STREAM_INPUT_BODY if that is a problem or had the one rule using the stream commented by default (libmodsec 3 incompatibility)
- We have a volunteer who would like to shift all rules that fit into phase 1 into phase 1.
- AppSecEU has been moved from Israel to UK and shifted to match the dev summit two weeks earlier. This would thus be perfect for our planned little CRS summit. @dune73 is in charge of this.
- dune73 is doing a ModSec/CRS/NGINX webinar with O'Reilly on January 9. Subscription is free, the slides will be shared afterwards.
- dune73 wrote a blog post about the development of the CRS project on the OWASP blog in December: https://owasp.blogspot.ch/2017/12/core-rule-set-evolution-of-an-owasp-project.html

**Comment by fzipi** [comment]
- Merge the PRs from azhao155.
- Testing policy definition (from #986)

**Comment by fgsch** [comment]
* Consider what to do with #974, pt 3.
