### ISSUE TITLE
921110 missing track and patch

### ISSUE THREAD

**Issue by spartantri** [SpiderLabs/owasp-modsecurity-crs#993]
921110 missing track and patch
`(?:\n|\r)+(?:get|post|head|options|connect|put|delete|trace|propfind|propatch|mkcol|copy|move|lock|unlock)\s+`
Is `capture` really used at all with non-capture regex?

**Comment by spartantri** [comment]
patch and track added, capture should be fixed under a cleanup ruleset PR

**Comment by dune73** [comment]
Thanks @spartantri. 

I see this changed, also the diff (and blame), but I can't seem to find the PR connected to this change. ???
