### ISSUE TITLE
update main GH page to be official website

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/owasp-modsecurity-crs#996]
In reading the documentation, I started by navigating to https://modsecurity.org/crs from this repository's landing page. However, it seems https://coreruleset.org/ is the official site as it is more recently updated.
If this is the case, could you update the this repository's link to point to the official site? Thanks!

Relates to discussion here:
https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/502

**Comment by dune73** [comment]
Thank you for reporting this @efx. True, that.

@csanders-git, can you do this, or do we need @victorhora / Spiderlabs to perform this for us? It's part of the title (?) when you click on our repository.

**Comment by csanders-git** [comment]
We'll need @victorhora to do this. Their CRS page is outdated and really shouldn't be in use at the top of the page. @victorhora can you please change this?

**Comment by csanders-git** [comment]
any update on this @victorhora

**Comment by victorhora** [comment]
Hey @csanders-git, I'm checking if I have rights for this change. I'll get back to you on that.

**Comment by csanders-git** [comment]
You should, this is what I think we're talking about

![image](https://user-images.githubusercontent.com/4632287/42669030-8c290d38-8621-11e8-86d6-f1560095a964.png)

**Comment by csanders-git** [comment]
We're still waiting on this almost a year later any update @victorhora? Is this the typical response timeline we should expect?

**Comment by vladbukin** [comment]
After July 13 passed 76 days or about 3 months and this is about 1/4 of a year. Is this a typical understanding of the calendar we should expect?

**Comment by dune73** [comment]
Guys, please stop with this passive aggressive tone.

@vladbukin: I appreciate you standing up for Trustwave as is your job. But the request to have our code repository and also modsecurity.org point to our website at https://coreruleset.org is a lot older than this issue. At least a year. And the promise to fix it too.

@csanders-git: I understand your frustration, but let's not vent in public.

**Comment by fgsch** [comment]
@victorhora Any update on this?

**Comment by dune73** [comment]
I wrote a message to four people at Trustwave. I'll keep you posted.

**Comment by dune73** [comment]
Another using reporting this and the outdated documentation on modsecurity.org in issue #1482. 

And still no fix.

**Comment by dune73** [comment]
Brought it up on the ModSecurity user mailinglist after the website's cert expired.
